### DISCUSSION TITLE
CSS fails to load

### DISCUSSION THREAD

**Discussion by Chrpre** [ExperienceLovelace/ha-floorplan#107] [Q&A]
Hi 

I moved my floorplan to a new installation, this time with the new ha-floorplan. 

But for some reason my css fails to have an effect on the colours of my doors or any othe style. When i hover over a door i clearly see the state

any ideas?

**Comment by pkozul** [comment]
Hi @Chrpre 

Can you include the relevant sections of your floorplan config, and CSS file?

**Reply by Chrpre** [reply]
Hi @pkozul 

thanks for takeing a look


CARD:

```
full_height: true
config:
  image: /local/community/ha-floorplan/floorplan.svg
  log_level: debug
  console_log_level: debug
  rules:
    - entities:
        - sensor.sileno_battery_level
      name: battery
      text_template: '${entity.state ? entity.state : "na"}%'
    - entities:
        - sensor.udhus_luftfugtighed
        - sensor.gaestevaerelse_fugt
        - sensor.have_humidity
      name: humidity
      text_template: '${entity.state ? entity.state : "na"}%'
    - entities:
        - sensor.gaestevaerelse_co2
      name: CO2
      text_template: '${entity.state ? entity.state : "na"}ppm'
    - entities:
        - sensor.gang_lux
        - sensor.stue_lux
      name: Lux
      text_template: '${entity.state ? entity.state : "na"}Lux'
    - entities:
        - sensor.motion_udhus
        - binary_sensor.gang_motion
        - binary_sensor.stue_motion
        - binary_sensor.bryggers_motion
      name: Motion
      states:
        - class: motion-sensor-off
          state: 'off'
        - class: motion-sensor-on
          state: 'on'
    - entities:
        - vacuum.sileno_lawnmower
      name: lawn
      states:
        - class: lawn-docked
          state: docked
        - class: lawn-cleaning
          state: cleaning
        - class: lawn-returning
          state: returning
    - entities:
        - binary_sensor.door_skur
        - binary_sensor.door_fryser
        - binary_sensor.mellem_door
        - binary_sensor.terrasse
        - binary_sensor.overdaekket
      states:
        - class: door-sensor-off
          state: 'off'
        - class: door-sensor-on
          state: 'on'

  stylesheet: /local/community/ha-floorplan/simple.css
type: 'custom:floorplan-card'
```
>

CSS file:

```

#floorplan  {
  padding: 10px;
}


#floorplan > svg {
} 

svg * {
  vector-effect: non-scaling-stroke !important;
}

/* Binary sensors */

.light-on {
  fill: #F9D27C !important;
  stroke-width: 2px !important;
} 

.light-off {
  fill: #808080 !important;
  transition: fill 5s ease;
}

.door-sensor-on {
  fill: #ff0000 !important;
  stroke-width: 2px !important;
}

.door-sensor-off {
  fill: #7CFC00 !important;
  stroke-width: 2px !important;
}


.motion-sensor-on {
  fill: #ff0000 !important;
  stroke-width: 2px !important;
}

.motion-sensor-off {
  fill: #808080 !important;
  stroke-width: 2px !important;
}

.switch-on {
  fill: #F9D27C !important;
  stroke-width: 2px !important;
}

.switch-off {
  fill: #808080 !important;
  transition: fill 5s ease;
}
```

**Reply by OzGav** [reply]
Can you edit you post above with all the indentation from your file and highlight it and press the <> button so that we can see the formatting?

**Comment by pkozul** [comment]
Hi @Chrpre 

Looking at your floorplan config, it looks like you're using the old version. Have a look at the YAML in the Home example to see what the newer syntax looks like for your rules.

https://experiencelovelace.github.io/ha-floorplan/docs/example-home/

For example, your 'Motion' rule should now look something like this:

```yaml
  - name: Motion
    entities:
      - vacuum.sileno_lawnmower
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: '${(entity.state === "on") ? "motion-sensor-on" : "motion-sensor-off"}'
```

The new syntax is more in line with what you see in Lovelace cards, so it made sense to move to that format.

**Reply by pkozul** [reply]
It's also worthwhile checking out the new documentation. The Rules section describes the new syntax.

https://experiencelovelace.github.io/ha-floorplan/docs/usage/#rules

**Comment by Chrpre** [comment]
Hi 

thank you for your response. I have tried to convert my config to the new version. I got the RGB lights to work with the example - for some reason the white light don't show any color )-,

I also tried to get the motion to work with my css file. I can see the state when i hover but no colour on the floorplan

```
    - name: Motion
      entities:
        - sensor.motion_udhus
        - binary_sensor.gang_motion
        - binary_sensor.stue_motion
        - binary_sensor.bryggers_motion
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data:
          class: >-
            ${(entity.state === "on") ? "motion-sensor-on" :
            "motion-sensor-off"}
    - entities:
        - vacuum.sileno_lawnmower
      name: lawn
      states:
        - class: lawn-docked
          state: docked
        - class: lawn-cleaning
          state: cleaning
        - class: lawn-returning
          state: returning
    - entities:
        - binary_sensor.door_skur
        - binary_sensor.door_fryser
        - binary_sensor.mellem_door
        - binary_sensor.terrasse
        - binary_sensor.overdaekket
      states:
        - class: door-sensor-off
          state: 'off'
        - class: door-sensor-on
          state: 'on'
    - entities:
        - light.skur_1
        - light.skur_2
        - light.fordoer1
        - light.fordoer2
        - light.leklint
        - light.hjorne
        - light.badevaerelse
        - light.gaestevaerelse
        - light.spisebord_lys
        - light.vaerelse_1
        - light.leas_vaerelse
        - light.wledkoekken
        - light.tradfri_bulb_6
      tap_action:
        action: toggle
      hold_action:
        action: more-info
      state_action:
        - action: call-service
          service: floorplan.style_set
          service_data: |
            >
              var elements = [
               `${entity.entity_id}`,
               `light_gradient_color_0`,
             ];

             var color = 'rgb(0, 0, 0)';
             var opacity = 0;

             if (entity.state === 'on') {
               if (entity.attributes.color_temp) {
                 var rgb = util.color.miredToRGB(entity.attributes.color_temp);
                 color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                 opacity = 1;
               }
               else if (entity.attributes.rgb_color) {
                 var rgb = entity.attributes.rgb_color;
                 color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                 opacity = 1;
               }
             }
             var style = `fill: ${color}; stop-color: ${color}; stop-opacity: ${opacity};`;

             return {
               elements: elements,
               style: style,
             };
  stylesheet: /local/community/ha-floorplan/hjem.css
type: 'custom:floorplan-card'
```


CSS:

```
* SVG size */

#floorplan > svg {
/*  max-width: 200px; */
}

/* SVG elements */

svg * {
  vector-effect: non-scaling-stroke !important;
}

/* Hover over */

.floorplan-shape:hover,
g.floorplan-hover > :not(text):hover,
g.floorplan-click > :not(text):hover,
g.floorplan-long-click > :not(text):hover,
:not(text).floorplan-hover:hover,
:not(text).floorplan-click:hover,
:not(text).floorplan-long-click:hover {
  stroke: #03a9f4 !important;
  stroke-width: 1px !important;
  stroke-opacity: 1 !important;
}


.motion-sensor-on {
  fill: #ff0000 !important;
  stroke-width: 2px !important;
}

.motion-sensor-off {
  fill: #778080 !important;
  stroke-width: 2px !important;
}
```

**Reply by exetico** [reply]
Are you able to control the color-temp. on the white bulb? Else, you wont be able to use that code to change the look of it. It's looking for RGB and color-temp. Maybe it makes sense to add yet another scenario for that example (@pkozul).

I'm not really sure what you're trying with the motion part. Graphics could help, and a little more details. 

_And oh, formater gerne din kode som man kan her på Github - så er det meget nemmere at læse 😁! But... Let's keep the conversation in English, so other people can use the information_ 😊.

**Comment by pkozul** [comment]
Hi @Chrpre

Regarding the light you said was not working on the floorplan, can you give us more info about what sort of light it is? I don't have RGB lights but I know others have been able to get their RGB lights working with floorplan.

**Reply by Chrpre** [reply]
Hi

I have a number of 'Hue White' bulbs. with these I can only control on/off and brightness. In my previous install i used css to make them yellow when on and black when off. I basically used the same template for my motionsensors for on/off.

**Reply by pkozul** [reply]
Hi @Chrpre 

Can you try changing your CSS to this? As you can see, aditional selectors have been added to select all child elements.

```css
.motion-sensor-on, .motion-sensor-on * {
  fill: #ff0000 !important;
  stroke-width: 2px !important;
}

.motion-sensor-off, .motion-sensor-off * {
  fill: #778080 !important;
  stroke-width: 2px !important;
}
```

Let us know how it goes.
