### DISCUSSION TITLE
Help starting up with Home Example

### DISCUSSION THREAD

**Discussion by ghost** [ExperienceLovelace/ha-floorplan#109] [Q&A] [answered]
Hello,

I have used the floorplan way back when it was straightforward. I am now installing it again via HACS and having difficulties getting the Home example to show up. 
The resources have been added correctly.

my folder structure:
![image](https://user-images.githubusercontent.com/53271118/119939434-ec972b00-bf9e-11eb-8cf0-ce2e40dc2131.png)

My code :

```
 - icon: 'mdi:home-assistant'
    title: Floorplan
    path: floorplan
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: 'custom:floorplan-card'
                full_height: true
                config:
                  image: /local/floorplan/examples/home/home.svg
                  stylesheet: /local/floorplan/examples/home/home.css
                  log_level: info
                  console_log_level: info
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
                    - entity: light.garage
                      element: light.garage
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data: >-
                          /local/floorplan/examples/home/light_${entity.state}.svg
                      tap_action: toggle
                    - entity: light.garage
                      element: light.garage.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: 'button-${entity.state}'
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                    - entity: light.garage
                      element: light.garage.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: '${entity.state}'
                      tap_action: false
                    - entity: switch.living_area_fan
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: '${(entity.state === "on") ? "spinning" : ""}'
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: 'button-${entity.state}'
                      hold_action:
                        action: call-service
                        service: homeassistant.toggle
                        service_data:
                          entity_id: switch.living_area_fan
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: '${entity.state}'
                      tap_action: false
                    - entity: camera.zagreb_ban_jelacic_square
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          image: '${entity.attributes.entity_picture}'
                          image_refresh_interval: 10
                    - entities:
                        - binary_sensor.main_bedroom
                        - binary_sensor.living_area
                      state_action:
                        action: call-service
                        service: floorplan.style_set
                        service_data:
                          style: >
                            fill: ${ entity.state === "on" ? "#F9D27C" :
                            "#7CB1F9" };

                            transition: ${ entity.state === "off" ? "fill 5s
                            ease" : "" };
```

All am getting is this:

![image](https://user-images.githubusercontent.com/53271118/119939833-79da7f80-bf9f-11eb-8af9-a47a1c0b5d51.png)
