### DISCUSSION TITLE
Problems in Core 2021.6.0b0

### DISCUSSION THREAD

**Discussion by dreimer1986** [ExperienceLovelace/ha-floorplan#111] [Q&A] [answered]
I have made a really nice floorplan and it worked up to 2021.5.5 quite nicely. All lamps were shown and all worked fine. Now only one lamp shows up and this one does not work anymore.

![image](https://user-images.githubusercontent.com/29841368/119948780-7a701780-bf99-11eb-871b-5d62de8f3947.png)

```
type: custom:floorplan-card
config:
  image: /local/floorplan/styles/home/home.svg?v=1
  stylesheet: /local/floorplan/styles/home/home.css
  defaults:
    hover_action: hover-info
    tap_action: more-info
  rules:
    - entities:
        - light.wohnzimmer
        - light.esszimmer
        - light.schlafzimmer
        - light.heimkino
        - light.bad
        - light.kueche
        - light.gang
        - light.schrank_light
        - light.kommode_light
        - light.tv_ambiente
      state_action:
        - action: call-service
          service: floorplan.image_set
          service_data: /local/floorplan/styles/home/light_${entity.state}.svg
        - action: call-service
          service: floorplan.class_set
          service_data: light-${entity.state}
      tap_action: toggle
```

```
28.5.2021, 09:47:17 INFO INIT Floorplan for Home Assistant (ha-floorplan) v1.0.23
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.schrank_light: unavailable (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.kommode_light: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.bad: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.kueche: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.wohnzimmer: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.gang: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.esszimmer: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.heimkino: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.schlafzimmer: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG STATE light.tv_ambiente: off (initial load)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.kommode_light (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.bad (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.kueche (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.schrank_light (setting image: /local/floorplan/styles/home/light_unavailable.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.wohnzimmer (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.gang (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.esszimmer (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.heimkino (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.schlafzimmer (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:18 DEBUG IMAGE light.tv_ambiente (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:25 DEBUG STATE light.tv_ambiente: attributes (last updated 28.5.2021, 09:06:58)
floorplan.js:67 28.5.2021, 09:47:25 DEBUG IMAGE light.tv_ambiente (setting image: /local/floorplan/styles/home/light_off.svg)
floorplan.js:67 28.5.2021, 09:47:26 DEBUG STATE light.tv_ambiente: attributes (last updated 28.5.2021, 09:06:58)
floorplan.js:67 28.5.2021, 09:47:26 DEBUG IMAGE light.tv_ambiente (setting image: /local/floorplan/styles/home/light_off.svg)
```
[home.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/6559189/home.zip)
