### DISCUSSION TITLE
Convert future datetime to remaining time

### DISCUSSION THREAD

**Discussion by tringler** [ExperienceLovelace/ha-floorplan#121] [General]
Hello,

who can help me to convert i.e. that string "2021-06-26T19:51:16.766951+00:00" to "39 minutes" inside the YAML?
Every hint is highly appreciated!

Thanks, Thomas

**Comment by exetico** [comment]
39 minutes, related to the current time... Or? 😁 And what would you like it to be, if it's an hour? I think there's a native time calc function in HA - but else it's easy to handle in other ways, too.

**Reply by OzGav** [reply]
Yeah since we don't exactly know what to do here are some hints as requested:
https://www.home-assistant.io/docs/configuration/templating/
https://community.home-assistant.io/t/time-calculations/85175

**Comment by tringler** [comment]
Sorry for my delay and thanks for your help! 
"2021-06-26T19:51:16.766951+00:00" is the time in the future and I want to compare it with the current time in order to get something like "39 minutes remaining".
Yes, using templates would be one option, but I would like to convert that inside the floorplan yaml in these lines:
```
 - name: Other
    entities:
      - entity: sensor.kitchen_dishwasher_remaining_program_time
        element: sensor.kitchen_dishwasher_remaining_program_time
    state_action:
      - service: floorplan.text_set
        service_data: '${(entity.state !== undefined) ? entity.state : "unknown"}
```
Is that possible?

**Reply by pkozul** [reply]
Hi @tringler 

Soon we will have a new version ready which will allow you to display time remaining, and time passed, in a human readable format.

Stay tuned...

**Reply by pkozul** [reply]
Hi @tringler 

We have a new version released to HACS.

Check out the Home example to see the new feature in action.

![image](https://user-images.githubusercontent.com/2073827/124197981-0f26e180-db13-11eb-8265-b2ec699138ae.png)

https://experiencelovelace.github.io/ha-floorplan/docs/example-home/

The relevant rule is shown below. The rule is executed whenever any HA entity changes its state (I.e. very frequently!), which allows the text to display how much time has elapsed since the enity's state changed. In your case, you'd be referencing some future date, which would instead display how much time is remaining.

```yaml
      - entity: '*'
        element: light.garage.last_changed
        state_action:
          - action: call-service
            service: floorplan.text_set
            service_data:
              text: 'Last changed: ${util.date.timeago(new Date(entities["light.garage"].last_changed))}'
```

As you can see in the service call above, we now have a function `util.date.timeago()` which formats the specified date, to show how much time has elapsed, or how much time remains.

Let us know how you go,
