### DISCUSSION TITLE
Multiple entities (lights) on one element?

### DISCUSSION THREAD

**Discussion by Vitani** [ExperienceLovelace/ha-floorplan#142] [Q&A] [answered]
Heya, is it possible to have one element control multiple lights? I tried using -

```
  rules:
    - name: Rooms
      entities:
        - entities: [ light.kitchen_passage, light.kitchen_side, light.kitchen_sink ]
          element: area.kitchen
      tap_action: homeassistant.toggle
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
```

but that doesn't work.

**Comment by OzGav** [comment]
I would just add those lights to a group and control the group.

**Reply by exetico** [reply]
I would do the same, for sure :-)

**Reply by Vitani** [reply]
I didn't even know groups were a thing! Only been using Home Assistant for one year ...

**Comment by exetico** [comment, marked as answer]
I would like to see a few more details next time. Thanks! 

I bet you're asking about controlling multiple lights.. But I'm not totally sure?

<hr>

If it's **multiple lights**, go with 1) or 2).

1) Group them and use light.turn_on with `group.office` (or whatever it's named)

2) Else, have you tried a formatting like this? (If you're not into the group things..)

_That's the basic solution in Home Assistant._

```yaml
service: light.turn_on
data:
  entity_id:
  - light.spotlys_kontor
  - light.sonoff1
  - light.sonoff2
```

_In ha-floorplan, **that translates to**:_
```yaml
tap_action:
    service: light.turn_off
    service_data:
      entity_id:
      - light.spotlys_kontor
      - light.sonoff1
      - light.sonoff2
```
And I can confirm, that it's working just fine on my floorplan.

<hr>

If you're trying to change multiple SVG elements at the same time... Well, that's another story. If so, kindly confirm, and provide some more information, including your SVG, if possible.
