### DISCUSSION TITLE
Help browser_mod popup in floorplan

### DISCUSSION THREAD

**Discussion by donnaran** [ExperienceLovelace/ha-floorplan#146] [Q&A] [answered]
Does anyone have working example of calling browser_mod popup e.g on hold_action/tap_action in floorplan?   Many Thanks

**Comment by exetico** [comment, marked as answer]
I'm not on my machine right now, but here's a fast dump. 

https://transfer.sh/wcKoeL/example-browser_mod.yaml


```yaml
entities:
  - switch.sonoffpow1
element: thing.3dprinter
tap_action:
  service: light.toggle
  service_data:
    entity_id: light.magichome1sonoff
hold_action:
  service: browser_mod.popup
  service_data:
    title: 3D Printer
    card:
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: automation.sluk_3d_printer_og_intel_nuc_med_octoprint
                name: Sluk 3D printer automatisk inkl. NUC
              - type: button
                entity: light.magichome1sonoff
          - type: custom:restriction-card
            restrictions:
              confirm:
                text: BekrÃ¦ft venligst at du vil Ã¦ndre ved disse enheder!
            card:
              type: entities
              show_header_toggle: false
              entities:
                - entity: switch.sonoffpow1
                  type: "custom:secondaryinfo-entity-row"   
                  secondary_info: 'Intel NUC er [[ if(device_tracker.58_fb_84_ec_29_03 == home, "tÃ¦ndt", "slukket") ]]'
                - entity: switch.ender3_cancel_print
                  name: 'Stop print'
                - entity: switch.ender3_shutdown_system
                  name: 'Sluk systemet'
          - type: 'custom:auto-entities'
            card:
              type: entities
              #title: Kontor
              show_header_toggle: false
            filter:
              include:
                - entity_id: "sensor.ender3*"
state_action:
  service: floorplan.class_set
  service_data:
    class: '${(entity.state === "on") ? "thing-on" : "thing-off"}'
```

Here's `custom:restriction-card` and `custom:auto-entities` in use, too.

**Reply by donnaran** [reply]
Worked. Thank you for providing the example. This is what i was after.

**Reply by donnaran** [reply]
Side note. do you have any example for controlling the brightness of the light. e.g slider type or using UP or Down image?

I have input_number defined as 1 to 100 and steps 10 on each slider move and some automation to adjust brighness. its work from the lovelace but trying to put similar in floorplan to control the lights brightness.

i have download one of the example below from the old version of floorplan showing how to control volume but can't worked out how to convert this for the brightness control. Your help would be much appreciated. 


  - elements:
      - floorplan.volume_000
      - floorplan.volume_010
      - floorplan.volume_020
      - floorplan.volume_030
      - floorplan.volume_040
      - floorplan.volume_050
      - floorplan.volume_060
      - floorplan.volume_070
      - floorplan.volume_080
      - floorplan.volume_090
      - floorplan.volume_100
    class_template: '
      let volumeLevel = entities[entities["floorplan.current_media_player"].state].attributes.volume_level;
      let elementVolumeLevel = parseInt(element.id.split("_")[1]) / 100;
      return (volumeLevel >= elementVolumeLevel) ? "visible" : "hidden-enabled";
      '
    action:
      service: media_player.volume_set
      data_template: '{
        "entity_id": "${entities[entities["floorplan.current_media_player"].state].entity_id}",
        "volume_level": ${(parseInt(element.id.split("_")[1]) / 100)}
      }'
![image](https://user-images.githubusercontent.com/56533418/133386270-418ec61b-65e7-4ca5-a941-852eae829126.png)


many thanks

**Reply by OzGav** [reply]
> do you have any example for controlling the brightness of the light. e.g slider type

If you just want a slider you could have `tap_action` set to `toggle` the light and `hold_action` set to `more-info` which will bring up a dialog box which would allow you to then adjust the brightness.

```
            - tap_action: light.toggle
              hold_action: more-info
              entities:
                - light.some_light_name

```

**Reply by donnaran** [reply]
Thanks for your reply. created browser_mod popup to control light brightness and colour on hold_action.

![image](https://user-images.githubusercontent.com/56533418/133436230-446d2a1c-a4e1-4f77-bbee-b158d61fa627.png). 
![image](https://user-images.githubusercontent.com/56533418/133437097-3b4f8d84-d7ed-4210-b633-e8ace3ed64ed.png)

**Reply by exetico** [reply]
Looks great! 

And btw... Share your code, so other can enjoy that, too 😄 !

**Comment by rpimeekle** [comment]
With browser_mod.popup using the example @exetico gave above, I noticed that if I clicked the entity on my ha-floorplan to bring up the popup on my computer, the popup displayed, however, if I had HA open on my phone app, the same popup was displayed there at the same time there.  In fact, if I opened the phone app later, that popup would immediately open if I had previously clicked it on my computer.

To fix this, I used this configuration:
```              
            ### Cameras
            - name: Cameras
              entities:
                - camera.camera_01
                - camera.camera_02
                - camera.camera_03
                - camera.camera_09
                - camera.camera_10

              state_action:
                - action: call-service
                  service: floorplan.style_set
                  service_data:
                    style: |
                      stroke: #000000;
                      stroke-width: 1px;
                      stroke-opacity: 1;
              tap_action:
                action: fire-dom-event  #it works with this method
                browser_mod:
                  command: popup
                  deviceID: this
                  title: Camera     #this can't be blank, but it would be neat to make it inherit the top-level entity, i.e. specific camera
                  card:
                      type: vertical-stack
                      cards:
                        - type: horizontal-stack
                          cards:
                            - camera_view: live
                              type: picture-glance
                              image: https://demo.home-assistant.io/stub_config/kitchen.png
                              entities:
                                - entity: binary_sensor.camera_01_motion
                              camera_image: camera.camera_01
                              entity: ''
                        - type: horizontal-stack
                          cards:
                            - type: button
                              entity: light.garage_lights
```

On a side note, I'm still trying to figure out if I can use this single block instance (with all cameras) to open a different popup depending on the camera entity selected.  That is, if I select Camera 1, it shows Camera 1 view with Camera 1 title, but if I select Camera 2, it shows Camera 2, etc.

**Reply by rpimeekle** [reply]
I figured out how to open different popups depending on the entity selected.  The method I used is documented here: https://github.com/thomasloven/hass-browser_mod#replacing-more-info-dialogs.  

In a nutshell, you pre-configure the entities you want with a custom card, so that when you call the 'more-info' action on that entity in your floorplan, you get the custom card rather than the default 'more-info' card that is associated with that entity.

For instance, where you would normally get a picture view when you select the cameras on my floorplan, now you get a picture-glance card with additional information on doors and sensors and lights related to that area.

```
views:
  - title: Floorplan
    path: floorplan
    icon: mdi:floor-plan          
    type: panel
    full_height: true
    ### POPUP CARDS - see https://github.com/thomasloven/hass-browser_mod#replacing-more-info-dialogs
    popup_cards:
      camera.camera_01:
        title: Driveway
        card:
          type: picture-glance
          camera_image: camera.camera_01
          camera_view: live
          image: https://demo.home-assistant.io/stub_config/kitchen.png
          entities:
            - entity: binary_sensor.camera_01_motion
            - entity: light.deta_switch_01_3rd
            - entity: sensor.garage_door_position
          entity: ''
        style: |
          ha-dialog {
            --mdc-dialog-max-width: 1080px !important;
          }
          .content {
            width: auto !important;
          }
      camera.camera_02:
        title: Backyard
        card:
          type: picture-glance
          camera_image: camera.camera_02
          camera_view: live
          image: https://demo.home-assistant.io/stub_config/kitchen.png
          entities:
            - entity: binary_sensor.camera_02_motion
            - entity: binary_sensor.door_04
        style: |
          ha-dialog {
            --mdc-dialog-max-width: 1080px !important;
          }
          .content {
            width: auto !important;
          }
### etc
```

Then for those particular entities, more-info calls the above configuration:

```
            ### Cameras
            - name: Cameras
              entities:
                - camera.camera_01
                - camera.camera_02
              state_action: false
              tap_action: more-info  ##see popup_cards: templates at start of file
```
