### DISCUSSION TITLE
Multiple lights in same room

### DISCUSSION THREAD

**Discussion by samuelsson86** [ExperienceLovelace/ha-floorplan#154] [Q&A] [answered]
Hi

I just started with ha-floorplan and I love it. I managed to get the lights working, just like in the example.

However, I have a room with two lights and I can't figure out how to make a rule that checks if the other light is on/off and then chooses the right lights-on combination. 

I have two lights in my office. I also have those lights in a group (light.kontor_lys).

This is the rule I use now:

```     
- name: Rooms
  entities:
    - entity: light.kontor_lys
      element: area.office
  tap_action: light.toggle
  state_action:
    - service: floorplan.class_set
      service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
```

And this is in my css file:

```
.light-on {
  opacity: 0 !important;
  transition: opacity .5s;
}

.light-off {
  opacity: 1 !important;
  transition: opacity .5s;
}
```

I now added two other images to my svg file. On those images only one of the two lights is on. Let's call the first one area.office_led (light.office_led) and area.office_ceiling (light.office_ceiling). So I would need a rule that checks which lights are on when the area is clicked or when one of the light states changes and then changes the opacity of the different areas to match the light combination. 

Is this possible?

**Comment by OzGav** [comment, marked as answer]
Not 100% sure I will fully answer your question here but here goes. The floorplan will change the appearance of your bulbs according to their state, you don't have to touch the screen for that to happen.

In regards to controlling your bulbs in a group I am not exactly sure what outcome you are after but I expect you will be able to come up with a solution using scripts. Below I will show a similar example which I use. I have a group of lights and sometimes some but not all of them will be on. The script checks to see if any of the lights are on (ie. the group wll be on) and if so touching the floorplan will turn all the lights off. If all the lights are off then touching the floorplan turns all of them on.

Floorplan:
```
            - tap_action:
                service: script.turn_on
              entities:
                - script.meals_room_lights_toggle
              name: Execute Scripts
```
Script:
```
meals_room_lights_toggle:
  sequence:
    service_template: >
      light.{% if is_state('light.meals_room', 'on') -%}
        turn_off
      {% else -%}
        turn_on
      {% endif %}
    data: 
      entity_id: light.meals_room
```

**Reply by samuelsson86** [reply]
Thanks for your reply. 
I don't think I would need the script. When I control the light group it normally turns on all the lights in the group. This hasn't really been a problem (yet?). 

I'm struggling with the floorplan side of it. Right now (in the code I posted above) I have the main floorplan image with all the lights on and then a smaller image of each room where the lights are off. When the state changes the small image with the lights off changes its opacity to 0 or 1 depending on the lights state.

But I don't understand how I could make this work with three images on top of the main image. If only the Ledstrip is on, I would need floorplan to change the opacity of the only-ceilinglight-on image and all-lights-off image to 0 while the image for only-ledstrip-on has to be opacity 1.  

I tried this yesterday but it doesn't work. I don't really know how to write JavaScript code.

```
- name: Office lights
  entities:
    - light.kontor_ledlist
    - light.kontor
  tap_action: false
  state_action:
    - action: call-service
      service: floorplan.class_set
      service_data:
        element: area.office_alloff
        class_template: >-
          if (entities["light.kontor"].state === off) and (entities["light.kontor_ledlist"].state === off)
          return "visible"; 
          else return "hidden";
    - action: call-service
      service: floorplan.class_set
      service_data:
        element: area.office_ledstrip_on
        class_template: >-
          if (entities["light.kontor"].state === off) and (entities["light.kontor_ledlist"].state === on)
          return "visible"; 
          else return "hidden";
    - action: call-service
      service: floorplan.class_set
      service_data:
        element: area.office_ceiling_on
        class_template: >-
          if (entities["light.kontor"].state === on) and (entities["light.kontor_ledlist"].state === off)
          return "visible"; 
          else return "hidden";
```
My css file now has those classes:

```
.hidden {
  opacity: 0 !important;
  transition: opacity .5s;
}

.visible {
  opacity: 1 !important;
  transition: opacity .5s;
}
```

Is this somehow possible to do this way?

**Reply by OzGav** [reply]
You need to decide how you want it to look and how you will control the lights. From there we can work out how to make it happen. In my kids bedrooms they have their bedside light and the whole room light. To toggle the whole room light I touch anywhere in the room. To toggle the bedside light I have a smaller button just outisde the wall of the house that I can touch. You can see it here: https://community.home-assistant.io/t/share-your-floorplan/21315/676?u=ozgav (In this example the room in the top right has its main light on and the desk lamp in the top left is on (you can see it lighting the desk and the button is also bright)

The appearance in the bedrooms is that when the bedside light is on there is a glow that lights up maybe a third of the room. I then put the main room light image above that so when the main light is on it obscures the bedside light and the whole room appears lit but I can still see whether the bedside is on because the button outside the room also changes colour. That is but one way to do it. I could have had the bedside button in the room but since I actually need to control the aircon, a ceiling fan and the bedside light it was more practical and looks great having those three buttons adjacent to each room.

You may not need to do all that checking because in Inkscape the layer that is uppermost will obscure the layers beneath unless you set an opacity of less than 100%. (I actually only use an opacity of 65% so that adjacent room lights that have overlapping images blend in well but I digress!). So I think you need to decide how will you control the lights in floorplan or maybe you don't want to you just want to see if they are on or off. Then decide how you want to be able to tell if they are on or off. Again I use an overall room light and an icon, I could have used an overall room light and then an even brighter bedside light image but I wanted it to more or less reflect reality and the bedside is not as bright as the room light.

Hope that makes sense? You can post a mockup image if you like if that makes it easier to describe what you want to t achieve.

**Reply by samuelsson86** [reply]
Thanks again for taking the time to help me! I finally managed to do what I want.

Controlling the light works fine. I just use the image that is on top in the svg file to toggle the light. Like this:

```
- name: Office light toggle
  entities:
    - entity: light.kontor_lys                           #This is the office light group
      element: area.office_ledstrip_on           #The image that is on top in the svg file
  tap_action: light.toggle
```
I don't really need to be able to control the lights seperatly. I'm ok with toggling the light group in floorplan.

This is from the svg file:

![image](https://user-images.githubusercontent.com/42771028/135427154-3149e8f7-b687-4264-bc2f-173af3b04b93.png)


On my floorplan all the doors are closed so I dont need to think about light going into other rooms.
Right now I dont have an image for "only ceiling light on" but the rest works with this:

```
- name: Office lights
  entities:
    - entity: light.kontor_ledlist
      element: area.office_ledstrip_on
    - entity: light.kontor
      element: area.office_alloff
  tap_action: false
  state_action:
    - action: call-service
      service: floorplan.class_set
      service_data:
        element: area.office_alloff
        class: |
          >
            if (entity.state === 'off' && entities["light.kontor_ledlist"].state === 'off') return "visible"; else return "hidden";
    - action: call-service
      service: floorplan.class_set
      service_data:
        element: area.office_ledstrip_on
        class: |
          >
            if (entities["light.kontor"].state === 'off' && entity.state === 'on') return "visible"; else return "hidden";
```

This is in the css file:

```
.hidden {
  opacity: 0 !important;
  transition: opacity .5s;
}

.visible {
  opacity: 1 !important;
  transition: opacity .5s;
}
```

I'm sure there's probably a much better way to do this but at least i works for now. 
Thanks!

**Reply by OzGav** [reply]
Great that you have it working but seems like we can simplify this a lot as you seem to be just wanting to toggle the light group and have a single light on image appear when it is on.  Looking at your Inkscape layers that all seems good as the light off pic is under the lights on. So you don't actually need to show or hide the lights off pic as it will be covered by the lights on. My house floor plan is one big image all lights off and then the small lights on images are placed appropriately and shown or hidden. 
So I think you can simply things as follows:

Change the object ID of `area.office_ledstrip_on` to `light.kontor_lys` in your SVG

Then change all of your UI-lovelace.yaml code you show above to just:
```
- name: Office light toggle
  entities:
    - entity: light.kontor_lys                           #This is the office light group
  tap_action: light.toggle
  state_action:
    - action: call-service
      service: floorplan.class_set
      service_data:
        class: '${(entity.state === "on") ? "visible" : "hidden"}'
```
I hope I have this right as you say in you first post _So I would need a rule that checks which lights are on when the area is clicked or when one of the light states changes and then changes the opacity of the different areas to match the light combination._ which seems to indicate you wanted to be able to see which of the two lights was on (supported by your middle solution which had three images) but the above solution seems to just have one lights on image and one lights off. Regardless I hope you can see you can simplify things by naming the objects in your SVG the same as your HA entities which saves all those extra `element `lines.

**Reply by samuelsson86** [reply]
I think I should have posted all my SVG layers. I have three possible layers for the office light. 

![image](https://user-images.githubusercontent.com/42771028/135581380-3b6fb374-af77-4d50-b86a-4aec87b2db76.png)

The layer called downstairs is the main image of the whole floor with all lights on (g120). The areas are images where the lights are off in the different rooms. But the office has both an all lights off layer and an only led strip on layer. (I don't have one yet for only ceiling light on)

Image 1: the main layer all the way on the bottom (downstairs)
![image](https://user-images.githubusercontent.com/42771028/135581804-e2940a93-0cca-436f-9b7d-e193335aafcb.png)

Image 2 the all lights off image 
![image](https://user-images.githubusercontent.com/42771028/135581920-000116e4-26af-445a-838d-77327a90e790.png)

Image 3: the ledstrip only image 
![image](https://user-images.githubusercontent.com/42771028/135581719-0d5b12ba-fe65-49ce-82bb-c615f5b27601.png)

You wrote: _the above solution seems to just have one lights on image and one lights off_ but my solution actually gives three possibilities. When both lights are off, only image 2 is visible and image 3 is hidden. When only the led strip is on then image 2 is visible but image 3 is hidden. And finally, when both are on (or also only the ceiling light) images 2 and 3 are hidden and the bottom layer, image 1, is visible.

Do you think there is a way to simplify this? Thanks for helping! :-)

**Reply by OzGav** [reply]
Yep this can be simplified: Here is your YAML:

```
- name: Office light toggle
  entities:
    - entity: light.kontor
    - entity: light.kontor_ledlist
  tap_action: light.toggle
  state_action:
    - action: call-service
      service: floorplan.class_set
      service_data:
        class: '${(entity.state === "on") ? "visible" : "hidden"}'
```

Change (if necessary) the order of your images so that the lights off image is on the bottom, the LED only image is next and the whole room light is on top. In Inkscape set the ID of the top layer `light.kontor` and the middle layer `light.kontor_ledlist`

What will now happen is when you touch on the image `light.kontor` will toggle state. When that happens the top layer will become visible and will obscure all the other layers. If the LED light is turned on (however you do that) then that layer will become visible but it won't be seen if the layer above is visible. That will meet all of your current functionality I think. If you want to be able to control the LED light from floorplan then you can do that but will require some more discussion!
