### DISCUSSION TITLE
Show hide a text element based on the state of a second entity

### DISCUSSION THREAD

**Discussion by OzGav** [ExperienceLovelace/ha-floorplan#156] [Q&A] [answered]
What I am wanting to do is have a text element showing the value of an entity but have that element shown or hidden based on the state of a second entity. I have currently fudged it to make it work but just wanting to know if there is a perfect solution. I currently have:
```
            - entities:
                - entity: sensor.power2b
                  element: car.charge.rate
              name: textSensors
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state.replace(/\s{2,}/g,"")}'
                - service: floorplan.class_set
                  service_data: 
                    class: '${(entity.state > 97) ? "always-visible" : "always-invisible"}'
```
So the text entity displays a numerical value but I actually want to show or hide that based on the state of a switch. I tried a couple of variations of this but it didn't work:
```
            - entities:
                - entity: sensor.power2b
                  element: car.charge.rate
              name: textSensors
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state.replace(/\s{2,}/g,"")}'
                - service: floorplan.class_set
                  
                  service_data: 
                    class: '${(switch.car_charger.state === "on") ? "always-visible" : "always-invisible"}' 
```
