### DISCUSSION TITLE
Issues getting my HA-Floorplan card to show.

### DISCUSSION THREAD

**Discussion by vlaryn** [ExperienceLovelace/ha-floorplan#166] [Q&A] [answered]
Hey all, I am trying to get my first HA-Floorplan setup. I have enabled yaml mode in my configuration.yaml file and created a dashboard there as well. I have also installed the HA-Floorplan from HACS and loaded the resource in the configuration.yaml. When I am trying to add the yaml code to display the card in a separate floorplan.yaml file it does not seem to load my svg file. I do have a css file as well so I believe it should display. I am going to include my configuration.yaml and floorplan.yaml. It seems like the card is getting loaded but not my svg file. Also I store my svg file in /config/www/floorplan/floorplan.svg but I reference it as /local/floorplan/floorplan.svg in the yaml code. https://www.codepile.net/pile/0D3j3OzM

**Comment by OzGav** [comment, marked as answer]
First thing to check is to type this into your browser
`http://YOUR.HA.IP.ADDRESS:8123/local/floorplan/floorplan.svg`
and you should see your floorplan appear. If not then that is a problem.

Looking at your floorplan.yaml I am not sure you have all your indents correct. Try this (and I have included the log_level option so you can see errors on the page). I haven't used the most simple implementation but that will help later if you use more of the options.

```
views:
  - title: Floorplan
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          log_level: info
          image:
            location: /local/floorplan/floorplan.svg
          stylesheet:
            location: /local/floorplan/floorplantest.css
```
