### DISCUSSION TITLE
class_set not working

### DISCUSSION THREAD

**Discussion by sambiam** [ExperienceLovelace/ha-floorplan#174] [Q&A] [answered]
I'm having some issues getting a section of my code to run properly. I'm following along with this video for my setup
[https://www.youtube.com/watch?v=MCNxgb0mrSA](url)
I'm quite new to all of this so I'm probably missing something super obvious

What I'm expecting it to do is return a class of 'light-on' or 'light-off' for the entities listed in the first entity list but this isn't showing up in the elements when I inspect it. 

```yaml
views:
  - title: Home
    theme: waves
    panel: true
    log_level: info
    console_log_level: info
    cards:
      - type: custom:floorplan-card
        style: |
          ha card {
            max width: 150vh;
            margin: 0 auto;
            background: none; 
          }
        config:
          image: /local/floorplan/examples/home/home_optimised.svg
          stylesheet: /local/floorplan/examples/home/home.css
          rules:
            - entities: 
                -switch.dining - light.family - light.spare - light.office -
                light.laundry - light.kitchen - light.bath - light.spotlights -
                light.string - switch.hall
              tap-action: false
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: light-${entity.state}
            - entities: 
                -light.bedroom -switch.dining - light.family - light.spare -
                light.office - light.laundry - light.kitchen - light.bath -
                light.spotlights - light.string - switch.hall
              tap-action:
                action: toggle
              state-action:
                action: call-service
                service: floorplan.style_set
                Service_data:
                  element: ${entity.entity_id.replace('light.', 'light_overlay.'}
```

I'm also seeing this error in the console which I don't fully understand
![image](https://user-images.githubusercontent.com/96670272/147519688-3e9a6c4d-ceb4-4144-8884-c14ca7007136.png)

I don't know if it makes a difference but I'm implimenting it in the raw configuration editor rather than through a yaml file as I couldn't figure out how to get ui-lovelace.yaml to link to the yaml where I placed the code using !include. I'm not sure if it's relevant but every time I save the file the quotations around 'light-${entity.state}' disappear

SVG file is attached for reference
[https://drive.google.com/file/d/1z4QN6Vr2mGw8xFR_apIPAsOtX6c5B6vK/view?usp=sharing](url)

**Comment by OzGav** [comment, marked as answer]
At first glance I think you have an indent problem. Can you reformat the above using the <> option?

**Reply by sambiam** [reply]
I wouldn't be surprised. I've updated the post to show the code

**Reply by OzGav** [reply]
Try this. I have simplified a little as some lines you had are the defaults. Also you had hyphens where there should have been underscores in a number of places. 

At the end there was a capital S and then some of the code is missing as you are calling `style_set` but there is no style in the `service_data`. Also you are replacing `light.` but two of your entities are `switch.`

```
views:
  - title: Home
    theme: waves
    panel: true
    cards:
      - type: custom:floorplan-card
        style: |
          ha card {
            max width: 150vh;
            margin: 0 auto;
            background: none; 
          }
        config:
          image: /local/floorplan/examples/home/home_optimised.svg
          stylesheet: /local/floorplan/examples/home/home.css
          log_level: info
          console_log_level: info
          rules:
            - entities: 
                - switch.dining 
                - light.family 
                - light.spare 
                - light.office 
                - light.laundry 
                - light.kitchen 
                - light.bath 
                - light.spotlights 
                - light.string 
                - switch.hall
              tap_action: false
              state_action:
                service: floorplan.class_set
                service_data: light-${entity.state}
            - entities: 
                - light.bedroom 
                - switch.dining 
                - light.family 
                - light.spare 
                - light.office 
                - light.laundry 
                - light.kitchen 
                - light.bath 
                - light.spotlights 
                - light.string 
                - switch.hall
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.style_set
                service_data:
                  element: ${entity.entity_id.replace('light.', 'light_overlay.'} 
                  style: |
                    some_css_characteristic: SOMETHING NEEDS TO GO HERE. EXAMPLE ON NEXT LINE 
                    opacity: ${(entity.state === "on") ? "1" : "0.1"}
```

also while you absolutely can use `service_data: light-${entity.state}` you might get errors or unexpected behaviour if the entity is unavailable. so I use these sorts of checks:
`'${(entity.state === "on") ? "light-on" : "light-off"}'`
`'${(["off", "unavailable", "idle", "paused"].includes(entity.state)) ? "media_player-off" : "media_player-on"}'`
