### DISCUSSION TITLE
Casting to Nest Hub: Custom element doesn't exist: floorplan-card

### DISCUSSION THREAD

**Discussion by Puddingpanzer** [ExperienceLovelace/ha-floorplan#187] [Q&A]
Hi, I set up my first floorplan and it works just fine in Browser and App. But when I try to cast the view via script on my Nest Hub it displays "Custom element doesn't exist: floorplan-card". How is this possible? Restarting HA and Nest Hub no difference. See the screenshot of my configuration. ha-floorplan installed via HACS. Other custom cards are working (i.e. webrtc camera)

Browser View:
![2022-01-12 12_10_57-Overview - Home Assistant - Chromium](https://user-images.githubusercontent.com/97258056/149129797-a18deaa7-6973-475b-a120-4459afe8d7c0.jpg)

Resource:
![2022-01-12 12_10_04-Configuration - Home Assistant - Chromium](https://user-images.githubusercontent.com/97258056/149129799-8afef465-d86f-41f5-a866-7c05daa56586.jpg)

File path:
![2022-01-12 12_09_46-NAS - Synology DiskStation - Chromium](https://user-images.githubusercontent.com/97258056/149129800-cf91e040-7733-48ff-a971-597ff9f7bc2b.jpg)

Cast Script:
![2022-01-12 12_11_39-Configuration - Home Assistant - Chromium](https://user-images.githubusercontent.com/97258056/149129791-8c2be283-0e74-4278-b1bf-8d2f3d3a333e.jpg)

Nest Hub error:
![20220112_115408](https://user-images.githubusercontent.com/97258056/149130464-b041e561-79ce-4346-9d17-539e6eb3a350.jpg)

**Comment by OzGav** [comment]
Yes I see some threads about a bunch of cards with the same problem. We will take a look at it.

**Comment by OzGav** [comment]
Looks like there are a bunch of potential issues. One might be the floorplan code but you can try this first:

According to here: https://community.home-assistant.io/t/custom-components-and-home-assistant-cast-solved/216762 the issue might be that the resource URL is using `/hacsfiles` instead of `/local/community` I saw some talk that if you just add another entry that causes the resource to be loaded twice which slows things down. Up to you whether you want to do that or just change your existing entry.

According to here https://community.home-assistant.io/t/home-assistant-cast-with-custom-cards/137457/14 you might need to add an entry to the `http:` section of your `configuration.yaml` For example:
```
http:
  cors_allowed_origins:
    - https://cast.home-assistant.io/
```

Try those two things and see if you can get it to work or at least improve and if not then it might be a coding issue in ha-floorplan

**Reply by Puddingpanzer** [reply]
Thank you, changing the resource URL brings me one step further. But now i got a black screen and error regarding the .css. The error doesn't occur in Browser View. Adding entries to cors_allowed_origins doenst affect anything.

![20220112_142619](https://user-images.githubusercontent.com/97258056/149150799-1fbe5c09-a27a-4866-9831-80c9f26c063c.jpg)

**Comment by OzGav** [comment]
Ok glad we have some progress. For any code changes hopefully @exetico will be able to have a look at the `LitElement` comments from here https://community.home-assistant.io/t/home-assistant-cast-with-custom-cards/137457/14

**Reply by Puddingpanzer** [reply]
Ok I temporarily fixed it by adding absolute URLs to my SVG and CSS for image and stylesheet tags. Have to find out why relative URLs are not working

**Reply by exetico** [reply]
HI all,

@OzGav  I don't get this. There's only talk about problems with fetching the CSS and SVG files. Where does the `LitElement` come into play? Nothing here shows a problem with `LitElement` - can't find anything where `LitElement` are mentioned in screenshots or raw text.

**Reply by OzGav** [reply]
I wasn’t sure as I don’t use cast so can’t test. That thread I linked just seemed to indicate others had to fix their custom cards by changing the way `LitElement` was wrapped.

@Puddingpanzer not sure where you were using relative paths before. If you need any more help please provide formatted relevant code excerpts.

**Reply by Puddingpanzer** [reply]
I used the [setup guide](https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/323?u=exetico) by exetico and edited it for my simple purpose for two lights and relative paths like the example:

```yaml
  - title: Erdgeschoss
    path: erdgeschoss
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: 'custom:floorplan-card'
                full_height: true
                config:
                  image: /local/floorplan/erdgeschoss/erdgeschoss.svg
                  stylesheet: /local/floorplan/erdgeschoss/erdgeschoss.css
                  log_level: info
                  console_log_level: info
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
                    - entity: light.stehlampe
                      element: light.stehlampe
                      tap_action: toggle
                    - entity: light.tischlicht
                      element: light.tischlicht
                      tap_action: toggle
```
as this didn't worked i changed the paths to absolutes, for example:

```yaml
                  image: https://my.domain.de/local/floorplan/erdgeschoss/erdgeschoss.svg
                  stylesheet: https://my.domain.de/local/floorplan/erdgeschoss/erdgeschoss.css
```
