### DISCUSSION TITLE
Trouble getting one svg to render but not another

### DISCUSSION THREAD

**Discussion by jtermi03** [ExperienceLovelace/ha-floorplan#188] [Q&A] [answered]
So after digging through the starting material and a lot of the very helpful posts here, I finally have a working prototype of my basement floorplan. However, the 1st and 2nd floors (which I have as additional cards) do not display in Lovelace, even though I've configured them the same. The logs only show a few expected missing HA entities that I didn't bother commenting out and a few missing temperature svg elements that I'm asking about separately. Switching logging to debug only showed the HA entity states properly loading. Could someone take a look?

SVGs: [floorplan.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/7856504/floorplan.zip)

Lovelace Custom Card YAML:
```
views:
  - title: Floorplan
    cards:
      - type: custom:floorplan-card
        title: Basement
        full_height: true
        config:
          image: /local/floorplan/basement.svg
          stylesheet: /local/floorplan/floorplan.css
          log_level: info
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:
            - name: Rooms
              entities:
                - entity: light.basement_shed_light
                  element: area.shed
                - entity: light.basement_shop_light
                  element: area.shop
                - entity: light.basement_utility_light
                  element: area.utility_closet
                - entity: light.basement_laundry_light
                  element: area.laundry_room
              tap_action: light.toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "icon-show" : "icon-hide"}'
            - name: Door/Window Sensors
              entities:
                - binary_sensor.shed_garage_door
                - binary_sensor.basement_shed_door
                - binary_sensor.shed_window_1
                - binary_sensor.shed_window_2
                - binary_sensor.shop_motion
                - binary_sensor.laundry_room_motion_detection
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "icon-show" : "icon-hide"}'
            - name: Temperature
              entities:
                - temp.basement
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ? Math.round(entity.state *
                    10) / 10 + "°" : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: current-temp
      - type: custom:floorplan-card
        title: 1st Floor
        full_height: true
        config:
          image: /local/floorplan/floor1.svg
          stylesheet: /local/floorplan/floorplan.css
          log_level: debug
          console_log_level: debug
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:
            - name: Rooms
              entities:
                - entity: light.garage_lights
                  element: area.garage
                - entity: light.foyer_overhead_lights
                  element: area.foyer
                - entity: light.front_porch_light
                  element: area.front_porch
[floorplan.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/7856536/floorplan.zip)

                - entity: light.living_room_overhead
                  element: area.living_room
                - entity: light.patio_light
                  element: area.patio
                - entity: light.back_porch_light
                  element: area.back_porch
                - entity: light.powder_room_overhead_light
                  element: area.powder_room
                - entity: light.pantry_light
                  element: area.pantry
                - entity: light.kitchen_lights
                  element: area.kitchen
                - entity: light.dining_room_lights
                  element: area.dining_room
                - entity: light.sun_room_lights
                  element: area.sun_room
              tap_action: light.toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "icon-show" : "icon-hide"}'
            - name: Light Icons
              entities:
                - light.garage_lights
                - light.foyer_overhead_lights
                - light.front_porch_light
                - light.living_room_overhead
                - light.patio_light
                - light.back_porch_lights
                - light.powder_room_overhead_light
                - light.pantry_light
                - light.kitchen_lights
                - light.dining_room_lights
                - light.sun_room_lights
              tap_action: light.toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
            - name: Door/Window Sensors
              entities:
                - binary_sensor.sun_room_motion_detection
                - input_boolean.kitchen_motion
                - binary_sensor.dining_room_motion_detection
                - binary_sensor.foyer_motion_detection
                - binary_sensor.living_room_motion_detection
                - binary_sensor.garage_motion_detection
                - binary_sensor.front_door_access_control_window_door_is_open
                - binary_sensor.garage_door_1
                - binary_sensor.garage_door_2
                - binary_sensor.garage_side_door
                - binary_sensor.living_room_door_frontpoint
                - binary_sensor.kitchen_door
                - binary_sensor.living_room_window_1
                - binary_sensor.living_room_window_2
                - binary_sensor.powder_room_window
                - binary_sensor.kitchen_window_l2
                - binary_sensor.kitchen_window_l1
                - binary_sensor.kitchen_window_l1
                - binary_sensor.kitchen_window_r2
                - binary_sensor.sun_room_window_l1
                - binary_sensor.sun_room_window_l2
                - binary_sensor.sun_room_window_l3
                - binary_sensor.sun_room_window_l4
                - binary_sensor.sun_room_window_c1
                - binary_sensor.sun_room_window_c2
                - binary_sensor.sun_room_window_c3
                - binary_sensor.sun_room_window_r1
                - binary_sensor.sun_room_window_r2
                - binary_sensor.sun_room_window_r3
                - binary_sensor.sun_room_window_r4
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "icon-show" : "icon-hide"}'
            - name: Temperature
              entities:
                - sensor.living_room_thermostat_temperature
                - sensor.kitchen_thermostat_temperature
                - sensor.sun_room_thermostat_temperature
                - sensor.garage_thermostat_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ? Math.round(entity.state *
                    10) / 10 + "°" : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: current-temp
```
CSS:

```
#floorplan  {
  padding: 10px;
}

/* #floorplan svg{
  height: 100vh!important;
} */

svg tspan {
  fill: var(--primary-text-color);
}

/* SVG shapes */

svg, svg * {
  vector-effect: non-scaling-stroke !important;
  pointer-events: all !important;
}

/* Hover over */
.ha-entity:hover {
  stroke: #03A9F4 !important;
  stroke-width: 1px !important;
  stroke-opacity: 1 !important;
}

/* Light Control */

.light-on {
  fill: #FFCC00 !important;
}

.light-off {
  fill: #808080 !important;
  transition: opacity .5s;
}

/* Binary Sensors */

.icon-show {
  opacity: 1 !important;
  transition: opacity .25s;
}

.icon-hide {
  opacity: 0 !important;
  transition: opacity .25s;
}

/* Things Control */

[id*="thing."].thing-on{
  opacity: 1 !important;
  filter: drop-shadow(0px -5px 3px #ffedde);
  fill: #fffae54f !important;
}

[id*="thing."]{
  opacity: 0 !important;
  transition: opacity .25s;
  -moz-transition: opacity .25s;
  -webkit-transition: opacity .25s;
}

/* Temperature text */

.static-temp, .static-temp tspan {
  fill: #ffffff;
}
```

Basement Log:

```
    1/12/2022, 12:22:53 PM WARNING CONFIG Cannot find 'temp.basement' in Home Assistant entities
    1/12/2022, 12:22:53 PM WARNING CONFIG Cannot find element 'binary_sensor.laundry_room_motion_detection' in SVG file
    1/12/2022, 12:22:53 PM WARNING CONFIG Cannot find 'binary_sensor.shop_motion' in Home Assistant entities
    1/12/2022, 12:22:53 PM WARNING CONFIG Cannot find 'binary_sensor.shed_window_2' in Home Assistant entities
    1/12/2022, 12:22:53 PM WARNING CONFIG Cannot find 'binary_sensor.shed_window_1' in Home Assistant entities
    1/12/2022, 12:22:53 PM INFO INIT Floorplan for Home Assistant (ha-floorplan) v1.0.28
```

1st Floor Log:

```
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find element 'sensor.living_room_thermostat_temperature' in SVG file
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find 'sensor.garage_thermostat_temperature' in Home Assistant entities
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find 'binary_sensor.foyer_motion_detection' in Home Assistant entities
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find element 'light.powder_room_overhead_light' in SVG file
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find element 'light.patio_light' in SVG file
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find element 'light.living_room_overhead' in SVG file
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find element 'light.front_porch_light' in SVG file
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find 'light.pantry_light' in Home Assistant entities
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find 'light.back_porch_lights' in Home Assistant entities
1/12/2022, 12:24:26 PM WARNING CONFIG Cannot find 'light.pantry_light' in Home Assistant entities
1/12/2022, 12:24:25 PM INFO INIT Floorplan for Home Assistant (ha-floorplan) v1.0.28
```
