### DISCUSSION TITLE
Conditionally changing which object is used by a rule

### DISCUSSION THREAD

**Discussion by jtermi03** [ExperienceLovelace/ha-floorplan#194] [Q&A]
Right now, my floorplan has a lights-off-background image that is always visible on the bottom layer and toggling lights shows/hides clipped images of each room with their lights on.

I'd like to have the room lighting reflect day/night status, so I also have an alternate lights-off-background-night with matching lights-on-night room areas, but haven't figured out how to leverage them.

I'm thinking that if I have a day/night boolean in HA, the YAML could reference it to choose which image to show, something to the effect of the below, any ideas?

```
          rules:
            - name: Rooms
              entities:
                - entity: light.living_room_light
                  IF day-night-boolean = 'day' THEN element: area.living_room
                  IF day-night-boolean = 'night' THEN element: area.living_room.night
              tap_action: light.toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "object-show" : "object-hide"}'
            - name: Background
              elements:
                  IF day-night-boolean = 'day' THEN element: background.day
                  IF day-night-boolean = 'night' THEN element: background.night
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "object-show" : "object-hide"}'
```
