### DISCUSSION TITLE
Undefined values for floorplan service actions

### DISCUSSION THREAD

**Discussion by adamgross42** [ExperienceLovelace/ha-floorplan#195] [Q&A] [answered]
Hi there,

I have an SVG file and configuration working fine for `tap_action`, but am having issues with `state_action`.  Looking at the [examples](https://experiencelovelace.github.io/ha-floorplan/docs/example-home/), I do see that `floorplan.class_set` and `floorplan.style_set` should work on a `switch` entity.

With `floorplan.class_set`, when the entity state changes, the SVG element gets a class of `undefined` applied, instead of the expected class or style.

With `floorplan.style_set`, nothing happens to the SVG element.  I was expecting the style `fill: yellow;` to be added.

The SVG element with this ID is of type `path` not type `g` as seen in the examples - could that be the issue?
Or any other thoughts on why the service isn't able to manipulate the SVG element?

Here is the approach I am taking:

```
  rules:
    - entities:
        - switch.living_room_lamp
      tap_action: homeassistant.toggle
      state_action:
        - action: call-service
          service: floorplan.class_set
          service-data: light-${entity.state}
        - action: call-service
          service: floorplan.style_set
          service-data: 'fill: yellow;'
```

I've also tried enumerating `service-data` in YAML to the Service Data Properties (`class` and `style`) per the [documentation](https://experiencelovelace.github.io/ha-floorplan/docs/usage/#services) for verboseness, that didn't change anything.

I've also tried putting single quotes around `light-${entity.state}` but the Home Assistant Lovelace web editor strips those out.

-----

Update:

Chrome browser JS console is showing an error for the style service, `TypeError: (intermediate value)(intermediate value)(intermediate value).split is not a function`.
Looking within the JS debugger, I can see that the `floorplan.js` function `setStyle()` (I think called from [here](https://github.com/ExperienceLovelace/ha-floorplan/blob/cbf735a09f6f58a8148d4e5ddb76c767b2429414/src/components/floorplan/floorplan-element.ts#L1987)) is trying to manipulate an SVG element with ID `switch.living_room_lamp.undefined` instead of `switch.living_room_lamp`.  Not sure where that string is coming from yet.

**Comment by OzGav** [comment]
I think the single quotes should be there. I edit my YAML with a text editor so I don't see the stripping that you have noticed. Try this YAML and if it doesn't work then might be an issue with your SVG. Also the style set doesn't make sense to me as you are filling with yellow for any state change. You would be better to just fill it yellow in your SVG and leave that out. In case that was a mistake I have shown an option to have it change from yellow to blue depending upon the state.

```
  rules:
    - entities:
        - switch.living_room_lamp
      tap_action: switch.toggle
      state_action:
        - action: call-service
          service: floorplan.class_set
          service-data: 'light-${entity.state}'
        - action: call-service
          service: floorplan.style_set
          service_data: 
            style: |
              fill: ${(entity.state === "on") ? "yellow" : "blue"}
```

**Reply by adamgross42** [reply]
Thanks for this sample.  I reconfigured Lovelace with a raw YAML file instead of using the web UI, but am still getting the same result.  Even if I put a static string `'light'` instead of `'light-${entity.state}'`, the HTML class isn't being appended.

In my configuration, I have multiple entities, and I just discovered that the `action`s are only being called on one of them - I don't know why not all of them.  When I click on the SVG, the `tap_action` executes just fine (the lights/switches physically turn on and off), but the `state_action`s aren't executing.
I also tested everything with a single entity definition, instead of using `entities` - same result.

The SVG elements look identical for the various entities, and they are all `switch` entities, so I don't think the SVG itself is the issue.  Is it possible that they don't expose the same metadata within Home Assistant somehow?  I see that one `switch` entity has the attribute `device_class: outlet` set, while others don't - but I don't see anything in the code for `ha-floorplan` that would care about `device_class`.

Doing some more breakpointing in JS with Chrome's debugger, I am seeing issues with [this for loop](https://github.com/ExperienceLovelace/ha-floorplan/blob/cbf735a09f6f58a8148d4e5ddb76c767b2429414/src/components/floorplan/floorplan-element.ts#L1946) - it iterates over a list with exactly one element in it, but the value by which the iteration is tracked (`targetSvgElement`) doesn't at all match the single element in the list `targetSvgElements` - it starts out with the correct SVG object, but then iterates a second time and ends up being the string `floorplan` which is the HTML ID for the container for this whole UI.

I may try to set up a development environment to debug this further, not sure what is happening...any tips are welcome!

Thanks also for the style syntax fix!

**Reply by OzGav** [reply]
Maybe there is an issue with your SVG or maybe a misunderstanding about how floorplan works. Based on some of the things you wrote above I will just talk a bit about how floorplan works.

If we take the example I provided above you should have a single object in your SVG which has the id `switch.living_room_lamp`. Assuming there are no other objects in your SVG which are obscuring it when you click/tap on the object it’s state will toggle and the both the class will be set as well as the style. It is probably unusual that you are doing both, I generally use `class_set` as I typically use the same styling for consistency.

As for a YAML entry for multiple entities you can certainly do that. I will provide an example in the next post but if you are finding you can tap on the object and it physically toggles state but your SVG does not change appearance then it sound like a problem with your YAML or CSS. You will be best to post a formatted excerpt of the non-working YAML and your SVG. We can then test it on our systems.

**Reply by OzGav** [reply]
Here is an example of multiple entities: (I use `homeassistant.toggle` as there are switches and lights)

```
            - tap_action:
                service: homeassistant.toggle
              entities:
                - light.abigail_bedside
                - light.hue_white_lamp_3
                - light.hue_white_lamp_2
                - switch.hannah_beside
                - switch.grace_switch
                - light.kids_desk_light
                - light.spare_bedroom
                - light.fairy_lights
                - switch.tank_pumo
                - light.pantry_bench_white
                - switch.car_charger
                - switch.main_pc_wol 
              name: Light and other icons
              state_action:
                service: floorplan.class_set
                service_data: 
                  class: '${(entity.state === "on") ? "lamp-on" : (entity.state === "off") ? "lamp-off" : "entity-unavailable"}'
```

**Reply by adamgross42** [reply]
Thanks, I agree setting both the class and style are unnecessary, was just doing that for testing.  I cleaned that up a bit below.

Here is my latest iteration of the YAML (changed the entity name slightly, but it still matches 1:1 with the SVG):

```
type: custom:floorplan-card
config:
  console_log_level: debug
  image: /local/home.svg
  stylesheet: /local/home.css
  defaults:
    hover_action: hover-info
    tap_action: more-info
  rules:
    - entities:
        - switch.living_room_corner_lamp
      tap_action: homeassistant.toggle
      state_action:
        service: floorplan.class_set
        service-data:
          class: light-${entity.state}
```

And the greatly-simplified SVG (for testing this feature):

```
<svg
   version="1.1"
   id="svg222"
   width="960"
   height="679"
   viewBox="0 0 960 679"
   sodipodi:docname="home.svg"
   inkscape:version="1.1.1 (c3084ef, 2021-09-22)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
<g
     inkscape:groupmode="layer"
     id="layer3"
     inkscape:label="Entities"
     style="display:inline">
    <path
       d="m 203.33602,463.73973 -6.78991,5.13595 3.61258,4.17841 v 33.94952 h -13.05751 v 8.70501 h 34.82003 v -8.70501 h -13.05752 v -33.51427 l 3.69963,-4.52661 -6.87695,-5.17948 -2.35035,-0.0435 m -14.84204,-20.67439 3.96078,12.53521 -1.00108,0.78345 -11.01183,-7.26868 8.05213,-6.04998 m 4.65718,-14.40679 -27.8125,20.93554 26.46322,17.45354 10.75068,-8.22623 -9.4014,-30.16285 m 27.33372,14.36326 8.09566,6.09351 -11.01184,7.26868 -1.00107,-0.73993 3.91725,-12.62226 m -4.61365,-14.36326 -9.44494,30.2499 10.79421,8.13918 26.46322,-17.45354 z"
       id="switch.living_room_corner_lamp"
       style="stroke-width:4.3525"
       inkscape:label="Living Room Corner Lamp" />
</g>
</svg>
```
