### DISCUSSION TITLE
What should we expect from "state_action" just after loading the page?

### DISCUSSION THREAD

**Discussion by arnaupv** [ExperienceLovelace/ha-floorplan#198] [Q&A]
Hi all, I'm trying to use **state_action** here:
```
rules:
  - entity: sensor.019676_ta
    element: text_r0c1
    state_action:
      action: call-service
      service: floorplan.text_set
      service_data:
        element: text_r0c1
        text: '${entity.state == "unavailable" ? "     -" : entity.state}'
```
From the documentation, I expect that the element `text_r0c1` text will be updated each time that `sensor.019676_ta` is updated. However I do not see this in my floorplan. Everything works fine when I use `tap_action` and click on the element. 

Question: 
Should the **text** of `text_r0c1` be replaced just after loading the page with the newest value of the entity? If this is NOT the case, how can I do that? Should I use `startup_action` for this purpose? Can I use entity values in the `startup_action`? :thinking: 

Thanks!
