### DISCUSSION TITLE
Is the "variables" definition still supported?

### DISCUSSION THREAD

**Discussion by arnaupv** [ExperienceLovelace/ha-floorplan#199] [Q&A] [answered]
I do not see any example in the documentation of how to define "variables".
However, this is present in the code v1.0.30

I remember that I saw some docs about the topic (some Examples), but I'm wondering if this feature is being deprecated and if there is documentation still available.

**Comment by OzGav** [comment]
Do you mean like used here? https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/433?u=ozgav

**Comment by arnaupv** [comment]
Hi @OzGav , I mean, like described [here](https://github.com/ExperienceLovelace/lovelace-floorplan/blob/024e3b51151d3b63355b672d761bb9836dd60b74/src/lib/floorplan.js#L574-L632) in the code.

And [here](https://github.com/ExperienceLovelace/lovelace-floorplan/blob/024e3b51151d3b63355b672d761bb9836dd60b74/src/lib/floorplan.js#L2035-L2051) in the floorplan actions.

**Comment by OzGav** [comment]
I had forgotten about this. I don’t use it but here is someone who did it might help you?

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/www/custom_ui/floorplan/clock_config.yaml

I don’t know why @pkozul didnt add reference to this in the docs?

**Comment by exetico** [comment, marked as answer]
I know this is a old discussion, but the variables is still in use. I've mentioned for @pkozul, that it's still missing in the docs.

With that said, the following solution works as expected:
```yaml
      variables:
      # Name can also be something without the "floorplan." prefix
      # it's just easier to handle and navigate in the keys
        - name: floorplan.state_light_spotlys_gang
          value: 'null'
        - name: floorplan.example_variable
          value: 'Bob example initiated'

      startup_action:
      # variable_set will only work as expected, if the variables has been declared in the variables: key
        - service: floorplan.execute
          service_data:
            script1: |
              > // Example  
              console.log("🥸 Floorplan started - I'm triggered by the startup_action config-key");
        - service: floorplan.variable_set
          service_data:
            variable: floorplan.example_variable
            value: |
              > console.log("🥸 Hi, example_variable will now be defined");
              return "Bob updated in startup_action";
        - service: floorplan.variable_set
          service_data:
            variable: floorplan.state_light_spotlys_gang
            value: |
              > // Not used for anything, but examples to ha-floorplan
              return "initiated";
```

Hopefully other people can use this for something :smile: .
