### DISCUSSION TITLE
Toggle an HA Group

### DISCUSSION THREAD

**Discussion by philosowaffle** [ExperienceLovelace/ha-floorplan#200] [Q&A]
Hello! Have a question about toggling a group of entities, sorry if this has been asked before. I did some searches through the discussions but did not find anything that seemed the same.  So lets say I have the following setup in HA:

- group.myGroup
  - light.lightA
  - light.lightB

In HA lovelace, I can create a card like below. It references the `group.myGroup` entity and calls the `Toggle` action on tap.  If any single light in the group is ON, then toggling the Group will turn them all OFF. And if all of the lights are OFF, then toggling the Group will turn them all ON.  This works by default in HA, no custom scripts needed. This is the behavior I am trying to mimic in floorplan.

```
if (all lights in group off) then turn all lights in group on;
if (any one light in group is on) then turn all lights off;
```

![2022-02-05_16-05-44](https://user-images.githubusercontent.com/7275041/152660542-26c20f96-10d8-486c-a116-03a65d9abee9.png)

Now in my SVG I have an element `group.myGroup` and in my yaml I define the following:

```
- entity: group.myGroup
   element: group.myGroup
   tap_action: toggle
```

When both `lightA` and `lightB` have a matching state, this works exactly as expected, both entities are toggled either on or off on tap.

The problem arises when `lightA=on` and `lightB=off`.  When the `homeassistant.toggle` service is called, it toggles each entity in the group individually, instead of toggling the group as a whole. So the end result is `lightA=off` and `lightB=on`.

I did some testing on HA in the Developer Tools, if you call the `homeassistant.toggle` for a `group` entity it also yields this weird behavior of toggling each entity in the group instead of the group as a whole. So I'm not sure how the lovelace is working, its clearly doing more than just using the underlying HA toggle service.

So, my question. Given this limitation in the `homeassistant.toggle` service, is there a way I can use functions or something in my floorplan yaml to achieve the same behavior as toggling a group from lovelace?

**Comment by OzGav** [comment]
I’m not sure I would call it a limitation as it is toggling the state of each entity in the group. If I understand you correctly you would like both lights to turn on if they are both off and both to turn off if either or both are on. To do that I use a script.

**Reply by philosowaffle** [reply]
In all cases in the HA UI, if you "toggle" a group entity, it behaves such that all lights turn on if all are off, and all turn off if any are on.  This is [the expected behavior for toggling a group entity](https://www.home-assistant.io/integrations/group/#group-behavior).

But the HA toggle service, passing in a  group entity, does not behave this way. It toggles each entity in the group individually. Which is not the expected behavior for toggling a group entity.

The limitation here is that HA does not seem to provide a service that allows you to toggle a group entity per the documented group behavior.


Edit: Writing a custom HA script is one valid way to work around this limitation. I was hoping, however, that I had missed something and there would be an easier to maintain/simpler solution someone had figured out.

**Reply by philosowaffle** [reply]
Did some more research, a similar question has been asked on the [HA forums](https://community.home-assistant.io/t/automation-make-groups-toggle-as-a-whole-like-in-ui/15557). And the solution is to use the below service template, which makes sense:

```
service_template: >
        {% if is_state('group.outside_lights','off') %}
          homeassistant.turn_on
        {% else %}
          homeassistant.turn_off
        {% endif %}
```

 I see documentation of how to template the `serivce_data` field but not anything about `serivce` itself.

Does ha-floorplan support templating in the [service](https://experiencelovelace.github.io/ha-floorplan/docs/usage/#call-service) field?

**Reply by OzGav** [reply]
Yeah ok I see what you mean. I haven’t tried templating the service field but give it a go. If it doesn’t work then use a script which is what I do.

**Reply by philosowaffle** [reply]
Closing the loop on this with a solution.  Templating the service field did not seem to work, so had to go the script route.

1. Create a generic Script in HA `script.toggle_group_entity`. This will be reusable for any time you want to script toggling a group entity.
```
alias: Toggle Group Entity
mode: single
icon: mdi:lightbulb-group-outline
description: Toggles a group entity using the default group on/off behavior
fields:
  group_entity:
    name: group_entity
    description: The group entity to be toggled
    required: true
    example: group.living_room_lights
    selector:
      entity:
        domain: group
sequence:
  - choose:
      - alias: If group is ON
        conditions:
          - condition: template
            value_template: '{{ is_state(group_entity, ''on'') }}'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: '{{ group_entity }}'
      - alias: If group is OFF
        conditions:
          - condition: template
            value_template: '{{ is_state(group_entity, ''off'') }}'
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: '{{ group_entity }}'
```

2. Update your floorplan.yaml with the following:
```
- entity: group.living_room_lights
    element: group.living_room_lights
    tap_action: 
      action: call-service
      service: script.turn_on
      service_data:
        entity_id: script.toggle_group_entity
        variables:
          group_entity: group.living_room_lights
    state_action:
      - action: call-service
        service: floorplan.class_set
        service_data:
          class: |
            >
            if (entity.state == 'off')
              return "light-off";

            if (entity.state == 'on')
              return "light-on";
```
