### DISCUSSION TITLE
The motion sensor status is not displayed. The sensor is located on the balcony floor of the first floor，Help, thanks developers

### DISCUSSION THREAD

**Discussion by ahonxxx** [ExperienceLovelace/ha-floorplan#219] [Q&A] [answered]
The problem is with this SVG image, which I exported from Sweet Home 3D and added the balcony property
binary_sensor.0x00158d00045b03f1_contact
Draw a rectangle individually, add attributes, work fine, sweethome exported svg directly add attributes problematic, thanks
![home](https://user-images.githubusercontent.com/54906315/167251980-49a2ea16-9f0a-419f-ae1b-cb273dcfc0ce.svg)

**Comment by exetico** [comment, marked as answer]
Hi

# Things I'd like to know

If the "Possible solution" doesn't help, please answer the following question, and include your yaml-code in the discussion.

Thanks!

1) What have you tried?
2) What is your current YAML setup
3) Have you secured that the element in the SVG matches the binary_sensors ID, or have you made the mapping in YAML, so ha-floorplan knows that you're trying to add binary_sensor.x to div-element y?


## Possible solution

Here's one of my solutions for a sensor, mapped to a SVG-element:

```yaml
name: Temperatur Hallway
element: sensor.hallway
entities:
  - sensor.aqara_sensor2_temperature
state_action:
        - service: floorplan.text_set
          service_data: '${entity.state ? Math.round(entity.state * 10) / 10 + "°" : "unknown"}'
        - service: floorplan.class_set
          service_data:
            class: 'static-temp'
```

![image](https://user-images.githubusercontent.com/3549445/167253595-14c9de77-3345-44ee-8478-096c488e50bb.png)

Note that the HA-sensor and the SVG text ID is not the same. I guess that's your problem? 
My Home Assistant sensor: `sensor.aqara_sensor2_temperature`
Is mapped to the SVG "text"-element with the following ID: `sensor.hallway`

So please follow the same kind of solution, if that's your problem.

I also noticed that you'e trying to change this:
![image](https://user-images.githubusercontent.com/3549445/167253727-62bc963e-80a1-4989-846a-fe0ffcd01b0f.png)

If that's the actual problem, you'd need to configure some CSS or make the JS code for the logic.

In my hallway I've the following solution:
```yaml
name: Hallway
entities:
  - light.spotlys_gang
  - switch.sonoff5
element: area.hallway
# groups: # Can be used to open group
#   - group.office
tap_action:
  service: light.toggle
  service_data:
    entity_id: light.spotlys_gang
state_action:
  service: floorplan.class_set
  service_data:
    class: '${(entity.state === "on") ? "light-on" : "light-off"}'
```

Here the class is defined to the path with ID `area.hallway`, on basis of the entities on both light.spotlys_gang and switch.sonoff5. I've added CSS styling for the classes called `light-on` and `light-off`

![image](https://user-images.githubusercontent.com/3549445/167253779-60ceb3b4-5cb6-4db1-8033-b12197ea4f51.png)

![image](https://user-images.githubusercontent.com/3549445/167253871-5a4099be-493d-4de1-8c5b-0b9b8b02eebe.png)
