### DISCUSSION TITLE
Sizing of icon svg files not to scale with floorplan.svg

### DISCUSSION THREAD

**Discussion by gillman99** [ExperienceLovelace/ha-floorplan#22] [Q&A] [answered]
It was recommended that I start another topic on this since it's a separate problem.  Below are screen shots of my svg in Inkscape and the 2nd is the svg in Floorplan/HA.  You can see the size of the 1 icon that I'm trying to add color change to is not consistent with the original svg.  I'm looking for pointers on why this is.  I've included my yaml code and css file below as well.  

Thanks in advance for your help.

![image](https://user-images.githubusercontent.com/76920134/104855985-86561980-58d5-11eb-86cb-842e290dbfe2.png)

![image](https://user-images.githubusercontent.com/76920134/104855996-8c4bfa80-58d5-11eb-8507-76ddbc22fad1.png)

```yaml
  - title: Floorplan2
    panel: true
    groups:
      - name: Lights
        entities:
          - light.caseta_r_wireless_in_wall_dimmer_2
          - light.caseta_r_wireless_in_wall_dimmer_3
          - light.caseta_r_wireless_in_wall_dimmer_4
          - light.caseta_r_wireless_in_wall_dimmer_5
        states:
          - state: 'on'
            class: light-on
          - state: 'off'
            class: light-off
        action:
          service: toggle
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          image: /local/floorplan/house2.svg?v=1.1.14
          stylesheet: /local/floorplan/floorplan.css
          defaults:
            hover_action: hover-info
          rules:
            - entity: light.caseta_r_wireless_in_wall_dimmer_5
              element: light.caseta_r_wireless_in_wall_dimmer_5
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: '/local/custom_ui/images/light_${entity.state}.svg'
              tap_action: toggle
            - entity: light.caseta_r_wireless_in_wall_dimmer_5
              element: light.caseta_r_wireless_in_wall_dimmer_5.button
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'button-${entity.state}'
              tap_action:
                action: call-service
                service: homeassistant.toggle
```

Floorplan.css (just changed to .txt so I could upload the file)
[floorplan.txt](https://github.com/ExperienceLovelace/ha-floorplan/files/5826842/floorplan.txt)
