### DISCUSSION TITLE
Make full_height option per image size not overall floorplan

### DISCUSSION THREAD

**Discussion by OzGav** [ExperienceLovelace/ha-floorplan#221] [Hanging feature requests]
I just came across a situation where I have a remote that is basically designed for widescreen (landscape) layouts. I decided I want to be able to use it on my mobile which worked but the buttons were very small. So I created a new SVG for the mobile device and used the image size option to select it like so:
```
cards:   
  - type: 'custom:floorplan-card'
    full_height: true
    config:
#      log_level: debug
      stylesheet:
        location: /local/floorplan/floorplan-remote.css
        cache: true
      image:
        sizes:
          - min_width: 0
            location: /local/floorplan/floorplan_sony_remote_mobile.svg
          - min_width: 700
            location: /local/floorplan/floorplan_sony_remote.svg
```
This works except the mobile version is even smaller now because I made it very tall and narrow and I have `full_height: true` in my config. So I either get the scrolling I want on my mobile and scrolling I don't want on every other device or vica versa. 
So the question is how hard would it be to move the full_height option down to the image location indent level so that it can be set per SVG like so:
```
cards:   
  - type: 'custom:floorplan-card'
    config:
#      log_level: debug
      stylesheet:
        location: /local/floorplan/floorplan-remote.css
        cache: true
      image:
        sizes:
          - min_width: 0
            location: /local/floorplan/floorplan_sony_remote_mobile.svg
            full_height: false
          - min_width: 700
            location: /local/floorplan/floorplan_sony_remote.svg
            full_height: true
```
