### DISCUSSION TITLE
Error using ha-floorplan in ui-lovelace-minimalist panel.

### DISCUSSION THREAD

**Discussion by j4c3** [ExperienceLovelace/ha-floorplan#223] [Bugs] [answered]
I have ha-floorplan setup in a panel based view in a ui-lovelace-minimalist dashboard.

Everything works, but when I go into the floorplan, then back out to the Overview (default) dashboard I have an error-card in the list of cards:

```
Invalid entity ID at position 0: *
type: entities
entities:
  - '*'
title: ''
```

Additionally, in Settings -> Devices -> Entities, I have an entity for * in the list.  Clicking on it has this info:

`This entity ('*') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation] for more detail.`

When I refresh the browser window, the * entity goes away, and does not show the error card in the Overview, or as a line in the entities list, until I browse to the ha-floorplan again.  

I didn't see any info about this, is using the floorplan as a tab/view this way preventing some cleanup code from running?

**Comment by OzGav** [comment]
Yes I can see that entity as well but I don’t have any errors associated with it. Will have to wait and see what @exetico says about this one….

**Comment by exetico** [comment]
I'll hopefully be able to check this in a week. Currently I'm away from my primary work-env. 👍

**Comment by exetico** [comment]
Just had the COVID – _if anyone has heard about that_ (😉). I'm almost back in the game.

Would you be able to share a stripped down version of your config, so I'm able to see how you've used the panel? Just to save me a bit of time.

**Reply by j4c3** [reply]
Oof, glad you're on the mend. 

My dashboard looks like this:

```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "Dashbaord"
theme: "minimalist"
background: "var(--background-image)"
views: !include_dir_merge_list "views/"
```


And the view with the floorplan, "1. floorplan.yaml" is:

```
- title: "Floorplan"
  type: panel
  path: floorplan
  badges: []
  cards:
    - type: 'custom:floorplan-card'
      full_height: true
      card_mod:
        style: |
          .type-custom-floorplan-card {
            margin: 10px;
            padding: 10px;
          }
          .type-custom-floorplan-card .content {
            display: contents !important;
          }
          floorplan-element {
            height: calc((100vh - 56px) - 21px - 30px);
          }                  
          @media (orientation: portrait) {  
            floorplan-element {
              display: block !important;
              height: calc((100vh - 56px) - 21px - 30px);
            }
          }
      config:
        image: /local/floorplan/file.svg
        stylesheet: /local/floorplan/file.css
        defaults:
          hover_action: hover-info
          tap_action: more-info
        startup_action:
          - service: floorplan.class_set
            service_data:
              element: MAIN
              class: visible
          - service: floorplan.class_set
            service_data:
              elements:
                - LOWER
                - UPPER
              class: hidden
        functions: |
          >
          return {
            getDashOffset: (countdownEntity, circle) => {
              if (countdownEntity.state !== undefined) {
                var dashArray = 'stroke-dasharray: ' + circle;
                var dashOffset = 'stroke-dashoffset: ' + circle * ( 1 - ( countdownEntity.state / 60 ));
                return `${dashOffset}`;
              }
            },    
            someOtherFunctionA: (entity) => {
              return 'foo'; 
            },
          };
        rules: !include_dir_merge_list "../rules/1. floorplan/"
```

Once I visit that page, I get the 'error' dialog on the default generated HA dashboard.

**Reply by exetico** [reply]
Hi, 

I tried to read through the issue twice, but I can't get to the same situation as you. I've also updated HA, just to be sure. Where should I look for the entity?

I'm using the Amoled theme, and ha-floorplan is also added as a panel like so:
```yaml
  - title: Floorplan
    icon: 'mdi:floor-plan'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack  
            cards:
              - config: !include lovelace/floorplan/_config-floorplan1.yaml
                type: custom:floorplan-card
                full_height: true
```

There's no errors here, if I jump between two panels.

**Reply by exetico** [reply]
**Update**
Just updated HA, and now I'm seeing:
![image](https://user-images.githubusercontent.com/3549445/175989003-90a500be-f6fe-4306-b266-ab79a24f79b5.png)

But I'm not seeing any errors related to the `*` element. But it's for sure generated with ha-floorplan. Well...

**Reply by OzGav** [reply]
Glad you are feeling better Tobias, yes I don’t see any errors as well but the OP indicated it was happening with the auto generated dashboard which I don’t use and I assume you don’t either. So I guess HA is trying to create a card with that entity but it is failing. Can you work out how or why this entity is being created?

**Reply by OzGav** [reply]
Another user just reported  this issue on the HA forums…

**Reply by eyalcha** [reply]
It also happens to me. If it helps, here is my simple dashboard. I use latest HA version. Note that after refreshing the page (not the floor plan page, the overview page), it disappears.I also see the '*' in the entities page.

```
title: Floorplan
views:

  - title: Ground Floor
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          image: /local/floorplan/floor1.svg?version=1.0.1
          stylesheet: /local/floorplan/floorplan.css?version=1.0.0
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:
            - entity: light.1
              element: light.1
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data:
                  image: /local/floorplan/lightbulb_${entity.state}.svg
                  cache: true          
              tap_action:
                action: call-service
                service: homeassistant.toggle
```
