### DISCUSSION TITLE
browser mode map card required second trigger to activate

### DISCUSSION THREAD

**Discussion by Alfiegerner** [ExperienceLovelace/ha-floorplan#224] [General]
Hi all, 

Minor annoyance just wondering if anyone has seen this and might have a solution.

At some point over the last year I think, my browser mod popup (coded as a more info) which has an embedded map card won't launch the map on the first attempt. But launching the popup second time it works fine.

So, first attempt:

![image](https://user-images.githubusercontent.com/596188/178132174-35ff5328-8203-4cdb-8509-1e06232ac53e.png)

And second:

![image](https://user-images.githubusercontent.com/596188/178132190-9aaae6d7-3b8c-498a-83f1-8beb0510fe12.png)

Full code for the popup below.  As I mentioned this used to work first time, not sure if something might have happened like in the slightly distant past where we needed to 'preload' some cards, any thoughts welcome.

Cheers.

```
   popup_cards:
      vacuum.chop_chop:
        title: Chop Chop
        card:
          cards:
            - entities:
                - entity: device_tracker.chop_chop
              hours_to_show: 12
              type: map
              dark_mode: false
              default_zoom: 20
            - entities:
                - entity: vacuum.chop_chop
                  type: custom:multiple-entity-row
                  name: chop chop
                  secondary_info: last-changed
                  entities:
                    - icon: mdi:play
                      tap_action:
                        action: call-service
                        service: vacuum.start
                        service_data:
                          entity_id: vacuum.chop_chop
                    - icon: mdi:pause
                      tap_action:
                        action: call-service
                        service: vacuum.pause
                        service_data:
                          entity_id: vacuum.chop_chop
                    - icon: mdi:home
                      tap_action:
                        action: call-service
                        service: vacuum.return_to_base
                        service_data:
                          entity_id: vacuum.chop_chop
                - type: custom:fold-entity-row
                  head:
                    type: section
                    label: Timers
                  entities:
                    - entity: input_datetime.main_garden_timer
                    - entity: input_datetime.driveway_garden_timer
                    - entity: input_datetime.start_main_garden_time
                    - entity: input_datetime.open_boundary_wire_time
                    - entity: input_boolean.automower_main_garden_timer_finished
                    - entity: input_boolean.automower_driveway_garden_timer_finished
                    - entity: input_boolean.automower_driveway_mode
                    - entity: timer.main_garden
                    - entity: timer.driveway_garden
                - type: custom:fold-entity-row
                  head:
                    type: section
                    label: Controls
                  entities:
                    - entity: input_boolean.daytime_mower_allowed
                    - entity: input_boolean.nighttime_mower_allowed
                - type: custom:fold-entity-row
                  head:
                    type: section
                    label: Rain
                  entities:
                    - entity: binary_sensor.rain_sensor
                    - type: custom:hui-element
                      card_type: history-graph
                      entities:
                        - entity: sensor.rain_sensor_analogue
                      hours_to_show: 24
                      refresh_interval: 0
                    - type: custom:hui-element
                      card_type: history-graph
                      entities:
                        - entity: sensor.water_tank_house_percentage
                      hours_to_show: 24
              show_header_toggle: false
              type: entities
          type: vertical-stack
```
