### DISCUSSION TITLE
Switching between floors

### DISCUSSION THREAD

**Discussion by beniwohli** [ExperienceLovelace/ha-floorplan#23] [Q&A] [answered]
Heya!

First of all, congrats on the new version of floorplan, amazing work!

Now, my house has 3 floors. Currently, I have arranged them next to each other on the SVG. However, especially on my phone, this makes the floors tiny and hard to interact with. I think I saw projects in the past that had some kind of a floor switcher. My plan was to add three elements to the SVG, with click handlers that show/hide the appropriate floor. Unfortunately, I haven't really kept up with Javascript since the days of jQuery, so I'm a bit stumped how and where I could add my JS code. I tried to embed it in the SVG itself, but there it doesn't seem to get executed. And adding it in the document root makes the SVG elements somewhat inaccessible behind a plethora of `shadowRoot`s...

Any ideas how I could achieve this?

**Comment by exetico** [comment]
Hi

One take could be to just have three views, and just switch between them with a service-call to HA.

But I think @pkozul have talked about a way of handling multiple floors, but I need to check, if the first suggestion can't fit your needs :-)

**Reply by ahonxxx** [reply]
Needed Showing/Hiding Layers in Floorplan，How to write yaml and CSS，thank you 。

**Comment by vajonam** [comment, marked as answer]
Here is an example. This I use for an overview of the house. 

```
type: vertical-stack
cards:
  - type: grid
    columns: 2
    cards:
      - type: 'custom:floorplan-card'
        full_height: false
        config: /local/floorplan/mainfloor.yaml
      - type: 'custom:floorplan-card'
        full_height: false
        config: /local/floorplan/secondfloor.yaml
      - type: 'custom:floorplan-card'
        full_height: false
        config: /local/floorplan/basement.yaml
```

**Comment by Alfiegerner** [comment]
Hi @exetico - very glad to see this get off the ground, awesome work.

In the old floorplan there was floorplan.class_toggle that I use to switch floors.  It's currently missing from this implementation but it was a very easy way of hiding or showing SVG layers.

**Reply by exetico** [reply]
https://experiencelovelace.github.io/ha-floorplan/docs/example-home/

See the YAML-code. Can't you use `class_set`? Else I need a bit more details, to understand your question :-)

**Reply by Alfiegerner** [reply]
Hi @exetico - thanks for looking at this. The `class_toggle` from the original version would allow toggling of classes across multiple elements / layers, i.e. if the class was present, when clicked it would remove it, if not present, it would add it. This provided an easy way to switch between floors.  Here's an example yaml config:

```
            - action:
                data:
                  classes:
                    - upper-layer-visible
                    - upper-layer-hidden
                  default_class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - lower_entity_layer
                service: floorplan.class_toggle
              elements:
                - toggle_entity_icon
              name: toggle_levels
```

with .css:
```
#upper_entity_layer.upper-layer-hidden {
  opacity: 0;
  display: none;
}

#upper_entity_layer.upper-layer-visible {
  opacity: 1;
  display: inherit;
}

#lower_entity_layer.upper-layer-hidden {
  opacity: 1;
  display: inherit:
}

#lower_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none;
}

```

I'm not sure how you'd achieve this using `class_set` - I think you'd need a `class_remove` as well but would be happy to hear any suggestions.

**Reply by exetico** [reply]
There's many ways of doing this, but maybe you should look at the style_set option?
https://github.com/ExperienceLovelace/ha-floorplan/discussions/40#discussioncomment-375815

You can also create a custom function, and do something simular:
https://github.com/ExperienceLovelace/ha-floorplan/discussions/48#discussioncomment-358582

Else, I guess we should hear @pkozul  about other suggestions. I can't really come up with other ways to do it, other than these two :-) It required a bit of code, but can be done quite easy.

**Reply by pkozul** [reply]
Hi @Alfiegerner 

Good catch! Looks like we missed adding `class_toggle` as a service in the new, revamped version of Flooplan. We've added it back in now, and it's available in v1.0.19.

https://raw.githubusercontent.com/ExperienceLovelace/ha-floorplan/master/dist/floorplan.js

I will leave it up to @exetico to release this version and get into HACS.

Let us know how you go with it.

**Reply by exetico** [reply]
👍 😄 

Release: [1.0.19 - `class-toggle` and easy datetime-formatting](https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.19)

**Reply by Alfiegerner** [reply]
That's awesome, thank you @pkozul and @exetico .  Also really appreciate the custom_function bit - will be very useful for me.
Cheers!

**Comment by amkochaki** [comment]
Hello. I'm also trying to manipulate (hide or unhide) the layers in the svg file, but unfortunately I'm not getting through with this version. My svg file is organized with several layers. I have layers that contain floor, layer that contains rooms and before I visible or unvisible each one, if anyone has any idea how to do this in this version I would appreciate it very much.

**Reply by exetico** [reply]
Have you checke the first answer including the suggestions? Else, It's very hard to help you out without details about that you've tried on basis of the other answer. Also, share both YAML, SVG and CSS will be helpful, too.

Images of how it's currently doing would also be a good idea to attach. 

And oh: Remember to format it correctly, in the reply. Thanks 😊

**Comment by amkochaki** [comment]
Thanks for your quick reply.

I'll try to explain it better with a very simple file: I have an svg file with two layers called page1 and page0. On page1 I have a rectangle with id: toggle_button and on page page0 I have any rectangle. I want to click on the rectangle with id: toggle_button and make the layer page0 visible or hidden. I tried this in this version but nothing happens, the page0 layer is not visible. There is also no error log.

here is yaml file:

```
show_side_bar: false
show_app_header: false
image: /local/floorplan/examples/home-multi/layers.svg?v=1.0.23
stylesheet: /local/floorplan/examples/home-multi/layer.css?v=1.0.23
log_level: info
console_log_level: info 
defaults:
    hover_action: hover-info
    tap_action: more-info
rules:
        - name: buttons
          elements:
            - toggle_button
          state_action:
            action: call-service
            service: floorplan.style_set
            data:
              elements:
                - page1
              classes:
                - layer-visible
                - layer-hidden
              default_class: layer-visible
```
Here the ccs file:

```
.layer-visible {
  display: initial !important;
 fill-opacity: 1 !important;
}
                    
.layer-hidden {
  display: none !important;
 fill-opacity: 0 !important;
}
```

And here is xml of file layers.svg

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg4524"
   inkscape:version="1.0 (4035a4fb49, 2020-05-01)"
   sodipodi:docname="layer1.bak.svg">
  <defs
     id="defs4518" />
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="-391.42857"
     inkscape:cy="560"
     inkscape:document-units="mm"
     inkscape:current-layer="page1"
     showgrid="false"
     inkscape:window-width="1680"
     inkscape:window-height="987"
     inkscape:window-x="-8"
     inkscape:window-y="-8"
     inkscape:window-maximized="1"
     inkscape:document-rotation="0" />
  <metadata
     id="metadata4521">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="page0"
     inkscape:groupmode="layer"
     id="page0">
    <rect
       style="display:inline;opacity:1;fill:#ffff00;fill-opacity:1;fill-rule:nonzero;stroke:#808080;stroke-width:0.0480341;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:0.866667"
       id="toggle_button"
       width="87.742432"
       height="86.986488"
       x="22.249584"
       y="11.222687"
       inkscape:label="toggle_button"
       mask="none" />
  </g>
  <g
     inkscape:groupmode="layer"
     id="page1"
     inkscape:label="page1"
     style="display:inline">
    <rect
       style="display:inline;opacity:1;fill:#800000;fill-opacity:1;fill-rule:nonzero;stroke:#808080;stroke-width:0.0451852;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:0.866667"
       id="toggle_button2"
       width="75.672508"
       height="89.251846"
       x="113.74599"
       y="10.46798"
       inkscape:label="toggle_button2" />
  </g>
</svg>

```

**Reply by Alfiegerner** [reply]
Hi @amkochaki - I think my memory of the code classes is not supported, only class.

The functionality is a bit different than previous version, this just toggles one class on and off rather than swapping 2 classes. Been a while since I looked at this so may be wrong.

 I have it working toggling between 2 layers follows:

```
            - element: toggle_entity_icon
              tap_action:
                action: call-service
                service_data:
                  classes:
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - lower_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels
```

With the following css:

```
#upper_entity_layer.upper-layer-visible {
  opacity: 1;
  display: inherit;
}

#lower_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none
}

```

And I think I also use default styles on the svg of lower layer visible, upper not, something like that anyway.

Doesn't answer if you have more than 2 layers but good enough for that.

**Reply by amkochaki** [reply]
Thank you very much this is perfect. More layers can be added without problems. The Upper layer which is the layer that is visible you have a button for a layer called lower. But I can add a middle layer and put one more button on the Upper layer. The ccs file would look like this:

```
}	
#upper_entity_layer.upper-layer-visible {
  opacity: 1;
  display: inherit;
}

#lower_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none
}
#middle_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none
}
```
the yaml file:

```
rules:

            - element: toggle_button2
              tap_action:
                action: call-service
                service_data:
                  classes:
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - lower_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels

            - element: toggle_button4
              tap_action:
                action: call-service
                service_data:
                  classes:
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - middle_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels    
``` 
If you want to add more layers add more buttons on the Upper layer and click on ccs and yaml as shown. I don't know if there is a better way to do this or if there is going to be a problem. In the next few days I will be adding the house plans with all the controls to do as it is.

**Reply by ahonxxx** [reply]
Can I share the original file? I didn't succeed after copying the code. thank you ahonxxx@gmail.com

**Reply by aparker21** [reply]
What am I missing from the above .yaml and .css?  I have input and used the name of my button and used the language you have provided on both the .css and .yaml files.  I can't get the button to do anything.  My cursor changes to a hand when I hover over it, so it recognizes it as an actionable button, so that part is right. . . .but how do I reference my files in order to get them to pull in as 'upper_entity_layer' and 'lower. . . .' and 'middle. . . . ', etc??  Do I simply input their name in the .css file instaed of the upper, middle, and lower_entity_layer?  I tried to use the file name in place of 'lower_entity_layer' and that didn't work.

My .yaml:
```
- title: Floorplan testing
    path: floorplan-testing
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/examples/home/home_simple1.svg
          log_level: info
          full_height: true
          rules:
            - element: 1st-floor-button
              tap_action:
                action: call-service
                service_data:
                  classes: null
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - lower_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels
          stylesheet: /local/floorplan/examples/home/home_simple.css
        full_height: true
        type: custom:floorplan-card
```
        
Here is my .css:
```
upper_entity_layer.upper-layer-visible {
  opacity: 1;
  display: inherit;
}

lower_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none
}
middle_entity_layer.upper-layer-visible {
  opacity: 0;
  display: none
}
```

I have no errors in the log.  I truly appreciate all help!!

**Reply by OzGav** [reply]
Can you please reformat your code by highlighting it and pressing the <> button. We can’t see if you have a simple indentation error

**Reply by aparker21** [reply]
I was trying to figure out how to do that like a madman yesterday and couldn't figure it out.  Thank you for pointing out what I needed to click on !!!

**Reply by aparker21** [reply]
I think my concern also is that nowhere have I pointed to my other svg file in order to make the change in class work.  I think that is what is missing and I don't know how to point my .svg files that I want to use for each floor class in the code provided.  Is it just a matter of naming the .svg files to something that matches what the code shows, or vice versa?  

Also, in my .css file the names are red.  For instance the "lower_entity_layer" portion of lower_entity_layer.upper-layer-visible is red.  That tells me the code isn't sure what to do with that lower_entity_layer.  It recognizes the .upper-layer-visible as it is a dark green the same as the other code I have in the css file that causes some of my layers to change opacity to show when a light is on in a room.

**Reply by OzGav** [reply]
In your SVG do you have two layers? Are those layers named `upper_entity_layer` and `lower_entity_layer`? Do those layers have at least one image in them?

**Reply by aparker21** [reply]
I have structured my svg file with mulitple layers namee accordingly.  Under each of those layers I have the needed layers for each element within that layer.  That all seems to be working correctly.  The one that is titled as the Upper Layer is definitely showing up first in my floorplan.  However, when I click on the button that I have programmed (as shown earlier above) nothing happens.  Where do you think the disconnect is?  Is it in the .css?  Is it in the .yaml?  I included `!important` next to the opacity in the .css file and also made sure there were semi colons after `display: none;`.  

Here is my folder structure in the .svg file:

```
-Buttons
  -text to display
  -button1
  -button2
  -button3
-upper_entity_layer
  -background layer and other layers to interact with
-middle_entity_layer
  -background layer and other layers to interact with
-lower_entity_layer
  -background layer and other layers to interact with
```
My entire .css file:

```
.entitystate-on{
    opacity: 0!important;
}

.entitystate-off{
    opacity: 0.6!important;
}

.entitystate2-on{
    opacity: 0.45!important;
}

.entitystate2-off{
    opacity: 0.6!important;
}

upper_entity_layer.upper-layer-visible {
  opacity: 1!important;
  display: inherit;
}

lower_entity_layer.upper-layer-visible {
  opacity: 0!important;
  display: none;
}
middle_entity_layer.upper-layer-visible {
  opacity: 0!important;
  display: none;
}
```

My entire .yaml file:

```
kiosk_mode:
  non_admin_settings:
    kiosk: true
    ignore_entity_settings: true
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
title: Our Floorplan
views:
  - title: Floorplan testing
    path: floorplan-testing
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/examples/home/home_simple2.svg
          log_level: info
          full_height: true
          rules:
            - element: basement-button
              tap_action:
                action: call-service
                service_data:
                  classes:
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - middle_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels
            - element: light-abbys_lamp
              entity: light.abbys_lamp
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/lamp_${entity.state}.svg
              tap_action: toggle
            - element: light-aarons_lamp
              entity: light.aarons_lamp
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/lamp_${entity.state}.svg
              tap_action: toggle
            - element: light-nursery
              entity: light.nursery_lamp
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/lamp_${entity.state}.svg
              tap_action: toggle
            - element: light-living_lamp
              entity: light.front_room_lamp
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/lamp_${entity.state}.svg
              tap_action: toggle
            - element: light-living-opacity
              entity: light.front_room_lamp
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate2-${entity.state}
              tap_action: toggle
            - element: light-front_porch_2
              entity: switch.shelly1pm_84cca89f8661
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: >-
                  /local/floorplan/examples/home/frontporchlamp_${entity.state}.svg
              tap_action: toggle
            - element: light-front_porch-primary
              entity: switch.shelly1pm_84cca89f8661
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: >-
                  /local/floorplan/examples/home/Main_Room_Bulb_${entity.state}.svg
            - element: light-front_porch-opacity
              entity: switch.shelly1pm_84cca89f8661
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action: toggle
            - element: light-garage-primary
              entity: light.front_room_lamp
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: >-
                  /local/floorplan/examples/home/Main_Room_Bulb_${entity.state}.svg
            - element: state-garage-primary
              entity: cover.garage_door
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/garage_${entity.state}.svg
              tap_action: toggle
            - element: light-garage-opacity
              entity: light.front_room_lamp
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action: toggle
          stylesheet: /local/floorplan/examples/home/home_simple.css
        full_height: true
        type: custom:floorplan-card
```
Let me know what else I can provide that will be helpful.  I feel like it is so close and I am just missing something simple.

**Reply by OzGav** [reply]
OK to clarify what will happen. `class_toggle` works by looking at the element and if the class is present, when clicked the specified class will be removed, if not present, it will be added.

You don't have to use `class_toggle`. I use `class_set` as I have five layers in one of mine and it is easier for me to know what will happen by making specific changes to the class of each layer. 

Having said that your description of your SVG suggests you have FOUR layers. Nothing will happen to your BUTTON layer because there is no mention of that in your yaml or CSS. I don't think anything is going to happen to your LOWER layer either because that is not mentioned in your YAML. What the CSS will do when applied correctly is show or hide an ENTIRE layer. The layer can be thought of as a group of objects. You can start by checking what will happen when a layer is turned on and off by going to Inkscape and selecting the OBJECTS toolbox and toggling the visibility of the whole layer on and off. Look at the picture below. I have collapsed all the layers so you can't see the objects and then I have hidden (the eye closed icon) all but the top two. If you hide your four layers and then turn them on individually you can than see what will happen when you apply the CSS correctly. If you aren't getting your desired effect then you don't have your SVG setup correctly.

![image](https://user-images.githubusercontent.com/19848947/217967432-b2b58bbe-d65c-419c-9b31-b9a2f1dad916.png)

So once you have your SVG correct then it is a matter of applying the correct classes to the correct layer. Also note that the following can happen. Inkscape shows you a graphical image of the SVG file which is actually a XML text file. The name you apply to your layer in Inkscape might not be reflected in the layer id inside the XML file as follows:

![image](https://user-images.githubusercontent.com/19848947/217968132-e05d9824-361c-48ba-a085-a37b7686476b.png)

So in my case I didn't bother renaming the ids but I did have to then refer to the layer ids in my CSS and NOT the layer labels. Thus this is my CSS:
```
#layer1.amp-layer-visible, #layer1.amp-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
#layer2.amp-layer-visible, #layer2.amp-layer-visible * {
  opacity: 0;
  display: none !important;
}
#layer3.amp-layer-visible, #layer3.amp-layer-visible * {
  opacity: 0;
  display: none !important;
}
#layer5.amp-layer-visible, #layer5.amp-layer-visible * {
  opacity: 0;
  display: none !important;
}
#layer6.amp-layer-visible, #layer6.amp-layer-visible * {
  opacity: 0;
  display: none !important;
}
```
And my yaml:
```
        - element: amp.button
          tap_action:
            - service: floorplan.class_set
              service_data:
                classes:
                class: amp-layer-visible
                elements:
                  - layer1
                  - layer3
                  - layer2
                  - layer5
                  - layer6
```

So hopefully you can see that when I click on `amp.button` the `amp-layer-visible` class is applied to the five layer elements and that results in one layer visible and the other four hidden. As I said you can do this with `class_toggle` but I found it easier to see what would happen by being explicit. The downside is I have 25 classses that I had to specify (cut and paste works wonders).

So hopefully now you understand the relationship between the SVG, CSS and YAML. This is true for all of how floorplan works but generally you are applying the class to an individual object (e.g. your `light-front_porch-opacity` element)

**Reply by aparker21** [reply]
You are providing so much great assistance and I truly appreicate it!!!  That said. . . .it still ins't working and I know it is on my end.  I have to be missing something somewhere.  My SVG file is set up much like yours and when I hide the upper layer the middle layer shows and when I hide that the lower layer shows.  Everything looks correct in my SVG file as far as I can tell.  All of the Entity ID's match the entity names.  So, my upper_entity_layer has that ID in the SVG as well, and so do the Middle and Lower layers.  Below is a screenshot.  I double checked and every layer is visible and the layer showing in the preview is the upper_entity_layer.  

![SharedScreenshot](https://user-images.githubusercontent.com/121689856/218125683-efc42a9d-6cd1-412d-af5a-e0b55d605604.jpg)

I double checked the XML for the svg and the id's are correct and match Inksckape perfectly. 

Below is my css file after copying your css and changing for my entites.  

```
upper_entity_layer.upper-layer-visible, upper_entity_layer.upper-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
middle_entity_layer.upper-layer-visible, middle_entity_layer.upper-layer-visible * {
  opacity: 0;
  display: none !important;
}
lower_entity_layer.upper-layer-visible, lower_entity_layer.upper-layer-visible * {
  opacity: 0;
  display: none !important;
}
```
I see that your code has pound signs, or hashtags.  Is that required or just to comment those out and my code doesn't need them if I want it to run?

I updated my .yaml code to delete the floorplan.class_toggle and pasted in your code and changed it for my entities and such.  It is here:

```
rules:
            - element: 2nd-floor-button
              tap_action:
                - service: floorplan.class_set
                  service_data:
                    classes:
                    class: upper-layer-visible
                    elements:
                      - upper_entity_layer
                      - middle_entity_layer
                      - lower_entity_layer
```

What am I missing??

Edit:

I thought I had to have all layers showing ion the SVG. . . .but that isnt' working. . . so I hid all layers except for the top two just as you have done in the SVG. . . that isn't working either.  I have cleared cache and reloaded the browser and still not working.

I also forgot to mention that in my CSS file the `upper_entity_layer`, `middle_entity_layer`, and `lower_entity_layer`, are all red.  the `.upper-layer-visible` are all green.  Does the red entity in the css mean it isn't recognizing them for some reason??

**Reply by aparker21** [reply]
I checked the inspector on my floorplan.  The upper_entity_layer is visible and highlighted.  The other two layers are grayed out (which sounds like that is correct).  All the entities within each layer are all there in the inspector.  So it appears to me I'm just missing the command to toggle each layers' visibility.

**Reply by OzGav** [reply]
yeah the hash symbol is not a comment in CSS it is a [selector](https://www.w3schools.com/cssref/sel_id.php) so you need that in there or it won't work.

Also as I indirectly tried to say you need to replicate the CSS for the visibility of your other layers. So for example you also need:
```
#upper_entity_layer.middle-layer-visible, #upper_entity_layer.middle-layer-visible * {
  opacity: 0;
  display: none !important;
}
#middle_entity_layer.middle-layer-visible, #middle_entity_layer.middle-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
#lower_entity_layer.middle-layer-visible, #lower_entity_layer.middle-layer-visible * {
  opacity: 0;
  display: none !important;
}
```

and you then need to ALSO do the same sort of thing for lower layer visible. Then you need to replcate the YAML to assign those classes to the layers. So you need THREE buttons one for each layer. Each button targets the SAME entities but applies a DIFFERENT class.

**Reply by OzGav** [reply]
P.S. We can simplify this at the end which I will get to but for now I am just trying to illustrate what is required and what is happening to make this work.

**Reply by aparker21** [reply]
I see!  That makes sense.  I sometimes need things spelled out in great detail.  And you have done it!!  I truly appreciate the asssistance! 

I do already have 3 buttons in my SVG file so I think I will be good there.  Just need to set up the .CSS and .YAML.  I will keep you posted!

**Reply by aparker21** [reply]
So this is my css file now:

```
#upper_entity_layer.upper-layer-visible, #upper_entity_layer.upper-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
#middle_entity_layer.upper-layer-visible, #middle_entity_layer.upper-layer-visible * {
  opacity: 0;
  display: none !important;
}
#lower_entity_layer.upper-layer-visible, #lower_entity_layer.upper-layer-visible * {
  opacity: 0;
  display: none !important;
}


#upper_entity_layer.middle-layer-visible, #upper_entity_layer.middle-layer-visible * {
  opacity: 0;
  isplay: none !important;
}
#middle_entity_layer.middle-layer-visible, #middle_entity_layer.middle-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
#lower_entity_layer.middle-layer-visible, #lower_entity_layer.middle-layer-visible * {
  opacity: 0;
  display: none !important;
}


#upper_entity_layer.lower-layer-visible, #upper_entity_layer.lower-layer-visible * {
  opacity: 0;
  isplay: none !important;
}
#middle_entity_layer.lower-layer-visible, #middle_entity_layer.lower-layer-visible * {
  opacity: 1;
  display: inherit !important;
}
#lower_entity_layer.lower-layer-visible, #lower_entity_layer.lower-layer-visible * {
  opacity: 0;
  display: none !important;
}
```

**Reply by aparker21** [reply]
We are making headway!!!!  The upper layer is visible by "default".  When I click on the 2nd floor button the middle floor shows. When I click it again, nothing happens. . . I think this is normal.  When I click the first-floor-button, the upper layer shows and if I cick it again, notihing happens.  When I click the basement-button the middle floor shows.  So I think I just have to adjust my .yaml file to point to the correct layer element.  Correct??

**Reply by aparker21** [reply]
I figured out all the issues and it is working perfectly!!!  Thank you soooooo much for your help and taking the time to walk me through this!!!!  Do you have a buymeacoffee link?

**Reply by OzGav** [reply]
Glad you have it working and thanks for the appreciation. Click on my user name to find the link.

**Reply by aparker21** [reply]
I lied. Now that the 3 buttons are working to change floors I cant click on any of the other elements on one of my floors (the only floor with elements set up).  Is it because they are above all other layers and somehow their layer is blocking me from being able to interact with the other layers?  Do I need to put a copy of all 3 buttons in each layer as opposed to being 1 set above all layers?

**Reply by OzGav** [reply]
Yes you do need to make sure that there is nothing in that top layer that is overlaping the ones below. If you have the buttons off to the side it should be fine. Make sure the buttons are only as big as they need to be (ie don't have a huge rectangle with a small icon in it)

**Reply by OzGav** [reply]
You can select your elements in Inkscape and set the stroke to a visible colour so you can see where it is and how big it is. Having one set of buttons in the top layer is fine.

**Reply by OzGav** [reply]
Your yaml looks ok but here.is a slightly simplified version to save a couple of lines. If you can name the element the same as the entity you can save that line. Call service is the default action so you don’t need that line.

```
            - entity: light.abbys_lamp
              state_action:
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/lamp_${entity.state}.svg
              tap_action: toggle
```
