### DISCUSSION TITLE
How can I set an "element template" for a list of entity IDs?

### DISCUSSION THREAD

**Discussion by ndbroadbent** [ExperienceLovelace/ha-floorplan#231] [Ideas]
Related: https://github.com/ExperienceLovelace/ha-floorplan/discussions/159

I'm designing a floorplan in Figma and it doesn't allow me to re-use the same ID. Sometimes I have multiple things in my SVG that control or display the same entity. I want to be able to add a prefix to the element ID, and define a template string (or JS function) that ha-floorplan will use.

Example:

I have some "hotspots" in my floorplan that are clickable rectangles to control certain lights. I want to prefix these IDs with "hotspot":

```
<g id="Hotspots">
<path id="hotspot.cover.garage_door"  ...
<rect id="hotspot.light.workshop_desk_lamp" ...
```

I also use those light entity ids in a different place:

```
<g id="Lights">
<g id="light.workshop_desk_lamp">
<path id="light.workshop_desk_lamp.off" ...
<g id="light.workshop_desk_lamp.on"> ...
```

So I want to be able to do this in my config:

```
rules:
    - entities:
        - light.workshop_desk_lamp
        - light.office_hue_bookshelf
        - light.hue_lightstrip_hallway_floor
        - cover.garage_door
      element: hotspot.${entity.entity_id}
      tap_action: toggle
```

I tried a few other ways but I get:

```
WARNING CONFIG Cannot find element 'hotspot.${entity.entity_id}' in SVG file
```

I also tried to specify a list of elements, but that crashes with an error: "A rule cannot contain both 'entities' and 'elements' in floorplan configuration."

The `entities` array is handy, but feels a bit restricted since I don't have any control over the SVG element IDs.

Is there any templating or JS I can use to solve this?
