### DISCUSSION TITLE
toggle css class not applied

### DISCUSSION THREAD

**Discussion by cereal2nd** [ExperienceLovelace/ha-floorplan#24] [Q&A] [answered]
i have the following config

```
 - entities:
        - switch.gang_voor
        - switch.gang
        - switch.zetel
        - switch.tafel
        - switch.slaapkamer_quin
        - switch.kamer_midden
        - switch.slaapkamer_yinn
        - switch.keuken
        - switch.badkamer
        - switch.buiten_voor
        - switch.waskot
        - switch.buiten_achter
        - switch.wc
        - switch.technische
        - switch.oprit
        - switch.pad_voor
        - switch.slaapkamer
        - switch.bureau
        - switch.dressing
        - switch.pomp_grondwater
        - switch.pomp_zwembad
        - switch.zolder
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data: 'binary-${entity.state}'
      tap_action:
        action: call-service
        service: homeassistant.toggle
```

And the CSS
```
.binary-on {
  fill: #F9D27C !important;
  transition: fill 2s ease;
}

.binary-off {
  fill: #7CB1F9 !important;
  transition: fill 2s ease;
}
```

But the fill is never applied, but the states are loaded (seeing it in the logs)
`
20/1/2021 20:35:44 DEBUG STATE switch.waskot: off (initial load)`

**Comment by exetico** [comment]
Is it simular to this?
https://github.com/ExperienceLovelace/ha-floorplan/issues/13

**Reply by cereal2nd** [reply]
its similar but not the same
i already tried the fill thing, but even then it doesn't work.

looking with the browsers inspector the class/style attribute are never applied on the rect svg shape

**Reply by exetico** [reply]
Are you able to reproduce it, if you're only using a single entity? Please do so, just to be sure.

Also, please share your SVG, so it's easier to see if it's a local thing. If you have a HA-testinstance, fell free to create another test on that. My classes are handled like they should.

**Reply by exetico** [reply]
I just spotted that you're missing a mapping value for the svg-object. So currently it doesn't know which SVG element needs the class.

Here's one example:
```yaml
entities:
  - device_tracker.0c_9d_aa_aa_aa_aa
element: thing.workstation
state_action:
  service: floorplan.class_set
  service_data:
    class: '${(entity.state === "on") ? "thing-on" : "thing-off"}'
```

`thing.workstation` are the defined ID on the SVG-element, and the `device_tracker` are the HA-entity. `element` are not present in your config.

**Reply by cereal2nd** [reply]
```
    - entities:
        - switch.bureau
      element: switch.bureau
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data:
          class: '${(entity.state === "on") ? "binary-on" : "binary-off"}'
      tap_action:
        action: call-service
        service: homeassistant.toggle
```

even with this config it doesn't seem to work, still the same scenario, no class is applied
