### DISCUSSION TITLE
Button to toggle switch doesn't work

### DISCUSSION THREAD

**Discussion by tidharmor** [ExperienceLovelace/ha-floorplan#248] [Q&A] [answered]
Hi,

I've recently started using floorplan and I'm stuck at configuring a button to toggle a switch on and off.
I added a Lovelace dashboard and edited the raw configuration yaml following the examples.
I have 2 floors and switching between them works.
I have a fan with an animation that turns on when the fan switch state is on, and this works.

However, this same fan switch does not toggle the state when I click on the button.
The switch entity id works when I use it to set the animation state, so I know it's ok.
When I change the tap_action to hold_action and then click the button I get the more-info action that is defined in the defaults,
so I know the button tap action is ok.
Currently the rule is simplified, but I also tried the full syntax and it also didn't work.

```
            - element: switch.1000b333d3_1.button
              entity: switch.1000b333d3_1
              tap_action: homeassistant.toggle

            - entity: switch.1000b333d3_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data:
                  class: '${(entity.state === "on") ? "spinning" : ""}'
```
The switch is from the eWeLink integration, which is why it has a strange id that I can't change: switch.1000b333d3_1
![image](https://user-images.githubusercontent.com/12812505/196228982-1c79b0f3-992c-4f82-8c39-151568c27558.png)

I can't figure out why the switch doesn't toggle on/off when I click the button.

Full Yaml:
(problem entity is at the bottom)
```
wallpanel:
  enabled: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 0
title: Home
views:
  - title: Floorplan
    path: floorplan
    type: panel
    badges: []
    cards:
      - type: custom:floorplan-card
        full_height: true
        config:
          image: 
            location: /local/floorplan/home.svg
            cache: false
          stylesheet: 
            location: /local/floorplan/home.css
            cache: false
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          startup_action:
            - service: floorplan.class_set
              service_data:
                elements: 
                  - ground_floor
                  - all
                class: layer-visible
            - service: floorplan.class_set
              service_data:
                elements:
                  - first_floor
                class: layer-hidden
            - service: floorplan.class_set
              service_data:
                elements:
                  - switch.pergula_area_fan
                class: spinning
          rules:
            - element: toggle_first_floor
              tap_action:
                - service: floorplan.class_set
                  service_data:
                    element: ground_floor
                    class: layer-visible
                - service: floorplan.class_set
                  service_data:
                    elements:
                      - first_floor
                    class: layer-hidden
            - element: toggle_ground_floor
              tap_action:
                - service: floorplan.class_set
                  service_data:
                    element: first_floor
                    class: layer-visible
                - service: floorplan.class_set
                  service_data:
                    elements:
                      - ground_floor
                    class: layer-hidden

            - element: switch.1000b333d3_1.button
              entity: switch.1000b333d3_1
              tap_action: homeassistant.toggle

            - entity: switch.1000b333d3_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data:
                  class: '${(entity.state === "on") ? "spinning" : ""}'

```
     
Here is the same switch configured in a normal dashboard:

```
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.1000b333d3_1
            icon: mdi:ceiling-fan
            show_state: true
            name: upstairs_fan
```
       
Thanks
