### DISCUSSION TITLE
displaying camera images on click

### DISCUSSION THREAD

**Discussion by m90att** [ExperienceLovelace/ha-floorplan#251] [Q&A] [answered]
Hi, I'm progressing with my floorplan and have lights, switches and media player entities working.  I want to add my cctv/blink cameras but am struggling.

In one of my existing dashboards I have each camera as a picture entity, e.g.
![image](https://user-images.githubusercontent.com/56609577/196261653-ca74810d-dbc9-4a85-9e3f-76fa49cdae61.png)

When I click on the entity, it opens a popup with a larger image, e.g.
![image](https://user-images.githubusercontent.com/56609577/196261748-e6cce00a-9e1a-4604-9d1e-891cc99e051f.png)

This popup is exactly what I'm looking to replicate in ha floorplan.  I have an svg element that I want to click on to open the popup,
![image](https://user-images.githubusercontent.com/56609577/196262059-a7993eda-ce97-4ca8-88fd-684a1e7d0578.png)
...but I just can't get the popup to work.

I can't find a way of making a service call to show the popup, other than browser mod, which I just can't get working.  Here is my code:

I can call the popup successfully using the dev tools...

```
service: browser_mod.more_info
data:
  entity: camera.blink_side
```
but when I try to call it from the svg element, it doesn't work...

```
  - element: cameras
    entity: camera.blink_side
    tap_action:
      action: call-service
      service: browser_mod.more_info
      data:
        entity: camera.blink_side
```
What am I doing wrong?!

Thanks, Matt

**Comment by exetico** [comment]
Hi,

Have you checked previous discussions, related to this? Here's one example:
https://github.com/ExperienceLovelace/ha-floorplan/discussions/146

I'm on the phone, so it's hard to give the code a go right now ☺️.

**Reply by m90att** [reply]
Thank you, I did, but I concluded that it wasn't right for my situation.  Now you've pointed me to it, I'll give it another go!

**Reply by exetico** [reply]
Great. Let me know how it goes.

**Comment by m90att** [comment, marked as answer]
Thank you for the steer @exetico, I've managed to get it working and have put it inside a honeycomb menu.  For completeness and hopefully to help others, this is what I did.

```
                - element: cameras
                  tap_action: 
                    action: call-service
                    service: honeycomb
                    service_data:
                      buttons:
                        - icon: mdi:doorbell-video
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: sensor.pws_temp
                                camera_image: camera.blink_side
                        - icon: mdi:sofa
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: binary_sensor.tv_status
                                camera_image: camera.blink_lounge
                        - icon: mdi:home
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: sensor.pws_wind_speed
                                  - entity: sensor.pws_wind_dir
                                camera_image: camera.blink_back             
                        - icon: mdi:car
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: light.garage
                                camera_image: camera.tapo
                        - icon: mdi:shovel
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: light.rear_floodlight
                                camera_image: camera.blink_rear_side 
                        - icon: mdi:garage-variant
                          color_type: card
                          color: 'var(--primary-background-color)'
                          tap_action:
                            action: call-service
                            service: browser_mod.popup
                            service_data:
                              content:
                                camera_view: auto
                                type: picture-glance
                                entities:
                                  - entity: light.outdoor_drive
                                  - entity: light.outdoor_porch
                                camera_image: camera.blink_drive
```

...which gives me...

![image](https://user-images.githubusercontent.com/56609577/196358336-c19a6564-fe18-4e19-9cbd-20ee396da9d1.png)

![image](https://user-images.githubusercontent.com/56609577/196358483-272b89d8-37ca-4170-84da-593f2980bcac.png)
