### DISCUSSION TITLE
How to pass entity id to browser_mod popup

### DISCUSSION THREAD

**Discussion by m90att** [ExperienceLovelace/ha-floorplan#252] [Q&A] [answered]
Hi again,

After getting the browser_mod popup to work last night, the next thing I'd like to do is use it to show the custom:mini-media-player card for any media_player element, as a hold_action.  The popup is working when I hard code the element_id, but I want to pass the entity id of the element clicked on to the popup, to avoid duplicating lots of code.

I've tried `${entity}` but it doesn't recognise it.  Again, I've searched but have not found anything.  How can I do this please?

```
                - entities:
                  - entity: media_player.garage_speaker
                    element: media_player.garage_speaker
                  - entity: media_player.bathroom
                    element: media_player.bathroom
                  - entity: media_player.kitchen
                    element: media_player.kitchen
                  - entity: media_player.study
                    element: media_player.study
                  - entity: media_player.lounge
                    element: media_player.lounge
                  tap_action: media_player.media_play_pause
                  state_action:
                    - action: call-service
                      service: floorplan.class_set
                      service_data: "${entity.state}"
                  hold_action:
                    action: call-service
                    service: browser_mod.popup
                    service_data:
                      content:
                        type: custom:mini-media-player
                        entity: "${entity}"
                        icon: mdi:speaker
                        speaker_group:
                          entities:
                            - entity_id: media_player.rear
                              name: Rear
                            - entity_id: media_player.kitchen
                              name: Kitchen
                            - entity_id: media_player.lounge
                              name: Lounge
                            - entity_id: media_player.en_suite
                              name: Ensuite
                            - entity_id: media_player.landing
                              name: Landing
                            - entity_id: media_player.bathroom
                              name: Bathroom
                            - entity_id: media_player.garage_speaker
                              name: Garage
                            - entity_id: media_player.study
                              name: Study
                        artwork: full-cover
```

**Comment by m90att** [comment]
Unfortunately, I still haven't been able to find out if this is possible so I had no option but to repeat the code for each media player.  To make it a little - but not much - cleaner, I used decluttering cards...

```
  icon-mini-media-player:
    default:
    - icon: music
    card:
      type: custom:mini-media-player
      entity: '[[entity]]'
      icon: mdi:music
      speaker_group:
        entities:
          - entity_id: media_player.rear
            name: Rear
          - entity_id: media_player.kitchen
            name: Kitchen
          - entity_id: media_player.lounge
            name: Lounge
          - entity_id: media_player.en_suite
            name: Ensuite
          - entity_id: media_player.landing
            name: Landing
          - entity_id: media_player.bathroom
            name: Bathroom
          - entity_id: media_player.garage_speaker
            name: Garage
          - entity_id: media_player.study
            name: Study
      artwork: full-cover
      volume_stateless: true
      info: scroll
      source: full
      hide:
        power: true
        icon: true

```

```
                - entities:
                  - entity: media_player.study
                    element: media_player.study
                  tap_action: media_player.media_play_pause
                  state_action:
                    - action: call-service
                      service: floorplan.class_set
                      service_data: "${entity.state}"
                  hold_action:
                    action: call-service
                    service: browser_mod.popup
                    service_data:
                      content:
                        type: custom:decluttering-card
                        template: icon-mini-media-player
                        variables:
                          - entity: media_player.study
```

**Reply by exetico** [reply]
You can save even more lines.

```
entity: media_player.study
element: media_player.study
```

can be shorten down to
```
entity: media_player.study
```

If the entity matches the element, there's no need to define it.

Here's one example with `person.tobias`:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/3549445/198360391-0c3b443a-6d17-43c7-adfc-04fdef9a6a53.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/3549445/198360841-5599343c-8255-4c0c-963b-288f39eebfec.png">

**Reply by m90att** [reply]
ah, thank you, that does make it cleaner

**Comment by exetico** [comment]
So you'd like to pass a value related to the element you're triggering - and parsing that entity to browser_mod, **only showing** that card, instead of all the media-players? Your description let's me think about the xy-problem. I'm not really sure what you're hoping to do - other than a technical description of it 😄 . I hope it makes a bit of sense.

I think there's two routes:
1) Using a "template" YAML-solution, generating a ha-floorplan code for each entity, instead of you, manually trying to use all entities in one ha-floorplan call (will require some advance tricks, or a add-on).
2) Extending our current solution, **if** it's not possible to do with the current code. But I like the thoughts, so let me know if I've understand the needs as you want them.

**Reply by exetico** [reply]
For point no. 1, here's one example of my sonos solution.

I've done this for a mod_browser card:

```yaml
          - type: custom:mini-media-player
            entity: media_player.sonos_kontor
            hide:
              power: true
            speaker_group:
              platform: sonos
              show_group_count: true
              entities: !include ../../../../entities_sonos.yaml
```

In my entities_sonos.yaml-file, I've added the following:
```yaml
                    - entity_id: media_player.sonos_stue
                      name: Stue
                    - entity_id: media_player.sonos_kontor
                      name: Kontor
                    - entity_id: media_player.sonos_kokken
                      name: Køkken
                    - entity_id: media_player.sonos_badevaerelse
                      name: Badeværelse
```

... But I know that not 1:1 what you're asking for 😄 .

But... I'll give you a better suggestion in a bit ;)

**Reply by m90att** [reply]
Yes, I've got 5 sonos media players which I have created svg icons for.  These are placed in each room.  When I click, it simply calls play/pause. I want to be able to quickly change source, see artwork, group, etc when I hold on the icon, but only for that media player.  I want to write the code to show mmp once and pass whichever button/media player I'm interacting with to it as a variable.

**Reply by exetico** [reply]
I'll post this as a new answer.

**Comment by exetico** [comment]
☕ **Did you find this useful, and would you like to say thanks? Buy me a coffee at**: [https://www.buymeacoffee.com/coffeetoexetico](https://www.buymeacoffee.com/coffeetoexetico) (_Support my ha-floorplan work, say thanks for 1-to-1 help in discussions and whatever else you think about 😺_)

<hr>

So @m90att ... More than three hours spend on this, cause I just noticed that many services (if not all?) can actually handle JavaScript as a data-input. That's somehow totally new information to me, which maybe sounds a bit off. But I've never had the needs to dig into the ha-instance like this.

Now I've updated all things, and researched a bit. I noticed that browser_mod also supported a data-element, so... It's time to play.

... Here I provide you a fresh 🔥  example on how to really do things with magic.
I'll extend our documentation at some point, with a topic like "using 3rd-party solutions with ha-floorplan" and "calling services within JS, instead of the YAML-way".

In the `content:` you'll finde a vertical stack with the following examples in a array:

1. What you asked for
2. Example where I'm using auto-entities for a room - _just to give some inspiration on how to use that, and maybe even consider to auto-gen entities in a popup, on basis of the group of the triggered entity, or simular._ .. You could also just consider to use the "group member" proporty in the entity element.

```yaml
name: Sonos
entities:
  - media_player.sonos_kontor
  - media_player.sonos_kokken
  - media_player.sonos_badevaerelse
  - media_player.sonos_stue
tap_action: media_player.media_play_pause
state_action:
  - action: call-service
    service: floorplan.class_set
    service_data: "${entity.state}"
hold_action:
  - action: call-service
    service: floorplan.class_set
    service_data:
      class: |
        > 
        try{
          browser_mod.service('popup',{title: "Media player",
          content: 
            {
              type: "vertical-stack",
              cards: [
                /* Media player for that specific room */  
                {
                  type: "custom:mini-media-player",
                  entity: entity.entity_id, /* entity.entity_id is the reference from hold_action from  ha-floorplan */
                  artwork: "full-cover",
                  hide: {
                    power: true
                  }
                },
                /* Auto-entitiy example, showing all from office - auto-entities is a custom lovelace function */
                {
                  type: "custom:auto-entities",
                  card: {
                    type: "entities",
                    show_header_toggle: false
                  },
                  filter: {
                    include: [{group: "group.office"}]
                  }
                }
              ]
            }
          })
          return `${entity.state}`;
        }catch(e){
          console.log("Well.. That didn't go as planned");
        }

```

Let me know if you have any questions.

Tested with HA 2022.8.5 + browser_mod 2.1.3


@OzGav I'm sure you'll find this very interesting, too.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/3549445/198705698-ba90c8ed-8cbb-4a69-93b7-06569b3a8895.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3549445/198706257-3c01e540-5a04-44f2-8ed5-31060077098e.png">

<img width="596" alt="image" src="https://user-images.githubusercontent.com/3549445/198705900-746b7e88-09dc-48ea-9b51-3e4d7a4126ab.png">

_Some Jazz was playing in the background.... OK.... Great?_ 😄 😆
