### DISCUSSION TITLE
Combine two entities.

### DISCUSSION THREAD

**Discussion by Hadatko** [ExperienceLovelace/ha-floorplan#253] [Ideas]
Hi, i didn't find information if we can combine information from two and more entities. I wanted to do new formula gas_consumption*gas_price where one is counter and second input_number.

**Comment by OzGav** [comment]
This isn't a question limitied to HA it applies to everywhere in HA that you want to do some math. You need to use a template sensor:
```
template:
   - sensor:  
      - unique_id: "gas_total_cost" 
        name: "Gas Total Cost"
        unit_of_measurement: 'Kč'
        state: >
          {{ states('sensor.gas_consumption') | float(0) * states('sensor.gas_price') | float(0) }}
```
