### DISCUSSION TITLE
Rules for multiple elements of the same type but with different Ids

### DISCUSSION THREAD

**Discussion by m90att** [ExperienceLovelace/ha-floorplan#266] [Q&A] [answered]
Hi,

Second question of the day...

I'm very familiar with the rule to handle multiple elements of the same type, e.g.

```
                - entities:
                    - climate.hall
                    - climate.bathroom
                    - climate.study
                    - climate.kitchen
                    - climate.lounge
                    - climate.spare_room
                  state_action:
                    - service: floorplan.text_set
                      service_data: '${(entity.attributes.current_temperature !== undefined) ? Math.round(entity.attributes.current_temperature * 10) / 10 + "° " : "unknown" }'
```
However, this is dependent on the SVG elements having the same id as the HA entities.

Is it possible to do the same - perform one rule on multiple elements - if their ids are different to the entities?  Or do I have to list out each one individually with its own rule, e.g.

```
                - element: text.temp_study
                  entity: climate.study
                  state_action:
                    - service: floorplan.text_set
                      service_data: '${(entity.attributes.current_temperature !== undefined) ? Math.round(entity.attributes.current_temperature * 10) / 10 + "°" : "unknown" }'
                - element: text.temp_lounge
                  entity: climate.lounge
                  state_action:
                    - service: floorplan.text_set
                      service_data: '${(entity.attributes.current_temperature !== undefined) ? Math.round(entity.attributes.current_temperature * 10) / 10 + "°" : "unknown" }'
```

I want to understand if there's an easy way to do it before I proceed with creating a function to do this.

Thanks

**Comment by exetico** [comment, marked as answer]
I actually tried to extend this locally yesterday, cause I spotted a need for it. _However: I deleted the comment in another other discussion, cause it was too long away from the main question._

The short version of your question is:
_"Can I use multiple elements for a single (or multiple) entities, and have ha-floorplan to manipulte each element on basis of the provided rule(s)?"_

Right?

I bet you're able to do it with some magical YAML template mapping, but what would require a plugin/custom-component or similar... But I need to check, how it can be handled in ha-floorplan.

Also: _+1 to you, for creating a both clean and easily understandable question!
It highly improves my tendency to give inputs/help, but also for other people to find your question by searching here (or on Google)._

**Reply by exetico** [reply]
After reading the 2. YAML code again, I think I get it.

ha-floorplan can't "manipulate" the "element" reference, on basis of the entity name. Like tripping the "climate"-prefix, and replacing it with "text" for the element-reference, but you should be able to do that, on your own.

I'll take a look, and get back. I need to fiddle a bit.

**Reply by exetico** [reply]
Here's what you ask for, if the svg-files using the prefix `customprefix`. You can change that, like you want to. Note that I'm defining the element+text key within the 'service_data`, instead of just defining the service_data. If the service_data is defined as `bob`, we'll use `bob` as the text. But if you define the `element` and the `text`, both of them can be "calculated values" with a custom function.

_I hope the following question matches what you're asking for:_
**Question**: Can I use the same rule for multiple entities, and map the entity-name to a correlated element-key, instead of duplicating my rules?

```yaml
          - entity:
              - light.hue1_light
              - light.hue2_light
            state_action:
              action: call-service
              service: floorplan.text_set
              service_data:
                element: |
                  > // Get our type and name
                  const [entityType, entityName] = entity.entity_id.split(".", 2);
                  // Our entity name will be defined in entityName (The light.hue1_light value will be splitted into "light" and "hue1_light")
                  return `customprefix.${entityName}`; // You'lll need to adjust this to `text.temp_${entityName}`
                text: |
                  > // Get our type and name
                  const [entityType, entityName] = entity.entity_id.split(".", 2);

                  // Debug info
                  console.log("entity", entity); console.log("element", element);console.log(entityType, entityName);

                  // Our entity name will be defined in entityName (The light.hue1_light value will be splitted into "light" and "hue1_light")
                  return `${entityName} ${entity.state}`; // You'll need to adjust this to the Math.round() statement of your choice
```

Get YAML, CSS and SVG here:
https://github.com/exetico/Home-Assistant_Attachments-for-YouTube/tree/main/Discussion-cases/Case1

![image](https://user-images.githubusercontent.com/3549445/202724154-be6fe682-01e3-478f-8569-51487559b0f0.png)


I guess that's a good video-topic "for the 5 minute video". I'll add it to my list of ideas.

**Reply by m90att** [reply]
Thank you...I've tried it but the element is undefined each time and I can't see why...

```
                - entity:
                    - sensor.lounge_hvac
                    - sensor.study_hvac
                    - sensor.bathroom_hvac
                    - sensor.kitchen_hvac
                    - sensor.spare_room_hvac
                    - sensor.hall_hvac
                  state_action:
                    action: call-service
                    service: floorplan.text_set
                    service_data:
                      element: |
                        > 
                        const [entityType, entityName] = entity.entity_id.split(".", 2);
                        return `outline.${entityName}`; 
                      text: |
                        > 
                        const [entityType, entityName] = entity.entity_id.split(".", 2);

                        console.log("entity", entity); console.log("element", element); console.log(entityType, entityName);

                        return `${entityName} ${entity.state}`; 
```

![image](https://user-images.githubusercontent.com/56609577/202769976-78ebce7e-2af5-487e-a8b5-9cdf13af4afa.png)

**Reply by exetico** [reply]
Is the element ids "outline.lounge_hvac" and so on?

"element" will be undefined in the console log, cause It's not defined in the 'parent rule'. But that's just fine, cause you're returning the element-id in your function.

**Reply by m90att** [reply]
ah..no, the element ids are outline.lounge, outline.study, etc...I can see the problem I think...it's still got the _hvac on the end

**Reply by m90att** [reply]
so some kind of substr using the '.' and '_' ?

**Reply by exetico** [reply]
Use `entityName.split('_')[0]`, and consider to wrap the whole statement in a try{} catch(e){} at this point, now what you're bringing even more logics into the runtime/execution 😊.

The entityName is already the things after the dot in the entity.

You can also do it with just a entityName.replace('_hvac','') 👍. In your case It's also possible to just use two times replace() on entity.entity_name, if you're considering to simplify it a bit. But I just did it in a bit more generic way.

**Reply by m90att** [reply]
Thanks @exetico...final code

```
                - entity:
                    - sensor.lounge_hvac
                    - sensor.study_hvac
                    - sensor.bathroom_hvac
                    - sensor.kitchen_hvac
                    - sensor.spare_room_hvac
                    - sensor.hall_hvac
                  state_action:
                    action: call-service
                    service: floorplan.class_set
                    service_data:
                      element: |
                        > 
                        try {
                          const [entityType, entityName] = entity.entity_id.split(".", 2);
                          const outlineName = entityName.replace('_hvac','');
                          return `outline.${outlineName}`; 
                        } catch(e) {
                          console.log("Dag nabbit... That didn't go as planned");
                        }      
                      class: |
                        > 
                        try {
                          const [entityType, entityName] = entity.entity_id.split(".", 2);

                          console.log("entity", entity); console.log("element", element); console.log(entityType, entityName);
                          return `${entity.state}`; 
                        } catch(e) {
                          console.log("Dag nabbit... That didn't go as planned");
                        }      
```

**Reply by exetico** [reply]
You're welcome :)

**Comment by m90att** [comment]
Yes, I've done it by replacing cliamte with text but I still need to do it for every element/entity pairing, which is why I was thinking a function is the way to go, but I thought I'd ask if there was another way, I was thinking/hoping something like this

```
              entities:
                - element: text.temp_study
                  entity: climate.study
                - element: text.temp_lounge
                  entity: climate.lounge
                - element: text.temp_hall
                  entity: climate.hall
                - element: text.temp_kitchen
                  entity: climate.kitchen
                  state_action:
                    - service: floorplan.text_set
                      service_data: '${(entity.attributes.current_temperature !== undefined) ? Math.round(entity.attributes.current_temperature * 10) / 10 + "°" : "unknown" }'
```
```
