### DISCUSSION TITLE
How to image_set and class_set for the same element?

### DISCUSSION THREAD

**Discussion by done7k** [ExperienceLovelace/ha-floorplan#267] [Q&A] [answered]
Can NOT set a CLASS for an image. 

```
    - name: weather icon
      entities:
        - weather.home
      state_action:
        - service: floorplan.image_set
          service_data:
            image: /local/floorplan/examples/home/weather-${entity.state}.svg
            cache: true
        - service: floorplan.class_set
          service_data:
            class: weathericon

```

This does not add the `weathericon` class to changed image element. If I remove `floorplan.image_set` the class is added. In another example I change text and set class and both work fine. Why `image_set` + `class_set` fail to add class?
