### DISCUSSION TITLE
elements

### DISCUSSION THREAD

**Discussion by vajonam** [ExperienceLovelace/ha-floorplan#27] [Q&A] [answered]
@exetico 

I have a sensor that needs to trigger multiple elements. So back_doors needs to trigger the state of 2 elements. I see that this is valid in the config. 

```
  - entity: binary_sensor.back_doors
    elements: 
      - binary_sensor.laundry
      - binary_sensor.patio
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data: "door-${entity.state}"
```

however when I run this it complains and about no element called `binary_sensor.back_doors` found. So I am guessing this not implemented yet?

**Comment by exetico** [comment, marked as answer]
Hi @vajonam  

So you need two elements (within your SVG) to be triggered, by a single `state` based of a Home Assistant entity, right?

I'm not sure if that's supported/implemented. But, it would make sense to implement for sure. I can see a good point of going so, in multiple scenarios.

If that's the point of this thread, fell free to create a feature-request 👍 !

**Reply by vajonam** [reply]
K will do.

**Comment by pkozul** [comment]
@vajonam Can you try something like this?

```
  - entity: binary_sensor.door
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: 'door-${entity.state}'
        elements:
          - svg.element1
          - svg.element2
```

The floorplan.class_set service allows you to specify multiple SVG elements.

**Comment by vajonam** [comment]
@pkozul  

if I set

```
  - entity: binary_sensor.back_doors
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data: "door-${entity.state}"
      elements:
        - binary_sensor.patio
        - binary_sensor.laundry
```

but because there is no element entity it complains about 

`floorplan.js:115 25/01/2021, 07:58:39 WARNING CONFIG Cannot find element 'binary_sensor.back_doors' in SVG file` 

but If I set the element on the top level it works as expected, seems a bit odd, but I can see how the code checks for the element first in the svg even its is overridden by the service_data. 

```
  - entity: binary_sensor.back_doors
    element: binary_sensor.patio
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: "door-${entity.state}"
        elements:
          - binary_sensor.patio
          - binary_sensor.laundry
```
