### DISCUSSION TITLE
Setting two classes for a single element based on two separate entities

### DISCUSSION THREAD

**Discussion by m90att** [ExperienceLovelace/ha-floorplan#300] [Q&A] [answered]
Hi,

I'm wondering what the best way to do this is.  My situation is that I have cctv camera elements that currently display if motion is detected by adding the class 'detected-on'.  I'd like to have these cctv camera elements show when the battery is low.  This is supplied from a different entity and I'd like to add 'battery-low' as a class.  My css will take care of how they are displayed.  For example:

element: cctv-front
class: 'detected-on' when entity camera.cctv_front_motion_detected is 'on'
class: 'battery-low' when entity camera.cctv_front_battery is 'on' (on means the low battery warning is on)
class: 'detected-on battery-low' when both entity states are 'on'

I can do both separately but the second overwrites the first rather than adds to it.  I can't find a floorplan.class_add service.  Would there be a way to do it with floorplan.class_toggle I wonder?

Thanks, Matt

**Comment by pkozul** [comment, marked as answer]
Hi @m90att 

Can you try this rule? I haven't tested it, but it should be OK.

```yaml
    - element: cctv-front
      entities:
        - camera.cctv_front_motion_detected
        - camera.cctv_front_battery
      state_action:
        service: floorplan.class_set
        service_data: |
          >
          let classes = [];

          if (entities['camera.cctv_front_motion_detected'].state === 'on')
            classes.push('detected-on');

          if (entities['camera.cctv_front_battery'].state === 'on')
            classes.push('battery-low');

          return classes.join(' ');
```
