### DISCUSSION TITLE
Time Formatting Question

### DISCUSSION THREAD

**Discussion by snbe82** [ExperienceLovelace/ha-floorplan#302] [Q&A] [answered]
Hello! First of all, I want to take the time to thank all of the developers of ha-floorplan. I've had so much fun setting this up, learning and experimenting along the way. You guys are awesome and I envy your coding knowledge!

<img width="1097" alt="Screen Shot 2022-12-19 at 10 47 23 AM" src="https://user-images.githubusercontent.com/26779591/208466181-757884eb-f8f2-4681-9c40-5fb9f82f3fd0.png">

I have a feeling I will have several questions, but the one I'm currently stuck on is _formatting my time from military to standard._

I saw in the documentation examples the ability to use `util.date.strftime` but I'm having trouble figuring out how/where to use that  code.

```
- element: textbox.clock
  entity: sensor.time
  state_action:
    action: call-service
    service: floorplan.text_set
    service_data: ${functions.util.date.strftime('%I:%M %p', sensor.time)}
```

This returns :
<img width="727" alt="Screen Shot 2022-12-19 at 11 13 03 AM" src="https://user-images.githubusercontent.com/26779591/208470245-1218e34e-a276-4d5d-8b8f-82a04432ba91.png">

I'm sure it's something simple, but I can't seem to figure it out :/

**Comment by exetico** [comment, marked as answer]
Hi

Thank you.

Is it just sensor.time, or something else?

The strftime is part of `util` not `functions`, so the utilities call should be to: `util.date.strftime`

`utils.date.strftime` expects a [date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date), but sensor.time only contains the time in the `state` key:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3549445/208477182-04135425-69ac-4c3c-bbe7-96b655ca3c51.png">

You'll have to create a valid date-string instead as pr. my knowledge. [strftime](https://www.npmjs.com/package/strftime) is very light-weight, so you'll have to do just a bit with your own hands 😸 (and not as `friendly` as a solution like [moment.js](https://momentjs.com/). We've used `strftime` to keep the package-size as low as possible.

You only have the timestamp in the `sensor.time`, so you'll need to help the library a bit for things to go as planned.

There's plenty of ways to do so, but here's a simple take on that part, now what you've provided the `sensor.time` to work with.

Here's a full example where you're able to learn a few tricks... Maybe?

```yaml

type: vertical-stack
cards:
  - type: markdown
    content: >-
      **Question**: How can I format sensor.time from military to standard (AM-PM).

      [Reference](https://github.com/ExperienceLovelace/ha-floorplan/discussions/302)
    title: Case 3
  - type: custom:floorplan-card
    full_height: false
    config:
      stylesheet: /local/floorplan/discussions/case3/case3.css
      image: /local/floorplan/discussions/case3/case3.svg
      console_log_level: debug
      defaults:
        hover_action: hover-info
        tap_action: more-info
      rules:
        # Reload button
        - element: button.reload
          tap_action:
            action: fire-dom-event
            browser_mod:
              service: browser_mod.javascript
              data:
                code: lovelace_reload();
        # Case
        - name: ConvertClockToAmPm
          element: customprefix.hue2_light
          entities:
            - sensor.time
          state_action:
            - service: floorplan.text_set
              service_data:
                element: customprefix.hue2_light
                text: |
                  > 
                  console.log(entity.state); // Entity value is "18:02"
                  const dateTimeString = "1900-01-01 " + entity.state; // You'll need to provide a full date-string to new Date() - so both date and time (See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
                  const dateTimeParsed = new Date(dateTimeString); // strftime expects a date object (See: https://www.npmjs.com/package/strftime)
                  return util.date.strftime('%I:%M %p',dateTimeParsed);
```

A bit stripped down version looks like:
```yaml
          state_action:
            - service: floorplan.text_set
              service_data:
                element: customprefix.hue2_light
                text: |
                  > 
                  return util.date.strftime('%I:%M %p',new Date("1900-01-01 " + entity.state));
```

And therefore also:
```yaml
          state_action:
            - service: floorplan.text_set
              service_data: ${util.date.strftime('%I:%M %p',new Date("1900-01-01 " + entity.state))}
```
