### DISCUSSION TITLE
Call-service floorplan.class_set evaluates script twice for two elements

### DISCUSSION THREAD

**Discussion by maxwroc** [ExperienceLovelace/ha-floorplan#304] [Q&A]
I'm trying to understand why the `class` value/script is being evaluated twice for the following rule:

I want to be able to click on the stairs element (there is a separate one for the ground and the first floor) to switch between the floors. So I wanted to bind listeners to the stairs elements (`ground_stairs_btn` and `first_stairs_btn`) and after click the group (`ground_floor` or `first_floor`) is shown or hidden. 

The `ground_stairs_btn` is a child of `ground_floor` and similarly the `first_stairs_btn` belongs to `first_floor`.

After clicking on `ground_stairs_btn` the `ground_floor` should be hidden and `first_floor` should be shown (class set to "visible"). And of course the opposite in the second case.

```yaml
    - name: Stairs
      elements:
        - ground_stairs_btn
        - first_stairs_btn
      tap_action:
        - service: floorplan.class_set
          service_data:
            element: ground_floor
            class: |
              >
              console.log("1", element.id);
              return element.id === "ground_stairs_btn" ? "hidden" : "visible";
        - service: floorplan.class_set
          service_data:
            element: first_floor
            class: |
              >
              console.log("2", element.id);
              return element.id === "ground_stairs_btn" ? "visible" : "hidden";
```

Here is what I get after clicking on the `ground_stairs_btn`:
![image](https://user-images.githubusercontent.com/8268674/208744418-7b60f100-8e50-470e-8a40-9ac498ce0377.png)

It looks like it evaluates the script against the target element which is a big surprise for me. Maybe the reason is that the "stairs" is one of the children of the target element?
