### DISCUSSION TITLE
Mutliple Floors - swiper-card custom card.

### DISCUSSION THREAD

**Discussion by vajonam** [ExperienceLovelace/ha-floorplan#31] [Show and tell]
An Idea for multiple floors.

Using the swipe-card https://github.com/bramkragten/swipe-card lovelace adding can do some cool effects to show multiple floors.

### yaml

```
type: 'custom:swipe-card'
parameters:
  effect: swipe
  preloadImages: false
  mousewheel: true
  parallax: true
  scrollbar:
    hide: false
    draggable: true
    snapOnRelease: true
cards:
  - type: 'custom:floorplan-card'
    title: Main Floor
    full_height: true
    config: /local/floorplan/mainfloor.yaml?v=2
  - type: 'custom:floorplan-card'
    title: Second Floor
    full_height: true
    config: /local/floorplan/secondfloor.yaml?v=2
  - type: 'custom:floorplan-card'
    title: Basement
    full_height: true
    config: /local/floorplan/basement.yaml?v=2
```

### result 

once setup you can swipe left and right to get the between the floors. 

![Peek 2021-01-23 13-05](https://user-images.githubusercontent.com/152501/105610104-c6a51400-5d7b-11eb-9fdc-64a56d3bade6.gif)
