### DISCUSSION TITLE
Using the same id for several SVG?

### DISCUSSION THREAD

**Discussion by ferbulous** [ExperienceLovelace/ha-floorplan#316] [Q&A] [answered]
Hi, I've added buttons icons to control lights & fans switch at my bedroom.
I've also added animation for the fan spinning when it's on, however with the fan button added, I can't use the same fan id for both items. Even if I use the fan id for the button icon, it would spin the icon instead of the fan svg

<img width="311" alt="image" src="https://user-images.githubusercontent.com/24526737/210967035-591404e6-fc48-4d7f-b16c-8d01585da9f7.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/24526737/211131168-87f6b94f-71d3-4858-9e78-8796d024fd41.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/24526737/211131185-9d4a9ac8-4404-44f7-9204-ba8b28c056eb.png">

yaml
```
            - entities:
                - switch.living_room_switches_3
                - switch.master_bedroom_3g_g2
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'switch-${entity.state}'

            - entities:
                - switch.living_room_switches_3
                - switch.master_bedroom_3g_g2
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "spinning" : ""}'
```

css
```
/* Spinning fan */

.spinning {
	animation-name: spin;
	animation-duration: 5s;
	animation-iteration-count: infinite;
	animation-timing-function: linear;
	transform-origin: center;
	transform-box: fill-box;
  }
  
  @keyframes spin {
	from {
	  transform: rotate(0deg);
	}
	to {
	  transform: rotate(360deg);
	}
  }

/* Switch icons */

.switch-off, .switch-off *  {
  opacity: 0.5 !important;
  stroke-opacity: 0 !important;
}

.switch-on, .switch-on * {
  stroke: #03A9F4 !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
}
```
What's the most suitable approach for this?
