### DISCUSSION TITLE
Fan animation moving when CSS applied

### DISCUSSION THREAD

**Discussion by Fidzero** [ExperienceLovelace/ha-floorplan#328] [Q&A] [answered]
Hello, 

I've been following along with the examples provided at https://experiencelovelace.github.io/ha-floorplan/docs/examples/ I am trying to replicate the fan functionality found on the Floorplanner Home Example, of a fan that can be turned on and off by clicking the icon and then having the icon rotate one the entity is "on" in home assistant. I have also included the multiple levels from the Multi Floor example. No matter what I try when I click the Element the Element moves its physical location on the card (moves to very top left), gets small and does begin its animation rotation.

I am using the CSS code and yaml code (albeit with my entity ID and Element names changed for my use case) from the Floorplanner Home Example. Any thoughts on solutions?

**Comment by OzGav** [comment, marked as answer]
You will need to post your CSS so we can see what you have and the YAML for your fan. Please make sure to format it with the <> button.

**Reply by Fidzero** [reply]
Appologies.

Fan YAML
```
- element: Upper-Bath-Fan
              entity: fan.upstairs_bathroom_fan
              tap_action:
                action: call-service
                service: homeassistant.toggle
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data:
                  class: '${(entity.state === "on") ? "spinning" : ""}'
```

CSS

```
/* SVG size */

#floorplan {
  padding: 10px;
}

#floorplan > svg {
  max-width: 1024px;
}

/* SVG elements */

svg * {
  vector-effect: non-scaling-stroke !important;
}
/* Animation */

.spinning {
  animation-name: spin;
  animation-duration: 5s;
  animation-iteration-count: infinite; 
  transform-origin: center;
  transform-box: fill-box;
  animation-timing-function: linear;
  position: relative;
  animation-fill-mode: Forwards;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
}

/* Hover over */

.floorplan-shape:hover,
g.floorplan-hover > :not(text):hover,
g.floorplan-click > :not(text):hover,
g.floorplan-long-click > :not(text):hover,
:not(text).floorplan-hover:hover,
:not(text).floorplan-click:hover,
:not(text).floorplan-long-click:hover {
  stroke: #03a9f4 !important;
  stroke-width: 1px !important;
  stroke-opacity: 1 !important;
}

 /* Entity State On */

.entitystate-on{
    opacity: 0.5;
    fill: rgb(250,250,210)!important
}

.entitystate-off{
    opacity:1;
}

/* Layers */

.layer-visible {
  display: inline !important;
}

.layer-hidden {
  display: none !important;
}
```

**Reply by OzGav** [reply]
OK yours is different to what I use. Try replacing your animation section with:
```
@keyframes rotation {
		from {
			-moz-transform: rotate(0deg);
               -webkit-transform: rotate(0deg);
                       transform: rotate(0deg);
		}
		to {
			-moz-transform: rotate(360deg);
             -webkit-transform: rotate(360deg);
                     transform: rotate(360deg);
		}
}

#fan\.upstairs_bathroom_fan,  {
          transform-origin: center;
  -webkit-transform-origin: center;         /* This affects iPad Safari */
     -moz-transform-origin: center;
	  -ms-transform-origin: center;
	    	       
}

.fan-on {
  animation: rotation 2s infinite linear;
  transform-box: fill-box;
  transform-origin: center;
}

```
And your yaml with (I have saved you a couple of lines by removing defaults)
```
            - element: Upper-Bath-Fan
              entity: fan.upstairs_bathroom_fan
              tap_action:
                service: fan.toggle
              state_action:
                service: floorplan.class_set
                service_data:
                  class: '${(entity.state === "on") ? "fan-on" : ""}'
```
