### DISCUSSION TITLE
Slow first time image loading

### DISCUSSION THREAD

**Discussion by kostromins** [ExperienceLovelace/ha-floorplan#331] [General]
Hi!

I am facing very slow image loading for floorplan. It takes about 6-9 seconds for image to appear in a card. SVG file is small, just few KB.

I have tried different SVG files as input, with and without rules, the loading time is approx the same.

Any ideas?

```
type: custom:floorplan-card
full_height: true
config:
  image: /local/solar/tmp.svg
  stylesheet: /local/solar/tmp.css
  rules: null 
```
