### DISCUSSION TITLE
Trouble Getting Values Into SVG

### DISCUSSION THREAD

**Discussion by jodysaliba** [ExperienceLovelace/ha-floorplan#332] [Q&A]
I can't seem to get this to work. I'm attempting to get a proof of concept working just pulling in one temperature sensor value, but can't seem to get working.

Preview of SVG:
![image](https://user-images.githubusercontent.com/1418509/227382592-57493983-2348-45b0-9e06-4fb7e19fe8d0.png)

I'm using Illustrator, since I don't want to download a program solely to get this going, but it seems like there's nobody else in here that is using Illustrator (search turns up empty). There's not a menu to input an "ID" in Illustrator, but it appears that you can change the ID by naming the elements like below:

![image](https://user-images.githubusercontent.com/1418509/227386002-cd88d4a0-6410-4be3-8981-a8dea4c111f6.png)

This is the output SVG from the above drawing:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="1280px" height="720px" viewBox="0 0 1280 720" style="enable-background:new 0 0 1280 720;" xml:space="preserve">
<rect id="background" style="fill:#E57373;" width="1280" height="720"/>
<text id="sensor.attic-temperature" transform="matrix(1 0 0 1 355.8149 436.5)" style="font-family:'MyriadPro-Regular'; font-size:260;">##.#*</text>
</svg>
```

As you can see, the text element itself has an ID of _sensor.attic-temperature_, and I put it in a group just to try to troubleshoot.

I've created a card with the following YAML:

```
config:
  console_log_Level: info
  defaults:
    hover_action: hover-info
    tap_actionL: more-info
  image: /local/floorplan/test-floorplan.svg
  rules:
    - element: sensor.attic-temperature
      entity: sensor.attic_temperature
      state_action:
        action: call-service
        service: floorplan.text_set
        service_data: ${entity.state}
  stylesheet: /local/floorplan/test-floorplan.css
  full_height: false
type: custom:floorplan-card
```

However, the following is what I get:
![image](https://user-images.githubusercontent.com/1418509/227386328-5188d02f-1fa5-4041-abe7-7f53cb7b715e.png)
I can't for the life of me figure out why the pinkish color is coming up transparent. Also, the placeholder "XX.X*" is extremely small and no value is displayed. My stylesheet is currently blank, as I just wanted to get a proof of concept going before attempting custom styles.

**Comment by jodysaliba** [comment]
Ok. made the change to my YAML (directly not caching the image):
```
config:
  console_log_Level: info
  defaults:
    hover_action: hover-info
    tap_actionL: more-info
  image:
    location: /local/floorplan/test-floorplan.svg
    cache: false
  rules:
    - element: sensor.attic-temperature
      entity: sensor.attic_temperature
      state_action:
        action: call-service
        service: floorplan.text_set
        service_data: ${entity.state}
  stylesheet: /local/floorplan/test-floorplan.css
  full_height: false
type: custom:floorplan-card
```
And now I get the following SVG:
![image](https://user-images.githubusercontent.com/1418509/227388005-1e3f24cf-ec5c-49b4-933c-f750cfae0d5b.png)
But how do I get the service call to override the placeholder text?
