### DISCUSSION TITLE
Floor plan SVG not visable

### DISCUSSION THREAD

**Discussion by GngrClapz** [ExperienceLovelace/ha-floorplan#336] [Q&A] [answered]
Let me start with im extremely new to HA entirely so i apologize if im missing things that would be considered common knowledge/simple! 
I downloaded all the files and i even follow the tut vid on YT until you copy the first yaml and return to see the floorplan svg, when i back out i see nothing besides 
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/133083982/b8366e44-49d2-4a47-9802-a27fbcba1924)

and then if i go back into the code and change  `  image: /local/floorplan/home_simple/home_simple.svg`   ` service_data: /local/floorplan/home_simple/light_${entity.state}.svg`  `stylesheet: /local/floorplan/home_simple/home_simple.css`    all by adding config to the front of them i get presented with a large Home assistant logo and diff errors! 
![Screenshot 2023-05-16 121500](https://github.com/ExperienceLovelace/ha-floorplan/assets/133083982/0a203348-f91b-4301-91ea-18811ab73ce7)
  the yaml im using come from this link directly ( https://github.com/exetico/Home-Assistant_Attachments-for-YouTube/tree/main/1_Getting-Started-with-ha-floorplan ) and ive made no changes to it besides what i mention!

**Comment by exetico** [comment, marked as answer]
Hi :-)

Welcome to the HA-world, and ha-floorplan.

Do you have a hacsfiles or www folder in your Home Assistant Configuration folder?
Did you restart Home Assistant, AFTER you installed HACS?
Where have you uploaded your svg and css file for your floorplan?

You can open your "Inspect" tool in the browser, to see where "ha-floorplan" are loaded from.

<img width="1060" alt="image" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/ca073c7d-c3c3-4ed4-83f8-d43620d32283">

We have had a few cases where people forget to restart Home Assistant after HACS has been enabled and the first addon installed.

If you're using the Hass.io solution, try `www` instead of `local` in `/local/floorplan/...`

**Reply by GngrClapz** [reply]
im pretty sure im using the hass.io version ? im using a Old PC to run my HA if that tells anything!
I tried changing the directories to `/www/floorplan`  and it still does not work! but i have taken screen grabs of where i store my files and my Inspect!  i dont seem to have the same thing you do to check where they load from! 
I did also restart HACS i even tried reinstalling the HA fp download from the video!

EDIT is there a way to tell if i installed improperly? 
edit of the edit  im a fool &forgot to add the screen snips
![Screenshot 2023-05-16 130854](https://github.com/ExperienceLovelace/ha-floorplan/assets/133083982/465784cb-a962-454d-bc95-1a34948783cc)
![Screenshot 2023-05-16 130910](https://github.com/ExperienceLovelace/ha-floorplan/assets/133083982/87d93fb4-586e-40bb-82fb-392f2d07341f)

**Reply by exetico** [reply]
The first thing i can see, if a "F" (uppercase) in the Floorplan folder. 

Could you try with a lower case one?

Also, kindly check with the inspection tool, as mentioned :)

**Reply by exetico** [reply]
@GngrClapz 
You started a new reply-thread by accident - lets use the first one :)

Thank you for the screenshot.

I'm unable to see what kind of problem you're facing as is. 

Have you tried opening up the URL in a new tab, or even another browser? 

You knowm the full URL for the .svg file. (`http://homeassistant:8123/www/floorplan/home_simple/home_simple.svg` if I type correctly)... Maybe also try with `local` in the other browser.

Are your homeassistant instance also resolveable at `homeassistant.local:8123` or similar? I just noticed that your pointing direcly to `homeassistant:8123` :)

And are you 100% sure that Home Assistant has been restarted? Like powered down, and started again? :) I'm not sure if that needed today, but they've improved their "restart" solution a bit over the years, so a good old restart by shutting it off, and turning it on again, could also be an idea.

If `config` are the top level of your Home Assistant instance, do you only see the `www` folder? If so, try and put in something else in the www folder, just to see if that changes somthing, and access the given file with `http://homeassistant:8123/www/whateverfile.png` or similar.

**Reply by GngrClapz** [reply]
okay, so im not sure which one did it but i started using firefox, and then coppied a new code ```
`title: Anton Floorplan
```
views:
  - title: Sample Entities
    path: sample-entities
    icon: ''
    badges: []
    cards:
      - type: entities
        entities:
          - entity: light.hueXYZ_light
            name: Test Light 1 (light.hue1)
          - entity: light.hue2_light
            name: Test Light 2 (light.hue2)
        title: Test Entities
  - title: My First Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_simple/home_simple.svg
          log_level: info
          rules:
            - element: light.hue1
              entity: light.hueXYZ_light
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: >-
                  /local/floorplan/home_simple/home_simple/light_${entity.state}.svg
              tap_action: toggle
            - element: light.hue1.button
              entity: light.hueXYZ_light
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: button-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light.hue1.text
              entity: light.hueXYZ_light
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${entity.state}
              tap_action: false
          stylesheet: /local/floorplan/home_simple/home_simple.css
        full_height: true
        type: custom:floorplan-card
```
```
`
 freshly from your files as i did originally and it works now! nothing else was changed! i went back to using local not www but the folder is still named www which confuses me! but oh well! 

 when you ask if my HA instance is resolvable at that location im not sure what you mean by this though!   my original question was answered though so ia ppreciate it it seems that maybe using google chrome doesnt work for me!
