### DISCUSSION TITLE
Simulate the flashing of LEDs

### DISCUSSION THREAD

**Discussion by Jonny-T-cyber** [ExperienceLovelace/ha-floorplan#34] [Q&A] [answered]
Hi everyone,
I'm a 'novice' with both HA and Floorplan.
My question is:
Using a binary-sensor in HA I would like to simulate the flashing of LEDs on a control panel recreated with a .svg file...
Anyone help me?
How do I post a picture here?
Thank you all

**Comment by exetico** [comment, marked as answer]
Hi

Pictures are shared with Ctrl+V, or by selecting the image icon.

Also, please take a look at this example - here's a battery-indicator in use:
https://experiencelovelace.github.io/ha-floorplan/docs/example-ring/

**Reply by Jonny-T-cyber** [reply]
The example is different from how I made it ...
In the following image I would like to turn on/off, for example, the small blue circle:

![image](https://user-images.githubusercontent.com/33354144/105905658-ffb2e200-6022-11eb-8afd-88ce054a79f3.png)

And this is my sensor code:
`
- platform: mqtt
  name: "coffe_LED_startPause"
  unique_id: "coffe_LED_startPause"
  state_topic: "coffee/status"
  payload_on: "d555000700000000380738070000000007200b"
  payload_off: "d5550007000000003807380700000000001917"
`
Please, can you help me?

**Reply by Jonny-T-cyber** [reply]
OK, I found the solution:

YAML:
```
- entity: binary_sensor.mySensor
  state_action:
    service: floorplan.class_set
    service_data:
      class: '${(entity.state === "on") ? "led_on_blue" : ""}'
```

CSS:
```
.led_on_blue {
  fill: #0000FF !important;
  fill-opacity: 1 !important;
}
```

Thanks all
