### DISCUSSION TITLE
Help with color of buttons

### DISCUSSION THREAD

**Discussion by Morcegolas** [ExperienceLovelace/ha-floorplan#340] [Q&A]
Hello, I’m new to ha-floorplan and I need some help. I’m adding some buttons, and in my current configuration my buttons have a small circle surrounding them, and when it’s off the fill of that circle is white, and when it’s on the white disappears because it have 0 opacity, the inside part is always black. 
I want to do it this way but I don’t know how. I want the fill on the circle to be always white, and the inside changes from grey ( off ) to black ( on ). 
Can anybody help me please?
Thanks. 

```
title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_modern/home_modern.svg
          rules:
            - element: light-kitchen-primary
              entity: light.cozinha_luz_cozinha_188
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-hall-primary
              entity: light.hall_de_entrada_luz_hall_95
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-francisca-primary
              entity: light.quarto_francisca_luz_87
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-office-primary
              entity: switch.luz_switch_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-hallway-primary
              entity: light.corredor_quartos_luz_corredor_85
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-mainroom-primary
              entity: light.quarto_principal_luz_quarto_p_80
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-mainroomrestroom-primary
              entity: light.wc_quarto_luz_wc_quarto_194
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: >-
                  /local/floorplan/home_simple/home_simple/light_${entity.state}.svg
              tap_action: toggle
            - element: button-reload
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.javascript
                  data:
                    code: lovelace_reload();
            - element: button-3dprinter-icon
              entity: switch.escritorio_mk3s_205
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: button-octoprint-icon
              entity: switch.escritorio_octoprint_170
              hold_action: more-info
          stylesheet: /local/floorplan/home_modern/home_modern.css
        full_height: true
        type: custom: floorplan-card
```

```
.entitystate-on{
    opacity: 0;
}

.entitystate-off{
    opacity: 1;
}
```

**Comment by OzGav** [comment]
You can make the background image where the button is white

**Reply by Morcegolas** [reply]
On the svg I changed 'button-octoprint-icon' from the circle to the icon, now when it is ON its black, but when is OFF it's white instead of grey. 
I can manipulate this on the svg, but for sure there is a better way of changing colours instead of changing opacity.

**Comment by Morcegolas** [comment]
I already got it going adding one more layer on the svg file for each button so when the opacity is set to 0 it shows the icon black with with background. But with this the 'clickable' area is only the black/grey logo, how do I fix this?

Thanks.

https://github.com/ExperienceLovelace/ha-floorplan/assets/14915279/51c4a3fe-d88d-4f1b-b398-f5375c6ce141

**Reply by OzGav** [reply]
If the circle is a SVG element then you can assign that the ID of `switch.escritorio_octoprint_170` then add to your CSS a class which changes the fill colour and not the opacity. When you then have a rule for the state change the fill colour will change.

**Reply by OzGav** [reply]
And to make your clickable area bigger you just have an invisible (no fill no stroke) shape at the top level that you are clicking.

**Reply by Morcegolas** [reply]
The circle is a svg element, on object proprieties I change ID to `switch.escritorio_octoprint_170` from what I understand. I need your help for the CSS part please.

**Reply by OzGav** [reply]
Something like (change the colour to whatever you like rgb values are also ok. See the docs for more ideas)

```
.entitystate-circle-on{
    fill: red;
}

.entitystate-circle-off{
    fill: blue;
}
```

**Reply by OzGav** [reply]
YAML addition 

```
            - entity: switch.escritorio_octoprint_170
              state_action:
                service: floorplan.class_set
                service_data: entitystate-circle-${entity.state}
```

**Reply by Morcegolas** [reply]
Thanks, I'm going to try it later today.

**Reply by Morcegolas** [reply]
The part of clicking the hole button is working, but the colour change its not, let me share my files with you:

CSS:
```
/* All good :/ */
.entitystate-on{
    opacity: 0;
}

.entitystate-off{
    opacity: 1;
}

.entitystate-circle-on{
    fill: red;
}

.entitystate-circle-off{
    fill: blue;
}
```

YAML
```
title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_modern/home_modern.svg
          rules:
            - element: light-kitchen-primary
              entity: light.cozinha_luz_cozinha_188
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-hall-primary
              entity: light.hall_de_entrada_luz_hall_95
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-francisca-primary
              entity: light.quarto_francisca_luz_87
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-office-primary
              entity: switch.luz_switch_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-hallway-primary
              entity: light.corredor_quartos_luz_corredor_85
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-mainroom-primary
              entity: light.quarto_principal_luz_quarto_p_80
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: light-mainroomrestroom-primary
              entity: light.wc_quarto_luz_wc_quarto_194
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: button-reload
              tap_action:
                action: fire-dom-event
                browser_mod:
                  service: browser_mod.javascript
                  data:
                    code: lovelace_reload();
            - element: button-3dprinter-icon
              entity: switch.escritorio_mk3s_205
              hold_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
            - element: button-octoprint-icon
              entity: switch.escritorio_octoprint_170
              hold_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
            - element: button-camera-icon
              entity: switch.escritorio_camera_rpi_207
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: button-blinds-icon
              entity: cover.escritorio_janela_180
              hold_action: more-info
            - element: button-lamp-icon
              entity: switch.luz_switch_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - entity: switch.luz_switch_1
              state_action:
                service: floorplan.class_set
                service_data: entitystate-circle-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
          stylesheet: /local/floorplan/home_modern/home_modern.css
        full_height: true
        type: custom:floorplan-card

```

PS: I had only changed the clickable area on the lamp icon to test, after I'll do it for all the others. Trying to understand all on my first room ;)

![home_modern](https://github.com/ExperienceLovelace/ha-floorplan/assets/14915279/86282084-75c7-451f-b4de-a20c69399ea4)

**Reply by Morcegolas** [reply]
I'm trying to get the logic here, already tried some things but didn't work. what I want to change color is the central part and not the circle itself.

I'm only testing the light icon:
```
            - element: lamp-clear-circle
              entity: switch.luz_switch_1
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: button-lamp-icon
              entity: switch.luz_switch_1
              state_action:
                service: floorplan.class_set
                service_data: entitystate-circle-${entity.state}
```

`button-lamp-icon` layer have 2 Paths in it, I think the problem might be in the circle or in this layer that have 2 Paths...
