### DISCUSSION TITLE
SVG Element click works properly only on paths in groups.

### DISCUSSION THREAD

**Discussion by nedevski** [ExperienceLovelace/ha-floorplan#343] [Bugs]
I've just started my ha-floorplan journey and I'm having a bit of an issue.

I've created a SVG file in Inkscape, I have areas for each room with the correct ID set.
I also have included the CSS file from one of the examples.

After creating the corresponding YAML, my areas are clickable and they toggle the entities (I'm using binary helpers for testing).
When using Inspect element, the correct areas also change their class to `light_on`/`light_off` respectively.

The issue is that only one of the areas actually changes it's color on click, the others are unresponsive.

See the attached file. The room on the right has 3 parts - top (desks), main (sofa and tv) and bottom (kitchen).
When I click on the kitchen - the class changes and the yellow dissapears. However when I click on the two living room parts, as you can see on the right - the class changes, but there is no change in visuals.

https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/0db0df0e-b1db-46d3-9e1b-a8313fe5cf17

**Comment by nedevski** [comment]
Update: I drew the areas as rectangles. For some reason that doesn't work.

If you're using a regular path - that also doesn't seem to work.

However if you put the path in a group and rename the group with the correct ID - suddenly it all works.

So in summary - you can't use rectangles or paths to be the clickable element, it has to be a **group** holding everything.

Here is my Inkscape project for clarity:
![floorplan-project](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/5fbff06c-619b-4546-aa47-b9b0d86ad5aa)

In order for it to work properly in HA, I export it to "plain SVG" and use that.

**Reply by OzGav** [reply]
Not sure that is true. Rectangles should work. If one of yours worked then they all should work. I suspect there is something different in the SVG between the elements…?

**Reply by nedevski** [reply]
I know it *should* work, but it doesn't, that's why I'm so baffled by it. I can provide additional info and even show you in a video call.

Not sure what is different between them - the kitchen is a group of 2 shapes, because it has two parts, the rest of the rooms are plain rectangles, because there is no need for anything more complex.

I just clicked on the shape thing in inkscape and drew the outline, then changed the ID in the properties. It's not even that I duplicated an element with some weird metadata, all shapes were drawn from scratch.

**Reply by OzGav** [reply]
Try taking the rectangle that does work and duplicate it (copy and paste) and see if that works….

**Reply by nedevski** [reply]
No rectangle works, the working area is a group with 2 shapes in it.

**Reply by OzGav** [reply]
Also please show your yaml I wonder if that is it actually….

**Reply by OzGav** [reply]
To prove if it is the yaml you could swap the working ID with a rectangle elsewhere and try clicking it

**Reply by nedevski** [reply]
```
- type: custom:floorplan-card
  full_height: true
  config:
    image: /local/floorplan/floorplan-export.svg
    stylesheet: /local/floorplan/floorplan.css
    cache: false
    log_level: info
    console_log_level: info
    defaults:
      hover_action: hover-info
      tap_action: more-info
    rules:
      - name: Rooms
        entities:
          - entity: input_boolean.living_room_light
            element: area.living_room_main
          - entity: input_boolean.living_room_terrace_light
            element: area.living_room_terrace
          - entity: input_boolean.kitchen_light
            element: area.kitchen
          - entity: input_boolean.bedroom_small_light
            element: area.bedroom_small
          - entity: input_boolean.bedroom_large_main_light
            element: area.bedroom_large_main
          - entity: input_boolean.bedroom_large_terrace_light
            element: area.bedroom_large_terrace
          - entity: input_boolean.terrace_light
            element: area.terrace
          - entity: input_boolean.bathroom_light
            element: area.bathroom
          - entity: input_boolean.toilet_light
            element: area.toilet
          - entity: input_boolean.server_room_light
            element: area.server_room
          - entity: input_boolean.hallway_inner_light
            element: area.hallway_inner
          - entity: input_boolean.hallway_outer_light
            element: area.hallway_outer
        tap_action: input_boolean.toggle
        state_action:
          service: floorplan.class_set
          service_data: '${entity.state === "on" ? "light-on" : "light-off"}'
      - name: Temperature
        entities:
          - input_number.temp_living_room
          - input_number.temp_small_bedroom
          - input_number.temp_large_bedroom
        state_action:
          - service: floorplan.text_set
            service_data: >-
              ${(entity.state !== undefined) ? entity.state + "°C"
              : "unknown"}
          - service: floorplan.class_set
            service_data:
              class: static-temp

```

**Reply by OzGav** [reply]
Why are you using input booleans?

**Reply by nedevski** [reply]
Because I haven't mounted all of the switches yet and I'm testing with that instead

**Reply by OzGav** [reply]
Ok. You also don’t need the element line for your simple setup. You can make the inkscape ID the same as your input boolean entity_id

**Reply by OzGav** [reply]
Also which one works?

**Reply by nedevski** [reply]
This one is the group:
```
- entity: input_boolean.kitchen_light
  element: area.kitchen
```

Bottom right on the plan.

**Reply by nedevski** [reply]
Ok, I've left a rectangle with just this in the config:
```
- entity: input_boolean.bedroom_large_terrace_light
```

ID/name are the same in the SVG, now it's not even clickable.

**Reply by OzGav** [reply]
Ok. First anything showing in the log at the bottom of the floorplan? Second try swapping the working ID to a non working rectangle. Third simplify your setup by removing all element lines and changing all Inkscape IDs to their corresponding entity_id

**Reply by OzGav** [reply]
Flush the browser cache

**Comment by nedevski** [comment]
@OzGav New thread, started from scratch. This is just providing a good starting point for my issue with bare minimum stuff in the way and I'm going to try your suggestions above in a bit.

I have only 1 zone - `light.living_room`. It's connected to a real device - `light.shelly_plug`.
Below is my configuration. The zone is active and it works, it toggles the device on/off.

However the visual layer doesn't toggle itself.

The image is definitely not cached and I restarted HA after adding the new file for good measure.

I'm using [this CSS](https://github.com/ExperienceLovelace/ha-floorplan/blob/master/docs/_docs/floorplan/examples/floorplanner_home/floorplanner_home.css) from the repo as is.

![floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/416db828-4b71-45ee-848f-f17e637ffa14)

```yaml
- type: custom:floorplan-card
  full_height: true
  config:
    image: /local/floorplan/v2/floorplan.svg
    stylesheet: /local/floorplan/v2/floorplan.css
    cache: false
    log_level: info
    console_log_level: info
    defaults:
      hover_action: hover-info
      tap_action: more-info
    rules:
      - name: Rooms
        entities:
          - entity: light.shelly_plug
            element: light.living_room
        tap_action: light.toggle
        state_action:
          service: floorplan.class_set
          service_data: '${entity.state === "on" ? "light-on" : "light-off"}'
```

**Reply by nedevski** [reply]
Change 1: Added a new **green** rectangle called `light.shelly_plug`.

![floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/9752d47e-eba3-4eb6-8d46-78714cbdeb12)

Modified the YAML to this, making the SVG layer and the entity share the same name and being the only clickable thing anywhere:

```yaml
rules:
  - name: Rooms
    entities:
      - entity: light.shelly_plug
    tap_action: light.toggle
```

Now the green rectangle is not clickable at all. I also have an error:
```
WARNING CONFIG Cannot find element 'undefined' in SVG file
```

**Reply by nedevski** [reply]
Change 2: Added the `element` parameter, now it's back to square one - device works, layer does **not** get toggled.

No logs in the console below.

```yaml
entities:
  - entity: light.shelly_plug
    element: light.shelly_plug
tap_action: light.toggle
```

**Reply by nedevski** [reply]
Change 3: I am dumb. I looked at the examples and understood why Change 1 is not working.
It's not `entity: something`, but `entities:` with passed a list.

That fixed the issue with the clickability and the device being toggled.
Still nothing on the visual side.

```yaml
rules:
  - name: Rooms
    entities:
      - light.shelly_plug
    tap_action: light.toggle
```

**Reply by nedevski** [reply]
Change 4: After change 2 didn't work, I renamed the green rectangle to a different name - `area.shelly_plug` with the yaml below.

This way it finally works??? And I'm not sure why.

Attaching the file for consistency
![floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/fe5813ea-c952-4db4-9ff1-1ca49fc5044b)

```yaml
entities:
  - entity: light.shelly_plug
    element: area.shelly_plug
tap_action: light.toggle
```

**Reply by nedevski** [reply]
Change 5: I added the green path shape in a group called LIGHTS by itself, while keeping its name and ID. Works well, the layer gets toggled. Good.

I've then added a rectangle for the living room called `area.living_room`. This is where it gets interesting.

With the SAME SVG it's working for the green rectangle, but not for the orange rectangle.
=> I'm only changing the `element:` name from `area.shelly_plug` to `area.living_room`.

Works for the green area, does not work for the orange one.

![floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/de847f3c-ed97-4930-9318-7218dc8db3ba)

```yaml
# does not work
rules:
  - name: Rooms
    entities:
      - entity: light.shelly_plug
        element: area.living_room
    tap_action: light.toggle
```

**Reply by nedevski** [reply]
Change 6: It's consistent now. I added two more layers - a weird shape called `area.bedroom_large` and a yellow rectangle called `area.bathroom`.

Both work as device toggles. Only the weird shape dissapears when clicked.

![floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/7324633/9dacce2a-7b15-49a5-9b88-8effa8f82b88)

```yaml
#works
entities:
  - entity: light.shelly_plug
    element: area.bedroom_large
tap_action: light.toggle
```

```yaml
# does not work
entities:
  - entity: light.shelly_plug
    element: area.bathroom
tap_action: light.toggle
```
