### DISCUSSION TITLE
How to make `class_toggle` work?

### DISCUSSION THREAD

**Discussion by patfelst** [ExperienceLovelace/ha-floorplan#344] [Q&A]
Hi I've tried many variations of syntax, but I can't get `class_toggle` to work. I have a button on my floorplan, each time I press it, I want to toggle the visibility of two text elements (room temperature). I know the button and css work as I tested them with `.class_set` (and `layer-visible`) and it works ok. 

Here is my rule and css:

```yaml
    - element: show-temps.button # this is actually an svg group, but its ID is set to this
      tap_action:
        service: floorplan.class_toggle
        service_data:
          classes:
            - layer-visible
            - layer-hidden
          elements:
            - temp-alfresco
            - temp-back-lounge
```
and css
```css
.layer-visible {
  display: block !important;
}
 
.layer-hidden {
  display: none !important;
}
```
I've read discussions https://github.com/ExperienceLovelace/ha-floorplan/discussions/23 and https://github.com/ExperienceLovelace/ha-floorplan/discussions/91 but still no luck.

I also have this, which successfully hides the text at startup:
```yaml
  startup_action:
    - service: floorplan.class_set
      service_data:
        elements:
          - temp-alfresco
          - temp-back-lounge
        class: layer-hidden
```

**Comment by OzGav** [comment]
I am going to suggest a different approach. Use a binary sensor to track the button press and then show and hide the other two elements based on the state of that sensor. Example (you shouldn't need the startup action):

```
            - tap_action:
                service: input_boolean.toggle
              entities:
                - input_boolean.show-temps-button
                
            - entity: input_boolean.show-temps.button
              element: temp-alfresco
              state_action:
                - service: floorplan.class_set
                  service_data:
                    class: '${(entity.state === "off") ? "always-visible" : "always-invisible"}'

            - entity: input_boolean.show-temps.button
              element: temp-back-lounge
              state_action:
                - service: floorplan.class_set
                  service_data:
                    class: '${(entity.state === "on") ? "always-visible" : "always-invisible"}'
```

You need to create the binary sensor elsewhere. Label the button you have in your SVG as `input_boolean.show-temps.button `or whatever you call it

```
.always-invisible {
  visibility: hidden !important; 
  opacity: 0 !important;
  stroke-opacity: 0 !important;
}

.always-visible {
  visibility: visible !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
}
```
