### DISCUSSION TITLE
Auto rotate based on orientation

### DISCUSSION THREAD

**Discussion by Abductist** [ExperienceLovelace/ha-floorplan#36] [Q&A] [answered]
Hi all,

Let me first just state that HA-Floorplan is amazing and so much thanks to everybody who has done any work on this. My question is, I have a floorplan where the width and the height aren't very similar so I'd like to have the SVG rotate based on the orientation of the device (ie my phone is portrait while my computer is landscape). I can get the SVG to rotate fine by using the following in my css file:

@media (orientation: landscape) {
  svg {
    transform: rotate(90deg);
  }
}

The problem with this is that the card doesn't resize appropriately. I'm a relative novice to CSS and was wondering if anyone knew how to get that working properly.

Thanks in advance!

**Comment by pkozul** [comment]
Hi @Abductist 

Thanks for trying out floorplan.

We haven't done any work on supporting rotation/orientation, but if we come up with a good solution, we'll post it there.

**Comment by exetico** [comment, marked as answer]
Hi Abductist

Did you find a good solution? 

If so, please share your code, so other people can use it :) 

If not, kindly let us know as well.

**Reply by pkozul** [reply]
Hi @Abductist 

We do have the ability to specify different SVG images, based on the size of your screen.

Can you try using the following format in your floorplan config? The `min_width: 0` image should be for the mobile version of your SVG, and then the `min_width: 576` should be for your normal (larger) SVG. You can change the `min_width` value to whatever makes sense, based on the screen width of your mobile.

```
title: Home
config:
  image:
    sizes:
      - min_width: 0
        location: /local/floorplan/examples/home/home-mobile.svg
      - min_width: 576
        location: /local/floorplan/examples/home/home-normal.svg
  stylesheet: /local/floorplan/examples/home/home.css
```

**Reply by philosowaffle** [reply]
I see this has been marked as answered, but I would like to raise that the current proposed solution is painful.  It requires us to maintain duplicate copies of our floor plan and to then ensure each one is updated anytime we make a change.  For simple transformations, like wanting to rotate the image when on a smaller screen, it would be much more ideal to have support for `@media` and transforms in the CSS.

In my specific use case, my floorplan looks great on my computer or on a tablet where you are likely working in landscape mode. However, on my phone, the icons are barely clickable because they are so small.  I would like to be able to rotate the floorplan to "portrait" orientation when on a small device like my phone so that it can take up more of the vertical screen real estate.

```
@media (max-width: 1024) {
  #floorplan > svg {
    transform: rotate(90deg);
    max-width: 1024;
  }
}
```

**Reply by OzGav** [reply]
So I assume you have tried this and it doesn't work? I though ha-floorplan would work with any valid CSS?

**Reply by exetico** [reply]
Hi @philosowaffle  

It's really up to the person, what works best for each use-case. Using the CSS are a good suggestion, if you're up to that kind of thing. So thank you for pointing that out. People are very welcome to do whatever they want, so it's good to have more inspiration on the table, for people to use :)

**Reply by philosowaffle** [reply]
@exetico maybe I should clarify. The css I posted does not work.  I expect it to work. In my hunt to determine why it doesn't work I came across this thread which to me implied this kind of css was not supported.

**Reply by OzGav** [reply]
What other options are you using though as you may be encountering limitations of Home Assistant as well? For example are you using `panel:true`

**Reply by exetico** [reply]
@philosowaffle  - Context are always a nice things. Thanks!

Remember to add `px` to the width-property in your mediaqueries :-) 

```css
@media only screen and (max-width: 1200px) {
  #floorplan > svg {
    transform: rotate(90deg);
    max-width: 1024;
  }
}
```

If you're ready to do something more modern, go with something like this:
```css
@media only screen 
  and (min-device-width: 1px) 
  and (max-device-width: 900px) 
  and (-webkit-min-device-pixel-ratio: 3)
  and (orientation: portrait) { 
    #floorplan > svg {
      transform: rotate(90deg);
      max-width: 1024;
    }
}
```

_Fell free to adjust the widt, and so on._

On that note: My phone are already rotating the viewport, if I rotate the phone, so I don't really get why it's a good idea. But for people with disabled "auto rotate", I totally get it.

![image](https://user-images.githubusercontent.com/3549445/143478274-f4586e9a-7a4f-46f3-b79f-17b8c8a4a30e.png)
