### DISCUSSION TITLE
Integrating text into the Floorplan (temperature)

### DISCUSSION THREAD

**Discussion by tinkerberlin** [ExperienceLovelace/ha-floorplan#362] [Q&A]
Hi there, 
I hope somebody can help. 

I'm trying to show the current temperature of a room in a text field on the floorplan. Lights (svg layers on/off) are working fine. However, I can't get the floorplan.set_text function to work. I've followed [this ](https://github.com/ExperienceLovelace/ha-floorplan/blob/master/docs/_docs/floorplan/examples/floorplanner_home/floorplanner_home.yaml) example and adapted it slightly (e.g. the "-" don't work in my config, I need to remove those for some reason). Below you can find the yaml code. I've also made a screenshot of the card; I'd want the "Udestue C" placeholder text to be replaced with the temperature.

Ideally, going forward, I might also have a "/ set temp" field (i.e. if the current temp is 19°C and the set-temp is 21°C it would say "19°C / 21°C"). But that's a problem for future me....

My attempt at getting the temperature into the floorplan is all the way at the bottom of the yaml-code.

Thank you!!

```
type: custom:floorplan-card
full_height: false
config:
  image: /local/Floorplan/EG-2-export2 (1).svg
  stylesheet: /local/Floorplan/EG.css
  defaults:
    hover_action: null
    tap_action: null
  rules:
    - entity: light.virtual_flur_unten
      element: Light.Flur-Unten
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.testswitch
      element: Light.Gaestezimmer
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_abstellkammer
      element: Light.Abstellkammer
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_wc_unten
      element: Light.WC-unten
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_treppenhaus_unten
      element: Light.Treppenhaus-unten
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_kuchenlicht
      element: Light.Kuechenlicht
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_wohnzimmer
      element: Light.Wohnzimmer
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_wohnzimmerregal
      element: Light.Wohnzimmerregal
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_esszimmer
      element: Light.Esszimmer
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: light.virtual_kuchentresen
      element: path27004
      state_action:
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "layer-visible" : "layer-hidden"}'
    - entity: sensor.temperatursensor_temperature
      element: text.tempbuero
      state_action:
        service: floorplan.text_set
        service_data: >-
          ${(entity.state !== undefined) ? Math.round(entity.state * 10) / 10 +
          "°" : "unknown"}
```

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/99590368/a296e453-56ef-4e9b-9fce-17a1753d215e)
(yes, I know the "light" effect isn't nice (yet), this is just pre-going live.)

**Comment by tinkerberlin** [comment]
I'm stupid and that's that. closing. 
I missed that in the svg the entity name was different from what I thought I had set it to.

**Reply by OzGav** [reply]
Before you go have a look at the examples to simplify your yaml. You can see your state action is the same in every rule so you can collapse all that down to half what you currently have.

**Reply by tinkerberlin** [reply]
Thank you @OzGav ! Yeah I know I could do that. However, for the time being, I'm happy it's working as intended. Once I have everything as I want it, I'll go about making things better/nicer/cleaner. 

I've looked at the examples a lot (!), just some things don't get into my head, so I'm using what I understand and working from there :-)

Btw. would you happen to know the syntax to pull the currently set temperature of a heater element into the textbox? I've tried a bunch of options, but nothing has worked so far.

**Reply by OzGav** [reply]
Is it an attiribute? `${entity.attributes.attribute_name}`

**Reply by tinkerberlin** [reply]
Yes. See the highlighted line in the screenshot below. 
Essentially, I'd want to have it say ("current temperature" / "desired temperature") 
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/99590368/3b61b6a6-790e-4b77-9d88-458678bd8e04)


[and super ideally, the color of the text (i.e. of the two temperature values) would be - let's say - black if the heater is off or the desired temperature is lower than the actual temperature and red if the desired temperature is above the actual temperature and the heater is heating. Too much? :-) ]

**Reply by tinkerberlin** [reply]
Or here: 
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/99590368/688dd7a6-dc82-4fbb-8dca-c1e6e1a12cb2)

**Reply by tinkerberlin** [reply]
I think the problem is, that I am trying to reference two HA entities in one text-field.?

**Reply by OzGav** [reply]
No problem! ha-floorplan exposes all HA entities. You can ccess the state of them like so:

`if(hass.states["sun.sun"].state === "below_horizon")`

`hass.states["fan.alfresco"].attributes.friendly_name)`

**Comment by tinkerberlin** [comment]
Thank you @OzGav! That has worked beautifully! Just one question: Is there a way to have the text update immediantly if the state of the attribute changes? So in this example: If I select a higher or lower temperature on the heater, it does not update the text with that new "target-temperature". I'd have to reload the entire dashboard for the value to upate on the floorplan.

**Reply by OzGav** [reply]
I think I recall this request from someone else in the past but not sure of a definite solution. I haven’t done this but maybe try a template sensor which reflects the attribute although it might only update when the state of the entity updates…?

**Reply by tinkerberlin** [reply]
Thank you for your help. 

I found a way to do this, that updates nearly instantaniously. Perhaps of interest to somebody in the future, so posting it here:

Create a "generic thermostat" in the config.yaml. For example: 
 ```
 - platform: generic_thermostat
    name: TEST_ClimateInFloorplan
    heater: climate.heater
    target_sensor: sensor.temperatursensor_temperature
    min_temp: 5
    max_temp: 40
    ac_mode: false
    target_temp: 17
    cold_tolerance: 1
    hot_tolerance: 1
    min_cycle_duration:
      seconds: 5
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1
```

To be clear, most of the stuff in there is not strictly necessary. So as you can see (@OzGav I know you'll know this, so this is more for anybody else), I've included the temperature sensor (any random temp sensor that you can integrate into HA) as the "target_sensor". This is the temperature the room currently has. The attribute "target_temp" is the temperature the room wants to achieve/is supposed to achieve. So this generic thermostat then controls the heater.

This way the target temperature and the current temperature are both in the same entity, meaning I can pull attributes from one entity into the floorplan...

```
    - entity: climate.test_climateinfloorplan
      element: text.gaestezimmer
      state_action:
        - service: floorplan.text_set
          service_data: >-
            ${entity.attributes.current_temperature != "unavailable" ?
            Math.round(entity.attributes.current_temperature) + " °C" :
             "?"} /  ${entity.attributes.temperature != "unavailable" ?
            Math.round(entity.attributes.temperature) + " °C" :
             "?"}
        - service: floorplan.class_set
          service_data:
            class: static-temp
```
