### DISCUSSION TITLE
Problem with config file (Cannot find 'pages' nor 'rules' )

### DISCUSSION THREAD

**Discussion by misko2k** [ExperienceLovelace/ha-floorplan#38] [Q&A] [answered]
Hi @all,
I am new with HA floorplan, and i have following problem. I have made my config  over raw configurator editor. 
My browser console shows me warning about this message , and i have rules defined. 

I added picture from chrome window where i read this message , and another one is my config. Can you please help me what is there wrong and where i can find description about structure of config file ?

![floorplan_rules](https://user-images.githubusercontent.com/21138890/106358291-accf7800-630b-11eb-8b45-fb64d83faf23.jpg)
![no_rules](https://user-images.githubusercontent.com/21138890/106358296-b35def80-630b-11eb-977c-c07a0dcef1e6.jpg)

**Comment by exetico** [comment, marked as answer]
Hi,

We're still working on the docs, but why this example:
https://experiencelovelace.github.io/ha-floorplan/docs/example-home/

Which version of Chrome, are you using? `enumerateDevices` should not be related to our solution. If it's anything related to ha-floorplan, it must be something with `navigator.userAgent` in `utils.ts`, but i don't think so. And I guess that's a bit too complicated for you. Sorry 😄 

Please do the following things:
- Create the same view, but with a normal Home Assistant component, and see if it's reporting the same error, too.
- Try and use the example form the "home" link, or one of the other examples.

**I don't really think the issue is related to ha-floorplan, but let me know how it goes** 😃

_And oh: Please don't use tags, unless it's **very important**_ 👍

**Reply by misko2k** [reply]
Sorry for tagging , didn't know that this will send kind of alert to all users..

About me , i am experienced microsoft full stack developer , coding since '91, so coding stuff is not to complicated to me.

1.) i have installed over HACS , HA-Floorplan , have added resource (/hacsfiles/ha-floorplan/floorplan.js) over configuration---> Lovelace Dashboard , after this i added new dashboard "my penthouse" and then i clicked on left side on "my pehthose" dashboard
2.) now i got copy of default dashboard , cleaned them up and over "Edit Dashboard", then "Raw configuration editor" got empty editor
3.) now here i have put this configuration from picture above ( i have added it as text too in this attachment)
4.) You have right that "enumerateDevices" is not part of HA-Floorplan (is part of Hass.IO and nothing has common to this post)
5.) I have added screenshoot of my console window to show your HA-Floorplan relevant lines , so that everyone can see which version of HA-Floorplan i use , and following message is related to this post

my rules will never fire cause HA-floorplan can not find them in my config. You see that HA-Floorplan is working , partialy , cause i get log messages

So can you please explain me structure of config file , or where is the bug in my config ? Or is this little too complicated for you ? 😂

![error](https://user-images.githubusercontent.com/21138890/106361125-8bc35300-631c-11eb-99cd-cb1a7916aa6a.jpg)


[my_penthouse_raw_Editor_config.txt](https://github.com/ExperienceLovelace/ha-floorplan/files/5898202/my_penthouse_raw_Editor_config.txt)

**Reply by exetico** [reply]
Hi again. You've not send out alerts - so no problem. I would just like to mention it, so no tag-notifications was sent to me 😄 ..


Both `defaults` and `rules` are at the same level as `config`. Why didn't you take a look at the example, as I was asking you to do? Or, maybe you didn't test with the example itself? (which was the point of it).

![image](https://user-images.githubusercontent.com/3549445/106364576-4c9efd00-6330-11eb-9bd2-eb6dd5653fe0.png)

![image](https://user-images.githubusercontent.com/3549445/106364584-5fb1cd00-6330-11eb-922d-b3ce5094ef87.png)


Please use the example(s), if you're not sure where to start with YAML 👍  (That's why I linked to it)

Move in both "defaults" and "rules", and you're good to go! 🔥 

Here's your code, like it should be:
```yaml
views:
  - panel: true
    badges: []
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          image: /local/floorplan/floorplan.svg?v=1.0.10
          stylesheet: /local/floorplan/floorplan.css?v=1.0.10
          log_level: info
          console_log_level: info
          defaults:
          hover_action:
              action: hover-info
              tap_action: more-info
          rules:
            - entity: sensor.wohnzimmer_temperature
                state_action:
                - service: floorplan.text_set
                    service_data: '${entity.state ? "known" : "unknown"}'
            - entity: media_player.sony_bravia_tv
                state_action:
                - service: floorplan.text_set
                    service_data: '${entity.state ? "known" : "unknown"}'
```
As you can see, each `- entitiy` should be pushed in a bit, too. Maybe you should  spend some time on the [basics](https://www.youtube.com/watch?v=FfjSA2o_0KA)
