### DISCUSSION TITLE
Error floorplan-card : Cannot read properties of undefined (reading 'ForEach')

### DISCUSSION THREAD

**Discussion by HugoNaza** [ExperienceLovelace/ha-floorplan#387] [Bugs] [answered]
Hello Home Assistant Community,

I am reaching out for some guidance regarding issues I've encountered while setting up a 3D floorplan on Home Assistant. Despite following the BitBorn tutorial closely and integrating all elements (including IDs, xlink:href, href, areas, and entities) via Inkscape, I am facing persistent error messages that I'm unable to resolve.
I have dowload floorplan and plugin associate with floorplan, and install the cards not in HACS manually like floorplan-card. I work also with YAML dashboard. 

![XML_Editor](https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/c7bd9487-926f-4cf6-bd8e-bc4c5814ed4d)

After uploading the SVG with only the background, the same errors occur. My YAML and CSS configurations seem correct, without apparent duplications that the error suggests. Even with a minimal YAML configuration, the error persists. Furthermore, all configurations have been double-checked for accuracy.

The SVG appears to load correctly initially upon clearing the cache and refreshing, displaying images, areas, entities, and shapes. However, after a few seconds, the following error messages appear: Cannot read properties of undefined (reading 'ForEach')
I have already try to hard-refresh, re-installe the plugin, search double occurrence, dowgrade home-assistant to update 2023.11.3 (I was in 2023.12).

I am attaching the error messages and the relevant portions of my code for reference.

Error : 

<img width="637" alt="Error" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/a3829156-bc53-4ab3-9342-7727748d787b">

![Error_console](https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/90f64113-5a72-44ca-9c70-cf201362e164)

YAML :

```
views:
  - title: 'Floorplan'
    path: 'floorplan'
    icon: 'mid:floor-plan'
    theme: 'lovelace-blue-blur'
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        entity: fp-card
        image: "/local/floorplan/floorplan_optimised.svg"
        stylesheet: '/local/floorplan/floorplan.css'
        style: >
          ha-card {
            max-width: 150vh;
            margin: 0 auto;
            background: none;
            box-shadow: none;
          }
        config:
          rules:
            - entity: media_player.tele_du_salon_2
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-tv media-player-${entity.state}'

            - entity: media_player.tv_chambre_2
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-tv media-player-${entity.state}'

            - entities:
                - binary_sensor.sensor_salon_v_2_mouvement
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'motion motion-${entity.state}'

            - entities:
                - light.buanderie
                - light.bureau
                - light.canape
                - light.couloir_01
                - light.couloir_02
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action: false
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'

            - entities:
                - light.buanderie
                - light.bureau
                - light.canape
                - light.couloir_01
                - light.couloir_02
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action:
                action: 'toggle'
              hold_action:
                action: more-info
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  element: "${entity.entity_id.replace('light.', 'light_overlay.')}"
                  style: |
                    if (entity.state != 'on') {
                      return 'display: none;';
                    }
                    let hue = 0;
                    let sat = 0;
                    if (entity.attributes.hs_color) {
                      hue = entity.attributes.hs_color[0];
                      sat = entity.attributes.hs_color[1];
                    }
                    if (sat < 10) {
                      return `
                        display: block;
                        filter: brightness(calc(${entity.attributes.brightness} / 255));`;
                    }
                    return `
                      display: block;
                      filter: sepia(100%)
                        hue-rotate(calc(${hue}deg - 55deg))
                        saturate(calc(${sat}% * 2))
                        brightness(calc(${entity.attributes.brightness} / 255));`
```

CSS :

```
`@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

svg, svg * {
  pointer-events: all !important;
  cursor: auto !important;
}

svg path {
  fill: inherit;
  stroke: inherit;
  stroke-width: inherit;
}

#light-overlays image {
  display: none;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;

}

#light-overlays image.light-on {
  display: block;
}

#areas path {
  fill: none;
}

#areas .light-on {
  stroke-width: 6px;
  stroke-opacity: 1;
  stroke: #a5e0e1;
}
`
```

Configuration.yaml :

``` 
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  dashboards:
    home-dashboard:
      mode: yaml
      title: Home
      filename: lovelace/dashboards/home/home-dashboard.yaml
  resources: # This should not be under dashboards
    - url: /local/cards/floorplan-card/floorplan-card.js
      type: module
    - url: /local/community/ha-floorplan/floorplan.js
      type: module
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module
    - url: /local/cards/card-mod/card-mod.js
      type: module
    - url: /local/cards/autoentities/autoentities.js
      type: module
    - url: /local/cards/button-card/button-card.js
      type: module`
````

I have search in internet, github or homeassistant forum, even ChatGPT, but I don't find any solution. 
Could anyone please provide insights into what might be causing these issues or suggest further troubleshooting steps?

Thank you for your time and assistance.

Best regards,

**Comment by OzGav** [comment]
Can you please format all the yaml with the <> button

**Reply by HugoNaza** [reply]
Thanks a lot for your answer, effectively the presentation was not optimal. I have reorganize the informations and put the code in box <> to be more clear. 

If you need any others informations or have any suggestions, I'm available. Thanks for your time.

**Reply by OzGav** [reply]
Have you installed ha-floorplan via HACS?

**Reply by OzGav** [reply]
Just trying to look at this now. Firstly, the tutorial you are trying to follow is very advanced. Try the following simplified yaml (I also fixed typos (e.g. mid in your icon line) and removed unnecessary quotes)

```
views:
  - title: Floorplan
    path: 'floorplan'
    icon: 'mdi:floor-plan'
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        config:
          image: /local/floorplan/floorplan_optimised.svg
          stylesheet: /local/floorplan/floorplan.css
          rules:
            - entity: media_player.tele_du_salon_2
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-tv media-player-${entity.state}'

            - entity: media_player.tv_chambre_2
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-tv media-player-${entity.state}'

            - entities:
                - binary_sensor.sensor_salon_v_2_mouvement
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'motion motion-${entity.state}'

            - entities:
                - light.buanderie
                - light.bureau
                - light.canape
                - light.couloir_01
                - light.couloir_02
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action: false
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
```

I assume you haven't shown your entire CSS as there are multiple missing classes....

**Reply by HugoNaza** [reply]
Thank you for your assistance so far. 
I have find a solution to correct the major problem. With the current code, the SVG loads correctly and interactions work as intended. However, I'm still encountering persistent issues with Floorplan in Home Assistant:

**- Device Status Integration in YAML:** I'm struggling to display the status (on/off) of my lights or TV using a class to trigger the "lighten" mode in CSS. It appears the YAML file isn't transmitting the ".light-on" status change needed to activate the corresponding CSS.

**- Console Errors:** There are ongoing errors in the development console, and I'm uncertain of their impact or how to resolve them.

Here's the current YAML code where I've added a group to fix a previous error, enabling correct entity detection. However, the integration of device states is still problematic:

**_YAML :_** 

```
- type: 'custom:floorplan-card'
        entity: fp-card
        image: "/local/floorplan/floorplan_optimised.svg"
        stylesheet: '/local/floorplan/floorplan.css'
        style: >
          ha-card {
            max-width: 150vh;
            margin: 0 auto;
            background: none;
            box-shadow: none;
          }
        groups:
          - entitiy: sensor.chambre_temp
            state_action:
              action: call-service
              service: textTemperatureChambre
              service_data:
                element: sample.multilinegroup_text
                shift_y_axis: 1.5em
                text: |

          - name: LightToggles
            entities:
              - media_player.salon_remote_tv
              - media_player.chambre_remote_tv
              - media_player.salon_enceinte
              - media_player.chambre_enceinte
              - media_player.douche_enceinte
              - cover.rideaux_salon_rideau
              - cover.rideau_buanderie_rideau
              - cover.rideau_chambre_rideau
              - light.salon_global
              - light.chambre_global
              - light.cuisine_global
              - light.salle_de_bain_global
              - light.buanderie
              - light.bureau
              - light.canape
              - light.porte
              - light.couloir
              - light.cuisine
              - light.douche
              - light.escalier_mur
              - light.escalier_top
              - light.frigo
              - light.lit
              - light.miroir
              - light.mur_chambre
              - light.toilette
              - light.tv_back
              - light.tv_top
            tap_action:
              action: 'toggle'
            hold_action:
              action: more-info

        rules:
          - entity: media_player.salon_remote_tv
            element: media_player_overlay.salon_remote_tv
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data:
                class: 'media-player-${entity.state}'
          - entity: media_player.chambre_remote_tv
            element: media_player_overlay.chambre_remote_tv
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data:
                class: 'media-player-${entity.state}'
          - entity: light.escalier_mur
            element: light_overlay.escalier_mur
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data:
                class: '${entity.state === "on" ? "light-on" : "light-off"}'
```

**_CSS :_** 

```
svg, svg * {
  pointer-events: all !important;
  cursor: auto !important;
}

svg path {
  fill: inherit;
  stroke: inherit;
  stroke-width: inherit;
}


#areas {
  fill: none;
}

#light-overlays image {
  display: none;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;
}

#light-overlays image.light-on {
  display: block;
}


#areas .light-on {
  stroke-width: 6px;
  stroke-opacity: 1;
  stroke: #a58ee1;
}

g path:active, g use:active, .light-on:active, g#entities > g:active path:not(.touch-area) {
	stroke: #9ed8ff99 !important;
	stroke-width: 4px;
	stroke-opacity: 0.7;
}

g#entites path, g#entites ellipse {
	stroke: var(--paper-item-icon-color);
	stroke-width: 1px;
	stroke-opacity: 1;
	fill: none;
}
g#entites .light-on {
	stroke: var(--paper-item-icon-active-color);
}

```

**_Screen errors :_** 

<img width="498" alt="Error" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/abc37ff1-9a49-425b-ae8b-ad4c63777266">




I appreciate any help you can provide to resolve these issues.

**Comment by OzGav** [comment]
I don’t see any light-off class that can be applied

**Reply by HugoNaza** [reply]
Oh yes effectively, before the code YAML was this one : 

```
state_action:
              action: call-service
              service: floorplan.class_set
              service_data: 'light-${entity.state}'

```

and it dosn't work with this configuration also ? 

_YAML actual part :_ 

```
- entity: light.escalier_mur
            element: light_overlay.escalier_mur
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data:
                class: '${entity.state === "on" ? "light-on" : "light-off"}'
```

But if I replace the class by : 'light-${entity.state}' like in the first YAML I have show you, it dosent work also.

_CSS actual part :_ 

```
#light-overlays image {
  display: none;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;
}

#light-overlays image.light-on {
  display: block;
}
```

Is it the good methode to blend in lighten mode the different PNG ? Or it's an other solution to do that ?

**Reply by OzGav** [reply]
Look at your css though. You have some classes called light-on but there are no classes called light-off. So I expect all your lights will probably show when they turn on but nothing will happen when they turn off?

here is a section of my css 

```
/* lights and lamps */

.light-off, .light-off * {
  fill: #E0E0EB !important;
}

.light-on, .light-on * {
  fill: #FFFF99 !important;
}

.lamp-off, .lamp-off *  {
  opacity: 0.5 !important;
  stroke-opacity: 0 !important;
}

.lamp-on, .lamp-on * {
  stroke: #03A9F4 !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
}
```

**Reply by HugoNaza** [reply]
Effectively this configuration was false in all the case, but I have try different varient, but in all the case it dosent work. I can show you which configuration doesn't work. 

But it's seem come from the YAML when he change the ID of my light into the ID of my entity to define my png. When I inspect my console, he show only the CSS with the display none and without the "light-on" (or even off because he don't indicate at all the state of the light). 

Have you an idea where it can come from ? What is the good way to create that ? 

**1. First iteration :** 

YAML :

```
  - type: 'custom:floorplan-card'
        entity: fp-card
        image: "/local/floorplan/floorplan_optimised.svg"
        stylesheet: '/local/floorplan/floorplan.css'
        style: >
          ha-card {
            max-width: 150vh;
            margin: 0 auto;
            background: none;
            box-shadow: none;
          }

groups:
          - entitiy: sensor.chambre_temp
            state_action:
              action: call-service
              service: textTemperatureChambre
              service_data:
                element: sample.multilinegroup_text
                shift_y_axis: 1.5em
                text: |

etc.

rules: 

          - entity: light.escalier_mur
            element: light_overlay.escalier_mur
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data:
                class: '${entity.state === "on" ? "light-on" : "light-off"}'
```

CSS : 

```
#light-overlays image.light-off {
  display: none;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;
}

#light-overlays image.light-on {
  display: block;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;
}
```

2. Iterations


YAML : 

```

same

groups:
          - entitiy: sensor.chambre_temp
            state_action:
              action: call-service
              service: textTemperatureChambre
              service_data:
                element: sample.multilinegroup_text
                shift_y_axis: 1.5em
                text: |

etc.

rules: 


service_data_template:
  class: '${entity.state === "on" ? "light-on" : "light-off"}'

```

CSS : 


```
#light\\.escalier_mur.light-on {
  display: block !important;
  mix-blend-mode: lighten !important;
}
#light\\.escalier_mur.light-off {
  display: none; 
}
```




**3.  iteration :** _But don't work at all_

```
config:
          image: '/local/floorplan/floorplan_optimised.svg'
          stylesheet: '/local/floorplan/floorplan.css'
          rules:

            - entities:
                - media_player.salon_remote_tv
                - media_player.chambre_remote_tv
                - light.buanderie
                - light.bureau
                - light.canape
                - light.porte
                - light.couloir
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action: false
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
```

CSS : 

```
#light-overlays image {
  display: none;
  mix-blend-mode: lighten;
  animation: 0.75s fade-in linear forwards;
}

#light-overlays image.light-on {
  display: block;
}
```


Thanks a lot for your time

**Reply by OzGav** [reply]
I think you need to simplify things. Use the yaml from your iteration three above but use this as your css


```
.light-off, .light-off *  {
  opacity: 0 !important;
  stroke-opacity: 0 !important;
}

.light-on, .light-on * {
  stroke: #03A9F4 !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
}
```

**Reply by HugoNaza** [reply]
I'm ok to simplify my code to fixe my problem, but your proposition doesn't work. 
Like I told you, the YAML don't seem indicate the statut of my different light. 

I have try your proposition, but it doesn't work and don't answer to my needs, because if my png are not in lighten mode it doesn't work at all. 

Why when I want create a YAML with this format he told me you need to define an entity ? 


```

- type: 'custom:floorplan-card'
        style: >
          ha-card {
              max-width: 150vh;
              margin: 0 auto;
              background: none;
              box-shadow: none;
          }
        config:
          image: '/local/floorplan/floorplan_optimised.svg'
          stylesheet: '/local/floorplan/floorplan.css'
          rules:
          - entities:
                - media_player.salon_remote_tv
                - media_player.chambre_remote_tv
                - light.buanderie
                - light.bureau
                - light.canape
                - light.porte
                - light.couloir
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action: false
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'

            - entities:
                - media_player.salon_remote_tv
                - media_player.chambre_remote_tv
                - media_player.salon_enceinte
                - media_player.chambre_enceinte
                - media_player.douche_enceinte
                - light.salon_global
                - light.chambre_global
                - light.cuisine_global
                - light.salle_de_bain_global
                - light.buanderie
                - light.bureau
                - light.canape
                - light.porte
                - light.couloir
                - light.cuisine
                - light.douche
                - light.escalier_mur
                - light.escalier_top
                - light.frigo
                - light.lit
                - light.miroir
                - light.mur_chambre
                - light.toilette
                - light.tv_back
                - light.tv_top
              tap_action:
                action: 'toggle'
              double_tap_action:
                action: more-info
```

**Comment by exetico** [comment]
As a answer to [387#discussioncomment-7852869](https://github.com/ExperienceLovelace/ha-floorplan/discussions/387#discussioncomment-7852869):
You're trying to set light-escalier_top as a example, right? I see no rules for `.light.escalier_top` in your CSS rules. The "set class" will require a class selector (not a id selector). As I'm jumping into this, maybe I'v missed something. However, I dont see how the two things should be alligned.

<img width="509" alt="image" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/3d910d70-1169-4ed1-a58b-c27f7729aad6">

In general, I also recommend all to not use dots as part of their SVG ID's. That's pointed out in my videoes, and in our documentation. With that said, some users report it works, anyways...

With the content you provided, I cant see any connections between your code.

For a chance to help without spending hours to guess what's going on, I'll always recommend provided a stipped down version of your work, where you share a sample SVG, CSS and YAML pack with **one entity** or maybe **two entities**, so it's possible to taggle your issue, without having the noise from all the other things. If other assets are required, share them too.

And oh, thank you for using ha-floorplan 😄 . Let's get this solved 👌 !

**Reply by HugoNaza** [reply]
Hello, thank you for your response.

My English might not be perfect, so I might have missed the part about avoiding dots in SVG IDs. I've made the changes, and if I understand correctly, we can handle this with the 'entity' and 'element' attributes, right? I've applied all your recommendations and have tried to unify my code to create a more solid foundation, but unfortunately, it still doesn't work as expected. Even the toggle function isn't working anymore.

Here's my simplified SVG along with the YAML and CSS files. I've included two lights and one TV (and one speaker, but without a PNG that changes based on the status). I might have made some mistakes since I'm a beginner, and I probably started with a complex configuration which didn't really help.

**_Summary of current issues:_**

- The status of the lights doesn't seem to be transmitted to the CSS to determine whether the PNG is displayed or not.

- The toggle to open the more-info dialogue isn't working anymore. I'm not sure why; everything worked perfectly before I simplified the files and removed the dots.

Fichier SVG : 
![floorplan_optimised](https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/7ed275d7-af16-442f-b0e7-8c71a62ebd8f)


**YAML :**

```
views:
  - title: 'Floorplan'
    path: 'floorplan'
    icon: 'mdi:floor-plan'
    theme: 'lovelace-blue-blur'
    panel: true
    cards:
    - type: horizontal-stack
      cards:
      - type: 'custom:floorplan-card'
        entity: fp-card
        image: "/local/floorplan/floorplan_optimised.svg"
        stylesheet: '/local/floorplan/floorplan.css'
        style: >
          ha-card {
            max-width: 150vh;
            margin: 0 auto;
            background: none;
            box-shadow: none;
          }
        groups:
          - name: LightToggles
            entities:
              - media_player.salon_remote_tv
              - media_player.salon_enceinte
              - light.salon_global
              - light.tv_back
              - light.tv_top
            tap_action:
              action: 'toggle'
            hold_action:
              action: more-info

          - name: TV
            entity: media_player.salon_Remote_tv
            element: media_player-salon_Remote_tv
            tap_action: more-info
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data: '${entity.state === "on" ? "media-on" : "media-off"}'

          - name: tv_top
            entity: light.tv_top
            element: light-tv_top
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data_template:
                class: '${entity.state === "on" ? "light-on" : "light-off"}'

          - name: tv_back
            entity: light.tv_back
            element: light-tv_back
            state_action:
              action: call-service
              service: floorplan.class_set
              service_data_template:
                class: '${entity.state === "on" ? "light-on" : "light-off"}'
```


**CSS :** 


```
#light-tv_top.light-on {
  display: block !important;
  mix-blend-mode: lighten !important;
}
#light-tv_top.light-off {
  display: none;
}

#light-tv_back.light-on {
  display: block !important;
  mix-blend-mode: lighten !important;
}
#light-tv_back.light-off {
  display: none;
}

#media_player-salon_remote_tv.media-on {
  display: block !important;
  mix-blend-mode: lighten !important;
}
#media_player-salon_remote_tv.media-off {
  display: none;
}
```


**CONSOLE :** 

<img width="712" alt="Error" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/1e52ce88-693f-4278-be5d-c28ab3138cd9">
<img width="715" alt="Error2" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/f3ca8da9-f147-4882-b2de-560a72e5b153">


Thanks, guys, for your help. I hope I've been clear enough in my explanations.

**Reply by OzGav** [reply]
We will get there but you have obvious errors in your yaml such as not having a rules section and it still isn’t simple enough and I don’t think you are understanding how the YAML, SVG and CSS all work together. Have a look at this post which summarises it https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/416?u=ozgav

As Tobias also said you need to simplify your YAML. Please use what I posted here https://github.com/ExperienceLovelace/ha-floorplan/discussions/387#discussioncomment-7818461

Then your CSS has to have a class which is IDENTICALLY NAMED to the class which you are setting in your YAML. Please look at the examples on GitHub. Do not look at the BitBorn example as it is too complicated. If you look at my example here https://github.com/ExperienceLovelace/ha-floorplan/discussions/387#discussioncomment-7836842 you will see `.light-on `and that is the same as what will be applied by this line in the yaml `service_data: 'light-${entity.state}'` The entity state will resolve and either `light-on` or `light-off` will be applied.

**Reply by OzGav** [reply]
OK I have loaded up your files. Firstly in your SVG these are the only entities listed
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/19848947/49bb0387-f1ad-471c-abf8-30fb7713d33b)

but your YAML has way more entities listed so to align these two this is the YAML you need:

```
views:
  - path: testfloorplan
    title: Test Floorplan 
    panel: true
    cards:  
      - type: 'custom:floorplan-card'
        config:
          log_level: info
          image:
            location: /local/floorplan/test/test.svg
            cache: false
          stylesheet:
            location: /local/floorplan/floorplan.css
            cache: true
          defaults:
            hover_action:
              action: hover-info
            tap_action:
              action: more-info
            hold_action: more-info
          rules:
            - entity: media_player.salon_enceinte
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-${entity.state}'

            - entity: media_player.salon_remote_tv
              tap_action: more-info
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'media-player-${entity.state}'

            - entities:
                - cover.rideaux_salon_rideau
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'motion-${entity.state}'

            - entities:
                - light.tv_back
                - light.tv_top
                - light.salon_global
              tap_action: toggle
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
```
 
and this CSS:

```
/* SVG shapes */

svg, svg * {
  pointer-events: all !important;
}

/* lights and lamps */

.light-off, .light-off * {
  fill: #E0E0EB !important;
}

.light-on, .light-on * {
  fill: #FFFF99 !important;
```
} 

Now when you click on the oval shape (which is `light.tv_top`) you should find the fill colour changes and your light should turn on and off. `light.tv_back` should also work and I think` light.salon_global `should also work. The media players wont do anything other than pop up the more info dialog as there is no CSS class in the file yet. The cover won't do anything at all as there is no CSS class yet and there is nothing specified for the `tap_action`.

I hope this will point you in the right direction.

**Reply by HugoNaza** [reply]
Thanks a lot for your answer and your time. 

Yes, for the test I have remove the majority of my light to focus on just some element and be more simple. I have let only two light, one spot and one diffuser, one of my TV, the global setting of the living room, one speaker and my curtain to have all the sort of entity I need. :) 

I have try the code you have send to me (and put in the same folder than in your exemple), and with this layout with rules, he say to me : "You need define an entity" and show to me the entire YAML code. I put your the error and the console at the end. 

With all my test, I have success to load correctly my plan only with the configuration "group" and not "rule" I don't know why. 
I don't know if he help, but if I had the location of the SVG and CSS before "config", I don't have this error, he can charge the SVG in a first time, but after the error : Cannot read properties of undefined (reading 'ForEach')

```
views:
  - path: testfloorplan
    title: Test Floorplan
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        entity: floorplan-card
        image: "/local/floorplan/test/floorplan_optimised.svg"
        stylesheet: '/local/floorplan/floorplan.css'
        config:
```

![Uploading Error4.PNG…]()

**Reply by OzGav** [reply]
Please try and upload the error message again as it hasn’t attached properly.

You can’t just put the various keys wherever you like. There are strict requirements https://experiencelovelace.github.io/ha-floorplan/docs/usage/

**Reply by HugoNaza** [reply]
I have follow the information here, but I dont understand when I use rules, I have always this error even if I follow the tutorials, documentations and even your recommendation. I don't understand where it come from. :/ 

Effectivly it dosen't load sorry. 
Do you need other error ? If yes, wich one can be useful ? 


My error is : <img width="1273" alt="Error4" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/4c89f026-e955-41ef-b1b5-5d88f71dcd85">

**Reply by OzGav** [reply]
This is working perfectly fine for me. How are you creating this view? Is it a completely empty dashboard that you have added this to?

**Reply by HugoNaza** [reply]
Oh ok, it's weird... I do certainly a dumb mistake!
Yes I do that in YAML file totally empty and link in the configuration.yaml. This file is totally empty and I put the code starting by :

```
views:
  - path: testfloorplan
    title: Test Floorplan
    panel: true
    cards:
```

With nothing before, and nothing after the code you give me. Is it the good way?!


I have also install a new configuration in an other SD card. I have connect my account for my light, my tv's and other. Download HACS then Ha-Floorplan then manually add Floorplan-card and I have the same issues.
I suppose he come from the code himself and must be simple or if it's not the case I'm a little bit lost.

I suppose I understand correctly the code and the logic, but I must take a little mistake :/ If you have some ideas, I'm interested! 😊

**Reply by OzGav** [reply]
What do you mean by this:

> and link in the configuration.yaml

**Reply by OzGav** [reply]
I'm suspicious of the error you see "the name floorplan card has already been used in this registry"

How have you added the floorplan.js resource?

**Reply by HugoNaza** [reply]
When I say "link in the configuration.yaml" I mean I added the .js resource to the configuration. I have add my configuration like that : 

```
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  resources: # This should not be under dashboards
    - url: /local/cards/floorplan-card/floorplan-card.js
      type: module
    - url: /local/community/ha-floorplan/floorplan.js
      type: module
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module
    - url: /local/cards/card-mod/card-mod.js
      type: module
    - url: /local/cards/autoentities/autoentities.js
      type: module
    - url: /local/cards/button-card/button-card.js
      type: module
  dashboards:
    test-dashboard:
      mode: yaml
      filename: test.yaml
      title: Test Dashboard
      icon: mdi:test-tube
      show_in_sidebar: true

```

For the error "the name floorplan card has already been used in this registry" I have any idea where he come from, it's very weird and maybe it's the reason of my bug, but why it happen also in new installation ?! 
And I can't bring more information in the console or the logs about that, I find any things. 

**I put you the screens of my ftp to show you how I have add the plugin :**
<img width="166" alt="Error2" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/1050d10b-0218-46a6-ae09-9c95afabe180">

**Also how I have insert my code in the YAML file. :** 
<img width="1107" alt="Error3" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/0ba4a832-c945-432c-b22b-786135a4f54f">


Thanks, I hope we can find an error I did haha
