### DISCUSSION TITLE
Seeking Guidance: Integrating Dynamic Light Colors onto PNGs in Home Assistant Floorplan

### DISCUSSION THREAD

**Discussion by HugoNaza** [ExperienceLovelace/ha-floorplan#390] [Q&A]
Hello,

First of all, thank you for the help you provided me last time.

However, I am now facing new challenges with my project and I could use your assistance to shed some light on them. My plan is working correctly: the YAML and CSS are well synchronized, and the lights turn on according to the state of my lamps. Nevertheless, I am stuck on a specific feature: transforming the color of each lamp directly onto the PNG images of my Floorplan.

After attempting to integrate information from the documentation, I found[ this tutorial](https://community.home-assistant.io/t/floorplan-ui-with-color-synced-lights/169417) which seems to be the most comprehensive on this subject. And I tried to add:

```
AFTER THAT
            tap_action: false
                state_action:
                  - action: call-service
                    service: floorplan.class_set
                    service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'

  - action: call-service
    service: floorplan.style_set
    service_data:
      style: >
        const hueRotation = entity.attributes.hs_color ? entity.attributes.hs_color[0] : 0;
        const opacity = entity.state === 'on' ? (entity.attributes.brightness / 255) : 0;
        return `filter: hue-rotate(${hueRotation}deg); mix-blend-mode: lighten; opacity: ${opacity};`;
```

But this does not seem to work with rules, it seems to only work for individual PNGs with the element property, and so I don't see how to do it in my case. Is there another way to achieve this with the code I have created?

I put the errors of this code at the end of my post.

YAML : 

```
views:
  - path: floorplan
    title: Floorplan
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: 'custom:floorplan-card'
          style: >
            ha-card {
                max-width: 85vh;
                margin: 0 auto;
                background: none;
                box-shadow: none;
            }
          config:
            image:
              location: /local/floorplan/floorplan_optimised.svg
              cache: false
            stylesheet:
              location: /local/floorplan/floorplan.css
              cache: false
            defaults:
              hover_action:
                action: hover-info
              tap_action:
                action: more-info
              hold_action: more-info
            rules:

              - entities:
                  - entity: media_player.salon_remote_tv
                    element: media_player_overlay-salon_remote_tv
                tap_action: false
                state_action:
                  - action: call-service
                    service: floorplan.class_set
                    service_data: '${(entity.state === "on") ? "media-on" : "media-off"}'

              - entities:
                  - cover.rideaux_salon_rideau
                  - cover.rideau_chambre_rideau
                  - cover.rideau_buanderie_rideau
                tap_action:
                  action: more-info
                hold_action:
                  action: "toggle"
                state_action:
                  action: call-service
                  service: floorplan.class_set
                  service_data: "motion-${entity.state}"

              - entities:
                  - light.salon_global
                tap_action:
                  action: more-info
                hold_action:
                  action: "toggle"
                state_action:
                  action: call-service
                  service: floorplan.class_set
                  service_data: "motion-${entity.state}"
                  
              - entities:
                  - entity: light.bureau
                    element: light_overlay-bureau
                  - entity: light.canape
                    element: light_overlay-canape
                  - entity: light.escalier_mur
                    element: light_overlay-escalier_mur
                  - entity: light.escalier_top
                    element: light_overlay-escalier_top
                  - entity: light.tv_back
                    element: light_overlay-tv_back
                  - entity: light.tv_top
                    element: light_overlay-tv_top
                tap_action: false
                state_action:
                  - action: call-service
                    service: floorplan.class_set
                    service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
                    
              - entities:
                  - light.bureau
                  - light.canape
                  - light.escalier_mur
                  - light.escalier_top
                  - light.tv_back
                  - light.tv_top
                tap_action: toggle
                state_action:
                  action: call-service
                  service: floorplan.class_set
                  service_data: 'light-${entity.state}'
```
                  

CSS : 

```
/* Cibler les images "allumées" */
image[id*="light_overlay-"].light-on {
  opacity: 1 !important;
  mix-blend-mode: lighten; /* Ajoutez ceci pour le mode lighten */
}

/* Cibler les images "éteintes" */
image[id*="light_overlay-"].light-off{
  opacity: 0 !important;
}

/* Styles par défaut pour toutes les images de lampes */
image[id*="light_overlay-"] {
  opacity: 0 !important; /* Opacité par défaut pour les lampes éteintes */
  transition: opacity .25s;
  -moz-transition: opacity .25s;
  -webkit-transition: opacity .25s;
  mix-blend-mode: lighten; /* Ajoutez ceci pour le mode lighten */
}

/* Cibler les images "allumées" */
image[id*="media_player_overlay-"].media-on{
  opacity: 1 !important;
  mix-blend-mode: lighten; /* Ajoutez ceci pour le mode lighten */
}

/* Cibler les images "éteintes" */
image[id*="media_player_overlay-"].media-off {
  opacity: 0 !important;
}

/* Styles par défaut pour toutes les images de lampes */
image[id*="media_player_overlay-"]{
  opacity: 0 !important; /* Opacité par défaut pour les lampes éteintes */
  transition: opacity .25s;
  -moz-transition: opacity .25s;
  -webkit-transition: opacity .25s;
  mix-blend-mode: lighten; /* Ajoutez ceci pour le mode lighten */
}
```

Errors : 

<img width="581" alt="Error2" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/98323334/9752d525-bf18-4ffe-bdc1-2b68d6170964">

Thank you very much for your help, and I hope I have not misunderstood again or made a silly mistake. Thank you in advance.
