### DISCUSSION TITLE
SVG layer/position in floorplan card

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#406] [Q&A] [answered]
## Hello again! Let me first thank everyone who helps me solve the conundrum!

I tried to solve the matter with the layers or the position of the SVG elements in the floorplan card via the css file and it doesn't work at all, rather, I can't do it with my current knowledge!!!

**The image below shows my problem:**

**where you can see, (the lines/edges of the rooms overlap strangely as if each room has its own leyer)**

![Označitev prostorov on-off](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/0b2332fe-0c20-4a8b-857a-f659419184ba)

**ID="areas" displays information from an SVG file about (stroke/lines) settings**
**class="entitystate-off" I would like to appear above ID="areas"**
**class="entitystate-on" I would like to appear above ID="areas" and class="entitystate-off"** 

![Inkscape-Layer position_DevTools](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/815abdbf-09a3-4ce3-aab6-9ea932358e28)

```In the Area folder in Inkscape, I have the edges of individual rooms, but they do not have the same leyer. The last has the lowest leyer```

![Inkscape-Areas layer position](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/9d3af973-8e5c-451c-b337-8f90d611e304)

```Should I choose one of these options:```

![Inkscape-Layer position](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a5096eb4-ffc9-4f19-8450-a81118302b96)

**Comment by exetico** [comment]
Your formatting of the text is very confusing. I'm not really sure what you're asking about, even after reading it a few times.

Could you describe it again? Maybe telling what the problem is, and what you expect, so we doesn't end up with a xy-problem.

**Reply by Trzinka** [reply]
Hi!

Sorry my native language is not english so (google translate)!!!

The problem is that with css settings:
```yaml
position: relative !important;
z-index: 10 !important;
```
with this i can't set layers for **element: areas** (which in html format works!!)

```yaml
#areas {
  position: relative !important;
  stroke-width: 5px !important;
  stroke: rgb(31, 184, 255) !important;
  stroke-opacity: 0.3 !important;	
  z-index: 10 !important;
}
```

`It should be layer 10 or above the background image`

```yaml
g .entitystate-off {
  position: relative !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
  stroke: green !important;
  stroke-width: 5px !important;
  z-index: 500 !important;
}
```

`It should be layer higher than 10 or above the areas`

```yaml
g .entitystate-on {
  position: relative !important;
  opacity: 1 !important;
  stroke-opacity: 1 !important;
  stroke: #FF1818 !important;
  stroke-width: 3px !important;
  stroke-dasharray: 80 !important;
  filter: blur(2px) !important;
  -webkit-filter: blur(2px) !important;
  animation: dash 15s infinite ease-in-out !important;
  z-index: 1000 !important;
}

@keyframes dash {
  to {
    stroke-dashoffset: 1000;
  }
}
```

`It should be layer higher than of all the above`

### All these elements are from svg file!!

**Reply by Trzinka** [reply]
## I'm currently having trouble displaying the 
`("stroke" The line around the rooms that should currently show blue where there is "no class", green where "cass: entitystate-off" and red with animation where "class is: entitystate-on")`
**layer based on the different class or ID**

**Comment by Trzinka** [comment, marked as answer]
# I did some thinking and came up with a solution.

`In the base background image, I added green color to the edges of the rooms so that it now looks like this:`
![background](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1892a42d-0cb5-49cd-baf5-346e70a6edcf)

`Then I cut the backgrounds of the rooms without walls (example):`
![sp](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/9dfa3ace-20d6-4fd1-9cf4-9d61dd4b9e0c)

`control via CSS`

```yaml
svg path {
  fill: inherit;
  stroke: inherit;
  stroke-width: 0px !important;
}

#areas {
  fill: none;
  stroke: none;
}

#areas .switch-on {
  stroke: red !important;
  stroke-width: 35px !important;
  stroke-opacity: 1;
  z-index: 600;
}
```

`In the floor plan card, I have a code for each room (example):`

```yaml
- entities:
    - switch.sw_st
    - switch.sw_vh
    - switch.sw_mi
    - switch.sw_gr
    - switch.sw_ho
    - switch.sw_sp
    - switch.sw_na
    - switch.sw_di
    - switch.sw_je
    - switch.sw_sh
    - switch.sw_ku
    - switch.sw_ko
  tap_action:
    action: call-service
    service: homeassistant.toggle
  state_action:
    action: call-service
    service: floorplan.class_set
    service_data: switch-${entity.state}
```

`The result is a nice overlapping of the edges of the rooms (example):`

![FP-Switch on](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e9ae9a85-e525-4659-9042-665497bf8775)

## I exaggerated the size of the images and because of this the page is very slow to load. (I'll scale down the images and SVG) and it should be perfect.
