### DISCUSSION TITLE
Request help with Overlays

### DISCUSSION THREAD

**Discussion by tsx-5** [ExperienceLovelace/ha-floorplan#407] [Q&A] [answered]
Hi,

Continuing my journey to a working 3D layout...  I've gotten my Basement layout (drawn with SH3D) into Inkscape and have added overlays (see svg file below).  I can hide/unhide different areas while I'm in Inkscape.  I followed this tutorial ( https://www.youtube.com/watch?v=f_3KAPc53hQ&t=614s ) to get the floorplan to show up in HA.  However, the overlays are not working consistently in HA.  Sometimes they show up when I inspect the code, but using the ID's prior to me changing them.  Other times they don't show up at all.  The only other hint I have is that the symbol next to the ID is different on mine than in the video

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/106412847/35a8e883-59f2-4e60-9eec-2edf586841e6)

Anyone have any ideas?

![Basement-ink-floorplan](https://github.com/ExperienceLovelace/ha-floorplan/assets/106412847/f38925c8-117b-4e32-a187-b9d4d09d00cf)

/homeassistant/www/floorplan/home_nasa/Basement-ink-floorplan.css
/* All good */
.entitystate-on(
    opacity: 0;
)

.entitystate-off(
    opacity: 0.7;
    fill: rgb(49,45,45);
)

Edit YAML code:
title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_nasa/Basement-ink-floorplan.svg
          rules:
            - element: Basement.open.light
              entity: light.scene_capable_dimmer
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
          stylesheet: /local/floorplan/home_nasa/Basement-ink-floorplan.css
        full_height: true
        type: custom:floorplan-card

**Comment by tsx-5** [comment]
Ok,

Seems part of the problem was the cache needing to be cleared.  After a few tries, I've gotten the default actions to work - but the element doesn't toggle the area opacity as the video illustrates.

**Reply by OzGav** [reply]
For a start can you properly format your yaml by using the <> button

**Comment by tsx-5** [comment]
Thanks for pointing that out!  A bit of trying it out and now I can post updated code block that inserts way better.

```
title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Google Dark Theme
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /local/floorplan/home_nasa/Basement-ink-floorplan.svg
          rules:
            - element: Basement.open.light
              entity: light.scene_capable_dimmer
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: Basement.patio.light
              entity: light.scene_capable_dimmer_2
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: Basement.gaming.light
              entity: light.gaming
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: Basement.laundry.light
              entity: light.laundry_room_fix_hs2000
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
            - element: Basement.workout.light
              entity: light.micro_smart_energy_illuminator_g2_2
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              double_tap_action:
                action: call-service
                service: homeassistant.toggle
          stylesheet: /local/floorplan/home_nasa/Basement-ink-floorplan.css
        full_height: true
        type: custom:floorplan-card
```

**Reply by OzGav** [reply]
I think @exetico made mention in the videos that . In element names is problematic so I would remove those for a start. 
Then I don’t use double tap action so change one of those to tap_action for testing (if the lights actually toggle but it is just the opacity that doesn’t change then disregard this)
Lastly, please show your CSS file (formatted)

**Reply by tsx-5** [reply]
```
/* All good */
.entitystate-off(
    opacity: 0;
)

.entitystate-on(
    opacity: 0.7;
    fill: rgb(38,45,45);
)
```
I'll rename the elements, as you suggest - and report back (likely after work)

**Comment by Trzinka** [comment]
**Hello!**

_I don't see that you using this_

```yaml
svg, svg * {
  position: relative !important;
  margin: 0px !important;
  max-height: 100vh !important;
  width: auto  !important;
  padding-top: 150px !important;
  padding-bottom: 150px !important;
  z-index: 0 !important;
}

svg path {
  fill: none;
  stroke: inherit;
}

#background {
  visibility: visible !important;
  opacity: 1 !important;
	mix-blend-mode: lighten !important;
}

#switch-coverings {
  visibility: hidden;
  transition: visibility 0s 0.5s, opacity 0.5s linear;
}

.entitystate-on {
  visibility: visible !important;
  opacity: 1 !important;
  transition: opacity 0.5s linear !important;
  animation: fade-in 0.75s linear forwards !important;
}

@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
 }
```
Use
### mix-blend-mode: lighten !important;
in your default background ID name:
![Background+DevTools](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/b77d6061-e71b-4483-ba64-9057f7219d26)
