### DISCUSSION TITLE
Synchronization with binary sensors

### DISCUSSION THREAD

**Discussion by Jonny-T-cyber** [ExperienceLovelace/ha-floorplan#41] [Q&A] [answered]
Hi all!
I'm simulating LEDs controlled by binary sensors.
As a test I visually display the status of the sensors on Lovelace.
LEDs are turned on/off very late compared to binary sensors on Lovelace and sometimes they do not turn on/off until I update the page (F5)
I do the simulation like this:

```
- entity: binary_sensor.my_led
  state_action:
    service: floorplan.class_set
    service_data:
      class: '${(entity.state === "on") ? "led_on" : "led_off"}'
```

CSS:

```
.led_on {
  fill: #FF8000 !important;
  fill-opacity: 1 !important;
}

.led_off {
  fill: #000000 !important;
  fill-opacity: 1 !important;
}
```
Is there any way to improve synchronization with binary sensors?
Thanks
