### DISCUSSION TITLE
My floor plan example:

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#411] [Show and tell]
My native language is slovenian!

# Updated 05.10.2024 - Contains:
> - Calendar and cameras are addon card, the rest is SVG (custom card=grid-layout)
> - Floor plan card - Dimming relative to external brightness
> - The colored edge (stroke) of the room where the light is on
> - Display the image of the room (illuminated) when the light is on
> - Display of the temperature and humidity in the rooms
> - Colored edge of device when consuming electricity
> - Colored edge of the printer when printing
> - Colored edge of the computer when it is on
> - Colored edge (blur) when the room heating is on
> - Full screen display on tablet/phone
> - Show the camera when it detects motion (for now, until I solve the issue to add more precise motion + object detection)
> - Display person (home/away) + battery status
> - Image display + borders (stroke) of open doors/windows
> - Partial display of weather as SVG elements
> - Navigate on hold to display other Lovelace cards

**Here is the zip file of the files I currently use.**
# [20250103.zip][fp.zip](https://github.com/user-attachments/files/18306426/fp.zip)
`The file fp-delovni.svg is the file I am editing. fp.svg file is optimize`

`view using file 20240830.zip:`
![20240630-FP](https://github.com/user-attachments/assets/9e8608ee-cf23-44d3-9032-ea4f84aa127b)

`Current view:`
On PC:
![20240413-HA_FP-PC](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/26c19f69-d1d9-44a2-8ecd-11442b1a57e6)

On tablet:
![20240413-HA_FP-Tablet](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/0e56b6b9-ac47-4632-b158-fc39b067e452)

On phone:
![20240413-HA_FP-Mobile](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/cf4de0d1-51ea-4b07-9a4c-6bccbba7b5b2)

Here is the zip file of the files I used which contains the other add-on cards in addition to the floor plan card. [20240216.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/14313293/20240216.zip)
`fp.svg file is optimize`

`view using file 20240216.zip:`

## My PNG files! In Inkscape I use the link to the files (they are not included in the SVG file)

# The images of the view below will be changed during my upgrade, but the essence will remain! The zip file will contain the latest settings!!

## Thanks to everyone from the group who helped me!!!!

**Comment by Trzinka** [comment]
# Inkscape tricks & tips

`How to XML editor`

![InkScape-XML](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1cf46122-3cd0-4c71-a068-95c8fc3c8cef)


## Why XML Editor

`Setting the size of the working area`

![InkScape-XML-Editor](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/72c6f72c-5b8e-4a1b-971e-9bc6fa68aee0)


`Setting the size and position of the image/objects`

![InkScape-XML-Editor1](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/9fcc7b42-f8f6-42ea-ac59-1e763755dd4b)


`Order of elements/objects in SVG`
(read: https://www.w3.org/Graphics/SVG/WG/wiki/Proposals/z-index)

![Luči-slike](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/542cec59-2146-4955-b264-95160f2c2d20)

```the lowest/first element/object is the lowest```

`Default setting for link to images which is broken/wrong`

![Switch](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e8154174-ff5e-4e4b-8af5-9451f36efcbd)

`It is necessary to add a link to the files in the HA folder`

![Inkscape-XML editor-HA link set up](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/feea8a13-068c-4b3d-ac5b-f5e92203fca8)


# Save the work file as normal. 

`To use in HA, follow the instructions:`

![Inkscape-save a copy](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/454eff33-b5bf-4ff3-965c-b06ce515f885)

## select a different file from the one you are working in !!!!

![Inkscape-save optimised](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e29916fe-c36a-4b82-afef-3c7bb1e47088)

**Comment by Trzinka** [comment]
# Changing the background image based on the time of day, which I don't use!!!
## If anyone doesn't like the blackout overlay with opacity???

`morning`
![jutro](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/b128aba0-7d52-43ab-b0e0-942930c9c6ae)

`until noon`
![dopoldan](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/2eef8076-2024-4cc9-bad5-d7ce57ad7304)

`noon`
![poldne](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/2d5e48d8-bb90-4f2e-83aa-8c1bf4f3f184)

`after noon`
![popoldan](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/ad54decb-85d3-4f4a-b865-490f6e87b6a2)

`evening`
![vecer](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/f9ede7b2-99b7-4e13-9acd-4d1457a0191d)

`night`
![noc](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/c3500fe4-458c-48cd-9e24-a2952f167477)


`code in sensors.yaml for the time of day sensor`
```yaml
  - platform: template
    sensors:
      del_dneva:
        friendly_name: "Del dneva"
        value_template: >
          {% set current_hour = strptime(states('sensor.time'), "%H:%M").hour %}
          {% set sun_state = states('sun.sun') %}
          {% if sun_state == "below_horizon" and current_hour < 22 %}
            Noč
          {% elif sun_state == "above_horizon" and current_hour < 6 %}
            Jutro
          {% elif '09:00' <= states('sensor.time') <= '11:45' %}
            Dopoldan
          {% elif '11:45' <= states('sensor.time') <= '12:15' %}
            Poldne
          {% elif '12:15' <= states('sensor.time') <= '19:00' %}
            Popoldan
          {% elif sun_state == "below_horizon" and current_hour < 16 %}
            Večer
          {% endif %}
```

`FP yaml`

```yaml
config:
  defaults:
    hover_action: hover-info
    tap_action: more-info
  image: /local/img/fp/fp.svg
  rules:
    - element: del_dneva
      entity: sensor.del_dneva
      tap_action: false
      hover_action: false
      state_action:
        action: call-service
        service: floorplan.image_set
        service_data: |
          >
           var imageName = ''; 
           switch (entity.state) { 
             case 'Jutro': imageName ='jutro'; break; 
             case 'Dopoldan': imageName = 'dopoldan'; break; 
             case 'Poldne': imageName = 'poldne'; break; 
             case 'Popoldan': imageName = 'popoldan'; break; 
             case 'Večer': imageName = 'vecer'; break; 
             case 'Noč': imageName = 'noc'; break;  
           } 
           return '/local/img/fp/' + imageName + '.png';     
```

## Be careful! The images are not the same size as the images in zip filel!

# Enjoy

**Comment by Trzinka** [comment]
# Let's go into more detail

`Where is the Floor plan located?`

![HA-FP](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/9ed007e2-7dae-40b4-b9ad-67e76923f5f5)

`For file editor click on three dots on top right side and select `Edit Dashboard``

![FP-Edit Dashboard](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/277b6826-9a2d-40c1-91f2-053693497c62)

`then again three dots on top right side and select `Raw configuration editor``

![FP-Raw Configuration Editor](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/58e64cbf-e554-4ec3-ac2c-a6f39c73536b)

`and now you are in `FP-Edit Configuration``

![FP-Edit Configuration](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a056e330-414d-4d06-916a-deb48e4d96f8)


`I made the first horizontal page, which allows for the addition of subsequent pages!`

![FP-horizontal-stack](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/275d5725-296e-4c2d-a3b0-94f0a1651930)

`Next is the card where I placed the cameras!`

![FP-vertical-stack](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/bc28c846-8f2b-4d4b-8008-7ac6610466d9)

`floor plan card`
```yaml
card_mod:                                                    //HACS add on card
    style: |
      :host {                                                //element in HTML (DOM) from HA "https://www.w3schools.com/jsref/dom_obj_all.asp"
        position: absolute !important;                       //position of page "https://www.w3schools.com/css/css_positioning.asp" and "https://www.w3schools.com/css/css_important.asp"
        heigh: auto;                                         //heigh of the object "https://www.w3schools.com/cssref/pr_dim_height.php"
        max-width: 18vw !important;                          //max-width of the object "https://www.w3schools.com/cssref/pr_dim_max-width.php"
        z-index: 10 !important;                              //setting the height of an object above other objects (layer)  "https://www.w3schools.com/cssref/pr_pos_z-index.php"  THIS PLACES THE ELEMENTS ABOVE ALL OTHERS!!!!!
        }
```

`Camera card!`

![FP-custom_webrtc-camera](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/fd77d443-8d8b-4a80-a0b3-3eac66eaae09)

`floor plan card`
```yaml
              - type: custom:webrtc-camera                      //HACS add on card
                card_mod:
                  style: |
                    :host {
                      position: absolute !important;
                      heigh: auto;
                      max-width: 18vw !important;
                      top: 100px !important;                   //The position of the object from the top "https://www.w3schools.com/cssref/pr_pos_top.php"
                      left: 40px !important;                   //Position of the object from the left "https://www.w3schools.com/cssref/pr_pos_left.php"
                      z-index: 10 !important;
                      }
                url: rtsp://192.168.1.42:8554/Jedilnica        //the path to the camera or server that stream video from the camera
                mode: webrtc
                muted: true                                    //sound muted
```

`Now the floor plan!`

![FP-SVG](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e11f8ddd-5894-4265-afa6-d0a6267e4d1e)

`floor plan card`         //read it: "https://experiencelovelace.github.io/ha-floorplan/docs/how-to-handle-size-and-expand-floorplan/"
```yaml
              - type: custom:floorplan-card
                panel: true
                full_height: true
                config:
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  image: /local/img/fp/fp.svg
                  stylesheet: /local/img/fp/fp.css
                  rules:
                    - element: background           //Sunlight opacity function (special sensor described above)
                      entity: sensor.povprecje_zatemnitve_doma
                      tap_action: false
                      hover_action: false
                      state_action:
                        action: call-service
                        service: floorplan.style_set
                        service_data: |
                          > return `opacity: ${entity.state};`
```

`css`
```yaml
svg, svg * {
  cursor: auto !important;                             // read it: "https://www.w3schools.com/cssref/pr_class_cursor.php"
  margin: 0px !important;                              // read it: "https://www.w3schools.com/css/css_margin.asp"
  max-height: 100vh !important;
  width: auto  !important;
  padding-top: 220px !important;                       //read it: "https://www.w3schools.com/css/css_padding.asp"
  padding-bottom: 220px !important;
  z-index: 0;                                          //is the lowest level/layer in this layout 
  }

svg path {                                             //setting for borders/line of rooms from SVG
  fill: inherit; ;                                     //read it: "https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill"
  stroke: inherit;                                     //read it: "https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes"
  stroke-width: 0px !important;                        //read it: "https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width"
  }
```

`Setting the background image (default image)!`

![FP-Background](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/8ea21fdc-eb7f-46a8-b48f-28ab0ad65abb)

`css`
```yaml
#background {
  display: block !important;                       //read it: "https://www.w3schools.com/cssref/pr_class_display.php"
  z-index: 1;                                      //is top above svg, svg * for 1 layer
 }
```

`How to set background images to show room images when the light/switch is on!`

![FP-Room](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a28f1887-832e-48d2-b1c6-9c26d80f46ce)

`floor plan card` 
```yaml
                    - entity: switch.sw_st
                      element: room.sw_st
                    - entity: switch.sw_vh
                      element: room.sw_vh
                    - entity: switch.sw_mi
                      element: room.sw_mi
                    - entity: switch.sw_gr
                      element: room.sw_gr
                    - entity: switch.sw_ho
                      element: room.sw_ho
                    - entity: switch.sw_sp
                      element: room.sw_sp
                    - entity: switch.sw_na
                      element: room.sw_na
                    - entity: switch.sw_di
                      element: room.sw_di
                    - entity: switch.sw_je
                      element: room.sw_je
                    - entity: switch.sw_sh
                      element: room.sw_sh
                    - entity: switch.sw_ku
                      element: room.sw_ku
                    - entity: switch.sw_ko
                      element: room.sw_ko
                    - entity: switch.sw_ko
                      element: room.sw_ko
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
```

`css`
```yaml
#rooms image {                                               //default for images of rooms that are illuminated (does not display)
  display: none;                                             //does not display any views
  mix-blend-mode: lighten;                                   //this setting is important for the overlap between images "https://www.w3schools.com/cssref/pr_mix-blend-mode.php"                 
  animation: 0.75s fade-in linear forwards;                  //for a nice transition between picture exchanges "https://www.w3schools.com/css/css3_animations.asp"
  }

@keyframes fade-in {                                         //animation that makes the image go from opacity 0 (hidden) to opacity 1 (full view) "https://www.w3schools.com/css/css3_animations.asp"
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

#rooms image.switch-on {                                     //what happens when the switch/light is turned on, or click on the room
  display: block !important;                                 //Shows a image
  opacity: 1;;                                               //opacity is not active
  z-index: 5 !important;                                     //is top above background for 4 layer
  }
```

`How to show room boundaries/lines to display when light/switch is on!`

![FP-Areas](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a283be7e-375d-41a5-b28a-d1d32040de2a)

`floor plan card` 
```yaml
                    - entities:
                        - switch.sw_st
                        - switch.sw_vh
                        - switch.sw_mi
                        - switch.sw_gr
                        - switch.sw_ho
                        - switch.sw_sp
                        - switch.sw_na
                        - switch.sw_di
                        - switch.sw_je
                        - switch.sw_sh
                        - switch.sw_ku
                        - switch.sw_ko
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
```

`css`
```yaml
#areas {                                                   //it shows nothing/hide
  fill: none;
  stroke: none;
  }

#areas .switch-on {
  stroke: red !important;
  stroke-width: 15px !important;
  stroke-opacity: 1;
  z-index: 6;                                              //is top above rooms image.switch-on for 1 layer
  }
```
