### DISCUSSION TITLE
New day new problems/ideas

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#412] [Q&A] [answered]
`FP yaml`
```
                    - entities:
                        - sensor.me_bo_current_consumption
                        - sensor.me_hora_current_consumption
                        - sensor.me_kl_current_consumption
                        - sensor.me_natv_current_consumption
                        - sensor.me_prst_current_consumption
                        - sensor.me_sk_current_consumption
                        - sensor.me_sptv_current_consumption
                        - sensor.me_ss_current_consumption
                        - sensor.me_vhra_current_consumption
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
```

i have ` sensor.me_hora_current_consumption` 
![FP-Elements current_consumption](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/0bc0aada-ced9-4ff1-91f0-1b7e311bb562)

## and I would like to be able to set up a condition if it is greater than or equal to be a  floorplan.class_set  `switchstate-on` otherwise  `switchstate-off`

```
if can be done after service_data: and code 
instead of service_data: switch-${entity.state}
```

**Comment by OzGav** [comment]
If I understand correctly you would have in your service data an IF statement which checks if the `entity.state` Is greater than whatever value you want then apply the appropriate CSS class.

**Comment by Trzinka** [comment]
### Magic man!

`Yes!`

```
The state of these entities is mostly greater than 0 and is a number and not (on/off)

(the refrigerator is always consuming something, the TV even if it is on standby, etc.)
```

**Comment by Trzinka** [comment, marked as answer]
# The solution is as follows:

```yaml
                    - entities:
                        - sensor.me_bo_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_hora_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_kl_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_natv_current
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.8) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_prst_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_sk_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_sptv_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 11) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_ss_current_consumptionz
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_vhra_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 0.5) ? "switch-on" :
                            "switch-off"}
                    - entities:
                        - sensor.me_hl_current_consumption
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: >-
                            ${(parseFloat(entity.state) > 15.5) ? "switch-on" :
                            "switch-off"}
```

`The end result:`
![FP-current_consumption](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/790113b0-14a5-4fdd-802c-0a1cb94bf07a)
