### DISCUSSION TITLE
Inkscape properti setting multiple objects (I would like to have as one element)

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#413] [Q&A] [answered]
**I have the following status in inkscape**

![Inkscape-settings](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1ed731c6-08d4-42c8-8932-7c096f0d4735)

In FP.yaml
```
                    - entities:
                        - switch.tm_vh
                        - switch.tm_mi
                        - switch.tm_sp
                        - switch.tm_na
                        - switch.tm_di
                        - switch.tm_ko
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
```

### I guess my implementation of the folder naming in Inkscape is wrong or not done correctly as shown in the image above "switch.tm_sp" and  "switch.tm_di" !!
