### DISCUSSION TITLE
Shelly power meter switch and how to call it in floor plan? Node Red

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#414] [Q&A] [answered]
## Hi. 

**I have a shelly power meter showing me**
![Shelly 1PM](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/6ae6392b-09a8-4053-b825-58c144d041a1)

`In floor plan card i have`
```yaml
                    - entities:
                        - switch.tm_vh
                        - switch.tm_mi
                        - switch.tm_sp
                        - switch.tm_na
                        - switch.tm_di
                        - switch.tm_ko
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: switch-${entity.state}
```

**Comment by Trzinka** [comment, marked as answer]
## I was in error when showing whether the heating is ON/OFF, because it is automatically controlled via Node Red, and I don't need the `tap_action` either, because it is only for display!!!

**The solution is as follows:**

```yaml
                    - entities:
                        - switch.tm_vh
                        - switch.tm_mi
                        - switch.tm_sp
                        - switch.tm_na
                        - switch.tm_di
                        - switch.tm_ko
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: '${(entity.state === "on") ? "switch-on" : "switch-off"}'                   
                      tap_action: false
```
