### DISCUSSION TITLE
Temperature text in svg and HTML

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#415] [Q&A] [answered]
## Ah yes, I need new help because I just don't understand how to do it, so I tried something!

`In Inkscape I made a new folder named text and added 6 elements to which I assigned an ID equal to the HA entity ID.`

![Inkscape-text](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/f2c3d146-b287-483f-97bb-c1fe4b7f6381)

**Is this even the right way?**

`In floor plan card i add:`

```yaml
                    - name: Temperature
                      entities:
                        - sensor.povprecje_temperature_di
                        - sensor.povprecje_temperature_jedilnica
                        - sensor.povprecje_temperature_kopalnica
                        - sensor.povprecje_temperature_michele
                        - sensor.povprecje_temperature_nata
                        - sensor.povprecje_temperature_spalnica
                        - sensor.povprecje_temperature_vhod
                      state_action:
                        - service: floorplan.text_set
                          service_data: >-
                            ${(entity.state !== undefined) ?
                            Math.round(entity.state * 10) / 10 + "°" :
                            "unknown"}
                        - service: floorplan.class_set
                          service_data:
                            class: static-temp
```

`In browser Dev Tools i can see`

![FP-text](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/f162b062-1cbd-49ae-ac3a-e611e92f72e0)

**Od HA dobim povprečno temperaturo za vsako sobo posebej!**

in CSS i have:

```yaml

.static-temp {
  fill: none;
  stroke: none;
  font-size: 10px;
  color: aliceblue;	
  font-style: italic;	
  z-index: 10;
}
```

# Apparently, again, my current knowledge ends here!

**Comment by Trzinka** [comment, marked as answer]
# With the help of watching a video and a bit of surfing the web, I solved the problem!!!

`In Inkscape I added text over the sidebar to get this:`

![Inkscape-text1](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a3fbc12e-d96f-49cb-b341-8edff5d9cd0e)

![Inkscape-text2](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e24f6943-c1d5-49ef-a4d7-88cb701d94e5)

`Then I checked through Dev tools to see what the hell was going on:`

![FP-20240125-DevTools](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/8d38ab53-2dd6-498b-8ad3-922bd9b4da5d)

`Fixed in fp.yaml`

```yaml
                    - entities:
                        - sensor.povprecje_temperature_di
                        - sensor.povprecje_temperature_jedilnica
                        - sensor.povprecje_temperature_kopalnica
                        - sensor.povprecje_temperature_michele
                        - sensor.povprecje_temperature_nata
                        - sensor.povprecje_temperature_spalnica
                        - sensor.povprecje_temperature_vhod
                      state_action:
                        - service: floorplan.text_set
                          service_data: >-
                            ${(entity.state !== undefined) ?
                            Math.round(entity.state * 10) / 10 + "°" :
                            "unknown"}
                        - service: floorplan.class_set
                          service_data:
                            class: static-temp
                      tap_action: null
```

`and add in fp.css`

```
tspan {
	fill: rgb(60, 122, 255);
	stroke: none;
	font-size: 50px !important;
	z-index: 10;
}
```

`Final result:`

![FP-20240125](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1cf4e541-3d43-4672-8338-92fe5ffb5885)

## This one was tough
