### DISCUSSION TITLE
Play the camera video (pop-up)  in the window if figate detects objects on the individual camera

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#416] [Q&A] [answered]
## Hi.
# I have a question: how/with what would I make the floor plan card play the camera video (pop-up)  in the window if figate detects objects on the individual camera?

`I don't like the current state (too annoying)!`

![20240126-FP cameras](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1ee70d8c-3a41-45dc-ac30-d29ba0dc76e6)

**Comment by OzGav** [comment]
I’m not 100% sure but you would have to start by finding an entity with a state that changes on object detection.

**Reply by Trzinka** [reply]
# Hi! I've been looking at bubble-card which has a pop-up option but somehow I can't get it to work.

`Would it be possible to arrange via the popup so that the video would be displayed if some of these sensors were detected`

![Frigat camera_1](https://github.com/Clooos/Bubble-Card/assets/40424965/ed99cf92-4c07-4db9-be92-fc160a2afde0)

`I currently have it set up like this`
```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#pop-up-jedilnica'
    trigger_entity: binary_sensor.diane_all_occupancy
    trigger_close: true
    state: camera.jedilnica
    trigger_state: 'on'
```

`I don't know if `trigger_state: 'on'' is correct given:`

![20240127-Frigat-Jedilnica-HA Developer tools](https://github.com/Clooos/Bubble-Card/assets/40424965/8d5ec7a7-c0f0-45ab-bf16-3760bf2af203)

`I would like to have such an appearance that if the camera detects an object, a pop-up video play, if possible.`

![20240126-FP cameras-Motion](https://github.com/Clooos/Bubble-Card/assets/40424965/1f26127e-04ce-4f9b-a04f-fca3efed63a5)

**Reply by OzGav** [reply]
I am not sure as I have not done this myself nor have I seen anyone do it. Have a look at browser-mod as well

**Comment by Trzinka** [comment, marked as answer]
# I finally found a solution that works best for me (it's not perfect).

`I'm using a Frigate for the sensor:`

![Frigat camera-Motion](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/44e888ff-7dcd-42e7-a581-b5f80887011d)


`fp yaml code`

```yaml
views:
  - title: Floor plan
    path: floorplan
    theme: blue_night
    icon: mdi:floor-plan
    panel: true
    type: panel
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.jedilnica_motion
                    state: 'on'
                card:
                  type: custom:webrtc-camera
                  card_mod:
                    style: |
                      :host {
                        position: absolute !important;
                        heigh: auto;
                        max-width: 18vw !important;
                        top: 100px !important;
                        left: 40px !important;
                        z-index: 1 !important;
                        }
                  url: rtsp://192.168.1.42:8554/Jedilnica
                  ui: true
                  poster: /local/img/fp/prosojna.png
                  muted: true
                  background: true
                  intersection: 0.75
                  mode: webrtc,webrtc/tcp,mse,hls,mjpeg
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.diane_motion
                    state: 'on'
                card:
                  type: custom:webrtc-camera
                  card_mod:
                    style: |
                      :host {
                        position: absolute !important;
                        heigh: auto;
                        max-width: 18vw !important;
                        bottom: 100px !important;
                        left: 40px !important;
                        z-index: 1 !important;
                        }
                  url: rtsp://192.168.1.42:8554/Di
                  ui: true
                  poster: /local/img/fp/prosojna.png
                  muted: true
                  background: true
                  intersection: 0.75
                  mode: webrtc,webrtc/tcp,mse,hls,mjpeg
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.nathalie_motion
                    state: 'on'
                card:
                  type: custom:webrtc-camera
                  card_mod:
                    style: |
                      :host {
                        position: absolute !important;
                        heigh: auto;
                        max-width: 18vw !important;
                        top: 100px !important;
                        right: 40px !important;
                        z-index: 1 !important;
                        }
                  url: rtsp://192.168.1.42:8554/Nata
                  ui: true
                  poster: /local/img/fp/prosojna.png
                  muted: true
                  background: true
                  intersection: 0.75
                  mode: webrtc,webrtc/tcp,mse,hls,mjpeg
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.spalnica_motion
                    state: 'on'
                card:
                  type: custom:webrtc-camera
                  card_mod:
                    style: |
                      :host {
                        position: absolute !important;
                        heigh: auto;
                        max-width: 18vw !important;
                        bottom: 100px !important;
                        right: 40px !important;
                        z-index: 1 !important;
                        }
                  url: rtsp://192.168.1.42:8554/Spalnica
                  ui: true
                  poster: /local/img/fp/prosojna.png
                  muted: true
                  background: true
                  intersection: 0.75
                  mode: webrtc,webrtc/tcp,mse,hls,mjpeg
              - type: custom:floorplan-card    
//this is where the floor plan card begins 
```

`Current view:`

![20240127-FP](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/64efcbe5-540f-4376-a3a3-9fe309b381c6)

`Current view, when the camera detects motion:`

![20240127-FP+camera](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/fef781ba-a7f0-4e33-8bdd-beb6bf7432ab)
