### DISCUSSION TITLE
Phone/tablet layout

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#419] [Q&A] [answered]
# Hi!

# I have a problem with the appearance of the floor plan card on the phone/tablet!

`It looks like this on the computer:`

![FP-PC horizontal](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e82857cb-239d-4232-855a-d8f3681f7a48)

`It looks like this on the phone:`
_Horizontal view_

![FP-Phone horizontal](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/00165afd-5d67-4dd6-a624-14608923aece)

_Vertical view_

![FP-Phone vertical](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/20972b04-ff4f-407b-8b8c-135ed73ca313)

`It looks like this on the tablet:`
_Horizontal view_

![FP-Tablet horizonta](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/38d9bbd9-d749-470e-ab3c-0351607dac98)

_Vertical view_

![FP-Tablet vertical](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/3ef2cba6-e2cd-4d9f-bad8-1b4ca363388c)

# How could I solve the horizontal layout on the phone/tablet?

**Comment by OzGav** [comment]
https://experiencelovelace.github.io/ha-floorplan/docs/how-to-handle-size-and-expand-floorplan/

and also look at using different versions of the floorplan depending on screen width https://experiencelovelace.github.io/ha-floorplan/docs/usage/#image

**Comment by Trzinka** [comment, marked as answer]
## So the solution is as follows:

# I installed Full Kiosk Browser on the tablet and marked it to run in full screen mode!

![Full Kiosk Browser](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/24679866-4ce6-424e-9f3a-d63161073a1d)

**More changes in**

`before in fp.yaml`
```yaml
views:
  - title: Floor plan
    path: floorplan
    theme: blue_night
    icon: mdi:floor-plan
    panel: true
    type: panel
    badges: []
    cards:
/*********************************************/
              - type: custom:floorplan-card
                panel: true
                full_height: true
                config:
```

`after  in fp.yaml`
```yaml
views:
  - title: Floor plan
    path: floorplan
    theme: blue_night
    icon: mdi:floor-plan
    panel: true
    badges: []
    cards:
/*********************************************/
              - type: custom:floorplan-card
                full_height: true
                config:
```

`before in CSS`
```
svg, svg * {
	cursor: auto !important;
	margin: 0px !important;
	max-height: 100vh !important;
	width: auto  !important;
	padding-top: 150px !important;
	padding-bottom: 150px !important;
	z-index: 0;
  }
```

`after  in CSS`
```
svg, svg * {
	cursor: auto !important;
	margin: 0px !important;
	max-height: 100vh !important;
	width: auto  !important;
	padding-top: 100px !important;
	padding-bottom: 20px !important;
	z-index: 0;
  }
```
