### DISCUSSION TITLE
Person status on FP

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#420] [Q&A] [answered]
# Hi again.

`I was looking at how to display the status of person and I came across this website:`
https://www.thehomeautomationblog.com/how-to-create-a-floorplan-in-home-assistant-part-5-interactive/

`it says so under the person`

```yaml
  - type: image
    entity: person.martin
    image: /local/lovelace/home/martin-home-250.png
    state_image:
      Away: /local/lovelace/home/martin-out-250.png
      Home: /local/lovelace/home/martin-home-250.png
      not_home: /local/lovelace/home/martin-out-250.png
    style:
      left: 6%
      top: 59%
      width: 12%
```

## Because I have 2 levels/layer of which 1 is for cameras and 2 is for floor plan! Details on: (https://github.com/ExperienceLovelace/ha-floorplan/discussions/411)

**I tried to add a person according to the aforementioned setting, but it doesn't work.**

Not sure if it would be best to make another one levels/layer for persons?

## I also don't understand why there have to be so many pictures in the settings?

`I tried like this:`

```yaml
              - type: picture-elements
                card_mod:
                  style: |
                    :host {
                      position: absolute !important;
                      heigh: 100vh !important;
                      width: auto;
                      top: 40px;
                      z-index: 1 !important;
                      }
                elements:
                  - type: image
                    entity: person.robert
                    image: /local/img/fp/Person-Frame.png
                    state_image:
                      Away: /local/img/fp/Robert-Away.png
                      Home: /local/img/fp/Robert-Home.png
                    style:
                      left: 400px
                      top: 100px
                      heigh: 8px !important
                      width: auto
                image: /local/img/fp/Person-Transparent.png   
```

`I prepared the following pictures for one person:`

Frame
![Person-Frame](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/c99b1c4e-c66b-4e29-ae9f-42dcbeb5c7e3)

Person home
![Robert-Home](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/4c0c4009-9e47-4bd8-a0e6-3f60b059c3b5)

Person  away
![Robert-Away](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/a002a1a1-99d9-4220-a1bf-b8252eb0c238)

would that be better to use?
![Robert](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/7a04a254-b3e8-42a1-8919-a5a6c913d66a)

>  **By the way, am I using too big images?**

## My brain has apparently stopped working and I'm blocked and I can't find a solution!

# Anyone have any ideas?

**Comment by Trzinka** [comment]
# This is what the card tree looks like:

![DevTools](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/fe4629ad-7756-4b01-b6b6-3fa854a07808)

**Reply by OzGav** [reply]
You can’t combine picture elements with ha-flooplan

**Reply by Trzinka** [reply]
# Okay. Thanks for the reply.

**But I still don't understand where I have to put which picture?**

**Reply by OzGav** [reply]
Put the home or away picture on the background. Then add the other picture in a layer (just like your lights on images) then toggle the visibility of that image based on home or away. You could also use image_set but I find it easier to just toggle the visibility of one object

**Comment by Trzinka** [comment, marked as answer]
# The final solution, although not the best, but it is possible to survive!

`View on the tablet via Full Kiosk Browser:`

![Screenshot_20240201-135730](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/ff8e6b93-35e5-4637-9493-91d51669ef51)


`View on computer:`

![FP-person](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/799fca73-5057-4594-8f7a-5ea1d5519ef9)


`code for fp.yaml`
```yaml
                cards:
                  - type: custom:stack-in-card
                    mode: horizontal
                    cards:
                      - type: custom:mushroom-person-card
                        entity: person.robert
                        icon_type: entity-picture
                        hide_name: true
                        layout: vertical
                        secondary_info: state
                      - type: conditional
                        conditions:
                          - entity: sensor.robert_mobitel_battery_state
                            state: charging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.robert_mobitel_battery_level
                          layout: vertical
                          icon_color: yellow
                          fill_container: true
                          name: Robert
                          icon: mdi:battery-charging-medium
                          hide_name: true
                          primary: >-
                            Baterija: {{
                            states('sensor.robert_mobitel_battery_level') }}%
                          card_mod:
                            style: |
                              mushroom-shape-icon {
                                animation: blink 1s linear infinite;
                              }          
                              @keyframes blink {
                                50% {opacity: 0;}
                              }
                      - type: conditional
                        conditions:
                          - entity: sensor.robert_mobitel_battery_state
                            state: discharging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.robert_mobitel_battery_level
                          layout: vertical
                          icon: |2
                              {% set bl = states('sensor.robert_mobitel_battery_level') | int %}
                              {% if bl < 10 %} mdi:battery-outline
                              {% elif bl < 20 %} mdi:battery-10
                              {% elif bl < 30 %} mdi:battery-20
                              {% elif bl < 40 %} mdi:battery-30
                              {% elif bl < 50 %} mdi:battery-40
                              {% elif bl < 60 %} mdi:battery-50
                              {% elif bl < 70 %} mdi:battery-60
                              {% elif bl < 80 %} mdi:battery-70
                              {% elif bl < 90 %} mdi:battery-80
                              {% elif bl < 100 %} mdi:battery-90
                              {% elif bl == 100 %} mdi:battery
                              {% else %} mdi:battery-unknown
                              {% endif %}
                          icon_color: |2-
                                      {% set bl = states('sensor.robert_mobitel_battery_level') | int %}
                                      {% if bl < 10 %} #cc0c16
                                      {% elif bl < 20 %} #e61e28
                                      {% elif bl < 30 %} #e3464e
                                      {% elif bl < 40 %} orange
                                      {% elif bl < 50 %} #f0b93a
                                      {% elif bl < 60 %} #f3f56c
                                      {% elif bl < 70 %} #f2f536
                                      {% elif bl < 80 %} #69f095
                                      {% elif bl < 90 %} #2ee669
                                      {% elif bl < 100 %} #05ad3b
                                      {% elif bl == 100 %} #03872d
                                      {% else %} grey
                                      {% endif %}
                          primary: >-
                            Baterija: {{
                            states('sensor.robert_mobitel_battery_level') }}%
                          tap_action:
                            action: more-info
                          fill_container: true
              - type: custom:stack-in-card
                mode: vertical
                card_mod:
                  style: |
                    ha-card {
                      background-color: rgba(255, 255, 255, .1);
                      }
                    :host {
                        position: absolute !important;
                        top: 60px !important;
                        left: calc(50% - 200px) !important;
                        z-index: 1 !important;
                        }
                cards:
                  - type: custom:stack-in-card
                    mode: horizontal
                    cards:
                      - type: custom:mushroom-person-card
                        entity: person.mojca
                        icon_type: entity-picture
                        hide_name: true
                        layout: vertical
                        secondary_info: state
                      - type: conditional
                        conditions:
                          - entity: sensor.mojca_mobitel_battery_state
                            state: charging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.mojca_mobitel_battery_level
                          layout: vertical
                          icon_color: yellow
                          fill_container: true
                          name: Mojca
                          icon: mdi:battery-charging-medium
                          hide_name: true
                          primary: >-
                            Baterija: {{
                            states('sensor.mojca_mobitel_battery_level') }}%
                          card_mod:
                            style: |
                              mushroom-shape-icon {
                                animation: blink 1s linear infinite;
                              }          
                              @keyframes blink {
                                50% {opacity: 0;}
                              }
                      - type: conditional
                        conditions:
                          - entity: sensor.mojca_mobitel_battery_state
                            state: discharging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.mojca_mobitel_battery_level
                          layout: vertical
                          icon: |2
                              {% set bl = states('sensor.mojca_mobitel_battery_level') | int %}
                              {% if bl < 10 %} mdi:battery-outline
                              {% elif bl < 20 %} mdi:battery-10
                              {% elif bl < 30 %} mdi:battery-20
                              {% elif bl < 40 %} mdi:battery-30
                              {% elif bl < 50 %} mdi:battery-40
                              {% elif bl < 60 %} mdi:battery-50
                              {% elif bl < 70 %} mdi:battery-60
                              {% elif bl < 80 %} mdi:battery-70
                              {% elif bl < 90 %} mdi:battery-80
                              {% elif bl < 100 %} mdi:battery-90
                              {% elif bl == 100 %} mdi:battery
                              {% else %} mdi:battery-unknown
                              {% endif %}
                          icon_color: |2-
                                      {% set bl = states('sensor.mojca_mobitel_battery_level') | int %}
                                      {% if bl < 10 %} #cc0c16
                                      {% elif bl < 20 %} #e61e28
                                      {% elif bl < 30 %} #e3464e
                                      {% elif bl < 40 %} orange
                                      {% elif bl < 50 %} #f0b93a
                                      {% elif bl < 60 %} #f3f56c
                                      {% elif bl < 70 %} #f2f536
                                      {% elif bl < 80 %} #69f095
                                      {% elif bl < 90 %} #2ee669
                                      {% elif bl < 100 %} #05ad3b
                                      {% elif bl == 100 %} #03872d
                                      {% else %} grey
                                      {% endif %}
                          primary: >-
                            Baterija: {{
                            states('sensor.mojca_mobitel_battery_level') }}%
                          tap_action:
                            action: more-info
                          fill_container: true
              - type: custom:stack-in-card
                mode: vertical
                card_mod:
                  style: |
                    ha-card {
                      background-color: rgba(255, 255, 255, .1);
                      }
                    :host {
                        position: absolute !important;
                        top: 60px !important;
                        right: calc(50% - 200px) !important;
                        z-index: 1 !important;
                        }
                cards:
                  - type: custom:stack-in-card
                    mode: horizontal
                    cards:
                      - type: custom:mushroom-person-card
                        entity: person.nata
                        icon_type: entity-picture
                        hide_name: true
                        layout: vertical
                        secondary_info: state
                      - type: conditional
                        conditions:
                          - entity: sensor.nathalies_iphone_battery_state
                            state: charging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.nathalies_iphone_battery_level
                          layout: vertical
                          icon_color: yellow
                          fill_container: true
                          name: Nathalie
                          icon: mdi:battery-charging-medium
                          hide_name: true
                          primary: >-
                            Baterija: {{
                            states('sensor.mojca_mobitel_battery_level') }}%
                          card_mod:
                            style: |
                              mushroom-shape-icon {
                                animation: blink 1s linear infinite;
                              }          
                              @keyframes blink {
                                50% {opacity: 0;}
                              }
                      - type: conditional
                        conditions:
                          - entity: sensor.nathalies_iphone_battery_state
                            state: discharging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.nathalies_iphone_battery_level
                          layout: vertical
                          icon: |2
                              {% set bl = states('sensor.nathalies_iphone_battery_level') | int %}
                              {% if bl < 10 %} mdi:battery-outline
                              {% elif bl < 20 %} mdi:battery-10
                              {% elif bl < 30 %} mdi:battery-20
                              {% elif bl < 40 %} mdi:battery-30
                              {% elif bl < 50 %} mdi:battery-40
                              {% elif bl < 60 %} mdi:battery-50
                              {% elif bl < 70 %} mdi:battery-60
                              {% elif bl < 80 %} mdi:battery-70
                              {% elif bl < 90 %} mdi:battery-80
                              {% elif bl < 100 %} mdi:battery-90
                              {% elif bl == 100 %} mdi:battery
                              {% else %} mdi:battery-unknown
                              {% endif %}
                          icon_color: |2-
                                      {% set bl = states('sensor.nathalies_iphone_battery_level') | int %}
                                      {% if bl < 10 %} #cc0c16
                                      {% elif bl < 20 %} #e61e28
                                      {% elif bl < 30 %} #e3464e
                                      {% elif bl < 40 %} orange
                                      {% elif bl < 50 %} #f0b93a
                                      {% elif bl < 60 %} #f3f56c
                                      {% elif bl < 70 %} #f2f536
                                      {% elif bl < 80 %} #69f095
                                      {% elif bl < 90 %} #2ee669
                                      {% elif bl < 100 %} #05ad3b
                                      {% elif bl == 100 %} #03872d
                                      {% else %} grey
                                      {% endif %}
                          primary: >-
                            Baterija: {{
                            states('sensor.nathalies_iphone_battery_level') }}%
                          tap_action:
                            action: more-info
                          fill_container: true
              - type: custom:stack-in-card
                mode: vertical
                card_mod:
                  style: |
                    ha-card {
                      background-color: rgba(255, 255, 255, .1);
                      }
                    :host {
                        position: absolute !important;
                        top: 60px !important;
                        right: calc(50% - 400px) !important;
                        z-index: 1 !important;
                        }                          
                cards:
                  - type: custom:stack-in-card
                    mode: horizontal
                    cards:
                      - type: custom:mushroom-person-card
                        entity: person.di
                        icon_type: entity-picture
                        hide_name: true
                        layout: vertical
                        secondary_info: state
                      - type: conditional
                        conditions:
                          - entity: sensor.di_mobitel_battery_state
                            state: charging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.di_mobitel_battery_level
                          layout: vertical
                          icon_color: yellow
                          fill_container: true
                          name: Diane
                          icon: mdi:battery-charging-medium
                          hide_name: true
                          primary: >-
                            Baterija: {{
                            states('sensor.di_mobitel_battery_level') }}%
                          card_mod:
                            style: |
                              mushroom-shape-icon {
                                animation: blink 1s linear infinite;
                              }          
                              @keyframes blink {
                                50% {opacity: 0;}
                              }
                      - type: conditional
                        conditions:
                          - entity: sensor.di_mobitel_battery_state
                            state: discharging
                        card:
                          type: custom:mushroom-template-card
                          entity: sensor.di_mobitel_battery_level
                          layout: vertical
                          icon: |2
                              {% set bl = states('sensor.di_mobitel_battery_level') | int %}
                              {% if bl < 10 %} mdi:battery-outline
                              {% elif bl < 20 %} mdi:battery-10
                              {% elif bl < 30 %} mdi:battery-20
                              {% elif bl < 40 %} mdi:battery-30
                              {% elif bl < 50 %} mdi:battery-40
                              {% elif bl < 60 %} mdi:battery-50
                              {% elif bl < 70 %} mdi:battery-60
                              {% elif bl < 80 %} mdi:battery-70
                              {% elif bl < 90 %} mdi:battery-80
                              {% elif bl < 100 %} mdi:battery-90
                              {% elif bl == 100 %} mdi:battery
                              {% else %} mdi:battery-unknown
                              {% endif %}
                          icon_color: |2-
                                      {% set bl = states('sensor.di_mobitel_battery_level') | int %}
                                      {% if bl < 10 %} #cc0c16
                                      {% elif bl < 20 %} #e61e28
                                      {% elif bl < 30 %} #e3464e
                                      {% elif bl < 40 %} orange
                                      {% elif bl < 50 %} #f0b93a
                                      {% elif bl < 60 %} #f3f56c
                                      {% elif bl < 70 %} #f2f536
                                      {% elif bl < 80 %} #69f095
                                      {% elif bl < 90 %} #2ee669
                                      {% elif bl < 100 %} #05ad3b
                                      {% elif bl == 100 %} #03872d
                                      {% else %} grey
                                      {% endif %}
                          primary: >-
                            Baterija: {{
                            states('sensor.di_mobitel_battery_level') }}%
                          tap_action:
                            action: more-info
                          fill_container: true
```

`images made by:`
**https://avatarmaker.net/**

![AvatarMaker](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/23bf8a11-c277-4224-92d0-7e730266cc80)

![AvatarMaker-choose gender](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/d3f54739-3b13-44e4-8b0b-580ccecdd1f2)

![AvatarMaker-Make avatar](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/d3de98f5-e7a8-4247-9ce0-efd78c3ecfd9)

![AvatarMaker-Download](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/034ea4b8-aeb1-4326-b49f-91fbbf70ebe1)


`or try`
https://avatarmaker.com/

`images used:`
![Robert-Home](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/09c4b5f1-0637-4026-93de-6caf783efd8d)

![Diane-Home](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/843601d8-eb11-407b-ac90-f12003a765e6)

![Mojca-Home](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/57775e9f-7d06-4e71-a7eb-5f527d5372d4)

![Nathalie-Home](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/162cb0d2-3ba9-486d-8e56-050b412e4b70)
