### DISCUSSION TITLE
Multiple floorplan navigation with dashboard views

### DISCUSSION THREAD

**Discussion by dlarkinsPonderosa** [ExperienceLovelace/ha-floorplan#424] [Q&A] [answered]
I've searched for every option and combination I can think of but can't get any of them to work.
My SVG files are larger and I have several floors to deal with so I don't want to combine them.

The most promising was this with floorplan.execute and browser_mod but it doesn't do anything when clicking on the entity.  I get a THIS not defined in the console so it looks like difficulty addressing the local browser.

    - entity: switch.kitchen_automation
      element: stairs.downstairs
      tap_action:
        - service: floorplan.execute
          service_data:
            my_custom_exec_calling_browser_mod: |
              > 
              try{
                // Call browser_mod service
                browser_mod.service('navigate',{navigation_path: "/lovelace/bottom-floor", browser_id: THIS}) 
              }catch(e){
                console.log("Well.. That didn't go as planned",e);
              }

**Comment by exetico** [comment]
Why do you use browsermod for that? We have a navigation util. Check the docs at the "usage" page.

**Reply by OzGav** [reply]
@dlarkinsPonderosa Please only ask your question in one place. Cross post https://community.home-assistant.io/t/multiple-floorplan-navigation-with-dashboard-views/687694/7

**Reply by dlarkinsPonderosa** [reply, marked as answer]
@OzGav  Sorry for the cross post. It wasn't clear if the various discussion areas were for the same purposes, looked at by the same people , or why there were two different places for the same thing with different frequency of posts.  

I had tried the navigate action but explicitly with call-service rather that the simpler solution that you provided.

I tried something like this (similar to the examples when searching navigate on the Usage page in the docs) and swear it didn't work:

```
  - name: JumpBottom
    element: stairs.downstairs
    tap_action:
      action: call-service
      service: homeassistant.navigate
      service_data:
        navigation_page: /lovelace/bottom-floor
      
```

I confirmed this answer from the cross post works, so thanks for that!

 ```
   - name: JumpBottom
      element: stairs.downstairs
      tap_action:
        action: navigate
        navigation_path: /lovelace/bottom-floor
```
