### DISCUSSION TITLE
Some javascript help, please

### DISCUSSION THREAD

**Discussion by tsx-5** [ExperienceLovelace/ha-floorplan#438] [Q&A] [answered]
Hey Team,

Like to get some assistance making my yaml/code a bit more efficient/clean...  The following snipet is for a ceiling light/fan, of which I have many.  It works (I might tweak colors and size later - but for now it's good).  

```
     - element: fan.guest_ceiling
      tap_action:
        action: call-service
        service: honeycomb
        service_data:
          entity: entity
          xy_pad:
            x:
              service: light.turn_on
              service_data:
                entity_id: light.guest_ceiling
                brightness_step_pct: '{{ x_percentage / 5 }}'
            'y':
              service: fan.increase_speed
              service_data:
                entity_id: fan.guest_ceiling
                percentage_step: '{{ x_percentage / 33 }}'
          buttons:
            - icon: mdi:lightbulb
              entity: light.guest_ceiling
              tap_action:
                action: more-info
            - icon: mdi:lightbulb-on
              entity: light.guest_ceiling
              active: true
              tap_action:
                action: toggle
            - show: false
            - icon: mdi:fan
              entity: fan.guest_ceiling
              tap_action:
                action: more-info
            - icon: mdi:fan-off
              entity: fan.guest_ceiling
              active: true
              tap_action:
                action: toggle

```
However, the downside to that code is that I have to copy it for each ceiling fan/light (of which I have many).  So, I was hoping to make the code a bit more adaptive.  My naming convention for these entities is "fan."room"_ceiling" and light."room"_ceiling".  Along with an element that has the same name as the fan."room"_ceiling.  What I would like to accomplish is to monitor the element, which drives one of the entities and use javascript to create the light name (by switching fan with light).  Here's what my current iteration of that looks like (and no it doesn't work).  One issue I am having is that using the inspect feature of my web browser doesn't show this section being executed - so I don't see what is going wrong (other than nothing happening with the ceiling fan/light).  And obviously, I'm not totally sure I have this even formatted correctly (assuming this can work at all).  Definitely appreciate any thoughts.

```

   - element: fan.spare_ceiling
      tap_action:
        action: call-service
        service: honeycomb
        service_data:
          entity: entity
          xy_pad:
            x:
              service: light.turn_on
              service_data:
                entity_id: |
                  > 
                  console.log("I'm trying here");
                  try {
                    console.log("I'm trying here, even more");
                    const outlineName = element.replace('light','fan');
                    console.log(outlineName);
                    return `outlineName`; 
                  } catch(e) {
                    console.log("That didn't go as planned");
                  }      
                brightness_step_pct: 5
 ...
```

**Comment by OzGav** [comment]
What about a function? https://experiencelovelace.github.io/ha-floorplan/docs/usage/#custom-functions

**Reply by tsx-5** [reply]
I do like the idea of a function... So, created this:

```
functions: |
  >
  return {
    FunctionA: (element) => {
    try {
      console.log("I'm trying here, even more");
      const NewName = element.replace('fan','light');
      return NewName; 
    },
  };
```

with me calling it like this:

```
          xy_pad:
            x:
              service: light.turn_on
              service_data:
                entity_id: ${functions.FunctionA(element)}
                brightness_step_pct: 5
            'y':
```
unfortunately, no love...  And I still can't find my debug line - so, not even sure the function is being called :-/
