### DISCUSSION TITLE
Is there any possibility to write comments in the floor plan card?

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#446] [Q&A] [answered]
Hi! My floor plan card has become almost unreadable and if I enter a comment (# Settings for lights) in order to find it faster, I can find the line where I have the settings for the behavior of the lights. But it would be even better if I could have a separate yaml file that I could edit with Visual studio?

**Comment by OzGav** [comment]
Not sure I inderstand the problem. As you say you can add comments to the YAML. You don't have to use the HA UI to edit the view. I have mine in YAML and I edit it with notepad++

**Reply by Trzinka** [reply]
Hi OzGav! Thanks for the reply. I can't write comments right now because the floor plan card automatically deletes them (not sure if the card is the culprit). I noticed somewhere that they make a floor plan yaml file and can edit it with Visual studio. as an example in the folder www/fp/fp.yaml

**Reply by OzGav** [reply]
Yes I believe that is the HA UI doing that. Maybe this will help https://www.youtube.com/watch?v=7AU5i-WUUxw

**Reply by Trzinka** [reply]
Oh yeah! 
I just need to understand how to set to current settings! 
Thank you.

**Comment by Trzinka** [comment]
OzGav, I don't know why I `can't buy you coffe` with my new card anymore? Is there any other way to give you a `some amount of €` for your efforts?

**Reply by OzGav** [reply]
😁 no it’s fine. Thanks.

**Reply by Trzinka** [reply]
Do you have any desire for something from AliExpress for about €15, so I can buy it for you?

**Reply by OzGav** [reply]
It’s fine thanks. I appreciate your sincerity.

**Comment by Trzinka** [comment]
Apparently, I added the following to configuration.yaml `too quickly and not carefully`:

```yaml
# Set Lovelace mode
lovelace:
  mode: storage
  dashboards:
    # Add dashboard in YAML mode
    floorplan-community:
      mode: yaml
      filename: lovelace/floorplan-community.yaml
      title: Floorplan Community
      icon: mdi:account-voice
      show_in_sidebar: true
      require_admin: false
```

Since it didn't bring me the desired result, I `later deleted the code written above and restarted HA`.

_Now the problem has arisen because the grid card, which also contains the floor plan card, does not show the floor plan card!_

Did the code above change the settings so much somewhere that simply removing the code and rebooting doesn't fix them and I have to do something else to achieve this?

**Reply by OzGav** [reply]
I don’t know. It shouldn’t have. I do most of my dashboards in yaml so I’m not that well versed in the UI mode. I would look at what is in the UI editor now. You could also try asking in the HA forums?

**Reply by Trzinka** [reply]
OzGav thanks for the reply.

`The floor plan grid card looked like this:`

![20240630-FP](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/4cde9f25-f31c-4c50-9069-11317dec8768)

How it was configured is under show and tell.

`Now I'm trying again like this:`

![FP-Lovelace](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/e625419c-f5de-432f-88df-103e6cf01ee9)

`I get stuck here:`

![Link to Fp yaml](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/275a1db3-5f3f-4683-b61b-932a2ab10166)

`But maybe there is another way that I don't know yet.`

By the way, I almost always configure yaml myself just for the sake of use

```yaml
card_mod:
 styles:
```

**Reply by OzGav** [reply]
Maybe this? https://community.home-assistant.io/t/lovelace-include-files/81641/5

**Reply by Trzinka** [reply]
Thanks again. 
As I could have expected, Home Assistant crashed again due to insufficient disk space!!! ;=(((((((((() 

When I restart it and restore the backup) I'll test and let you know).

**Comment by Trzinka** [comment, marked as answer]
It's a bit more complicated but doable!:

`#1` In the root directory, you create a file called fp.yaml, for example

`#2` In configuration.yaml add:
```yaml
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Flore plan-Grid
      icon: mdi:floor-plan
      show_in_sidebar: true
      filename: fp.yaml
```
and save it.

`#3` You copy the content of the card in yaml format from the desired one to the created fp.yaml file and save it.

`#4` Restart HA.

`#5` The new icon and name you specified in configuration.yaml will appear in your sidebar.

`#6` You can now delete the old card!
