### DISCUSSION TITLE
floorplan.stayle_set or css

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#448] [Q&A] [answered]
### I have a setting in fp.yaml:
```yaml
- entity: sensor.me_kl_current_consumption
  tap_action: false
  state_action:
    service: floorplan.class_set
    service_data:
      class: >-
        ${(parseFloat(entity.state) > 1.4) ? "switch-on" :
        "switch-off"}
```
### `Is it possible to add that if it is greater than 2 that then the state is (working)? Therefore, I would monitor 3 states {off, on and working}, "the air conditioner"`

and fp.css:
```
#elements {
    fill: none;
    stroke: none;
}

 #elements .switch-on { 
    stroke: rgb(78, 192, 245) !important;
    stroke-width: 5px !important;
    stroke-opacity: 1;
    z-index: 6;
}
```
it works up to here

_**then:**_
```
#elements.switch-on #sensor\.me_kl_current_consumption {
    stroke: rgb(78, 192, 245) !important;
    stroke-width: 35px !important;
    filter: blur(36px);
    -o-filter: blur(36px);
    -ms-filter: blur(36px);
    -moz-filter: blur(36px);
    -webkit-filter: blur(36px);
    stroke-opacity: 1;
    z-index: 7 !important;
}
```
which does not work?

i also tried:
`[id='sensor.me_kl_current_consumption'] .switch-on ... `

I would like the air conditioner to have, when working:
```
stroke-width: 35px !important;
filter: blur(36px);
```
