### DISCUSSION TITLE
service: floorplan doesnt exist

### DISCUSSION THREAD

**Discussion by guylogo** [ExperienceLovelace/ha-floorplan#449] [Bugs] [answered]
![image](https://github.com/user-attachments/assets/d092395f-adf2-4d5d-ae16-8e2233956c41)
![image](https://github.com/user-attachments/assets/5068479d-049b-4727-a3f8-673374f8fd48)
I already downloaded HA-floorplan from HACS and I search service:floorplan in SERVIECS but it dont exist any. Is it normal? or Can i use it normally. Because right now i have error in this line.

![image](https://github.com/user-attachments/assets/ea47c7ed-0c73-4f00-b3d0-be93fd9d4da3)

                  rules:
                    - entities: 
                      - light.kitch_light_backlight
                      tap_action:
                        action: toggle
                      state_action:
                        action: call-service
                        service: floorplan.style_set #That mean this line
                        service_data:
                        element: "{{ entity.entity_id.replace('light.', 'light_overlay.') }}"
                          style: |
                            >
                            if (entity.state !== "on") {
                              return "display: none;";}
                            return "display: block;";

**Comment by OzGav** [comment]
Have you added it as a resource?

**Reply by guylogo** [reply]
lovelace:
                              mode: storage
                              resources:
                                  - url: /hacsfiles/ha-floorplan/floorplan.js
                                    type: module

**Reply by guylogo** [reply]
is it correct way put the resource? I write this code on configuration.yaml.

**Reply by OzGav** [reply, marked as answer]
No. If you are using STORAGE mode you need to add it through the UI.

![image](https://github.com/user-attachments/assets/3660f2cf-87cf-4624-81e7-a8aea4ac26fa)

If not then it should look like this
```
lovelace:
  mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  resources:
  - type: module
    url: /hacsfiles/ha-floorplan/floorplan.js
```

**Reply by guylogo** [reply]
lovelace:
                          mode: yaml
                          resources:
                            - type: module
                              url: /hacsfiles/ha-floorplan/floorplan.js
                          # Add dashboard in YAML mode
                          dashboards:
                             test-dashboard: 
                                mode: yaml
                                title: yamlmodetest2
                                icon: mdi:floor-plan
                                show_in_sidebar: true
                                require_admin: false
                                filename: test-dashboard/config.yaml

I have written the new one. And i already reload: All YAML CONFI and restart home assistant but it doesnt show like before. Or what i need to do after it?

**Reply by OzGav** [reply]
> it doesnt show like before

What do you mean by this?

**Reply by guylogo** [reply]
![image](https://github.com/user-attachments/assets/2d4a58d5-8770-40f6-9e79-9b06c5a5e52e)
It still doesnt have service: floorplan on SERVICES

**Reply by OzGav** [reply]
That doesn’t matter. It isn’t a HA service it is a floorplan service so it won’t show there.

**Reply by OzGav** [reply]
Looking at your error message I think you just have indenting problems. I can’t tell what line 43 is but your indenting should be like this

 ```
     rules:
        - entities:
            - sensor.ibbq_17a2_temperature_probe_1
            - sensor.ibbq_17a2_temperature_probe_2
            - sensor.ibbq_17a2_temperature_probe_3
            - sensor.ibbq_17a2_temperature_probe_4
            - input_number.bbq_probe1_tolerance
            - input_number.bbq_probe1
            - input_number.bbq_probe2
            - input_number.bbq_probe3
            - input_number.bbq_probe4
          tap_action: more-info
          state_action:
            service: floorplan.text_set
            service_data: >-
              ${entity.state != "unavailable" ? (Math.floor(entity.state)) :
              "OFF"}

```

edit: The element key should be indented and I think the entity name needs to be indented one more as well
