### DISCUSSION TITLE
Is it possible to have a function that take several entities as parameter ?

### DISCUSSION THREAD

**Discussion by zen2** [ExperienceLovelace/ha-floorplan#455] [General]
I need a way to iterate on several entities in a function to use it like it:

YAML:
```
- entities:
  - entity_1
  - entity_2
  - entity_3
  state_action:
  - service: floorplan.style_set
    service_data:
      style: ${functions.style_multiple(entities)}
```

function:
```
    style_multiple: (entities) => {
          ***  code that use state of entity_1, entity_2, entity_3, entity_4 ***
    },
```

My tries show that entities in the function are all entities of HA and not the list from floorplan YAML declaration.
Note that I need to manipulate the declared entities in the same function , not to apply the function to each entities indiviually.
Is it possible to achieve this ?

**Comment by exetico** [comment]
Hi,

What do you actually try and accomplish here? The real-world result, of the logic's you're trying to code.

With that kind of info, I think it's easier to give you the best recommendation. Provide visual examples too, if possible.

I'm unsure about the actual use-case, here. And that's a classic XY Problem.

**Comment by zen2** [comment]
Allright. I got an alerts system composed of several alert type:

![image](https://github.com/user-attachments/assets/f44b63ef-d9a8-4f49-9b73-0e67b4fa394e)

For each alert type I display an icon with a frame with informations.
Alert's icons are side by side on a line.
All alert's frame is right under icons and their geometry (position and size) are the same.
There is a colored line in the frame under corresponding icon.
Alerts are triggered by binary_sensor that are in use for icon id in svg.
Alert's frames are svg elements with a dark gradient that let display the background by transparency.

When there is several alerts in the same time, their icons are displayed and only the last alert frame is displayed.
I use too tap_action on icons to select the frame to display while hiding other ones (because I don't want that overlays of several frames bring several darker level that render almost as dark black).

My main problem is when an active alert stop the related frame is hidden letting only icons without frame on screen.
I want when several alerts are displayed and one suddenly stop to  be able to compute the highest priority one to display the related frame. Actually each alert trigger the display of its frame and remove others ones. When one alert is off it remove it's own frame.

Actual yaml code is really redundant and if I could use a function that can work with several entities I could compute and so populate elements to display/hide.

Sorry for the complexity and thanks for this fantastic code ;)

**Reply by exetico** [reply]
I think I get it. 

Personally I'd make a helper entity in Home Assistant instead, preparing the data as Id like it to be, **and** use that entity in my panel. At least, if I understand what you're asking about.

With that said: Take at look at the latest beta-release, here you'll be able to call multiple style_sets after each other. Maybe that's good enough for you? :-) 

https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.45-beta.1

**Reply by zen2** [reply]
> I think I get it.
> 
> Personally I'd make a helper entity in Home Assistant instead, preparing the data as Id like it to be, **and** use that entity in my panel. At least, if I understand what you're asking about.
> 
> With that said: Take at look at the latest beta-release, here you'll be able to call multiple style_sets after each other. Maybe that's good enough for you? :-)
> 
> https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.45-beta.1
I've seen the last besta release I was wondering if it was connected to this discussion ;)

Anyway I've solved it by creating a HA select that contains all frame's names and that is set by switched on alerts priority.

HA entitites:
- several `binary_sensor.*_alert` set to on if alert have been triggered
- several `frame.*_alert` that display alerts content
- one `select.frame_alert` that contains all alert's names that is set to the most important one from active alerts
- specific entities related to specific alert embedded in each frame alert

On floorplan:
- `binary_sensor.*_alert` display respective alert icon
- `frame.*_alert` display respective alert panel content with an indicator under respective icon
- `select.frame_alert` display the most important frame alert if there is one or several alerts
- `binary_sensor.*_alert` tap_action hide all frames and then display the selected one

Related YAML:
```
- entities:
  - binary_sensor.fire_alert
  - binary_sensor.flood_alert
  - binary_sensor.power_alert
  - binary_sensor.unavailable_alert
  - binary_sensor.ota_alert
  state_action:
  - service: floorplan.class_set
    service_data: '${ entity.state === "on" ? "layer-visible" : "layer-hidden" }'
  tap_action:
  - service: floorplan.class_set
    service_data:
      class: "layer-hidden"
      elements:
      - frame.fire_alert
      - frame.flood_alert
      - frame.power_alert
      - frame.unavailable_alert
      - frame.ota_alert
  - service: floorplan.class_set
    service_data:
      class: "layer-visible"
      element: '${entity.entity_id.replace("binary_sensor","frame")}'

- entity: select.frame_alert
  state_action:
  - service: floorplan.class_set
    service_data:
      class: "layer-hidden"
      elements:
      - frame.fire_alert
      - frame.flood_alert
      - frame.power_alert
      - frame.unavailable_alert
      - frame.ota_alert
```

Screenshot:
![image](https://github.com/user-attachments/assets/75b687bf-1bc0-4bfe-b56a-392e18fa7363)
