### DISCUSSION TITLE
navigation_path, hold_action

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#465] [Q&A] [answered]
Hi.

I'm having trouble with the hover action navigation path and I don't know what's wrong?

An example:

```yaml
########################################################
#   Room switches control
########################################################
            - entities:
                - switch.sw_na
                - switch.sw_di
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - element: room.sw_na
              entity: switch.sw_na
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/nathalie
            - element: room.sw_di
              entity: switch.sw_di
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/diane
```

`Is the path I see in the browser correct and is hold_action: in the right place?`
![HA-Path](https://github.com/user-attachments/assets/c5d37e9b-b45c-4316-b5de-634286db6018)

Thanks for your help.

**Comment by OzGav** [comment]
Yes that should work I do the exact same thing

```
            - tap_action:
                service: switch.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace/mgzsev             
              entities:
                - switch.car_charger
              name: Light and other icons
              state_action:
                service: floorplan.class_set
                service_data: 
                  class: '${(entity.state === "on") ? "lamp-on" : (entity.state === "off") ? "lamp-off" : "entity-unavailable"}'
```

**Reply by Trzinka** [reply]
Hi OzGav!

Thanks for the reply.

I've been looking at my settings a bit and it seems I might have something configured wrong:
```yaml
########################################################
#   Room switches control
########################################################
#################################
# Room switches STROKE control
#################################
            - entities:
                - switch.sw_st
                - switch.sw_vh
                - switch.sw_mi
                - switch.sw_gr
                - switch.sw_ho
                - switch.sw_sp
                - switch.sw_na
                - switch.sw_di
                - switch.sw_je
                - switch.sw_sh
                - switch.sw_ku
                - switch.sw_ko
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
#################################
# Room switches PICTURE control
#################################
            - element: room.sw_st
              entity: switch.sw_st
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - element: room.sw_vh
              entity: switch.sw_vh
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/vhod 
            - element: room.sw_mi
              entity: switch.sw_mi
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/michele
            - element: room.sw_gr
              entity: switch.sw_gr
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - element: room.sw_ho
              entity: switch.sw_ho
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/hodnik
            - element: room.sw_sp
              entity: switch.sw_sp
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/spalnica
            - element: room.sw_na
              entity: switch.sw_na
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/nathalie
            - element: room.sw_di
              entity: switch.sw_di
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/diane
            - element: room.sw_je
              entity: switch.sw_je
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/jedilnica
            - element: room.sw_sh
              entity: switch.sw_sh
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/shramba
            - element: room.sw_ku
              entity: switch.sw_ku
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kuhinja
            - element: room.sw_ko
              entity: switch.sw_ko
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kopalnica
```

`The first set draws strokes, the second changes the picture!`

**Now I don't know if it is correct to use the same state_action and tap_action for both?**

**Reply by OzGav** [reply]
Yes I do think that will work.  But why did you do it like that? All of the individual rooms are watching for state changes in those same entities. If you just remove the first section I think it should work

**Reply by Trzinka** [reply]
Hi OzGav thanks again for your reply.

To be honest, I don't know why I have it made like that!

`The idea was that the first set (Room switches STROKE control) controls:`
![FP-SVG areas](https://github.com/user-attachments/assets/b6c3f56c-31ad-45e6-8ad5-9ca197dc88a5)
![FP-SVG areas-ID](https://github.com/user-attachments/assets/46e1f193-37ea-4657-938d-3c8612d503b3)

`And the next set (Room switches PICTURE control) controls:`
![FP-SVG rooms](https://github.com/user-attachments/assets/52f3fb21-2edf-4e75-9a01-6fe18aa51769)
![FP-SVG rooms-ID](https://github.com/user-attachments/assets/c0feee47-5fbc-42f4-98f0-c3c343e9f848)

That is, the first set defines the space and draws a line on the edges when the light is on, while the second set shows the image of the illuminated spaces.

**Hmm, it would be logical that only the second string is sufficient, but it is not entirely clear to me because the SVG file takes into account layers and CSS z-index so, in my humble opinion, the rabbit is hiding somewhere in this bush.**

**Reply by Trzinka** [reply]
`If I delete:`
```yaml
#################################
# Room switches STROKE control
#################################
            - entities:
                - switch.sw_st
                - switch.sw_vh
                - switch.sw_mi
                - switch.sw_gr
                - switch.sw_ho
                - switch.sw_sp
                - switch.sw_na
                - switch.sw_di
                - switch.sw_je
                - switch.sw_sh
                - switch.sw_ku
                - switch.sw_ko
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
```

**It no longer shows me the lines around the rooms when the light is on???**

**Reply by OzGav** [reply]
Yes sorry I didn't look closely enough at what you were doing. So then that is working correctly so leave the first block in. Was there anything else?

**Reply by Trzinka** [reply]
OzGav thanks.

**Comment by Trzinka** [comment, marked as answer]
I found it!

Obviously, it is necessary to link (navigation_path) to an element that is higher in the SVG file.

`I had to fix it in fp.yaml so that it now looks like this:`
```yaml
########################################################
#   Room switches control
########################################################
#################################
# Room switches STROKE control
#################################
            - entity: switch.sw_st
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_vh
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/vhod 
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_mi
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/michele
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_gr
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ho
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/hodnik
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_sp
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/spalnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_na
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/nathalie
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_di
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/diane
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_je
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/jedilnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_sh
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/shramba
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ku
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kuhinja
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ko
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kopalnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
#################################
# Room switches STROKE control
#################################
            - entity: switch.sw_st
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_vh
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/vhod 
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_mi
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/michele
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_gr
              tap_action:
                service: homeassistant.toggle
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ho
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/hodnik
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_sp
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/spalnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_na
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/nathalie
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_di
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/diane
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_je
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/jedilnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_sh
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/shramba
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ku
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kuhinja
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
            - entity: switch.sw_ko
              tap_action:
                service: homeassistant.toggle
              hold_action:
                action: navigate
                navigation_path: /lovelace-di/kopalnica
              state_action:
                service: floorplan.class_set
                service_data: switch-${entity.state}
```

**Now if I hold over the room, it redirects me to the desired lovelace within the Home assistant.**

**Comment by remmob** [comment]
How does this work, because it is driving me insane! 
A have this rule 
```
- entity: input_boolean.alarm
  element: Woonkamer-lights
  state_action:
    - action: call-service
      service: floorplan.image_set
      service_data: 
        image: /local/test/lightbulb_${entity.state}.svg
  tap-action: 
    action: navigate
    navigation_path: /lovelace/default_view
```
The image get updated the I change the state, but the link is not applied.
