### DISCUSSION TITLE
How can I do two actions? I want to set the image and the style on state change

### DISCUSSION THREAD

**Discussion by Neriderc** [ExperienceLovelace/ha-floorplan#482] [Q&A] [answered]
When a door is unlocked, I want to update the image to an unlocked padlock and also make this image red. I am not sure how to combine the two together. Either of these rules works on it's own but not both of them:

```
rules:
                    - entity: lock.front_door
                      element: lock.front_door
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data: >-
                          /local/floorplan/${functions.isDoorLocked(entity.state) ? "locked" : "unlocked"}.svg
                      tap_action:
                        action: call-service
                        service: >-
                          lock.${functions.isDoorLocked(entity.state) ? "unlock" : "lock"}
                    - entity: lock.front_door
                      element: lock.front_door
                      state_action:
                        action: call-service
                        service: floorplan.style_set
                        service_data:
                          element: lock.front_door
                          style: |
                            >
                            return `fill: ${functions.isDoorLocked(entity.state) ? 'rgb(0,0,0)' : 'rgb(255, 0, 0)'}; cursor: pointer;`;
```

I have also tried this, based on another discussion I saw, but it doesn't seem to work.

```
rules:
                    - entity: lock.front_door
                      element: lock.front_door
                      state_action:
                        - service: floorplan.image_set
                          service_data: |
                            >
                            /local/floorplan/${functions.isDoorLocked(entity.state) ? "locked" : "unlocked"}.svg
                        - service: floorplan.style_set
                          service_data:
                            element: lock.front_door
                            style: |
                              >
                              return `fill: ${functions.isDoorLocked(entity.state) ? 'rgb(0,0,0)' : 'rgb(255, 0, 0)'}; cursor: pointer;`;
                      tap_action:
                        action: call-service
                        service: |
                          >
                          lock.${functions.isDoorLocked(entity.state) ? "unlock" : "lock"}
```

There are no errors, but it only briefly flashes the colour it's supposed to be during the state change, then goes back to having no style set (but the image change stays).

Both of the above formats have the same effect, to change the image but not retain the new fill colour.

Any tips on getting this to work?
