### DISCUSSION TITLE
how can floorplan.image_set auto refresh without m

### DISCUSSION THREAD

**Discussion by alasharim** [ExperienceLovelace/ha-floorplan#484] [Q&A]
![image](https://github.com/user-attachments/assets/ac5e3f11-b592-45a2-95a7-aceac1f0cdad)

here you can see a screenshot of my floorplan and the path for my ecovacs vacuum on the top right room which i took from the ecovacs integration.

the way i have this setup is as follows:

YAML

```
           - name: Set vacuum path
              entities:
                - element: entity-overlay
                  entity: image.schmidt_map
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: |
                  ${entity.attributes.entity_picture} 

```

CSS:

```
#entity-overlay {
  pointer-events: none !important;

  /* Increase contrast and adjust brightness without grayscale or invert */
  filter: brightness(0.5) contrast(8) invert(1) saturate(0);
  mix-blend-mode: multiply;
  opacity: 0.7;
}
```

everything works perfectly except that i have to manually refresh the page to see the updated path.

is there a way for it to refresh automatically without me having to manually refresh?
