### DISCUSSION TITLE
more info for different entity

### DISCUSSION THREAD

**Discussion by pmansvelder** [ExperienceLovelace/ha-floorplan#486] [Q&A] [answered]
I have what seems to be a simple question: in the docs for lovelace (https://www.home-assistant.io/dashboards/actions/) it states that you can use the more-info action with the parameter entity to get more info from a different entity than the one you are clicking on:

> entity string (Optional, default: none)
> 
> Overrides the default entity to show when the action is defined as more-info

When I try to do this in the yaml file for the floorplan:

```
                - entities:
                    - switch.ikea_of_sweden_tradfri_control_outlet_switch_3
                  tap_action:
                    action: more-info
                    entity_id: climate.freya
```
I still just get the info for the main entity (switch.ikea_of_sweden_tradfri_control_outlet_switch_3) , not the one I want (climate.freya). I get no error messages in the log or console.

What am I missing here?

Any help would be appreciated.

Peter Mansvelder

**Comment by OzGav** [comment]
Might not have been implemented in ha-floorplan @exetico ??

**Reply by exetico** [reply, marked as answer]
Possibly. I'll need to check the code, before I'm sure. @pmansvelder fell free to raise it as a possible bug in https://github.com/ExperienceLovelace/ha-floorplan/issues

I'll close it again, if it's due to something else, and follow up in this thread, no matter what.

Please link to this discussion in the issue, too :-)

I can't promise anything about a timeline, but I'll check as soon as I get some time to look at it.

Thanks.

**Reply by exetico** [reply]
If it's still relevant, please do what I've described. I'm marking this as the answer right now.

**Reply by PB45-99** [reply]
Hello :) First of all thanks for all your work to make our Dashboard more beautiful ;)

Does this problem still happens? (Because the diskussion-opener never make a bug report)

```yaml
      - element: wohnzimmer_heizung_rechts
              entity: number.map_wohnzimmer_temperatur_heizung_rechts
              tap_action:
                action: more info
                entity_id: light.flur_deckenlampe
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data:
                  class: '${(entity.state > 18) ? "warm" : "cold"}'
```

The more info part doesn´t work for me. I know, this example makes not really sense. I only use the light entity because its easier to debug.

Tanks, Mili

**Comment by Trzinka** [comment]
```yaml
                - entities:
                    - switch.ikea_of_sweden_tradfri_control_outlet_switch_3
                  tap_action:
                    action: more-info
                    entity_id: climate.freya
```

Is `climate.freya` is the entity correctly named or is it `switch.climate.freya` instead?
