### DISCUSSION TITLE
ERROR loadFloorplanSvg in floorplan-card with home example

### DISCUSSION THREAD

**Discussion by gitmirko** [ExperienceLovelace/ha-floorplan#49] [Q&A] [answered]
Hi,
I'm trying to get the **home example** running. I've installed ha-floorplan through HACS on Home Assistant OS.
I've created a folder under _/config/floorplan-home_ with the following files from the **home example**:
```
/config/home-floorplan/
/config/home-floorplan/light_on.svg
/config/home-floorplan/home.yaml
/config/home-floorplan/home.svg
/config/home-floorplan/light_off.svg
/config/home-floorplan/home.css
/config/home-floorplan/home.lovelace-card.yaml
/config/home-floorplan/home.lovelace-view.yaml
/config/home-floorplan/simulations.yaml
```
And I've tried to include it as a lovelace card with this configuration:
```
  - title: floorplan
    path: floorplan
    panel: true
    badges: []
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          image: /config/home-floorplan/home.svg
          stylesheet: /config/home-floorplan/home.css
          log_level: info
          console_log_level: info
          defaults: null
          hover_action:
            action: hover-info
            tap_action: more-info
          rules:
            - entity: sensor.wohnzimmer_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? "known" : "unknown"}'
            - entity: media_player.sony_bravia_tv
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? "known" : "unknown"}'
```
And this is the error that I'm getting right now:
```
    2/9/2021, 10:11:37 PM ERROR loadFloorplanSvg/<@https://XXX.duckdns.org:8123/hacsfiles/ha-floorplan/floorplan.js:195:4734 l@https://XXX.duckdns.org:8123/hacsfiles/ha-floorplan/floorplan.js:119:1473
    2/9/2021, 10:11:37 PM INFO INIT Floorplan initialized
```
I'm struggling to find a way to fix this problem. Could you please point me in the right direction?

Best regards
Mirko
