### DISCUSSION TITLE
Does defaults work for double_tap_action?

### DISCUSSION THREAD

**Discussion by 42Network** [ExperienceLovelace/ha-floorplan#491] [Q&A] [answered]
I have several rooms for which I want double tap to toggle the lights, so I thought I would just add a default to the existing defaults, like this:
```
defaults:
  hover_action: hover-info
  tap_action: more-info
  double_tap_action:
    action: call-service
    service: homeassistant.toggle
```
However, after reloading my dashboard, double-clicking did not work. If I put the whole double_tap_action section within the rules for each element, it works however. Is this the expected behavior?

Thanks
