### DISCUSSION TITLE
ID Problem

### DISCUSSION THREAD

**Discussion by Trzinka** [ExperienceLovelace/ha-floorplan#496] [Q&A] [answered]
Hi.

I have the following configuration in InkScape:
![InkScape-Elektrika](https://github.com/user-attachments/assets/d6ca2627-9789-4dc3-a861-0954f07891b8)

It doesn't show me the ID in DevTools:
![FP-Elektrika](https://github.com/user-attachments/assets/44c56512-38d0-4cbb-92bf-b8afb78a57c2)

Entity properties:
![DevTools-Elektrika](https://github.com/user-attachments/assets/d6414d15-3e08-4126-969a-c62f1ab937f2)

Configuration in fp.yaml:
```yaml
            - entities:
                - sensor.p1_meter_power_phase_3
                - sensor.p1_meter_power_phase_2
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ? Math.round(entity.state)  + "W" : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: static-temp
              tap_action: false
```

Thank you! Happy holidays and a happy new year.

**Comment by OzGav** [comment]
Have you grouped that element with others?

**Reply by Trzinka** [reply]
Hi OzGav. Thanks for the reply.

If I understand you correctly, I created these two elements in InkScape inside the electrical (elektrika) folder:
![InkScape-Elektrika2](https://github.com/user-attachments/assets/f443bc33-7727-44a0-8fe8-2509a5af6331)

In fp.yaml
```yaml
########################################################
#   Electricity TEXT display
########################################################
            - entities:
                - sensor.tarifi
                - sensor.primerjava_blokov
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state)}
                - service: floorplan.class_set
                  service_data:
                    class: static-temp
              tap_action: false
            - entity: sensor.elektro_network_tariff
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ? Math.round(entity.state) : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: static-temp
              tap_action: false
            - entities:
                - sensor.p1_meter_power_phase_3
                - sensor.p1_meter_power_phase_2
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ? Math.round(entity.state)  + "W" : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: static-temp
              tap_action: false
```

In DevTools I don't see the ID tag for `sensor.p1_meter_power_phase_3` and `sensor.p1_meter_power_phase_2` like the other 3, which show me as I wanted (I still need to finish them in terms of design)
![FP-Elektrika2](https://github.com/user-attachments/assets/bc1d804c-979d-42d8-97c1-a929ed40a5df)

**Reply by OzGav** [reply]
What you see in that first image is the label not necessarily the ID. Click on the following icon to check. I generally make the ID and label the same

![image](https://github.com/user-attachments/assets/ce44d0e9-394b-409b-91a4-ee992ee20ea1)

**Reply by Trzinka** [reply]
The first image in this message shows the ID name. Is it possible that the ID name is too long?

**Reply by Trzinka** [reply]
![InkScape-Elektrika](https://github.com/user-attachments/assets/411e74ff-7df1-4f17-b5ce-814ef6228c3a)

**Comment by Trzinka** [comment, marked as answer]
Apparently the ID name in InkScape was really too long. Now that I shortened it, it works.


![InkScape-Elektrika3](https://github.com/user-attachments/assets/a0db4951-78fa-4fef-95d3-14ca35e8a729)

![FP-Elektrika3](https://github.com/user-attachments/assets/902292a4-0d0b-46f1-bedd-9566872bcd5b)


fp.yaml
```yaml
            - entity: sensor.p1_meter_power_phase_3
              element: faza_c
              state_action:
              - service: floorplan.text_set
                service_data: >-
                  ${(entity.state !== undefined) ? Math.round(entity.state)  + "W" : "unknown"}
              - service: floorplan.class_set
                service_data:
                  class: static-temp
              tap_action: false
            - entity: sensor.p1_meter_power_phase_2
              element: faza_b
              state_action:
              - service: floorplan.text_set
                service_data: >-
                  ${(entity.state !== undefined) ? Math.round(entity.state)  + "W" : "unknown"}
              - service: floorplan.class_set
                service_data:
                  class: static-temp
              tap_action: false
```
