### DISCUSSION TITLE
Control two different entities with tap and double tap.

### DISCUSSION THREAD

**Discussion by chrkov** [ExperienceLovelace/ha-floorplan#497] [Q&A] [answered]
I have several ceiling fans that have a light in them also.  I wanted to single tap to toggle the light and double tap to toggle the fan.   

entities:  (these work just fine)
light.ceiling_fan is for the fan
light.light_4 is the light in the fan

Here is my rule.
```
            - element: image895
              entity: light.ceiling_fan
              tap_action:
                action: call-service
                service: light.toggle
                data:
                  entity_id: light.light_4
              double_tap_action: toggle
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: >-
                  ${(entity.attributes.brightness > 0 &&
                  entity.attributes.brightness <= 82) ? "spin-low" : ""}
                  ${(entity.attributes.brightness >= 83 &&
                  entity.attributes.brightness <= 170) ? "spin-med" : ""}
                  ${(entity.attributes.brightness >= 171) ? "spin-high" : ""}
```
double tap works as expected and toggles the fan (entity light.ceiling_fan).  But single tap still toggles the fan instead of entity light.light_4.   Is this not supported?
