### DISCUSSION TITLE
I can't manipulate the display-attribute via service floorplan.style_set and javascript

### DISCUSSION THREAD

**Discussion by perlchamp** [ExperienceLovelace/ha-floorplan#498] [General]
Hello out there,
to help, you need to be able to use Inkscape.
If you are really interested in helping then please follow my steps:
1. Open file doku_04.svg (attached) in Inkscape, CTRL + SHIFT + L to open the layer and objects settings.
2. Open the 'OVERLAYED' layer and click on the 'closed eye' symbol to the right of the entry 'binary_sensor.esp_8266_ip59_tuer_offen_pin' -> an open front door should now be displayed in the floor plan. Clicking again - now on the open eye - will undo this display and vice versa.
2. If necessary, mark the entry 'binary_sensor.esp_8266_ip59_tuer_offen_pin' so that a dashed frame with arrows can be seen in the floor plan.
3. Now call up the internal xml editor using CTRL + SHIFT + x. The line in question should already be marked after opening, and the 'style' attribute should be visible in the right xml editor window.
4. Make the xml editor window as small as possible and move it to the left so that both the xml editor and the front door in the floor plan as well as the right sidebar can be seen.
5. Again to the right of the entry 'binary_sensor.esp_8266_ip59_tuer_offen_pin' click on the 'closed eye' symbol -> in the xml editor the value of the 'style' attribute changes at the same time from 'display:none' to 'display:inline' and vice versa -> nice!

You can assume that I have configured the ha-floorplan card correctly, i.e. I have an empty css-file, a separated yaml configuration file called doku.yaml, the contents of which are listed below:

```
image: /local/doku/doku_03.svg
stylesheet: /local/doku/doku.css
cache: true
log_level: info
console_log_level: info
defaults:
  hover_action: hover info
  tap_action: more info
rules:
- entity: binary_sensor.esp_8266_ip59_door_open_pin
  element: binary_sensor.esp_8266_ip59_door_open_pin
  state_action:
    - service: floorplan.style_set
      service_data:
      style: |
        display: ${entity.state === 'ON' ? 'inline' : 'none'};

```
You are also very welcome to check all things relevant to ha-floorplan in the svg file using the xml editor. These should be fine.

PROBLEM:
It doesn't work!
My intention has been recognized? I want the red door to be displayed when the sensor status is 'on'.
WHAT is wrong (with the Javascript code)? 
Of course, my doku.yaml contains even more entries - if you want to see the complete file, just request it.
So I have some entities with temp- and air-values ​​as entries. These values ​​no longer appear when I add the javascript line.

[EDIT]
Are you able to upload the attached svg-file? If not, what can i do to make it (as download) possible?
[/edit]
Thank you very much in advance!

So long
Pc
![doku_04](https://github.com/user-attachments/assets/fe11e310-6e6f-48ea-98d5-86efab4134cd)
