### DISCUSSION TITLE
Conditional color on text

### DISCUSSION THREAD

**Discussion by jonirgens** [ExperienceLovelace/ha-floorplan#500] [Q&A] [answered]
I need help to set the color of the temperature depending on the value of an attribute.
Thanks for a great floorplan component. I have that up and running with control of lights and showing the temperature as shown in your examples. Great.
I want to change the color of the temperature depending on whether the floor heating is on or not.

I have included the temperatur as described like this:
```
name: Temperature
              entities:
                - climate.kontor
                - climate.entre
                - climate.fjernsynsstue
                - climate.grovkokken
                - climate.kokken
                - climate.lejlighed_badevaerelse
                - climate.lejlighed_kokken
                - climate.pejsestue
                - climate.spisestue
                - climate.stue_lejlighed
              state_action:
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ?
                    entity.attributes.current_temperature + "°" : "unknown"}
                - service: floorplan.class_set
                  service_data:
                    class: static-temp
```
And each entity has an attribute hvac_action showing 'heating' or 'idle' (coming from my Salus system).

How do I change the color of the shown temperature depending on the hvac_action attribute?
I have tried to find inspiration from others - but I can not find any solution to this.

**Comment by OzGav** [comment]
This doesn’t use an attribute but you should get the idea

```
                - service: floorplan.class_set
                  service_data: |
                    >
                      var uv = parseFloat(entity.state.replace("°", "")); 
                      if (uv < 3) return "uv-low"; 
                      else if (uv < 8) return "uv-medium"; 
                      else return "uv-high";
```

and here is some code which shows how to return something based on state

```
              state_action:
                - service: floorplan.image_set
                  service_data: |
                    >
                    var imageName = '';
                    switch (entity.state) {
                      case 'PumpOff':
                        imageName = 'pool_heating_off2';
                        break;
                      case 'Auto':
                        imageName = 'pool_heating_auto';
                        break;
                      case 'AutoOn':
                        imageName = 'pool_heating_autoon';
                        break;
                      case 'PumpOn': 
                        imageName = 'pool_heating_on';
                        break;
                    }
                    return '/local/floorplan/images/' + imageName + '.svg?v=2';
                 
```

**Reply by jonirgens** [reply]
Thanks. Very useful for making the if statement. That part should be straight forward now.
But how do I set the color of the text? I assume I need to use the style_set service, but how do I use that to set the color?
And sorry for stupid question, I am only 1-2 months into Home Assistant and I would not call myself a developer - so I am on a steep learning curve here. But is the syntax you apply above in the service_data section Javascript? Which is different from the Jinja syntax used in Templates, right?

**Reply by exetico** [reply]
Hi,

Have you checked our documentation, the live examples and my videos on YouTube?

I know the answer is easy to simply provide here, but in other for you to understand ha-floorplan, you need to spend an hour or two, in other to understand each service and the relationship between the browser, ha-floorplan, a dedicated CSS file, and your SVG file 🙂.

Class set will be possible to use, if you provide a CSS file.

Style set will be possible to use, if you provide `color: #FFFFFF` or similar, and target a given element in your SVG file.

I'll highly recommend you to spend a few hours on YouTube:
https://youtube.com/playlist?list=PL5xKVw-BInX1phV-Tnjznwd2YG5mEOvWL&si=Ee_TjSx34HdgYZmR

After watching the videos, kindly let me know if you find yourself in a situation, with questions to specific topics or solutions. I'll try and remember them, and mention them in upcoming videos.

**Reply by jonirgens** [reply]
Thanks for your answer.
I have watched those videos several times, and I must admist they are very advanced for me. I slowly understand more and more everytime I see them. They have been very very usefull - but for a non-developer I would prefer them to be more simple, explaining each step in more details with more simple examples.

I have tried adding the color statement into the CCS file, but that did not work. Then I tried to use the fill option instead like this:
```
.static-temp {
   fill:  #FF0000 !important; 
 }
 ```
(copied from my CSS file)

That also does not work. But when I open the dashboard and press inspect on the text I can see that there is a fill: #ffffff; from element.style which overwrites the fill in .static-temp. If I uncheck the fill:#ffffff from element.style in the brower the text becomes red (#FF0000 is red).

How do I overwrite the white fill color from element.style?

Then I tried using the style_set instead like this (inspired from your videos):
```
 - service: floorplan.style_set
    service_data:
       style: fill:#FF0000 !Important
```
but the text is still white.

**Reply by exetico** [reply]
Answer can be found here: https://github.com/ExperienceLovelace/ha-floorplan/discussions/500#discussioncomment-11776302

**Comment by exetico** [comment, marked as answer]
_Answer to the initial question, and follow up to question: https://github.com/ExperienceLovelace/ha-floorplan/discussions/500#discussioncomment-11775586_

That's great to hear. I understand that it can be a bit too much, in the first phase of managing XML, CSS, HTML and other things on top of that.

This example shows a way to set a given color: https://experiencelovelace.github.io/ha-floorplan/docs/example-remote/

The use of `!important` will do the job. Notice the lower-case `i`, too. In your code, it's a upper-case `I`. Quite a few things is case-sensitive in JavaScript, and CSS, too.

I'm sure you'll be doing great in a few days 😎!

Another way of setting the style, is simply by using `fill:#FF0000!important` as the style_set value.

Here's one way of using style_set:

```yaml
        state_action:
          action: call-service
          service: floorplan.style_set
          service_data:
            style: |
              fill: ${ entity.state === "on" ? "#F9D27C" : "#7CB1F9" };
              transition: ${ entity.state === "off" ? "fill 5s ease" : "" };
```

Doing it even more simple with:

```yaml
      state_action:
        service: floorplan.style_set
        service_data: 'fill:#FF0000!important'
```


It's possible to make it way more complex by using JavaScript, to get related information about the entity, or other entities.

```yaml
      state_action:
        - action: call-service
          service: floorplan.style_set
          service_data: |
            >
              var elements = [
                `${entity.entity_id}`,
                `${entity.entity_id}.gradient_color_0`,
              ];

              var color = 'rgb(0, 0, 0)';
              var opacity = 0;

              if (entity.state === 'on') {
                if (entity.attributes.color_temp) {
                  var rgb = util.color.miredToRGB(entity.attributes.color_temp);
                  color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                  opacity = 1;
                }
                else if (entity.attributes.rgb_color) {
                  var rgb = entity.attributes.rgb_color;
                  color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                  opacity = 1;
                }
              }
              var style = `fill: ${color}; stop-color: ${color}; stop-opacity: ${opacity};`;

              return {
                elements: elements,
                style: style,
              };
```

It will work for other actions than `state_action`, ofc.

Let me know how it goes! Also, it's great that you're using the Inspect-tool already. That will surely help you with the next couple of issues.

_And lastly, a tip which could save you a bit of time_:
Sometimes a "fill" on a given SVG element, will not fill it. If you're finding yourself in a situation where it's not possible to color a given thing with `fill`, try and color it in InkScape first, hereafter take a look at what's changed in the SVG code.

**Reply by jonirgens** [reply]
Thanks - very good examples. I am learning...
I applied the very simple style_set example you made above. That now works as good (or bad) as doing it in the class_set. The white fill from element.style still takes priority. Also when changing to a small "i" in important.

I checked the text in Inkscape and the text has a white fill in there, I can see that also goes into the SVG file - so I assume that is where the white fill in element.style comes from.

I just can't get the fill from class_set or style_set to overrule it (unless I deactive the element.style white fill under inspect in the browser).

Then I tried to set the color of the text in Inkscape to "undefined" and that did the trick. Now the text is red in the dashboard based on the value from class_set or style_set :-)

Problem fixed!

**Reply by exetico** [reply]
It's fixed; Great! But you need to pick up what you've just experinced.

I guess you've faced a problem with the priority of the CSS styling.

Would you mind sharing the CSS you saw, before you fixed it by removing the fill?

![image](https://github.com/user-attachments/assets/45b74a6b-aed3-4e98-bcb9-bd3d9d71d83e)
_Example of the Inspect tool, where you're able to see both the CSS rules, and part of the SVG file, in the HTML source-tree._

1) Did the original fill from the InkScape use "!important", too? That's not expected, normally. "!important" **should** have won the "priority game"
2) It's great that you're using classes - it's the best way of keeping track of things. Personally I try and use "light-{state}" or similar, to keep track on/off styling of every light, or similar. But, to be honest, I'v not found time to make a proper floorplan in our current space, after we've moved away from the floorplan you can find in our documentation.

Also, I understand that you've watched the videos. That's great! This video do target most of the things we're talking about right now:
https://www.youtube.com/watch?v=oqO4Vx6U1Mo&list=PL5xKVw-BInX1phV-Tnjznwd2YG5mEOvWL

**Reply by jonirgens** [reply]
Sure - below you can see the SVG file (with a white fill from InkScape) in the green box and the element.stye to the right. No "!important" added to the fill from InkScape.

![image](https://github.com/user-attachments/assets/c3e8698c-8b4d-40df-96a0-5882a2dc2a24)

You can see the red fill being strikedout under "Inherited from text#climate.kontor..."

**Reply by jonirgens** [reply]
Looks like this when the white fill is removed in InkScape

![image](https://github.com/user-attachments/assets/67c4db4a-5907-4cdc-b81d-ab17ba48b1fd)

**Reply by exetico** [reply]
Adjust your CSS, so it's like:

```
.static-temp tspan{
   fill: #FF0000!important; 
 }
```

Or, use multiple selectors:

```
.static-temp, .static-temp tspan {
   fill: #FF0000!important; 
 }
```
That should overwrite the styling of the color defined in Inkscape 😄 .

Adding a more precise CSS query does also impact the priority of a given CSS style, like the `fill`.

**Reply by jonirgens** [reply]
yes, that works. Now the text with white fill in InkSpace is red in the dashboard. Thanks!
What does tspan do?

**Reply by exetico** [reply]
You're welcome :) 

That's [the element to define a text](https://www.w3schools.com/graphics/svg_text.asp). SVG does have it's own elements, that are not identical with regular HTML. Same often goes for things like coloring, sizing, scaling and similar things.

I use the text option sometime, It depends on what you're doing. ha-floorplan will sometime break you're lines into multiple tspans, in some cases where you're using new-line characters. But I guess that's a tip for another day 😄 . More details about a text ending up as a tspan due to linebreaks, can be found here: https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/1.0.36

Here's one example with "text":
<img width="1451" alt="image" src="https://github.com/user-attachments/assets/90f6a448-abe9-484b-b80a-23ca27400c10" />
<img width="651" alt="image" src="https://github.com/user-attachments/assets/69b9f975-7709-4440-9b49-8fdba4f10d3e" />


Wrapping tspans around tspans can also be helpful in some scenarios where you're setting position, and other styles, too. But it doesn't look that clean, for sure.

**Comment by jonirgens** [comment]
For other readers - this is the code I ended up with:
```
          name: Temperature
              entities:
                - climate.kontor
                - climate.entre
                - climate.fjernsynsstue
                - climate.grovkokken
                - climate.kokken
                - climate.lejlighed_badevaerelse
                - climate.lejlighed_kokken
                - climate.pejsestue
                - climate.spisestue
                - climate.stue_lejlighed
              state_action:
                - service: floorplan.class_set
                  service_data: |
                    >
                      if (entity.attributes.hvac_action == 'heating') return 'heating-on';
                      else return 'heating-off';
                - service: floorplan.text_set
                  service_data: >-
                    ${(entity.state !== undefined) ?
                    entity.attributes.current_temperature + "°" : "unknown"}
```
with this in my CSS file:
```
/* Color on Temperature text */

.heating-on tspan{
  fill:  orangered !important; 
}

.heating-off tspan{
  fill:  green !important; 
}
```
This is the result (floorplan drawing still WIP :-) ) - orange showing where the floorheating is on
![image](https://github.com/user-attachments/assets/9dc708e2-86f8-4c5d-be0a-d9f9243614b5)
