### DISCUSSION TITLE
Add additional class to elements

### DISCUSSION THREAD

**Discussion by DeathByDisco** [ExperienceLovelace/ha-floorplan#502] [Q&A] [answered]
Hello everyone, I need a bit of help.
In my floorplan, I have animated my media elements (paths).
When the TV, speakers, or other media are on, I use floorplan.class.set to add the state as class “on” to these elements which I then use to trigger the animation via CSS. The path of these elements then pulses.

`   
 - entity: media_player.samsung_living_room
    tap_action: more-info
    state_action:
    action: call-service
    service: floorplan.class_set
    service_data: media-player-${entity.state}
`
result = class="media-player-on"

Now, I would like to be able to disable the animation with a button, even if the devices are still on.

Is it possible to add an additional class to the existing “on” class when I toggle a helper button?

Helper - Switch - Toggle —> Add an additional class to my media elements class. e.g "animation-off"
to get a result like class="media-player-on animation-off"

Is that possible ? 
Or is there a better solution available ?

**Comment by OzGav** [comment]
Why do you want to add an additional class? Just change the class with your button. Have you tried it?

**Comment by DeathByDisco** [comment]
Thank you for your suggestion :) 

I’ve tried implementing the functionality where toggling a button changes the class of some elements, but I’m facing an issue changing the class back when i toggle again. 
Here's the behavior I’m observing:

1.Initial State:
When I turn my TV on, the class "on" is dynamically added to the element using the code I shared earlier.
Result: The element has the following class: class="media-player-on".

2.Creating the "Animation Off" Button:
I created a helper button named "Animation Off" - input_boolean.animation_off
The button uses the following code to add the class animation-off to my media elements:

```
  - entity: input_boolean.animation_off
    state_action:
      service: floorplan.class_set
      service_data:
        elements: 
          - media_player.samsung_living_room
          - media_player.samsung_kitchen
          - media_player.samsung_bath_room
        class: animation-off
```

3.Expected Behavior:
Turning the TV On:
The class changes to "media-player-on"  triggering the CSS animation. WORKS FINE

Toggling the "Animation Off" Button (ON):
The class "media-player-on" gets replaced with the class "animation-off", stopping the CSS animation. WORKS FINE 

Toggling the "Animation Off" Button (OFF):
Nothing happens the class "animation-off" stays in the source code. 

THE GOAL IS 
The class "animation-off" gets removed, and the class gets changed back to "media-player-on" DOES NOT WORK

**Reply by OzGav** [reply]
Please use the <> button to properly format your code so we can see if there is an indetation problem. Have you tried a more simple version as a proof of concept? 

edit: Sorry I read your post more carefully. I think you need this:

```
entity: input_boolean.animation_off
element: media_player.samsung_living_room
state_action:
  service: floorplan.class_set
  service_data:
    class: '${entity.state == "on" ? "animation-off'" : "media-player-on"}''
```

**Reply by DeathByDisco** [reply]
I changed the code a bit and the exchange of the class works well for my elements BUT lets say my other TVS are off and i toggle the button again to get the animation working again the class "media-player-on" gets also added to the devices which are turned off and then they start to animate. 

```
  - entity: input_boolean.animation_off
    state_action:
      service: floorplan.class_set
      service_data:
        elements: 
          - media_player.samsung_living_room
          - media_player.samsung_kitchen
          - media_player.samsung_bath_room
        class: >-
          ${entity.state == "on" ? "animation-off" : "media-player-on"}
```

edit: is it possible to filter the elements list to apply the class changes only to elements with the status "on" ?
