### DISCUSSION TITLE
SVG elements don't work after changing floorplan

### DISCUSSION THREAD

**Discussion by weemaba999** [ExperienceLovelace/ha-floorplan#507] [Q&A]
Hi,

I started off with my floorplan being an png file I exported in resolution 960x540. After setting up that png file in Inkscape, I started implementing my different 'elements'. Everything went well, my motion.gang element highlighted when there was motion in the hall.

Afterwards, I decided to expert that same file as png in a higher resolution. I created the svg elements exactly the same way as I did in the former floorplan, using the same ID & same label, but for some reason, my 'blink' & opacity doesn't work anymore. None of the elements I created work anymore.

By uploading my old svg, everything works just fine, the new one doesn't

I reduced my html & css file in order to see if I can get ONE element working, but it still doesn't?

My Yaml:

```
views:
  - title: Floorplan
    path: floorplan
    theme: Google Dark Theme
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config:
          image: /local/house/floorplan.svg
          cache: true
          stylesheet: /local/house/floorplan.css
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:
            - name: Security
              entities:
                - entity: binary_sensor.hue_motion_sensor_1_motion_2
                  element: motion.gang
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "detection-on" : "detection-off"}'
```

Here's my CSS file:

```
#floorplan  {
  padding: 10px;
}

/* #floorplan svg{
  height: 100vh!important;
} */

svg tspan {
  fill: var(--primary-text-color);
}



/* SVG shapes */

svg, svg * {
  vector-effect: non-scaling-stroke !important;
  pointer-events: all !important;
}



/* Hover over */
.ha-entity:hover {
  stroke: #03A9F4 !important;
  stroke-width: 1px !important;
  stroke-opacity: 1 !important;
}

/* Security Check */

path[id*="motion."].detection-on {
  fill: red !important;
  opacity: 1 ;
  animation: blink 2s linear infinite;
}

path[id*="motion."].detection-off {
  fill: green !important;
  opacity: 1 ;
  animation: blink 2s linear infinite;
}


@keyframes blink {
    50% { opacity: 0; }
}
```

And this is how my element looks like:

![image](https://github.com/user-attachments/assets/dba8a84e-5b2d-47f4-a418-c010c7de8b69)

Does anyone have any clue. Seems like my svg elements have a hidden path and are indexed and that by using my new svg image, it doesn't find the svg in the background

Thanks a lot !

Kr,

Bart
