### DISCUSSION TITLE
Toggle Camera with same element combined with binary_sensor for motion ?

### DISCUSSION THREAD

**Discussion by weemaba999** [ExperienceLovelace/ha-floorplan#510] [General]
Hi,

I want my svg-element of the camera turn red & blink when there's motion. At the same time, I want to be able to press that element to have live stream of the camera. Is that 'uberhaupt' possible ?

![image](https://github.com/user-attachments/assets/a423a012-60dc-41b4-a317-5d9e33c74d07)

```
- name: Cameras
              entities:
                - element: camera.front
                  entity: binary_sensor.g4_pro_motion
                  state_action:
                    service: floorplan.class_set
                    service_data: '${(entity.state === "on") ? "motion-on" : "motion-off"}'
                - element: camera.front
                  entity: camera.g4_pro_high
                  tap_action:
                    action: call-service
                    service: browser_mod.popup
                    service_data:
                      title: Camera Front
                      card:
                        type: picture-entity
                        entity: camera.g4_pro_high
                        camera_view: live

```

I'm a fast learner, but need the help in the beginning to understand the way of logics,

Thanks in advance !

Kr,

Bart

**Comment by OzGav** [comment]
Having the entity in the second rule doesn't make sense as you do nothing if it changes state. I would expect you just want this:

            - name: Cameras
              entities:
                - element: camera.front
                  entity: binary_sensor.g4_pro_motion
                  state_action:
                    service: floorplan.class_set
                    service_data: '${(entity.state === "on") ? "motion-on" : "motion-off"}'
                  tap_action:
                    action: call-service
                    service: browser_mod.popup
                    service_data:
                      title: Camera Front
                      card:
                        type: picture-entity
                        entity: camera.g4_pro_high
                        camera_view: live

**Reply by weemaba999** [reply]
Thanks for your reaction @OzGav . 
But when I apply this, I get the window of my binary_sensor.g4_pro_motion instead of the picture-entity and the live feed of my camera.

Kr,

Bart

**Reply by OzGav** [reply]
I am not sure if that syntax for browser mod will work as it is different to what I use. Try something like this:

```
          tap_action: 
            action: fire-dom-event
            browser_mod:
              command: call-service
              service: browser_mod.popup
              data:
                  title: Camera Front
                  card:
                    type: picture-entity
                    entity: camera.g4_pro_high
                    camera_view: live
```
