### DISCUSSION TITLE
View Browser vs Ipad

### DISCUSSION THREAD

**Discussion by weemaba999** [ExperienceLovelace/ha-floorplan#512] [General]
Hi, 

I currently have my dashboard as follows:

![image](https://github.com/user-attachments/assets/6ed93def-bb43-4a47-a3d9-af8c46c8a3f9)

But when I open that same dashboard on the companion app on my iPad 12", I have the ha-floorplan covered just half of the size of my screen (top-bottom). Is there a way to stretch or make the HA-floorplan (which is in the main panel) go to the bottom of my iPad ? Eventually without changing the SVG (currently 1920 x 1080) ?

Thanks a lot !

Kr,

Bart

**Comment by OzGav** [comment]
You don’t show the image on the iPad so can’t be sure but you can’t stretch the image. If the aspect ratio changes you will have black bars somewhere. Just make sure you have full height set to true

```
views:
  - panel: true
    cards:
      full_height: true
```

**Comment by weemaba999** [comment]
![WhatsApp Image 2025-02-19 at 00 00 43](https://github.com/user-attachments/assets/030e229a-8d2c-4fd7-a229-5282d51d2942)

```
kiosk_mode:
  non-admin_settings:
    kiosk: true
    ignore_entity_settings: true
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
views:
  - path: floorplan
    title: ''
    theme: Google Dark Theme
    type: sidebar
    cards:
      - type: entities
        entities:
          - type: custom:paper-buttons-row
            buttons:
              - entity: input_boolean.2ndfloor
                layout: icon
                icon: mdi:home-floor-2
                name: false
              - entity: input_select.cards
                icon: mdi:calendar
                name: false
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: calendar
              - entity: input_select.cards
                icon: mdi:speaker
                name: false
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: music
              - entity: input_select.cards
                icon: mdi:power-plug
                name: false
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: devices
              - entity: input_select.cards
                icon: mdi:cctv
                name: false
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: cameras
              - entity: input_select.cards
                name: false
                icon: mdi:cloud
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: weather
              - entity: input_select.cards
                name: false
                icon: mdi:select-multiple
                tap_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.cards
                    option: settings
        state_color: true
        view_layout:
          position: main
      - type: custom:floorplan-card
        config:
          image: /local/house/floorplan.svg
          cache: true
          stylesheet: /local/house/floorplan.css
          full-height: true
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:

```
