### DISCUSSION TITLE
Mobile Notification is not working

### DISCUSSION THREAD

**Discussion by nikos445** [ExperienceLovelace/ha-floorplan#515] [Bugs]
Hello,
I wanted to point that these kind of notifications/actions/commands for Mobile Apps are not working:

```
      - action: notify.mobile_app_<your_device_id_here>
        data:
          message: "command_webview"
          data:
            command: "/lovelace/settings"
```
            
anyone found a workaround?

I tried also this:
```

    - action: call-service
      service: notify.mobile_app_xxx
      service_data:
        data: |
          > return { command: "/lovelace/settings" }
        message: "command_webview"

```
but it didn't work.

![image](https://github.com/user-attachments/assets/6f0bb997-14bd-4937-8fb4-e0fe6d7c1940)
