### DISCUSSION TITLE
Unable to use element object in service_data for image_set service

### DISCUSSION THREAD

**Discussion by garyjlo** [ExperienceLovelace/ha-floorplan#518] [Bugs] [answered]
I was trying to set a rule that, based on an HA weather entity, I could set multiple elements in my SVG floorplan, in this case, a text_set for the temperature and image_set an icon for the weather condition.
```
    - entity: weather.demo_weather_north
      state_action:
        - action: call-service
          service: floorplan.text_set
          service_data:
            element: sensor.weather_temperature
            shift_y_axis: 2em
            text: ${ entity.attributes.temperature }${ entity.attributes.temperature_unit }
        - action: call-service
          service: floorplan.image_set
          service_data:
            element: sensor.weather_condition
            image: /local/icons/weather/${ entity.state }.svg
```
I did a lot of trial and error and could not get it to work.

Eventually I found a successful workaround by splitting it into two rules, with the image_set one moving the element field up to the top level, out of service_data:
```
    - entity: weather.demo_weather_north
      state_action:
          action: call-service
          service: floorplan.text_set
          service_data:
            element: sensor.weather_temperature
            shift_y_axis: 2em
            text: ${ entity.attributes.temperature }${ entity.attributes.temperature_unit }

    - entity: weather.demo_weather_north
      element: sensor.weather_condition  #<-- element moved out of service_data
      state_action:
        action: call-service
        service: floorplan.image_set
        service_data:
          image: /local/icons/weather/${ entity.state }.svg
```

Is this a bug? The documentation lists element and elements as valid objects for all service_data sections.

**Comment by exetico** [comment]
Hi,

Could you please let me know where you find the reference, pointing you to add `element` as a service_data key?

```yaml
    - entity: weather.demo_weather_north
      state_action:
        - action: call-service
          service: floorplan.text_set
          service_data:
            element: sensor.weather_temperature ⬅️ I'm asking about this
            shift_y_axis: 2em
            text: ${ entity.attributes.temperature }${ entity.attributes.temperature_unit }
        - action: call-service
          service: floorplan.image_set
          service_data:
            element: sensor.weather_condition
            image: /local/icons/weather/${ entity.state }.svg
```

The element reference neds to be at the top of the rule, in other words, at the same level, as you define `state_action`, `tap_action` and so on 😄 .

If you've found a broken example, I'd be more than happy to correct that, or look into any misleading information.

_Maybe I even remember wrongly. If it was meant to work this way, and it's now not working anymore, I'll take a look at that._
