### DISCUSSION TITLE
How to apply css class the right way?

### DISCUSSION THREAD

**Discussion by gitmirko** [ExperienceLovelace/ha-floorplan#52] [Q&A] [answered]
Hi,
I'm not sure which way I should apply style classes in the rules section.

This works:
```
          rules:
            - entities:
                - light.esstisch
                - light.vorraum_treppe
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
```
But I would prefer this way (at least I think) but this doesn't work:
```
          rules:
            - entities:
                - light.esstisch
                - light.vorraum_treppe
              states:
                - state: 'on'
                  class: light-on
                - state: 'off'
                  class: light-off
                - state: unavailable
                  class: light-unavailable
              propagate: true
```
I've just copied it from [here](https://github.com/DubhAd/Home-AssistantConfig/tree/live/www/floorplan/config/home). What does **propagate: true** even do? :)

Best regards
Mirko
