### DISCUSSION TITLE
What a shame --- which difference the day makes

### DISCUSSION THREAD

**Discussion by perlchamp** [ExperienceLovelace/ha-floorplan#537] [General]
Hi everybody out there,
first: i'm still beginner, so i don't have the real overview, so this is why i'm still asking...

I've created a YAML-based floorplan-dashboard. Everything is working well. But i did some things differently as the maintainer did, so my question now is, whether this would cause some errors, or whether i can use this by going this way.

It's all about splitting yaml-code. 
Therefor the folder 'rules' was created in the same folder, where the floorplan configuration file is placed. The reference to this folder works.
This is the content of the floorplan configuration file (only one rule, because i want to keep it simple for you) :
```
image: /local/ha-floorplan/floorplan-01.svg
stylesheet: /local/ha-floorplan/floorplan.css
cache: false
log_level: info
console_log_level: info
defaults:
  hover_action: hover-info
  tap_action: more-info
rules:
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
```

That's what the maintainer said (last line):
configuration file:
```
image: /local/ha-floorplan/floorplan-01.svg
stylesheet: /local/ha-floorplan/floorplan.css
cache: false
log_level: info
console_log_level: info
defaults:
  hover_action: hover-info
  tap_action: more-info
rules: !include_dir_list rules/
```

And he said: one file for only one rule. That would be the content of his rule-yaml-file:
```
name: Wetter
element: weather.forecast_home
entities:
  - weather.forecast_home
state_action:
  - service: floorplan.text_set
    service_data: '${entity.state ? Math.round(entity.state * 10) / 10 + "°" : "unknown"}'
```
I did not understand, why this is different to the usual way. The usual way (my knowledge) is to set an !include-statement and copy(cut) the rules-section and paste it in an empty rule-file, done!. That's the way i did it with all other breaks and they still work. And this is what HA recommends.
I have nearly 60 rules. Why must i...

1. put one rule in one file
2. change the content completely ('throw' an eye on my rule file below for compairing)

So i did try the following:
configuration-file (last line) :
```
image: /local/ha-floorplan/floorplan-01.svg
stylesheet: /local/ha-floorplan/floorplan.css
cache: false
log_level: info
console_log_level: info
defaults:
  hover_action: hover-info
  tap_action: more-info
rules: !include_dir_merge_list rules/  ####dir_merge_list, not dir_list
```
rule file (there you can put in MORE than one rule)
```
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
```
I haven't change the rule content, no key 'name', no key 'entities' (why 'entities:'? there is only one rule per file, so why not 'entity' ?). 
That's very confusing and annoying (like the whole documentation is). 

And ;-) ... :
**The difference is, what the day makes ;-).** This has been done in _2 minutes_ (60 rules !)
My way is working, i didn't have to change anything. 

BUT:
my question now is: is this ok or will this force some errors in the future?
Who can answer this question really well?

Many thanks in advance !

So long
Pc
