### DISCUSSION TITLE
Possible Bug?

### DISCUSSION THREAD

**Discussion by OzGav** [ExperienceLovelace/ha-floorplan#54] [Q&A] [answered]
Chrome devtools says I am running version 1.0.17

Everything was working OK. However after MUCH trial and error if I have either of the following in my ui-lovelace

```
            - entities:
                - binary_sensor.rumpus_light_on
              name: Virtual Lights
              state_action:
                service: floorplan.class_set
                service_data: 
                  class: '${(entity.state === "on") ? "light-on" : "light-off"}'
                  
            - entities:
                - sensor.ultrasonic_sensor_2
              name: Tank Quantity Text
              state_action:
                service: floorplan.text_set
                service_data: '${entity.state != "unavailable" ? Math.ceil((2.2 - (entity.state - 0.17)) / 2.2 * 100) + "%" : "UNK %"}'
```

then I get this error:

```
floorplan.js?v=14:137 Uncaught (in promise) TypeError: Cannot read property 'svgElement' of undefined
    at HTMLElement.callFloorplanService (floorplan.js?v=14:137)
    at HTMLElement.callService (floorplan.js?v=14:137)
    at HTMLElement.handleActions (floorplan.js?v=14:137)
    at HTMLElement.<anonymous> (floorplan.js?v=14:137)
    at Generator.next (<anonymous>)
    at floorplan.js?v=14:61
    at new Promise (<anonymous>)
    at v (floorplan.js?v=14:61)
    at HTMLElement.handleEntity (floorplan.js?v=14:137)
    at HTMLElement.<anonymous> (floorplan.js?v=14:137)
```

I tried to rollback to 1.0.14 but nothing I tried had the version label change so I am not sure if that was successful. I have rebooted with 1.0.17 again. 

Note that those two excerpts from my ui-lovelace.yaml were from two different floorplans (I run three in fact). If I remove those everything seems to be working OK. 

Ideas?
