### DISCUSSION TITLE
Unable to get floorplan to render

### DISCUSSION THREAD

**Discussion by lightingghost** [ExperienceLovelace/ha-floorplan#557] [Q&A] [answered]
I just tried to follow the video in

 https://github.com/exetico/Home-Assistant_Attachments-for-YouTube/blob/main/2_2_Create-your-own-floorplan-in-Inkscape-and-ha-floorplan-logics/

I copied the filed to my home assistant server and using the following yaml for config

```
title: Modern Floorplan
views:
  - title: My Modern Floorplan
    path: floorplan
    theme: Home Assistant
    panel: true
    type: panel
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          image: /config/www/floorplan/home_modern.svg
          stylesheet: /config/www/floorplan/home_modern.css
          rules:
            - element: light-restroom-primary
              entity: light.bedroom_light
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: entitystate-${entity.state}
              tap_action:
                action: call-service
                service: homeassistant.toggle
        full_height: true
        type: custom:floorplan-card
```

However, the console showed error of 
```
floorplan.js?hacstag=188323494110:54 4/14/2025, 11:06:57 PM WARNING CONFIG Cannot find element 'light-restroom-primary' in SVG file
```

and only a home assistant logo was rendered. I checked the SVG file, `light-restroom-primary was indeed in the file.

From the network, `home_modern.css` showed status OK

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/9a12421a-6554-47d4-a70a-04766dba1d87" />
Any help will be appreciated.
