### DISCUSSION TITLE
Icons moving once config added

### DISCUSSION THREAD

**Discussion by instakill-sec** [ExperienceLovelace/ha-floorplan#57] [Q&A] [answered]
I am having an issue where after i create my SVG and add a config to one of the lamps, it moves the icon to the top left and makes it larger (seems to do this with any of the icons). I can not work out why it is doing it.
This is a screenshot of my SVG in inkspace
![image](https://user-images.githubusercontent.com/55617956/109433515-d1cb1e00-7a64-11eb-82c3-a50f597faf8d.png)
And this is it within HA once i add code to the lamp from the bottom right room
![image](https://user-images.githubusercontent.com/55617956/109433538-f8895480-7a64-11eb-8c17-045bcf5fb4d2.png)
This is the config i have created:
```
type: 'custom:floorplan-card'
config:
  image: /local/floorplan/home/floorplan.svg
  stylesheet: /local/floorplan/home/floorplan.css
  log_level: info
  console_log_level: info
  full_height: true
  defaults:
    hover_action: hover-info
    tap_action: more-info
  rules:
    - entities:
        - light.ac_lamp
      state_action:
        action: call-service
        service: floorplan.image_set
        service_data: '/local/floorplan/lamp_${entity.state}.svg'
      tap_action: toggle
```
This is a zip of my SVG's and the css
[hafloorplan.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/6057956/hafloorplan.zip)
Any help would be appreciated.
Thanks
