### DISCUSSION TITLE
dataset_set: what is it for?

### DISCUSSION THREAD

**Discussion by BluePenguin0** [ExperienceLovelace/ha-floorplan#576] [General]
I want to setup a panel for each floor of my floorplan. The SVG contains all 3 floors - each floor is positioned at a different x position e.g. 0 , 1000 and 2000). I was hoping to change the viewBox attribute to show the appropriate floor depending on the panel selected.
![svg_viewBox](https://github.com/user-attachments/assets/c0507782-51ac-445b-8f7d-c7f515dd94bf)
I was hoping to use the dataset_set service....but this does not do what I hoped.
1.  How do I modifiy the viewBox attribute from YAML?
2. What is the purpose of the dataset_set service?

**Comment by BluePenguin0** [comment]
I have been able to place all 3 floors at position 0 and then change the class of each floor to only show that floor when required. But I want to be able to click on a room and then zoom into that room. I have managed to acheive the required functionality within a browser - but wanted this functionality in HA.

**Reply by exetico** [reply]
If you've already done that in the browser, it's just a question about implement it in a function, or even, just duplicating the code if needed, and adjusting it. Take a look at our function-implementation, and call it with our `execute`-service 🙂.

**Comment by exetico** [comment]
Thats actually a good idea – toggle layers on/off in Inkscape, can become a real pain sometimes. 

But I'd need to look into it, at some point. I'll try and give you a idea or two, once I get time to do so - if other people aren't able to come up with a suggestion.

You're very much able to manipulate the SVG with JavaScript, so it's possibly not that difficult.

**Reply by BluePenguin0** [reply]
Mmmm...sorry, I have not tried JS within YAML....will take a look

**Reply by exetico** [reply]
No rush.. Its fine to use the community, for that, too 😁.

The docs does covers it, so fell free to checkout the "Usage" - examples. There's maybe something interesting in my personal repo, too:
https://github.com/exetico/Home-Assistant_Attachments-for-YouTube

**Reply by zen2** [reply]
> Thats actually a good idea – toggle layers on/off in Inkscape, can become a real pain sometimes.

I use a lot on my floorplan class_set to set layers visible/hidden and yes it's a real pain because that require a lot of redundancy.
A classical example is multi-floor management, this is a a simple three floor example:

```

startup_action:
- service: floorplan.class_set
  service_data:
    class: layer-visible
    element: level_0
- service: floorplan.class_set
  service_data:
    class: layer-hidden
    elements:
    - level_1
    - level_-1

rules:
  - elements:
    - to_level_0
    - from_stairway_1
    tap_action:
    - service: floorplan.class_set
      service_data:
        class: layer-visible
        element: level_0
    - service: floorplan.class_set
      service_data:
        class: layer-hidden
        elements:
        - level_1
        - level_-1

  - elements:
    - to_level_1
    - from_stairway_0
    tap_action:
    - service: floorplan.class_set
      service_data:
        class: layer-visible
        element: level_1
    - service: floorplan.class_set
      service_data:
        class: layer-hidden
        elements:
        - level_0
        - level_-1

  - element: 
    - to_level_-1
    tap_action:
    - service: floorplan.class_set
      service_data:
        class: layer-visible
        element: level_-1
    - service: floorplan.class_set
      service_data:
        class: layer-hidden
        elements:
        - level_0
        - level_1
```

It's working as a radio button on a list of elements to apply selectively two class layer-visible/layer-hidden on list of elements.
So we got:
- action elements (to_level_* from_stairway_*)
- layers elements (level_*)
- relation_ship between actions and layers elements
- a class for selected layers (layer-visible)
- a class for unselected layers (layer-hidden)
- layers elements that will use class A
- layers elements that will use class B (that is all layers elements minus class A ones)

So we can imagine a radio_class_select and the preceding example could simply be write:

```
- radio_class_select:
  - element: to_level_-1
    layer: level_-1
  - elements:
    - to_level_0
    - from_stairway_1
    layer: level_0
  - elements:
    - to_level_1
    - from_stairway_0
    layer: level_1
  startup_select: level_0
  class_selected: visible
  class_unselected: hidden
```
element and layer keys could be declined as list with respectively elements and layers keys to add a maximum of flexibility.

Actually that could be used:
- as a simple radio buttons
- to manage a menu (contextual or not)
- to manage tabs
- to manage floors
- to manage multi-remote
- ...

My imagined example could also be a floorplan.radio_class_set with related service data... My example is only to show that it could be possible to avoid redundancy for an easier multi-layers management.
