### DISCUSSION TITLE
state_action - floorplan.class_set doesn't work as expected

### DISCUSSION THREAD

**Discussion by scythk** [ExperienceLovelace/ha-floorplan#586] [Q&A] [answered]
I've integrated my TV with adb, it's state is either "off" or "unavailable" when turned off. So I configured floorplan as below
```
    - name: TV
      entities:
        - element: media_player.android_tv_192_168_11_36
          entity: media_player.android_tv_192_168_11_36
      tap_action:
        action: call-service
        service: >
          ${(entity.state in ['playing','idle','paused','standby']) ? "script.tv_off" : "script.tv_on" }
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data:
          class: "${(entity.state in ['off','unavailable']) ? 'tv-off' : 'tv-on'}"
```
But it does't work:
![44cd2b1e9e1153a24fbea351109dc45e](https://github.com/user-attachments/assets/64d94bed-e03d-4de7-bc44-b33e162f2d13)
`${(entity.state === unavailable)` works but is there any way I can figure it out without setting another template sensor?
