### DISCUSSION TITLE
Floorplan with Camera and Cover

### DISCUSSION THREAD

**Discussion by jressel01** [ExperienceLovelace/ha-floorplan#69] [Show and tell]
hello everyone,
after I had some problems with the migration from the old floorplan to the new one, which are solved, I put my floorplan online. Maybe it will help some of you.

The camera picture below can be changed by clicking on one of the cameras around the house. 
With a hold on the cameras the live view is opened.

Some things in my files can be written more cleanly. If there is time.
<img width="1036" alt="floorplan" src="https://user-images.githubusercontent.com/70316907/111873523-f003aa00-8990-11eb-9b31-81450856b7ed.PNG">
[Floorplan_yaml_svg_css.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/6175774/Floorplan_yaml_svg_css.zip)

**Comment by nebbiadigiorno** [comment]
hi man!
great works!
i am trying your code. The single camera works just fine but i cannot replicate the camera view. i copy the yyamls code and i add your camera code (css) into mine but it does not work.... any suggestion?

**Reply by jressel01** [reply]
hi
look inside the svg. For the Camera i has 2 IDs. One was the "rect" with ID camera.live_view_t and a group of it with ID  camera.live_view.
```
    <g
       id="camera.live_view">
      <rect
         style="fill:#d4d4d4;stroke:#727272;stroke-width:0.366448"
         id="camera.live_view_t"
         width="29.633553"
         height="19.633551"
         x="60.255821"
         y="82.040298" />
    </g>
```
i have one (Helper) Input_Select
<img width="374" alt="input_select" src="https://user-images.githubusercontent.com/70316907/111911827-54913880-8a67-11eb-8768-7d80ebed3a66.PNG">

```
                    - name: Cameras
                      entities:
                        - camera.f_garten
                        - camera.f_garage
                        - camera.f_klingel
                        - camera.f_polo
                        - camera.f_haustuer
                        - camera.speilhaus_camera
                      state_action:
                        - service: floorplan.class_set
                          service_data:
                            class: |
                              >
                                return "camera-idle";
                      tap_action:
                        action: call-service
                        service: input_select.select_option
                        service_data:
                          entity_id: input_select.cam_select
                          option: '${entity.entity_id}'
                      hold_action: more-info
```
with tap on the cams is switch the Input select to the name from the cam i want to view
```
                    - name: Live_view
                      entity: input_select.cam_select
                      elements:
                        - camera.live_view_t
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          elements: camera.live_view
                          image: '${entities[entity.state].attributes.entity_picture}'
                          image_refresh_interval: 60
```
this show witch the input select say

**Reply by nebbiadigiorno** [reply]
sorry but i don't understand the first 2 point.
"look inside the svg. For the Camera i has 2 IDs. One was the "rect" with ID camera.live_view_t and a group of it with ID camera.live_view."
and the helper... do you mean the helper in home assistant?
![Immagine](https://user-images.githubusercontent.com/59627032/111912810-9a500000-8a6b-11eb-9738-3cd12542a589.png)

For the .svg, i just copy your "sqaure" to my .svg file

**Reply by jressel01** [reply]
Helper at homeassistant "A discesa"

For the view i made a rect in the SVG and give it a name. then i group this and give it the second name

**Comment by nebbiadigiorno** [comment]
ok the ha helper did the trick!
thanks a lot!

**Reply by nebbiadigiorno** [reply]
the only things that doesn't works is the refresh of the live-view

**Reply by exetico** [reply]
Check https://github.com/ExperienceLovelace/ha-floorplan/discussions/58#discussioncomment-501477 - remember to update ha-floorplan, if you're not on the latest version.

**Reply by nebbiadigiorno** [reply]
yes i am on the 1.0.21
i put the cache: true

```
                    - name: Live_view
                      entity: input_select.cam_select
                      elements:
                        - camera.live_view_t
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          elements: camera.live_view
                          image: '${entities[entity.state].attributes.entity_picture}'
                          image_refresh_interval: 10
                          cache: true
```

but it does not work

**Reply by jressel01** [reply]
since the new version with cache option the refresh dont work

21.3.2021, 19:59:44 INFO INIT Floorplan for Home Assistant (ha-floorplan) v1.0.21beta1
```
                    - name: Live_view
                      entity: input_select.cam_select
                      elements:
                        - camera.live_view_t
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          elements: camera.live_view
                          image: '${entities[entity.state].attributes.entity_picture}'
                          cache: false
                          image_refresh_interval: 10
```

**Reply by nebbiadigiorno** [reply]
i have to put: cache:false, or only delete it?

**Reply by nebbiadigiorno** [reply]
i deleted the "cache", but that was the config that i had before. same result. it does not works

**Reply by jressel01** [reply]
think we must wait for a Fix. Today i Update HA-Floorplan and it dont work

**Reply by pkozul** [reply]
@jressel01 

In your rule, I think you might not be using the correct syntax for accessing the entity's picture. Can you try one of the following?

```
        image: '${entities[entity.entity_id].attributes.entity_picture}'
```
or
```
        image: '${entity.attributes.entity_picture}'
 ```

Does it now work?

**Reply by jressel01** [reply]
i have one Flooreplan for test with this yaml but it dont work.
```
                    - name: Live_view
                      entity: camera.f_klingel
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          image: '${entity.attributes.entity_picture}'
                          cache: false
                          image_refresh_interval: 10
```
22.3.2021, 06:17:39 INFO INIT Floorplan for Home Assistant (ha-floorplan) v1.0.21beta1
