### DISCUSSION TITLE
versioning SVG

### DISCUSSION THREAD

**Discussion by Telmo** [ExperienceLovelace/ha-floorplan#73] [Q&A] [answered]
I seem to be running into caching issues, whenever I update the SVG it does not update in the browser event after a shift + reload. Is there a way to version the SVG (I use inkscape) so I can make sure the proper version is displayed?

**Comment by jressel01** [comment, marked as answer]
disable the cache in your config.
```
                config:
                  image:
                    location: /local/floorplan/xyz.svg
                    cache: false
                  stylesheet:
                    location: /local/floorplan/xyz.css
                    cache: false
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
```
