### DISCUSSION TITLE
Displaying binary sensor that had last motion

### DISCUSSION THREAD

**Discussion by pkozul** [ExperienceLovelace/ha-floorplan#79] [Show and tell]
Hi there,

Just sharing how I implemented 'last motion', which is something that was part of the original version of Floorplan.

First of all, I created a sensor in HA to keep track of which binary sensor detected the most recent motion. There are actually 2 sensors shown below... one stores the entity ID of the binary sensor, and the other stores the name of the binary sensor.

```
- platform: template
  sensors:
    last_motion_entity_id:
      friendly_name: 'Last Motion Entity ID'
      value_template: >
        {%-
          set entities = [
            states.binary_sensor.kitchen,
            states.binary_sensor.laundry,
            states.binary_sensor.garage
          ]
        %}
        {% for entity in entities %}
          {% if as_timestamp(entity.last_changed) == as_timestamp(entities | map(attribute='last_changed') | max) %}
            {{ entity.entity_id }}
          {% endif %}
        {% endfor %}
    last_motion_entity_name:
      friendly_name: 'Last Motion'
      value_template: '{{ states[states.sensor.last_motion_entity_id.state].name }}'
```

I then have a floorplan rule that sets the CSS classes for the binary sensors on my floorplan. As you can see,the rule is executed whenever any of the binary sensors change their state, or when the last motion sensor (created above) changes.

The rule then calls the `floorplan.class_set` service, but it doesn't do this just for the binary sensor that has changed, but rather, it calls this service for each of the binary sensors (one at a time). This ensures that any binary sensor (on the floorplan) that was previously displayed as the 'last motion' sensor has a chance to revert back to its normal display. So, in other words, whenever the rule is executed, the `floorplan.class_set` service is called 3 times - once for each of the binary sensors. The actual class that gets set consists of 2 CSS classes.... one class is for the binary sensor on/off state (fll colour for the room), and the other class is the for the last motion (outline of the room).

```
  - entities:
      - binary_sensor.kitchen
      - binary_sensor.laundry
      - binary_sensor.garage
      - sensor.last_motion_entity_id
    state_action:
      - service: floorplan.class_set
        service_data:
          elements:
            - binary_sensor.kitchen
            - binary_sensor.laundry
            - binary_sensor.garage
          class: 'binary-sensor-${entities[element.id].state} ${(entities["sensor.last_motion_entity_id"].state === element.id) ? "last-motion" : "" }'
```

The CSS classes:

```
/* Binary sensors */

.binary-sensor-on {
  fill: #F9E2AE !important;
}

.binary-sensor-off {
  fill: #BBD5F9 !important;
  transition: fill 10s ease;
}

/* Last motion entity */

.last-motion {
  stroke: #8a6d3b !important;
  stroke-width: 1px !important;
  stroke-opacity: 1 !important;
}
```

Here you can see the Salon had the 'last motion', hence the background show around the room.

![image](https://user-images.githubusercontent.com/2073827/112569446-46ad3000-8e38-11eb-848c-ea454e9dce71.png)

**Comment by Zoltant7** [comment]
Hi!
If i would display the name in the SVG text element what should I write ?      
instead of

class: 'binary-sensor-${entities[element.id].state} ${(entities["sensor.last_motion_entity_id"].state === element.id) ? "last-motion" : "" }'

I would write :
```
  - entities:
      - binary_sensor.kitchen
      - binary_sensor.laundry
      - binary_sensor.garage
      - sensor.last_motion_entity_id
    state_action:
      - service: floorplan.text_set
        service_data:
          elements:
            - binary_sensor.kitchen
            - binary_sensor.laundry
            - binary_sensor.garage
          text: states[states.sensor.last_motion_entity_id.state].name
```


I simply cannot tackle the right syntax !
Thanks

**Reply by OzGav** [reply]
As a first suggestion have a look here for examples of the text_set syntax https://github.com/ExperienceLovelace/ha-floorplan/discussions/91 and of course the docs https://experiencelovelace.github.io/ha-floorplan/docs/usage/

**Reply by Zoltant7** [reply]
Yep, I saw that ! I simply cannot get the text displayed from a template sensor on the SVG

**Reply by OzGav** [reply]
Ok but your example isn’t per the link I provided. Try starting with something simple like

```
            - entities:
                - binary_sensor.kitchen
              name: textSensors
              state_action:
                service: floorplan.text_set
                service_data: '${entity.state ? entity.state.replace(/\s{2,}/g,"") : "---"}'
```
