### DISCUSSION TITLE
how to in YAML-mode ?

### DISCUSSION THREAD

**Discussion by acognard** [ExperienceLovelace/ha-floorplan#81] [General]
I all,
i have tryied many ways to use floorplan !

But did non find any solution on how to begin :(

![image](https://user-images.githubusercontent.com/11726569/112679292-49c21380-8e6c-11eb-8b51-6eae88fb6159.png)

![image](https://user-images.githubusercontent.com/11726569/112679322-57779900-8e6c-11eb-8f2a-56bbfe356521.png)

ressources.yaml
```
- url: /hacsfiles/ha-floorplan/floorplan.js
  type: module
```
  ui-lovelace.yaml
```
custom_header:
  compact_mode: true

views: #!include_dir_merge_named /lovelace
  - !include lovelace/ui_floorplan.yaml  
  - !include floorplan/examples/home/simulations.yaml
  - !include floorplan/master.yaml    

resources: !include lovelace/resources/ui_resources.yaml
```

Tks for your help.

**Comment by exetico** [comment]
Hi 

Could you please try again, with one of our examples? That the best way to start debugging a problem. Include errors, if you're facing any.

https://experiencelovelace.github.io/ha-floorplan/docs/example-home/

**Reply by acognard** [reply]
I did :(

![image](https://user-images.githubusercontent.com/11726569/112719204-03b29180-8ef8-11eb-962e-8ab2c9c82e72.png)


![image](https://user-images.githubusercontent.com/11726569/112719235-36f52080-8ef8-11eb-9daf-39f94b0d8c26.png)

ui-lovelace.yaml
```
custom_header:
  compact_mode: true

swipe_nav:
  wrap: false
  animate: swipe
  skip_tabs: 5,6,7,8
  prevent_default: true
  swipe_amount: 30
title: !secret name

views: #!include_dir_merge_named /lovelace
  - !include lovelace/ui_home.yaml

  - !include floorplan/examples/home/home.yaml


resources: !include lovelace/resources/ui_resources.yaml
```

**Reply by OzGav** [reply]
If you are working in YAML mode I am not sure the `resources: ` line should be there. When in YAML mode the floorplan.js module should be referenced as follows in your configuration.yaml

```
lovelace:
  mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  resources:
  - type: module
    url: /hacsfiles/ha-floorplan/floorplan.js
```

It is also difficult to see how the includes work. Can you try just adding the YAML directly to your ui-lovelace.yaml first and get that working?

**Reply by acognard** [reply]
thank you for your help OzGav.

ui-lovelace.yaml
```
custom_header:
  compact_mode: true

swipe_nav:
  wrap: false
  animate: swipe
  skip_tabs: 5,6,7,8
  prevent_default: true
  swipe_amount: 30
title: !secret name

views: #!include_dir_merge_named /lovelace
  - !include lovelace/ui_home.yaml
  - !include lovelace/ui_floorplan.yaml
  - !include lovelace/floorplan/examples/home/home.yaml  
```
configuration.yaml
```
lovelace:
  mode: yaml

  resources:
    - url: /hacsfiles/ha-floorplan/floorplan.js
      type: module 
```
![image](https://user-images.githubusercontent.com/11726569/113028890-b6e2eb00-9183-11eb-9aca-862b63500938.png)

![image](https://user-images.githubusercontent.com/11726569/113031755-feb74180-9186-11eb-92f9-7813e6004297.png)

home.yaml
```
sidebar_title: Home Sample
config:
  show_side_bar: false
  show_app_header: false
  config:
    image: lovelace/floorplan/examples/home/home.svg
    stylesheet: lovelace/floorplan/examples/home/home.css
...
```

Page is still empty.

I am desarmed !

Sincerly

**Reply by exetico** [reply]
Have you tried to put all in the same file, to simplify it?...

I must say, I've lost the scope of the situation - and I'm unsure about what's missing in your config(s). We've plenty of users, where it's working just fine - also fully updated.

If you take a look at the Network-tab in Chrome, are the CSS and SVG loaded as it should?

**Reply by OzGav** [reply]
I think it might be your path to the image and stylesheet
Please make a copy of your ui-lovelace.yaml and put it in a safe place. Then just create a ui-lovelace.yaml which has this:
```
title: Home Assistant
views:
  - panel: true
    cards:
      - config:
          log_level: info
          image:
            location: /local/floorplan/examples/home/home.svg
            cache: true
          stylesheet:
            location: /local/floorplan/examples/home/home.css
            cache: true
```

Let us know if anything appears.
