### DISCUSSION TITLE
Odd scaling since version 1.0.20 on Amazon Fire HD 8 (2020)

### DISCUSSION THREAD

**Discussion by DerEnderKeks** [ExperienceLovelace/ha-floorplan#84] [Q&A] [answered]
When using version 1.0.20+ the floorplan card (on a view in panel mode) is no longer consuming the full height on my Amazon Fire HD 8 (2020), while it looks fine on any other device. In version 1.0.19 everything looks as expected.
Do I need to change anything to make it work again? I fear that the outdated webview browser on the tablet is screwing stuff up.

1.0.20+:
![Screenshot_20210405-171409](https://user-images.githubusercontent.com/12559640/113591531-48df6d80-9634-11eb-9c59-d956e4863114.png)
1.0.19:
![Screenshot_20210405-171425](https://user-images.githubusercontent.com/12559640/113591536-4a109a80-9634-11eb-8954-556d1759353c.png)

**Comment by OzGav** [comment]
Have you tried the `full_height: true` option which is mentioned in these two discussions?
Sizing and caching https://github.com/ExperienceLovelace/ha-floorplan/discussions/58
full_height not working https://github.com/ExperienceLovelace/ha-floorplan/discussions/46

**Reply by DerEnderKeks** [reply]
Yep, but that didn't change anything unfortunately..

**Reply by OzGav** [reply]
Sorry then...I don’t use it ... will have to wait for @pkozul or @exetico ...

**Comment by exetico** [comment, marked as answer]
Could you please share your configs? It's always much easier to help out, if the YAML are shared "up front". Please share all things related to the view in panel-mode, including the name and so :-)

**Reply by DerEnderKeks** [reply]
Sorry, here you go:

<details>
<summary>Lovelace config</summary>

```yaml
title: Wallpanel
views:
  - title: Floorplan
    path: floorplan
    panel: true
    badges: []
    cards:
      - config:
          image: /local/floorplan/floorplan.svg
          stylesheet: /local/floorplan/floorplan.css
          full_height: true
          defaults:
            hold_action: more-info
          rules:
            - entity: light.bedroom_bed_lamp
              tap_action: toggle
              state_action:
                - service: floorplan.class_set
                  service_data: 'light-${entity.state}'
                - service: floorplan.style_set
                  service_data: >
                    >

                    let style = 'fill: "";';

                    if (entity.attributes.rgb_color) style = `fill:
                    rgb(${entity.attributes.rgb_color[0]},${entity.attributes.rgb_color[1]},${entity.attributes.rgb_color[2]});`

                    return style;
            - entity: light.xxx_ceiling_lamp
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
            - entity: light.xxx_table_lamp
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
            - entity: light.xxx_wall_lamps
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
            - entity: light.hallway_ceiling_lamp
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
            - entity: light.living_room_ceiling_lamp
              tap_action: toggle
              state_action:
                service: floorplan.class_set
                service_data: 'light-${entity.state}'
            - entity: sensor.climate_sensor_living_room_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
            - entity: sensor.climate_sensor_kitchen_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
            - entity: sensor.climate_sensor_hallway_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
            - entity: sensor.climate_sensor_xxx_room_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
            - entity: sensor.climate_sensor_xxx_room_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
            - entity: sensor.climate_sensor_bedroom_temperature
              state_action:
                - service: floorplan.text_set
                  service_data: '${entity.state ? entity.state + "°C" : "???"}'
        type: 'custom:floorplan-card'

```

</details>

<details>
<summary>floorplan.css</summary>

```css
svg * {
  vector-effect: non-scaling-stroke !important;
}
#walls {
  fill: #10303e;
}
tspan {
  fill: #e1e1e1;
}
.light-unavailable {
  fill: #6f6f6f;
}
.light-on {
  fill: #fdd835;
}
.light-off {
  fill: #44739e;
}
```

</details>

**Reply by exetico** [reply]
`full_height: true` should be at the same level as `type: 'custom:floorplan-card'`


```yaml
      - config:
          image: /local/floorplan/floorplan.svg
          stylesheet: /local/floorplan/floorplan.css
          full_height: true <!-- Wrong position. Should be at the same level as "config" and "type".
          defaults:
            hold_action: more-info
          rules:
...
        type: 'custom:floorplan-card'
        full_height: true <!-- Correct position
```

And **not** within `config:`.

Example of correct usage:
```yaml
  - path: floorplan
    theme: Google Dark Theme
    title: Floorplan
    panel: true
    badges: []
    cards:
      - config:
          console_log_level: info
          defaults:
            ...
          image: /local/floorplan/examples/home/home.svg
          log_level: info
          rules:
            ...
          stylesheet: /local/floorplan/examples/home/home.css
        full_height: true
        type: 'custom:floorplan-card'
```

The config provided here, are also correct:
https://github.com/ExperienceLovelace/ha-floorplan/discussions/58#discussioncomment-420493
