### DISCUSSION TITLE
Why is there no complete function document, where can I find it

### DISCUSSION THREAD

**Discussion by myxu13** [ExperienceLovelace/ha-floorplan#91] [Q&A]
Why is there no complete function document, where can I find it

**Comment by exetico** [comment]
It's still on the way. We're waiting for @pkozul to complete it.

Check our examples in the docs, for some of the things.

**Reply by OzGav** [reply]
@exectico is right that is the best source but here are some small examples for all of the functions I am aware of:
### class_set
```
            - entities:
                - switch.bedroom_aircon_zone
              name: Aircon icons
              state_action:
                service: floorplan.class_set
                service_data: 
                  class: '${(entity.state === "on") ? "aircon-on" : "aircon-off"}'
```

### style_set
```
            - entities:
                - binary_sensor.main_bedroom
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: |
                    fill: ${ entity.state === "on" ? "#F9D27C" : "#7CB1F9" };
                    transition: ${ entity.state === "off" ? "fill 5s ease" : "" };
```

### text_set
```
            - entities:
                - sensor.time
              name: textSensors
              state_action:
                service: floorplan.text_set
                service_data: '${entity.state ? entity.state.replace(/\s{2,}/g,"") : "---"}'
```

### image_set
```
            - name: Rumpus App Icon
              entities:
                - sensor.rumpus_app_name
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: |
                  >
                    var imageName = '';
                    switch (entity.state) { 
                      case 'Google Play Movies': imageName = 'icon-googleplay'; break; 
                      case 'Spotify': imageName = 'icon-spotify'; break; 
                      case 'Prime Video': imageName = 'icon-prime'; break; 
                      case 'Netflix': imageName = 'icon-netflix'; break; 
                      case 'Kodi': imageName = 'icon-kodi'; break; 
                      case 'YouTube': imageName = 'icon-youtube'; break; 
                      case 'Disney+': imageName = 'icon-disney'; break; 
                      case 'off': imageName = 'off'; break;      
                      default: imageName = 'icon-default'; break; 
                    } 
                    return '/local/floorplan/images/' + imageName + '.svg?v=3';
```
                    
### page_navigate

I dont use this so look here: https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489/171

### window_navigate
```
            - entities:
                - sensor.low_battery_sensors
              tap_action:
                service: floorplan.window_navigate
                data: /lovelace/problems
```
### variable_set

I don't use this so look here: https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/www/custom_ui/floorplan/clock_config.yaml

### class_toggle
```
            - element: toggle_entity_icon
              tap_action:
                action: call-service
                service_data:
                  classes:
                  class: upper-layer-visible
                  elements:
                    - upper_entity_layer
                    - lower_entity_layer
                service: floorplan.class_toggle
              name: toggle_levels
```

Then there are a number of ACTIONS that are monitored for:

`state_action:` Subsequent section is actioned if there is a change in state of the listed entities.
`tap_action:` Subsequent section is actioned if the SVG element is tapped/clicked
`hover_action:` Subsequent section is actioned if the SVG element is hovered over
`hold_action:` Subsequent section is actioned if the SVG element is tapped/clicked and held

Default actions can be specified for all these actions (if there is nothing in the rule for a specific SVG object) For example:
```
views:
  - panel: true
    cards:
      - config:
          image:
            location: /local/floorplan/floorplan_3d-light.svg
            cache: false
          stylesheet:
            location: /local/floorplan/floorplan.css
            cache: true
          defaults:
            hover_action:
              action: hover-info
            tap_action:
              action: more-info
          rules:
            - entities:
...
```
