### DISCUSSION TITLE
Please help me finish installing Floorplan as a lovelace card.

### DISCUSSION THREAD

**Discussion by withay** [ExperienceLovelace/ha-floorplan#97] [Q&A] [answered]
I'm trying to install Floorplan.  I'm not having luck, and I'm not experienced at this.
I'm using the instructions exetico put on the HA forums, "Floorplan now available as a lovelace card", post 315.
I already have HACS.
I installed the ha-floorplan repository.  Restarted.
Step 1.  I've validated that the resources is added in http://{HA-IP}:8123/config/lovelace/resources
Step 2.  I've created a new view, title Floorplan, url floorplan.  I clicked Save.

As I want to use Floorplan as a Lovelace card, I skipped steps 3-13, because of the below:  the part where he says:  "Also… It’s totally possible to use the GUI for almost every step, if you like to do so."
Step 1.  I clicked the + Add Card button in the Floorplan.
Step 2.  I clicked "Manual".
Step 3.  I copied/pasted the wall of code.

And that's where the instructions for it stopped.

So I got a popup, two sided.  The left side shows what I pasted.  At the bottom of the left side it reads:  
Configuration errors detected:
Custom element not found: floorplan-card

On the right side is a large red box with the same pasted info, and at the top it reads:  Custom element doesn't exist: floorplan-card.

"Save" is greyed out.  I don't know what to do from this point.

**Comment by OzGav** [comment, marked as answer]
Have you done step 5 as described here https://experiencelovelace.github.io/ha-floorplan/docs/quick-start/

**Reply by withay** [reply]
Oh.  No, that wasn't in there, I didn't see that.  So...   I did mention I was VERY MUCH a beginner, right?  I don't know what that step means.  I never added any of the folders under "www" because the part of the instructions I followed didn't say to (I thought that was for NON lovelace card, that part).  And I'm afraid I don't know what a module is, OR a resource file.  Yes, I feel rather dumb.

**Reply by OzGav** [reply]
Go to CONFIGURATION>>LOVELACE DASHBOARDS>>RESOURCES and add it there as a JavaScript module. The path you want is *probably* /hacsfiles/ha-floorplan/floorplan.js but check where you installed it.

I am not sure about your step 1 in your initial post did you manually put the file there because that is not where HACS normally installs files. If you manually added it there you can delete it.

**Reply by withay** [reply]
I just looked - it is already there.

**Reply by withay** [reply]
![image](https://user-images.githubusercontent.com/35699292/116628000-364b1200-a91c-11eb-8e81-673813b54445.png)

**Reply by withay** [reply]
I just did some searching, though, and found this:

![image](https://user-images.githubusercontent.com/35699292/116628189-95a92200-a91c-11eb-9bc7-0c49d65eb1b4.png)

**Reply by OzGav** [reply]
Ok please paste in your ui-lovelace.yaml (just the floorplan section) and make sure you format it by highlighting it all and pressing the <> button

**Reply by OzGav** [reply]
On your second reply that is correct that is where HACS puts the files

**Reply by withay** [reply]
I think I may have posted as you were posting?  My lovelace resource doesn't point to the files in the second pic - should I change the lovelace resource?

**Reply by OzGav** [reply]
No HA resolves /hacsfiles to .../config/www/community

**Reply by withay** [reply]
```
  - title: Floorplan
    path: floorplan
    theme: Google Dark Theme
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: 'custom:floorplan-card'
                full_height: true
                config:
                  image: /local/floorplan/examples/home/home.svg
                  stylesheet: /local/floorplan/examples/home/home.css
                  log_level: info
                  console_log_level: info
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
                    - entity: light.garage
                      element: light.garage
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data: '/local/floorplan/examples/home/light_${entity.state}.svg'
                      tap_action: toggle
                    - entity: light.garage
                      element: light.garage.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: 'button-${entity.state}'
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                    - entity: light.garage
                      element: light.garage.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: '${entity.state}'
                      tap_action: false
                    - entity: switch.living_area_fan
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: '${(entity.state === "on") ? "spinning" : ""}'
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: 'button-${entity.state}'
                      hold_action:
                        action: call-service
                        service: homeassistant.toggle
                        service_data:
                          entity_id: switch.living_area_fan
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: '${entity.state}'
                      tap_action: false
                    - entity: camera.zagreb_ban_jelacic_square
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          image: '${entity.attributes.entity_picture}'
                          image_refresh_interval: 10
                    - entities:
                        - binary_sensor.main_bedroom
                        - binary_sensor.living_area
                      state_action:
                        action: call-service
                        service: floorplan.style_set
                        service_data:
                          style: >
                            fill: ${ entity.state === "on" ? "#F9D27C" : "#7CB1F9"
                            };

                            transition: ${ entity.state === "off" ? "fill 5s ease"
                            : "" };
```
