### ISSUE TITLE
CSS fill doesn't work

### ISSUE THREAD

**Issue by michelanello** [ExperienceLovelace/ha-floorplan#13]
Hi to everybody.
I'm not able anymore to change the fill color of the SVG object. I'm able via CSS to modify the visibility and the opacity but noway for the color.

Here is the CSS part:
```
.light-on {
  fill: red !important;
}

.light-off {
  fill: white !important;
}
```
and the YAML part:
```
    - entities:
        - switch.twinkly
        - light.wled
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data: '${(entity.state === "on") ? "light-on" : "light-off" }'
      tap_action:
        action: call-service
        service: homeassistant.toggle
```
The YAML part is correct and object are well named infact , changing the CSS to:
```
.light-on {
  opacity: 1 !important;
}

.light-off {
  opacity: 0.2 !important;
}
```
it works correctly.

Any suggestion on how to solve it?

**Comment by exetico** [comment]
Hi :-) 

Are the bulbs colored? If so, try and give the fill-solution a try:
https://experiencelovelace.github.io/ha-floorplan/docs/example-light/

(Select "YAML") 

If you still like to go the old fashion way, I'll see what I can found out :-) However, I'm using the `class_set` myself, and it's working fine with "fill", too (Just tested it).

![image](https://user-images.githubusercontent.com/3549445/104217549-d3507080-543b-11eb-877e-c4537f2325b8.png)

But `!important` are needed, for sure:

```yaml
name: Livingroom
entities:
  - group.livingroom
element: area.livingroom
tap_action:
  service: light.toggle
  service_data:
    entity_id: light.aeotec_zw111_nano_dimmer_level
state_action:
  service: floorplan.class_set
  service_data:
          class: |
            ${(entity.state === "on") ? "light-on" : "light-off"}
```

```css
/* Light Control */
path[id*="area."].light-on{
  opacity:1!important;
  fill: red!important;
}
```



What kind of object(s) are your svg-elements? You can try and share it, if it's not working as expected.

Here's another example, of a random thing:
![image](https://user-images.githubusercontent.com/3549445/104217866-36420780-543c-11eb-86a0-a4a3ed4f3fb9.png)

```yaml
state_action:
  service: floorplan.class_set
  service_data:
    class: '${(entity.state === "on") ? "thing-on" : "thing-off"}'
```

```css
/* Things Control */
[id*="thing."].thing-on{
  opacity:1!important;
  filter: drop-shadow(0px -5px 3px #ffedde);
  fill: #fffae54f !important;
}

[id*="thing."]{
  opacity:0!important;
  transition: opacity .25s;
  -moz-transition: opacity .25s;
  -webkit-transition: opacity .25s;
}
```
