### ISSUE TITLE
[BUG] `double_tap_action` not working.

### ISSUE THREAD

**Issue by AngellusMortis** [ExperienceLovelace/ha-floorplan#132]
**Describe the bug**

`double_tap_action` not working.

**To Reproduce**
1. Create a rule with the `double_tap_action`
2. Attempt to Double click

**Expected behavior**

The expectation would be that the `double_tap_action` would fire like other actions.

**Desktop (please complete the following information):**
(latest stable at the time of creation)
 - OS: Windows 10 21H1 (build 19043.1083)
 - Browser: Microsoft Edge / Firefox Developer Edition
 - Version: 91.0.864.71 / 91.0b7

**Smartphone (please complete the following information):**
(latest stable app version at the time of creation)
 - Device: Android GSI ROM
 - OS: Android 10
 - Browser: HA App
 - Version: 2021.6.2-full

**Share configuration**
Please share:

Example Rule:
```yaml
- element: background-kitchen
  entity: input_boolean.kitchen_occupancy
  double_tap_action:
    action: navigate
    navigation_path: /lovelace/kitchen
    confirmation:
      text: Verify?
```

**Additional context**
Replacing `double_tap_action` with `tap_action` or `hold_action` results in confirmation prompt appearing/navigation working. It seems to specifically be an issue with `double_tap_action`. 

I did double-check, there are also no documentation examples using `double_tap_action`.
