### ISSUE TITLE
[BUG] floorplan.text_set wrap the output text inside a <title/> tag

### ISSUE THREAD

**Issue by MarlBurroW** [ExperienceLovelace/ha-floorplan#143]
**Describe the bug**
When I use `floorplan.text_set` to display the state of an entity, the output text is wrapped inside a <title> tag.
Text value is not visible because a title in a text tag is probably not a valid SVG semantic.

**To Reproduce**
1. Create a simple SVG with a text tag `<text id="temperature"></text> inside`
2. Add a rule to set the text tag with an entity state.
```yaml
rules:
  - element: temperature
    entity: sensor.my_temperature
    state_action:
      - service: floorplan.text_set
        service_data: '${entity.state ? entity.state + "°C" : "unknown"}'
```

**Expected behavior**

```html
<text id="temperature">29°C</text>
```

**Observed behavior**
```html
<text id="temperature"><title>29°C</title></text>
```

**Screenshots**
![alt text](https://d3dehtdmp2rwcw.cloudfront.net/ms_254763/HXUJC2RWTUhOXm0f6kJngx206eOLFQ/Floorplan%2B-%2BHome%2BAssistant%2B2021-09-05%2B00-49-20.png?Expires=1630796400&Signature=UaLs7sM8Yc4Ai4gGZvx-yu83Vs-JOTYH4IprzdVh4lEzx0dai7HQXJMGje7OKD10m-GZcH-IJE4B3ZIP4a6Xm3~7TbwgqBQvfuyjAPt6tPBnBLBveWxCOouqhqYDq3hRRna8fXFd0JVg050QPB72nYuo3pijB9qB5z1H~MTmxmdqwlPhd48AUtiUmOdWyzku65VmV5ZynXNG0l9qJsfC~Nkof7~NqE7cvaNQ-HkWMADQeho-1JMhczbisTz5XMZ7N7~ajtft5TxPmMsNRjK~U13vXrrCGnepdaDepcHZyR9CJmVXqzzATCKjYysOCGE2IJ491GZkkKB9Vg~23I7Ukw__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA "Logo Title Text 1")

**Desktop (please complete the following information):**
 - OS: MacOSX 11.2.2
 - Browser: Chrome 93.0.4577.63 (Official Build) (x86_64)
 - HA: 2021.9.1 (HAOS x86 on a NUC)
 - HA Frontend: 20210830.0
 - ha-floorplan: 1.0.27
