### ISSUE TITLE
[FEATURE] Expose state without overwriting existing css classes

### ISSUE THREAD

**Issue by FlorianLudwig** [ExperienceLovelace/ha-floorplan#179]
**Is your feature request related to a problem? Please describe.**

I would like to expose the state of an entity to svg/css without interfering with existing css classes.

**Describe the solution you'd like**
To avoid having to deal with removing, replacing etc css classes, I think it would be easiest to use data attributes. 

Example yaml:
```
      state_action:
        - action: call-service
          service: floorplan.attr_set
          service_data:
            state: ${entity.state}
            foo: bar
```

Result would be:
```
<tag data-state="$state" data-foo="bar">
```

**Describe alternatives you've considered**

Using `class_set`:

```
      state_action:
        - action: call-service
          service: floorplan.class_set
          service_data:
            class: ha-state-${entity.state}
```

The issue with this solution is that it overwrites all existing css classes - and I already have css classes in my svg.

Another possibility would be to have a new class function that remembers which css classes were in the original svg and doesn't touch those:

```
      state_action:
        - action: call-service
          service: floorplan.class_set
          service_data:
            class: ha-state-${entity.state}
            keep_original_classes: true
```

This should remove classes which were added by ha-floorplan but keep the classes from the initial svg file.
