### ISSUE TITLE
Specify an array of elements to change the state on for a given entity

### ISSUE THREAD

**Issue by vajonam** [ExperienceLovelace/ha-floorplan#28]
**Is your feature request related to a problem? Please describe.**
The ability to sent multiple elements based on one sensor in home assistant, for example I have two door contact sensors in series, and would like to set the state of each of doors to open when sensor is in the open state

**Describe the solution you'd like**
something like
```
   - entity: binary_sensor.door
      elements:
         - svg.element1
         - svg.element2
```    

**Describe alternatives you've considered**
Currently I have two rules, which isn't the end of the world, but will be nice to target multiple svg elements. 

**Illustrations and examples**
see above

**Additional context**
https://github.com/ExperienceLovelace/ha-floorplan/discussions/27#discussioncomment-304358

**Comment by exetico** [comment]
I would just like to hear, what kind of things you're changing, based of a `door` sensor? One showing it's open, and another... _what_? :-) 

Overall I personally think we should implement this, in the future🎆

**Comment by vajonam** [comment]
Right now I have doors hooked up in series to save I/o inputs on a security
system. So if that sensor is high then one of two doors can be open

Others can be if have 3D model and based on sensor I want to change state
on multiple svg elements to darken or lighten the scene etc.

**Comment by pkozul** [comment]
@vajonam Can you try something like this?

```
  - entity: binary_sensor.door
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: 'door-${entity.state}'
        elements:
          - svg.element1
          - svg.element2
```

The `floorplan.class_set` service allows you to specify multiple SVG elements.

**Comment by vajonam** [comment]
@pkozul  

if I set

```
  - entity: binary_sensor.back_doors
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data: "door-${entity.state}"
      elements:
        - binary_sensor.patio
        - binary_sensor.laundry
```

but because there is no element entity it complains about 

`floorplan.js:115 25/01/2021, 07:58:39 WARNING CONFIG Cannot find element 'binary_sensor.back_doors' in SVG file` 

but If I set the element on the top level it works as expected, seems a bit odd, but I can see how the code checks for the element first in the svg even its is overridden by the service_data. 

```
  - entity: binary_sensor.back_doors
    element: binary_sensor.patio
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: "door-${entity.state}"
        elements:
          - binary_sensor.patio
          - binary_sensor.laundry
```

**Comment by pkozul** [comment]
@vajonam 

How about if you try this?

```
  - entity: binary_sensor.back_doors
    elements:
      - binary_sensor.patio
      - binary_sensor.laundry
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: "door-${entity.state}"
#        elements:
#          - binary_sensor.patio
#          - binary_sensor.laundry
```

As you can see, I have included both elements at the top level, and commented them out in the `service_data`. Let us know if that works.

**Comment by vajonam** [comment]
This was the reason I opened the FR in the first place.

with that config that I see that its not really looking at the elements array at the top level. 

```
floorplan.js:115 26/01/2021, 09:10:34 WARNING CONFIG Cannot find element 'binary_sensor.back_doors' in SVG file
```

**Comment by pkozul** [comment]
@vajonam Can you please try the latest version 1.0.12? Your original config should hopefully work now.

**Comment by vajonam** [comment]
I dont see the 1.0.12 version tag yet, but I did update to 'master; can confirm this works.

```

  # Set both back doors on one sensor
  - entity: binary_sensor.back_doors
    elements:
      - binary_sensor.patio
      - binary_sensor.laundry
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data:
        class: "door-${entity.state}"
        # elements:
        #   - binary_sensor.patio
        #   - binary_sensor.laundry
```

can close this once this appears in HACS.
