### ISSUE TITLE
[FEATURE] Use selectors other than ids for matching HA properties

### ISSUE THREAD

**Issue by geiseri** [ExperienceLovelace/ha-floorplan#348]
I use [Diagrams.net](https://www.drawio.com/) to generate my floorplans.  The stencils make it easy to build floorplans, add all the clipart, etc.  It's not as fancy as the other tools, but it's great for 2d.  When I pair that with the [svg-data](https://www.drawio.com/doc/faq/plugins) plugin it allows me to add custom data properties to the exported SVG.

![Screenshot 2023-07-31 at 12 48 27 PM](https://github.com/ExperienceLovelace/ha-floorplan/assets/2265693/a6406d34-1d07-42b0-9bd9-6b88f2f383fa)

Then on SVG export, I get the following output:

```xml
<g id="cell-eSdvFNF39oNR8OCdurj1-20"
    content="&lt;object label=&quot;&quot; ha_id=&quot;sensor.weatherstation&quot;/&gt;"
    data-label="" data-ha_id="sensor.weatherstation">
    <rect x="215" y="66" width="120" height="60" fill="rgb(255, 255, 255)"
        stroke="rgb(0, 0, 0)" pointer-events="all" />
</g>
```

Currently, I manually edit the resulting svg export from diagrams and then replace the `id` value with the `data-ha_id` value.  It works, but it's annoying to have to edit it every time I modify the layout.   It would be handy to be able to select the property that the sensor is resolved from.

**Comment by OzGav** [comment]
Will see what others think but I guess you could also try and ask them to allow you to modify the ID via that plugin?

**Comment by geiseri** [comment]
It was non-obvious, but if you double-click on the text of the ID you can change it.  It will prepend `cell-` to the id, but other than that it will work as advertised.   You can feel free to close this if you think the feature request otherwise doesn't make any sense.

**Comment by exetico** [comment]
I'll consider this, as I understand why it could be useful. There's too many things around my head right now, so I can't promose on when I'll look into it, but hopefully at some time 😄. _PR's a welcome, if other are looking into this feature request._

@geiseri : How does Diagrams.net works in practice? For me it sounds a bit odd, compared to Inkscape. But we all have different preferences 😃 !

**Comment by exetico** [comment]
HI @geiseri  

Could you please give this a go? Also, @OzGav  :) ...

[floorplan-dataset_support.js.zip](https://github.com/ExperienceLovelace/ha-floorplan/files/12347002/floorplan-dataset_support.js.zip)

Unpack and replace floorplan.js. Remember to secure caching or similar are not playing with you.

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/afb14404-9fb2-45d1-b2c4-cab2d8cc101a)

In the top of your ha-config, where you also define the `image`, `rules` and `stylesheet`, add a new key with the name of `element_data_attribute` with the targeted data-key name, **without** `datakey-xyz` or whatever.

Provising:
```yaml
...
image: /local/floorplan/floorplan1.svg?v=1.1.14
rules: !include_dir_list include/
element_data_attribute: 'hakey'
console_log_level: error
...
```

![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/3549445/97aadfde-6c17-4ad7-90b1-ee87ecacd7d8)

In my `rect` SVG El, I have set the dataset to be `data-hakey="thing_test"`, which matches `hakey` in the config. Therefore ha-floorplan will look for that value, too, and match this:

```yaml
entities:
  - device_tracker.0a_1a_1a_11_1a_1a
#element: thing.workstation-old # Old id reference
element: thing_test
state_action:
  service: floorplan.class_set
  service_data:
    class: '${(entity.state === "on") ? "thing-on" : "thing-off"}'
```

Kindly note that I've only tested this for the hover and state. I'm seeing some off things with "state_action" and "tap_action", but I'd still like you to confirm that this is the expected need you have (ofc. without the bugs).
