### ISSUE TITLE
[FEATURE] 'floorplan.text_set' should support element which has text as child

### ISSUE THREAD

**Issue by Skarbo** [ExperienceLovelace/ha-floorplan#358]
**Description**
Prior to version 1.0.36 [setText](https://github.com/ExperienceLovelace/ha-floorplan/blob/f167c0581d96bcca2eb6feb2c31b3a3de924d90c/src/lib/utils.ts#L86) would look for any existing `tspan` children and change the child text. 

From version 1.0.36 with new line feature [setText](https://github.com/ExperienceLovelace/ha-floorplan/blob/a323398a8520bd85331fe073dd4890bd1ab395de/src/lib/utils.ts#L86) will presume that entity is a `text` node and append `tspan` with the text to that node.

This does not work if you use `floorplan.text_set` on a entity that is a `g` node, for example.

**Current experience**
*Original SVG*
```svg
<svg>
<g id="temperature.kitchen">
<text><tspan x="5" y="5">99.9°</tspan></text>
</g>
</svg>
```

*YAML*
```yaml
- name: Temperatures
   entities:
     - element: temperature.kitchen
       entity: sensor.kitchen
   state_action:
     - service: floorplan.text_set
       service_data: '10.0°'
```

*Produced SVG*
```svg
<svg>
<g id="temperature.kitchen">
<tspan>10.0°</tspan>
</g>
</svg>
```

*Expected SVG*
```svg
<svg>
<g id="temperature.kitchen">
<text><tspan x="5" y="5">10.0°</tspan></text>
</g>
</svg>
```

**Suggestion**
Update `setText` to look for child `text` node if element is not `SVGTextElement`.

```typescript
static setText(
  textElement: HTMLElement | SVGElement,
  text: string,
  shiftAxisY: string
): void {
  if (!(textElement instanceof SVGTextElement)) {
    textElement = textElement.querySelector('text') || textElement;
  }
```
