### ISSUE TITLE
[BUG] Objects with "clip-path" are not shown in Lovelace card

### ISSUE THREAD

**Issue by Aephir** [ExperienceLovelace/ha-floorplan#360]
**Describe the bug**
Objects created with a "clip path", that retain the `clip-path` in the svg do not render in Home Assistant.

<details> 

<summary> for instance this: </summary>

```
       id="trunk_open"
       x="-431.81723"
       y="-330.76248"
       clip-path="url(#clipPath1)"
       inkscape:svg-dpi="1"
       transform="translate(431.81725,251.18381)" /><image
       width="285.75"
       height="619.125"
       preserveAspectRatio="xMidYMid"
       xlink:href="data:image/jpeg;base64,
```

</details>

**To Reproduce**
1. Create svg file ini inkscape.
2. Improt some image
3. Create a shape for "clipping", overlay them and select "set clip"
4. (potentially do the same again with a new clip path/shape and the already clipped object)
5. try using in a lovelace `custom:floorplan-card`

**Expected behavior**
You see all objects that are there in the svg file/editor.

**Screenshots**
What I see in inkscape:
<img width="1129" alt="Screenshot 2023-08-27 at 23 01 16" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/20152788/440da4f6-7277-4ab1-9426-f7339739b830">

What I see in lovelace:
<img width="523" alt="Screenshot 2023-08-27 at 23 04 19" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/20152788/15af929c-d975-43da-82f8-aa12f76eedaf">

**Desktop (please complete the following information):**
 - OS: macOS 13.5.1
 - Browser Tested with several
 - Version Tested with several

**Share configuration**
Please share:
You can see the current (work in progress) files here: https://github.com/Aephir/ha-tesla-lovelace-floorplan
I have also tried a minimal yaml config where I don't mention any of the `element`s that are not shown; they still don't show up.

My current workaround has been to `Make bitmap copy` of each, but it seems like that shouldn't be necessary?

**Comment by Aephir** [comment]
No I think this is still an issue. 

<details>

<summary> With this card (simplified to use only one single rule for testing!): </summary>

```
type: custom:floorplan-card
config:
  image:
    location: /local/floorplan/tesla/tesla_floorplan_v1.svg
    cache: false
  stylesheet:
    location: /local/floorplan/tesla/tesla_floorplan.css
    cache: false
  console_log_level: warn
  defaults:
    hover_action: hover-info
    tap_action: more-info
  rules:
    - name: Driver Front
      entities:
        - entity: binary_sensor.tesla_model_y_all_openings
          element: driver_front_open
      tap_action: disable
      state_action:
        service: floorplan.class_set
        service_data: >-
          ${(entity.attributes.driver_front === "open" &&
          entity.attributes.driver_rear === "closed") ? "visibility-on" :
          "visibility-off"}
```

</details>

I see this:
<img width="500" alt="Screenshot 2023-08-28 at 21 51 34" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/20152788/ed1263e8-91fc-4535-b1e1-215f48700754">

But with the exact same code, just using `location: /local/floorplan/tesla/tesla_floorplan_no_clip.svg` (a version where I took all the object that were "clipped" and selected "Make a bitmap copy" and used them), it looks like this:

<img width="490" alt="Screenshot 2023-08-28 at 21 52 01" src="https://github.com/ExperienceLovelace/ha-floorplan/assets/20152788/84432190-a327-47cc-8494-1d33a844822a">

All the car doors and ports are the same, and have the same names (I renamed all the "bitmap copies" to match the originals which I deleted).
