### ISSUE TITLE
[BUG] You need to define an entity error on previously working code.

### ISSUE THREAD

**Issue by MadMirza** [ExperienceLovelace/ha-floorplan#363]
Hi, 
I have a few floorplan codes that were previously working, I am unsure what caused the following issue, tried to search around and did some basic troubleshooting.
The last major change would be updating HA to Core 2023.7.3
I did use the floorplans for a while after the update until everything broke.
The card is also updated to the latest version.
I have shared the error and my codes below, i did try removing some parts of the codes that seemed not required, but nothing helped.
Any help is great, Thank you.
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/150f854f-0561-4a71-9292-1201f19a5376)
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/6043df2e-edec-4835-a40d-984379fb04cb)
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/6dd79fe6-4696-4b18-b9fa-76c91f0bc72e)

**Comment by OzGav** [comment]
Have you flushed the browser cache?

**Comment by MadMirza** [comment]
yes, tried multiple times. Tried other browsers as well.

**Comment by OzGav** [comment]
Tough one. I havent seen that error before. How do you create your floorplans? In the UI or YAML?

**Comment by MadMirza** [comment]
Using YAML,  i did try defining an entity although not required, just in case to see what happens.
Then another error occurs asking me to define an SVG file (already was defined), adjusted the code to remove that error as well.
Then finally the error is gone with a weird looking floorplan that has multiple floorplan on top of one another, with no controls working.

**Comment by OzGav** [comment]
What you do you mean by "defining an entity"?

**Comment by MadMirza** [comment]
just added  one random entity to remove the error, which is a dumb move ig

**Comment by OzGav** [comment]
Can you post your full yaml...Also you can look in the console log to see if there are any clues there

**Comment by MadMirza** [comment]
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/1895437c-b1e9-4bd9-b65c-c7b833b78ac1)
This removes the error, but is useless,
Posting the code below.

**Comment by MadMirza** [comment]
```
views:
  - title: skytest
    path: skytest1
    icon: "mdi:account"
    panel: true
    cards:
      - type: custom:floorplan-card
        style:
          top: 50%
          left: 50%
          height: 100%
          width: 100%
        log_level: info
        config:
          image:
            location: /local/kfp/kfp.svg
            cache: false
          stylesheet: /local/kfp/floorplan.css
          rules:
            - entities:
                - entity: light.tss_ceiling_light
                  element: areadininglights
                - entity: input_boolean.2
                  element: araentrance
                - entity: input_boolean.3
                  element: areajuniorbedroom
                - entity: input_boolean.4
                  element: areakitchenledstrips
                - entity: input_boolean.5
                  element: areakitchenceiling
                - entity: input_boolean.6
                  element: areakitchencountertop
                - entity: input_boolean.7
                  element: areamastertoiletceiling
                - entity: input_boolean.8
                  element: areamastertoiletvanity
                - entity: input_boolean.9
                  element: areambraccent
                - entity: input_boolean.10
                  element: areambrceilinglight
                - entity: input_boolean.11
                  element: areambrentrance
                - entity: input_boolean.12
                  element: areambrspotlights
                - entity: input_boolean.13
                  element: areaspota
                - entity: input_boolean.14
                  element: areastoreroom
                - entity: input_boolean.15
                  element: areatvspot
                - entity: input_boolean.16
                  element: areawalkway
                - entity: input_boolean.17
                  element: areacommontoiletceiling
                - entity: input_boolean.18
                  element: areacommontoiletshower
              tap_action:
                action: "toggle"
              hold_action:
                action: more-info
            - entities:
                - entity: light.tss_ceiling_light
                  element: dininglights
                - entity: input_boolean.2
                  element: entrance
                - entity: input_boolean.3
                  element: juniorbedroom
                - entity: input_boolean.4
                  element: kitchenledstrips
                - entity: input_boolean.5
                  element: kitchenceiling
                - entity: input_boolean.6
                  element: kitchencountertop
                - entity: input_boolean.7
                  element: mastertoiletceiling
                - entity: input_boolean.8
                  element: mastertoiletvanity
                - entity: input_boolean.9
                  element: mbraccent
                - entity: input_boolean.10
                  element: mbrceilinglight
                - entity: input_boolean.11
                  element: mbrentrance
                - entity: input_boolean.12
                  element: mbrspotlights
                - entity: input_boolean.13
                  element: spota
                - entity: input_boolean.14
                  element: storeroom
                - entity: input_boolean.15
                  element: tvspot
                - entity: input_boolean.16
                  element: walkway
                - entity: input_boolean.17
                  element: commontoiletceiling
                - entity: input_boolean.18
                  element: commontoiletshower
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "show" : "hide"}'

            - name: Fans
              entities:
                - entity: fan.ceiling_fan
                  element: fanstudy
              tap_action: toggle
              hold_action:
                action: more-info
              state_action:
                service: floorplan.class_set
                service_data:
                  element: fansmall
                  class: '${(entity.state === "on") ? "spinning" : "show"}'

```

**Comment by MadMirza** [comment]
```
views:
  - title: skytest
    path: skytest1
    icon: "mdi:account"
    panel: true
    cards:
      - type: custom:floorplan-card
        style:
          top: 50%
          left: 50%
          height: 100%
          width: 100%
        log_level: info
        config:
          image:
            location: /local/kfp/kfp.svg
            cache: false
          stylesheet: /local/kfp/floorplan.css
          rules:
            - entities:
                - entity: light.tss_ceiling_light
                  element: areadininglights
                - entity: input_boolean.2
                  element: araentrance
                - entity: input_boolean.3
                  element: areajuniorbedroom
                - entity: input_boolean.4
                  element: areakitchenledstrips
                - entity: input_boolean.5
                  element: areakitchenceiling
                - entity: input_boolean.6
                  element: areakitchencountertop
                - entity: input_boolean.7
                  element: areamastertoiletceiling
                - entity: input_boolean.8
                  element: areamastertoiletvanity
                - entity: input_boolean.9
                  element: areambraccent
                - entity: input_boolean.10
                  element: areambrceilinglight
                - entity: input_boolean.11
                  element: areambrentrance
                - entity: input_boolean.12
                  element: areambrspotlights
                - entity: input_boolean.13
                  element: areaspota
                - entity: input_boolean.14
                  element: areastoreroom
                - entity: input_boolean.15
                  element: areatvspot
                - entity: input_boolean.16
                  element: areawalkway
                - entity: input_boolean.17
                  element: areacommontoiletceiling
                - entity: input_boolean.18
                  element: areacommontoiletshower
              tap_action:
                action: "toggle"
              hold_action:
                action: more-info
            - entities:
                - entity: light.tss_ceiling_light
                  element: dininglights
                - entity: input_boolean.2
                  element: entrance
                - entity: input_boolean.3
                  element: juniorbedroom
                - entity: input_boolean.4
                  element: kitchenledstrips
                - entity: input_boolean.5
                  element: kitchenceiling
                - entity: input_boolean.6
                  element: kitchencountertop
                - entity: input_boolean.7
                  element: mastertoiletceiling
                - entity: input_boolean.8
                  element: mastertoiletvanity
                - entity: input_boolean.9
                  element: mbraccent
                - entity: input_boolean.10
                  element: mbrceilinglight
                - entity: input_boolean.11
                  element: mbrentrance
                - entity: input_boolean.12
                  element: mbrspotlights
                - entity: input_boolean.13
                  element: spota
                - entity: input_boolean.14
                  element: storeroom
                - entity: input_boolean.15
                  element: tvspot
                - entity: input_boolean.16
                  element: walkway
                - entity: input_boolean.17
                  element: commontoiletceiling
                - entity: input_boolean.18
                  element: commontoiletshower
              state_action:
                action: call-service
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "show" : "hide"}'

            - name: Fans
              entities:
                - entity: fan.ceiling_fan
                  element: fanstudy
              tap_action: toggle
              hold_action:
                action: more-info
              state_action:
                service: floorplan.class_set
                service_data:
                  element: fansmall
                  class: '${(entity.state === "on") ? "spinning" : "show"}'

```

**Comment by MadMirza** [comment]
how do i check the logs?

> Can you post your full yaml...Also you can look in the console log to see if there are any clues there

**Comment by OzGav** [comment]
Go to developer tools for your browser and you will find it in there. Chrome right click INSPECT then CONSOLE in the menu at the top

**Comment by MadMirza** [comment]
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/84062580-5c59-42c5-b44e-b9f5f03918ef)

**Comment by OzGav** [comment]
OK do you see your SVG when you put this in your browser `http://<YOUR_HA_IP>:8123/local/kfp/kfp.svg`

**Comment by MadMirza** [comment]
![image](https://github.com/ExperienceLovelace/ha-floorplan/assets/100464787/1bf4010f-4285-4d39-95e7-1b04c0ecc502)
yes

**Comment by OzGav** [comment]
Try this slimmed down yaml

```
views:
  - title: skytest
    path: skytest1
    icon: "mdi:account"
    panel: true
    cards:
      - type: custom:floorplan-card
        log_level: info
        config:
          image:
            location: /local/kfp/kfp.svg
            cache: false
          stylesheet: /local/kfp/floorplan.css
          rules:
            - entities:
                - entity: light.tss_ceiling_light
                  element: areadininglights
              tap_action:
                service: light.toggle
            - entities:
                - entity: light.tss_ceiling_light
                  element: dininglights
              state_action:
                service: floorplan.class_set
                service_data: '${(entity.state === "on") ? "show" : "hide"}'

            - name: Fans
              entities:
                - entity: fan.ceiling_fan
                  element: fanstudy
              tap_action: 
                service: fan.toggle
              state_action:
                service: floorplan.class_set
                service_data:
                  element: fansmall
                  class: '${(entity.state === "on") ? "spinning" : "show"}'
```
