### ISSUE TITLE
Do I understand correctly that with Inkscape & Floor plane Lovelace:

### ISSUE THREAD

**Issue by Trzinka** [ExperienceLovelace/ha-floorplan#398]
Do I understand correctly that with:
```
                - entities:
                    - switch.sw_st
                    - switch.sw_vh
                    - switch.sw_mi
                    - switch.sw_gr
                    - switch.sw_ho
                    - switch.sw_sp
                    - switch.sw_na
                    - switch.sw_di
                    - switch.sw_je
                    - switch.sw_sh
                    - switch.sw_ku
                    - switch.sw_ko
                  tap_action:
                    action: toggle
                  state_action:
                    action: call-service
                    service: floorplan.style_set
                    service_data:
                      element: >-
                        ${entity.entity_id.replace('switch.',
                        'light_covering.')}
                      style: |
                        >
                        if( entity.state !== "on" )
                            return "display: none;";
```
" I'm calling this from Inkscape:"

![Luči-slike](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/102c57bc-4c26-40ec-aa4e-442bf3b4a7f4)

"and with this:"
```
                - entities:
                    - switch.sw_st
                    - switch.sw_vh
                    - switch.sw_mi
                    - switch.sw_gr
                    - switch.sw_ho
                    - switch.sw_sp
                    - switch.sw_na
                    - switch.sw_di
                    - switch.sw_je
                    - switch.sw_sh
                    - switch.sw_ku
                    - switch.sw_ko
                  tap_action: false
                  state_action:
                    action: call-service
                    service: floorplan.class_set
                    service_data: switch-${entity.state}
```
"should call this:"
![Switch-obrobe](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1001346a-8132-43cf-a279-9a8558365ad7)

In floor plan Lovelace/Ha card i have this:
```
            config:
              stylesheet: /local/img/fp/fp.css
              image: /local/img/fp/fp.svg
              default:
                hover_action: hover-info
                tap_action: more-info
              rules:
                - element: background
                  entity: sensor.del_dneva
                  tap_action: false
                  hover_action: false
                  state_action:
                    action: call-service
                    service: floorplan.image_set
                    service_data: |
                      >
                       var imageName = ''; 
                       switch (entity.state) { 
                         case 'Jutro': imageName ='jutro'; break; 
                         case 'Dopoldan': imageName = 'dopoldan'; break; 
                         case 'Poldne': imageName = 'poldne'; break; 
                         case 'Popoldan': imageName = 'popoldan'; break; 
                         case 'Večer': imageName = 'vecer'; break; 
                         case 'Noč': imageName = 'noc'; break;  
                       } 
                       return '/local/img/fp/' + imageName + '.png';
```

###When I look with DevTools I see:

![Log-FP](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/460e0d90-5ef6-46b9-8470-002655379ab4)

###I can see this :

![Luči-slike](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/d9f09ce9-ec9e-4007-aa81-93a3de04c0ec)

##when the switch is on, the image should also change, or if I understand correctly, come to the foreground.

**Comment by Trzinka** [comment]
and with that you should be calling this:
```
                - entities:
                    - switch.sw_st
                    - switch.sw_vh
                    - switch.sw_mi
                    - switch.sw_gr
                    - switch.sw_ho
                    - switch.sw_sp
                    - switch.sw_na
                    - switch.sw_di
                    - switch.sw_je
                    - switch.sw_sh
                    - switch.sw_ku
                    - switch.sw_ko
                  tap_action: false
                  state_action:
                    action: call-service
                    service: floorplan.class_set
                    service_data: switch-${entity.state}
```
## should call this:
![Switch-obrobe](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/1001346a-8132-43cf-a279-9a8558365ad7)
