### ISSUE TITLE
Showing the picture of the room when the switch is on!!!

### ISSUE THREAD

**Issue by Trzinka** [ExperienceLovelace/ha-floorplan#402]
**Hello again.**

`I'm obviously doing something wrong.`

Folder in HA:

![Files](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/4a6ccaed-6de1-49ab-a840-738344c4ac76)
```
I have pictures that change according to the sensor that determines what part of the day it is, 
but I would like to show the other pictures that show rooms when the switch is on!
```
entity in HA = switch.sw.ho
element in SVG = switch_sw_ho
switch_sw_ho = link to ho.png
my SVG file = fp.svg
```
I have the following structure in inkscape!!!
```
"del_dneva" (english: time of day) contains pictures of the whole house at different times.
"light-covering" contains images of individual rooms when the light is on.
```
part of fp.svg
```
![BG-sw-cocering](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/9fb978a1-6a57-4f04-b5e7-6f51e6959c9b)

I don't understand the following configurations very well. 

In floor plan card I have:

```yaml 
    - element: switch_sw_ho
      entity: switch.sw_ho
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data: entitystate-${entity.state}
      tap_action:
        action: call-service
        service: homeassistant.toggle

"and"

    - element: switch_covering_sw_ho
      entity: switch.sw_ho
      state_action:
        action: call-service
        service: floorplan.class_set
        service_data: entitystate-${entity.state}
      tap_action:
        action: call-service
        service: homeassistant.toggle
```
In DevTools i can see:

![DevTools](https://github.com/ExperienceLovelace/ha-floorplan/assets/40424965/2edc6100-24ce-45aa-b547-82be39452377)

my fp.css
```
@keyframes fade-in {
	from {
		opacity: 0;
	}
	to {
		opacity: 1;
	}
}

svg, svg * {
	pointer-events: all !important;
	cursor: auto !important;
	display: block !important;
	margin: 0px !important;
	max-height: 100vh !important;
	width: auto  !important;
	padding-top: 50px !important;
	padding-bottom: 50px !important;
}

svg path {
	fill: inherit;
	stroke: inherit;
	stroke-width: inherit;
}
  
#switch_coverings {
	display: none !important;
	mix-blend-mode: lighten !important;
	animation: 0.75s fade-in linear forwards !important;
}

#switch_coverings .entitystate-on {
	display: block !important;
	z-index: 100 !important;
}

#areas {
	fill: none !important;
	stroke: none !important;
	stroke-width: 0 !important;
}
 
#areas .entitystate-on {
	visibility: visible !important;
	stroke-opacity: 1 !important;
	stroke: #118cdd !important;
	stroke-width: 3px !important;
}
```

_The lines of the room where the light is on appear to me. The picture that should show the light on in the room doesn't!_

**The question is: do I need to correct something in the fp.css file or do I need to enter something new in the floor plan card?**
