### ISSUE TITLE
[BUG] Styles no longer applying since recent update.

### ISSUE THREAD

**Issue by riskitforabiscuit1252** [ExperienceLovelace/ha-floorplan#436]
This is how my code has been for while and the custom floorplan styling always worked and applied correctly. Since updating my HA system and HACS installs I can't get the styles to apply at all and they will not show up at all when I inspect element either. Has anyone else had these issues? Has something changed and am I required to update my YAML? 

PS. (I've tried making these styling changes in the floorpan.css file as well and this would not show either. But of course I may have inputted it correctly. I am atleast sure that the below YAML at least _was_ correct before my updated)

This is the styling I wanted to apply: 

``` yaml
            style: >
              ha-card {
                  max-width: 117vh;
                  background: none;
                  box-shadow: none;
                  margin: 0 auto;
              }

```
This is how it was laid out in my code.

``` yaml

title: "Home"
path: "home"

#theme: floorplan
panel: true
cards:
  - type: vertical-stack
    cards:


      - type: horizontal-stack
        cards:
          #################################################
          # Floorplan
          #################################################
          - type: "custom:floorplan-card"
            style: >
              ha-card {
                  max-width: 117vh;
                  background: none;
                  box-shadow: none;
                  margin: 0 auto;
              }

            config:
              image: "/local/floorplan/floorplan_optimised.svg"
              stylesheet: "/local/floorplan/floorplan.css"
              rules:
```

My rules and entities were below this but I didn't think it was worth including this above.
