### ISSUE TITLE
breaking yaml code for rules doesn't work

### ISSUE THREAD

**Issue by perlchamp** [ExperienceLovelace/ha-floorplan#516]
I'm up-to-date, using HA-OS

This is the scenario:
I did install floorplan and it works fine. 
Here is the folder- and file structure (in Studio Code Server):
![Image](https://github.com/user-attachments/assets/5fd0f563-3874-4451-9840-ae3d79bb48b6)

So the working directory is: 

> /local/community/ha-floorplan/

And the configuration-file is: 

> home.yaml

Lets have a look to the hole dashboard (as proof that floorplan works):
![Image](https://github.com/user-attachments/assets/6ff1b9e6-2bd9-4e6c-9ab5-62949c154d7b)

Lets have a look to the dashboard yaml-code (raw-configuration-editor):
```
views:
  - title: Home
    config:
      show_side_bar: false
      show_app_header: false
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
        card_mod:
          style: |
            ha-card {
              border-radius: 0px;
              padding: 0px;
              margin: -8px 0 0 -8px; 
              /* 
              */
            }
       ...
```
As you can see, the configuration-file 'home.yaml' is outsourced docu-like.

Now lets have a look to the content of the home.yaml (modified for you with a standard-entity, that everybody should have, so reproducing this bug is simple):
```
image: /local/community/ha-floorplan/_grundriss_wg4-ha31.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info

defaults:
  hover_action: hover-info
  tap_action: more-info

rules:
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
          ${entity.state == "clear-night" ? "klare Nacht" : ""}
          ${entity.state == "cloudy" ? "bewölkt" : ""}
          ${entity.state == "partlycloudy" ? "teilweise bewölkt" : ""}
          ${entity.state == "rainy" ? "regnerisch" : ""}
          ${entity.state == "snowy-rainy" ? "Schneeregen" : ""}
          ${entity.state == "sunny" ? "sonnig" : ""}
          ${entity.attributes.temperature ? entity.attributes.temperature + " °C"  : "--"}
          ${entity.attributes.humidity ? entity.attributes.humidity + " %"  : "--"}
          ${entity.attributes.pressure ? entity.attributes.pressure + " hPa"  : "--"}
          ${entity.attributes.wind_speed ? entity.attributes.wind_speed + " km/h"  : "--"}
          ${entity.attributes.uv_index ? entity.attributes.uv_index + " uvi"  : "0 uvi"}
```
How it looks like (without sidebar):
![Image](https://github.com/user-attachments/assets/2fdc6b8d-0871-4e86-9062-2e83a73ec59f)
So the modification is working fine, too.

Now the goal is to outsource the rules (one file per rule), so i did adjust the code of the floorplan-configuration-file 'home.yaml' (last code line):

```
image: /local/community/ha-floorplan/_grundriss_wg4-ha31.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info

defaults:
  hover_action: hover-info
  tap_action: more-info

rules: !include_dir_list rules
```
i also did try the following !include-statements without success (always after adjustment i did restart HA):
1. rules: !include_dir_list rules/
2. rules: !include_dir_list /rules
3. rules: !include_dir_list /rules/
4. rules: !include_dir_merge_list rules/
5. rules: !include_dir_merge_list /rules
6. rules: !include_dir_merge_list /rules/

The directory-structure and the content of the rules-folder (in Studio Code Server):
![Image](https://github.com/user-attachments/assets/0b571018-c9b9-4a9a-bab9-254da0ba36db)

And the content of the rules_weather_forecast_home.yaml:
```
- entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
          ${entity.state == "clear-night" ? "klare Nacht" : ""}
          ${entity.state == "cloudy" ? "bewölkt" : ""}
          ${entity.state == "partlycloudy" ? "teilweise bewölkt" : ""}
          ${entity.state == "rainy" ? "regnerisch" : ""}
          ${entity.state == "snowy-rainy" ? "Schneeregen" : ""}
          ${entity.state == "sunny" ? "sonnig" : ""}
          ${entity.attributes.temperature ? entity.attributes.temperature + " °C"  : "--"}
          ${entity.attributes.humidity ? entity.attributes.humidity + " %"  : "--"}
          ${entity.attributes.pressure ? entity.attributes.pressure + " hPa"  : "--"}
          ${entity.attributes.wind_speed ? entity.attributes.wind_speed + " km/h"  : "--"}
          ${entity.attributes.uv_index ? entity.attributes.uv_index + " uvi"  : "0 uvi"}
```

I also did try this (This was the answer of the maintainer):
```
name: weather_forecast_home
element: weather.forecast_home
entities:
  - weather.forecast_home
state_action:
  - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
          ${entity.state == "clear-night" ? "klare Nacht" : ""}
          ${entity.state == "cloudy" ? "bewölkt" : ""}
          ${entity.state == "partlycloudy" ? "teilweise bewölkt" : ""}
          ${entity.state == "rainy" ? "regnerisch" : ""}
          ${entity.state == "snowy-rainy" ? "Schneeregen" : ""}
          ${entity.state == "sunny" ? "sonnig" : ""}
          ${entity.attributes.temperature ? entity.attributes.temperature + " °C"  : "--"}
          ${entity.attributes.humidity ? entity.attributes.humidity + " %"  : "--"}
          ${entity.attributes.pressure ? entity.attributes.pressure + " hPa"  : "--"}
          ${entity.attributes.wind_speed ? entity.attributes.wind_speed + " km/h"  : "--"}
          ${entity.attributes.uv_index ? entity.attributes.uv_index + " uvi"  : "0 uvi"}
```

The result of both is a black floorplan:
![Image](https://github.com/user-attachments/assets/8cf79001-5541-46b3-959a-0a89f21ce2af)

THIS IS A BIG BUG, isn't it ?

You need more information? Tell me !

Many thanks in advance !

**Comment by exetico** [comment]
Separating your YAML, are not related to ha-floorplan. I have provided a solution which are tested 1:1 on both Home Assistant running on Docker, and Home Assistant powered by Home Assistant Operating System.

For other people finding this, please take a look at case7 provided here:
https://github.com/ExperienceLovelace/ha-floorplan/discussions/323#discussioncomment-12435922

This is not a bug.

I'd suggest you use case7, get that to work, and work backwards, by fitting your own rules into that one.

**Comment by zen2** [comment]
I'm agree with exetico, it is a pure yaml problem.

I use it without any problems but you need to take care about the spacing of each level of files.
By the way, seems strange to put yaml files in /local/ that is designed to serve web elements to the frontend.

Following it is an extract of my setup that use different includes and an include_dir_merge_list.
Note that my main dashboard is a yaml file.

The files tree:

- ui-lovelace.yaml
- **lovelace/**
  - 00_floorplan
  - 10_level_0
  - 11_level_1
  - 40_energy
  - 50_network
  - 51_energy
  - 56_media
  - **floorplan/**
      - functions.yaml
      - house.yaml
      - **rules/**
          -  clim.yaml
          -  date.yaml
          -  light.yaml

**ui-lovelace.yaml** (main dashboard)
```
background: linear-gradient(315deg, rgba(0,0,0,1), rgba(150,150,150,1) 100%)

title: MyHome
views:
  - !include lovelace/00_floorplan
  - !include lovelace/10_level_0
  - !include lovelace/11_level_1
  - !include lovelace/51_energy
  - !include lovelace/50_network
  - !include lovelace/56_media
```

**lovelace/00_floorplan**
```
icon: 'mdi:home'
panel: true
path: house
title: House

cards:
  - type: 'custom:floorplan-card'
    full_height: true
    config: !include floorplan/house.yaml
```

**lovelace/floorplan/house.yaml**
```
image:
  location: /local/floorplan/house.svg
  cache: false

stylesheet: /local/floorplan/house.css
console_log_level: warning

defaults:
  hover_action:
    action: hover-info
  tap_action:
    action: false

functions: !include functions.yaml

startup_action:
- service: floorplan.class_set
  service_data:
    class: layer-visible
    element: level_0
- service: floorplan.class_set
  service_data:
    class: layer-hidden
    elements:
    - level_1
    - level_-1
    - multimedia

rules: !include_dir_merge_list rules/
```

**lovelace/floorplan/functions.yaml**
```
|
  >
  return {
    style_contact: (entity) => {
      if (entity.state === 'on') {
        return `fill: #00ff19; opacity: 0.8;`;
      }
      else if (entity.state === 'off') {
        return `fill: #000000; opacity: 0.4;`;
      }
      else {
        return `fill: #ff0000; opacity: 1;`;
      }
    },

    style_motion: (entity) => {
      if (entity.state === 'on') {
        return `fill: #00ffff; opacity: 0.8;`;
      }
      else if (entity.state === 'off') {
        return `fill: #000000; opacity: 0.4;`;
      }
      else {
        return `fill: #ff0000; opacity: 1;`;
      }
    },

    style_clim_rdc: (entity) => {
      var color = `#000000`;
      var opacity = 1.0;

      console.log( "style_clim_rdc: " + entity.state );

      switch (entity.state) {
        case 'off': color = `#000000`; opacity = 0.5 ; break;
        case 'fan_only': color = `#061735`; opacity = 1.0 ; break;
        case 'dry': color = `#FD6400`; opacity = 1.0 ; break;
        case 'cool': color = `#29A0DC`; opacity = 1.0 ; break;
        case 'heat': color = `#DF382C`; opacity = 1.0 ; break;
        case 'heat_cool': color = `#8800AA`; opacity = 1.0 ; break;
      }
      return `fill: ${color}; opacity: ${opacity}`;
    }
```

**lovelace/floorplan/rules/clim.yaml**
```
- entities:
  - climate.rdc
  tap_action: more-info
  state_action:
  - service: floorplan.style_set
    service_data: ${functions.style_clim_rdc(entity)}
  - service: floorplan.class_set
    service_data: '${(entity.state === "off") ? "" : "spinning" }'
```

**lovelace/floorplan/rules/date.yaml**
```
- entities:
  - sensor.my_date
  - sensor.time
  state_action:
  - service: floorplan.text_set
    service_data: '${entity.state ? entity.state : "???"}'
```

**lovelace/floorplan/rules/light.yaml**
- entities:
  - light.a1
  - light.a2
  - light.b1
  - light.b2
  tap_action: toggle
  hold_action: more-info
  state_action:
  - service: floorplan.style_set
    service_data: ${functions.style_light(entity)}

**Comment by perlchamp** [comment]
Thank you for your answers:
@zen2 :

> By the way, seems strange to put yaml files in /local/ that is designed to serve web elements to the frontend.

I don't understand this, because i did install ha-floorplan via HACS and the (default) install directory is:

> config/www/community/ha-floorplan

And the following files has been installed automatically:
```
config/www/community/ha-floorplan/
    • floorplan-examples.js
    • floorplan-examples.js.gz
    • floorplan.js
```
The example-files can be deleted. Where shell i put my floorplan files? 

Your file-tree:
i did not have a lovelace folder. is this a hidden one? it is directly under config? (config/lovelace)
Is it important where to place the files, because without breaking everything still works fine.

> Note that my main dashboard is a yaml file.

I don't understand this. I created my dashboard by the following procedure:
1. Ha → Settings → Dashboards → + Add dashboard → Standard dashboard → Title: Floorplan → Create 
2. Open the dashboard just created (by clicking on the button of the same name) 
3. In the header click on the pencil symbol (right outside) → In the Dashboard Edit Dialog window, click on the 3-point icon (also in the header on the right outside) → Select control → select option: starting with an empty dashboard. 
4. In the header click on the 3-point symbol on the right (the EDIT mode is still activated) → Select RAW configuration editor → Now replace the current code with the following code:
```
views:
  - title: Home
    config:
      show_side_bar: false
      show_app_header: false
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
        card_mod:
          style: |
            ha-card {
              border-radius: 0px;
              padding: 0px;
              margin: -8px 0 0 -8px; 
              /* 
              */
            }
``` 
To keep it simple as possible, we can delete the card_mod-section:
```
views:
  - title: Home
    config:
      show_side_bar: false
      show_app_header: false
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
```
Is this a yaml-dashboard? I'm a beginner, so i don't know exactly.

how said, this is my working home.yaml:
```
image: /local/community/ha-floorplan/_grundriss_wg4-ha31.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info

defaults:
  hover_action: hover-info
  tap_action: more-info

rules:
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
          ${entity.state == "clear-night" ? "klare Nacht" : ""}
          ${entity.state == "cloudy" ? "bewölkt" : ""}
          ${entity.state == "partlycloudy" ? "teilweise bewölkt" : ""}
          ${entity.state == "rainy" ? "regnerisch" : ""}
          ${entity.state == "snowy-rainy" ? "Schneeregen" : ""}
          ${entity.state == "sunny" ? "sonnig" : ""}
          ${entity.attributes.temperature ? entity.attributes.temperature + " °C"  : "--"}
          ${entity.attributes.humidity ? entity.attributes.humidity + " %"  : "--"}
          ${entity.attributes.pressure ? entity.attributes.pressure + " hPa"  : "--"}
          ${entity.attributes.wind_speed ? entity.attributes.wind_speed + " km/h"  : "--"}
          ${entity.attributes.uv_index ? entity.attributes.uv_index + " uvi"  : "0 uvi"}
```
we can cut this to hold it small and simple:
```
image: /local/community/ha-floorplan/_grundriss_wg4-ha31.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info

defaults:
  hover_action: hover-info
  tap_action: more-info

rules:
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
```
THIS IS WORKING !

so i only have one rule. If i do the following (simple !include-statement):
```
image: /local/community/ha-floorplan/_grundriss_wg4-ha31.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info

defaults:
  hover_action: hover-info
  tap_action: more-info

rules: !include rules.yaml
```
rules.yaml:
```
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
```
than i get a black dashboard-screen. And this is normally the usual way to break a yaml. I did this in the configuration.yaml and it works, of course. 
Where is the error?

> I'm agree with exetico, it is a pure yaml problem.

If so, why nobody can tell me Where is the error. If i see p.ex. a python code, i can tell 'look at this line, you have to...'. But yaml, nobody knows. You only get the answers: 'maybe wrong indents'. (maybe!) ...
So i have to try thousands of indent and '-' variants?
So far, nobody was able to give me a concrete answer, you too. So it should be ok?
And i'm the only one with that problem? Can't believe this, because i did install via HACS and followed the instruction of the docu. 
And it's working (without breaking yaml). 
Again:
WHERE  is the error ?

It wood be great, if you could find some time to reproduce my way. This should take at maximum 10 minutes, cause it's just copy & paste. Use my files and their contents. You only have to adjust the path and the svg-image. The entity is a standard one, so you don't have to use another. First without breaking, and then with.
I hope, you will find the error, and maybe(!) it's not a yaml-problem. Knowing is better than believing...

Many thanks in advance !
