### ISSUE TITLE
After installing ha-floorplan via HACS you have to use the installation folder for your files

### ISSUE THREAD

**Issue by perlchamp** [ExperienceLovelace/ha-floorplan#517]
What i did:

1. i did install ha-floorplan via HACS
ha-floorplan was then installed in the '/config/www/community/ha-floorplan' directory.
The files 'floorplan.js' and 'floorplan.js.gz' were also automatically created in this folder.
2. in this folder i put an empty 'home.css', an empty 'home.yaml' and the svg-file '_grundriss_yamlbreak.svg'. This file only includes one text-element witch referred to the weather.forecast entity. I can send you this svg, so we can work with the same files. I didn't know, how to attach this file (as download-link) here.
3. the empty 'home.yaml' i filled with the following code:
```
image: /local/community/ha-floorplan/_grundriss_yamlbreak.svg
stylesheet: /local/community/ha-floorplan/home.css
cache: false
log_level: info
console_log_level: info
defaults:
  hover_action: hover-info
  tap_action: more-info
rules:
  - entity: weather.forecast_home
    element: weather.forecast_home
    state_action:
      - service: floorplan.text_set
        service_data: |
          ${entity.attributes.friendly_name ? entity.attributes.friendly_name + "/Pfalz"  : ""}
          ${entity.state ? entity.state : "--"}
```
INFO:
```
image: /config/www/community/ha-floorplan/_grundriss_yamlbreak.svg
stylesheet: /config/www/community/ha-floorplan/home.css
```
or
```
image: _grundriss_yamlbreak.svg
stylesheet: home.css
```
DOES NOT WORK... you have to use '/local/'

4. i did create a dashboard by the following way:
- settings -> dashboards -> add dashboard -> default dashboard -> title: floorplan -> create
- open dashboard -> click on the pencil-icon in the header -> in the popup click on the 3-points-symbol -> click on 'take control' -> in the popup select 'start with an empty dashboard' -> click on 'take controll'
- open the raw-configuration-editor of this new dashboard and replace its content with the following:
```
views:
  - title: Home
    config:
      show_side_bar: false
      show_app_header: false
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
``` 
**INFO 1:** 
'/config/www/community/ha-floorplan/home.yaml' DOES NOT WORK, you have to use '/local/'

5. restart HA, clearing browser-cache

**The result:**
![Image](https://github.com/user-attachments/assets/62ef6931-34a6-4184-9ad7-4aa82b190c0a)

GREAT, everything is working.

Then i wanted to remove my floorplan files ('home.yaml', 'home.css' and '_grundriss_yamlbreak.svg') to another folder. So i created the folder 'ha-floorplan' directly in the config directory, so the new working directory now is 

> /config/ha-floorplan

In this folder i removed the three files 'home.yaml', 'home.css' and '_grundriss_yamlbreak.svg'.

By this i had to adjust the dashboard code (via raw-configuration-editor), specially the lines which referr to the working-directory. So i did this (only adjusted code):
dashboard (only adjusted code):
```
config: /config/ha-floorplan/home.yaml
```

home.yaml (only adjusted code):
```
image: /config/ha-floorplan/_grundriss_yamlbreak.svg
stylesheet: /config/ha-floorplan/home.css
```
I did restart HA, cleared the caches ...
... BUT the adjustments didn't work ! The dashboardI displayed a black ha-floorplan-window. 

IF this is not a bug, so my thinkings are (i'm a beginner, so i can't figure out by myself) :
1. The standard-dashboard does not 'deliever' or support some features
2. Because of INFO 1 you cannot use /config/... and so you have to use the installation folder for your ha-floorplan-files.
3. However -i always want to learn -, i like to know, where is the error, what did i wrong.

WHY HAVE I USE THE INSTALLTION FOLDER FOR MY FILES ?

off topic:
These are things i would like to read in the documentation. Are you not willing to update it? Your answers or 'solutions' based maybe on yaml-dashboard an manually installed repositories, but recommended is to install via HACS and using first gui for dashboard-creation!
I trust you per 100% that your examples work. No doubt. But it seems, that you installed floorplan not by the recommended way, by the way for beginners !

And it's too difficult for a beginner to install and configure it the way you did, imo.

And if you are open for the beginner-site, than i can write (update) some parts of the documentation. Your documentation has to ordered for beginners.
1. installing via HACS
2. creating dashboard
3. how to get it working (very simple svg file only with text-element and the way to use it)
4. how to use text-elements, entities, onclick-behaviours, and so on. Text-elements are the most important things here, aren't they ?
5. how to style text in the svg-file (you don't need css for text-styling, use inkscape and the svg-file for that) 
6. at least drawing the floorplan
7. drawing features (lights, open doors, open windows), hide them (display:none) and display them, if needed (display:on). No embedded pictures are needed, they all can placed in the svg in another level, of course...

**Comment by zen2** [comment]
You have to use `/local/ `in yaml files for files under` /config/www/`.

Else everything is relative to `/config/` path.

So you need:
```
image: ha-floorplan/_grundriss_yamlbreak.svg
stylesheet: ha-floorplan/home.css
```

**Comment by perlchamp** [comment]
Thank you. I'm a little bit confused. I try to explain:
In my other thread (other issue) you wrote:

> So I advice you to create two directories: one for your web static content and one for your yaml configuration.
> For example:
> 
>     - www/floorplan/ for your floorplan svg and your css
>     - floorplan/ for you home.yaml and others included yaml with directories if needed
> 

If i'm right, then i shell put the svg- and the css-file in the folder

> /local/community/ha-floorplan

It's the installation-folder and so the same folder where the floorplan.js-file is placed, right?
if so, then your answer:

> image: ha-floorplan/_grundriss_yamlbreak.svg
> stylesheet: ha-floorplan/home.css

is wrong, because 
1. this is the content of the home.yaml
2. the svg- and css-file should placed in the /local/community/ha-floorplan, so no need to change this file

But about the main-problem (issue) you didn't write nothing. The problem is the reference to the home.yaml in the dashboard config-section (last line):
```
views:
  - title: Home
    config:
      show_side_bar: false
      show_app_header: false
    type: sidebar
    cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
```
if the home.yaml is placed in /config/ha-floorplan how to refer to this in dashboard?
INFO:
`config: ha-floorplan/home.yaml`,
`config: /ha-floorplan/home.yaml`,
`config: config/ha-floorplan/home.yaml` and
`config: /config/ha-floorplan/home.yaml`,
does not work.

Only `config: /local/community/ha-floorplan/home.yaml` works ! (if home.yaml is placed in the installation-directory)
And until now i could not figure out how to refer if home.yaml is placed in an extern folder (outside of /local/community/ha-floorplan)...

It was a theoretical answer and i pleased you to test your 'solution' before posting.

**Comment by zen2** [comment]
I won't go further on this topic as it is not related to floorplan anyway.

**Comment by perlchamp** [comment]
> In lovelace web mode, dashboard are stored as json files as /config/.storage/lovelace.dashboard_title and so not as yaml file.
> I've tried to create a new web dashboard and include my existing flooplan yaml but the interface don't accept the !ncludedirective at all.
> 
> So it seems web mode dashboard doesn't support include file/directory directives and so you need to use a yaml mode dashboard to be able to use include directives.

THANK YOU ! YOU'RE WELCOME !

That's one of the things i told before, but the maintainer was numb on that ear !

1. But is it necessary to use an !include-statement for inclusion?
If you throw an eye - again - to my  lovelace web mode (part of it) :
```
cards:
      - type: custom:floorplan-card
        full_height: true
        config: /local/community/ha-floorplan/home.yaml
```
then you can see that's possible to include files, but - it seems - only these which are placed in the www-directory. 
Is there a way to refer outside of www?

2. IMPORTANT: does THAT mean, that !include-directives don't work in the home.yaml (specially) for breaking rules ?

3. I use 'Studio Code Server' the most time. And there i cannot see this. storage (and other) folders. Are they marked as hidden?
How to make them visible? If you know, please tell me, before you send me to a cross-reading-never-ending-journey, thanks.

4. I hope, the maintainer will read this post, too, so he has time to adjust his documentation and answers he given in other threads !

5. I think, this is something for the next WTH-month, isn't it?

6. Does that mean, that floorplan does only work (as expected) in pure yaml-dashboards ?

7. It is a pure yaml-problem or could adjustments of the floorplan-code by the maintainer solve these problems/behaviour ? (because with other cards i didn't have any problems...)

MANY THANKS - again - FOR YOUR TIME ! (maybe you did learn something, too. I did !)
