### ISSUE TITLE
Unable to use element object in service_data for image_set service

### ISSUE THREAD

**Issue by exetico** [ExperienceLovelace/ha-floorplan#519]
### Discussed in https://github.com/ExperienceLovelace/ha-floorplan/discussions/518

<div type='discussions-op-text'>

<sup>Originally posted by **garyjlo** March 12, 2025</sup>
I was trying to set a rule that, based on an HA weather entity, I could set multiple elements in my SVG floorplan, in this case, a text_set for the temperature and image_set an icon for the weather condition.
```
    - entity: weather.demo_weather_north
      state_action:
        - action: call-service
          service: floorplan.text_set
          service_data:
            element: sensor.weather_temperature
            shift_y_axis: 2em
            text: ${ entity.attributes.temperature }${ entity.attributes.temperature_unit }
        - action: call-service
          service: floorplan.image_set
          service_data:
            element: sensor.weather_condition
            image: /local/icons/weather/${ entity.state }.svg
```
I did a lot of trial and error and could not get it to work.

Eventually I found a successful workaround by splitting it into two rules, with the image_set one moving the element field up to the top level, out of service_data:
```
    - entity: weather.demo_weather_north
      state_action:
          action: call-service
          service: floorplan.text_set
          service_data:
            element: sensor.weather_temperature
            shift_y_axis: 2em
            text: ${ entity.attributes.temperature }${ entity.attributes.temperature_unit }

    - entity: weather.demo_weather_north
      element: sensor.weather_condition  #<-- element moved out of service_data
      state_action:
        action: call-service
        service: floorplan.image_set
        service_data:
          image: /local/icons/weather/${ entity.state }.svg
```

Is this a bug? The documentation lists element and elements as valid objects for all service_data sections.</div>

**Comment by exetico** [comment]
Hi @garyjlo. Thank you for providing the extra context. I've created a issue, on basis of your inputs. I'll take a look at it, and see if it's just you, our documentation, or maybe a bug in the code.

**Comment by exetico** [comment]
Hi @garyjlo

Please test the new pre-release here:
https://github.com/ExperienceLovelace/ha-floorplan/releases/tag/v1.0.49-rc.1

With that said; You're not right about the documentation. Object mentioned in "_Service data can be dynamically constructed using JavaScript code. Below is the full set of objects that are available when writing code._" are not keys, which can be used as part of the service_data in your YAML configuration. That's objects to be used, if you write JavaScript. Here you're able to pull data from Home Assistant, and use our util-functions, and more. 

Here's a simple example where `entities` are used to pull a state from another entity, than the one used to trigger `state_action`.

```
            - entity: light.trodfri5_light # weather.forecast_home
              state_action:
                  action: call-service
                  service: floorplan.text_set
                  service_data:
                    element: sensor.udestue
                    shift_y_axis: 2em
                    text: ${ entities['weather.forecast_home'].attributes.temperature }${ entities['weather.forecast_home'].attributes.temperature_unit }
```

**However**, I fully get that it's confusing that you're able to use `element` in the other Floorplan Service calls. Therefore I've extended the code, so you're able to define the element, as part of the service-data for the `image_set` service, too.

This is experimental at the moment, as I've not found time to make a full test, and testing in general, are not that well scoped in ha-floorplan. In other words: A pre release is needed, to test if other people does face issue, caused by this change.

**Comment by garyjlo** [comment]
Thank you for looking into this and explaining about the documentation
I very much appreciate you extending the code so that image_set behaviour can be consistent with other Floorplan service calls.

However, I got the pre-release files, and copied the new ha-floorplan.js files into my hacs/community directory:
![Image](https://github.com/user-attachments/assets/99df4587-46f3-4932-88aa-c0fc7bba74e3)

Then I restarted my HA, hard cleared my cache as well as reloaded my dashboard but I'm not seeing the new code work when I move the element key from top-level down into the service_data section.

**Comment by exetico** [comment]
What version does ha-floorplan prints out, if you open the Console in your browser, and refresh on a page with a ha-floorplan card?

Module-caching is kinda hard to work with in HA. Your browser normally does a painful good job, sticking to the current content of the js-files.

**Comment by garyjlo** [comment]
You are right, the floorplan console is still printing out v1.0.48 still on init, it's also here on all the plugin init logs:
![Image](https://github.com/user-attachments/assets/ae6fe06a-ffc7-41b8-b22f-67dd50d50e82)

I've tried many reloads, restarting HA, bumping the version in Resources (v=1.0.49 as well as v=1.0.49-rc.1), I tried deleting the js directly from browser cache storage, but 1.0.48 seems to keep coming back.
![Image](https://github.com/user-attachments/assets/f4d610a4-4605-4488-9d22-dd3151e06773)

I can confirm that the floorplan.js I put into www/community/ha-floorplan should be the right one (pre-release)
![Image](https://github.com/user-attachments/assets/1b985cab-7cb4-44a8-a3a2-3bdf0d4c0b55)

I originally wanted to install the pre-release from HACS but I did not find it in the dropdown
![Image](https://github.com/user-attachments/assets/1fdb7f16-82f8-481a-a036-e3684b50645a)

**Comment by OzGav** [comment]
With the dev tools open go to the network tab and tick the disable cache box then refresh the browser (with the dev tools still open) and see if that fixes it

**Comment by garyjlo** [comment]
I was finally able to get the pre-release loaded - the issue was the zipped copy of the js file in the hacs folder that needed to also be removed or replaced.

The update does work for me now, and I can use `element` in `image_set`'s `service_data`, thank you.

However, it did have one unexpected change that ended up exposing a bug elsewhere in my code...

I had a rule like this to assign the styling of several similar lights:
```
    - entities:
        - light.basement
        - light.bedroom
        - light.front_door
        - light.living_room
        - light.office
      state_action:
        action: call-service
        service: floorplan.style_set
        service_data:
          style: *style-ceiling-dimmable-light
```

In my floorplan svg, the elements that I want styled have exactly the same name as the HA entity, and I believe floorplan 1.0.48 code was somehow defaulting `element` in `service_data` to the entity id, and so my code just worked.

1.0.49-rc.1 broke that, and my lights were not getting styled when the state changed.

I ended up having to add this to set the element properly:
```
    - entities:
        - light.basement
        - light.bedroom
        - light.front_door
        - light.living_room
        - light.office
      state_action:
        action: call-service
        service: floorplan.style_set
        service_data:
          element: ${ entity.entity_id }              <-- added line
          style: *style-ceiling-dimmable-light
```

I think this is better because you are forced to explicitly provide the element - I was actually a little confused how my code worked magically before. However, this could break other users' workflow if they had relied on this, and if they are not aware of the entity object and it's attributes (I had to learn about it just now to fix my issue)
