### ISSUE TITLE
[BUG] State Action - Text Set with No Value Sets 0

### ISSUE THREAD

**Issue by Happy-Cadaver** [ExperienceLovelace/ha-floorplan#558]
**Describe the bug**
Noticed this behavoir after the last update to v1.1.0, I expect that it's related to the added feature of being able to set a default for `state_action`. I did try adding the default to false with no improvment.
```yaml
defaults:
  state_action: false
```

Using `state_action:` on an `input_text.` entity  that utilises `service: floorplan.text_set` sets a numeric 0 when the `input_text` has no value.

**To Reproduce**
1. Create an `input_text` helper but do not give it any value.
2. Utilise a Rule on the `input_text` entity using `service: floorplan.text_set` to update the .svg file.
3. Create a text element in a .svg file with dummy text and an ID identical to the `input_text` helpers name.
4. Run it through HA front end.

**Expected behavior**
I expect to see no text when the `input_text` helper has no text. This was the behaviour before the last ha-floorplan update.

**Screenshots**
Red encircilings highlight effected elements

With empty `input_text` entity.

![Image](https://github.com/user-attachments/assets/326eec80-d424-49f5-bc95-7452920f83d2)

![Image](https://github.com/user-attachments/assets/be4e9a17-5f69-48d8-8d92-06fd8d2b883d)

With value in the `input_text` entity.

![Image](https://github.com/user-attachments/assets/547444f8-c230-4ba1-9c25-f216a3ba5fa7)

![Image](https://github.com/user-attachments/assets/9824c3f0-83f2-4091-b2f6-eb1ef3bc3cb1)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Iridium, Chrome, and Edge
 - Version: Current

**Smartphone (please complete the following information):**
 - Device: Galaxy S10+, S25, and Tab 7A
 - OS: Current Supported per Device
 - Browser: N/A, HA Companion App
 - Version: Current

**Share configuration**
Please share:
```yaml
- entity: input_text.next_track
  state_action:
    service: floorplan.text_set
    service_data: ${entity.state}
```
```css
tspan {
  fill: rgb(0, 0, 0) !important;
  font-family: Georgia, serif !important;
  font-variant: small-caps !important;
  stroke: rgba(222, 184, 135, 1);
  stroke-width: 0.05px !important;
}
```
```svg
<text
           xml:space="preserve"
           id="input_text.next_track"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:8.15025px;font-family:Georgia;-inkscape-font-specification:Georgia;white-space:pre;display:inline;fill:#000000;stroke-width:0.679191"
           inkscape:label="input_text.next_track"
           x="55.074425"
           y="20.097147"><tspan
             id="tspan1-0"
             style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-family:Georgia;-inkscape-font-specification:Georgia;stroke-width:0.679191">Next: Billy Joel • A Matter of Trust</tspan></text>
```
**Additional context**
