### ISSUE TITLE
[FEATURE]  Set of standard  dynamic images

### ISSUE THREAD

**Issue by geiseri** [ExperienceLovelace/ha-floorplan#74]
**Is your feature request related to a problem? Please describe.**
I have absolutely no artistic talent but I am pretty good at code.  It would be cool to have a simple way to add simple things like thermometers and other "simple" gauges to the floor plan.

**Describe the solution you'd like**
What I would like to do is to be able to put a simple rect like this in the main svg floor plan:
```xml
  <rect
     y="1463"
     x="10"
     height="393.60974"
     width="280"
     id="sensor.wirelesstag_front_room_temperature" />
```

Then in the yaml have something like this:

```yaml
- entity: sensor.wirelesstag_front_room_temperature
  element: sensor.wirelesstag_front_room_temperature
  image: /local/floorplans/thermometer.svg
  stylesheet: /local/floorplans/thermometer.css
  state_action:
    action: call-service
    service: floorplan.set_gauge_value
    service_data:
      name: svg_id
      value: '${entity.state}'
```

Where "image" and "stylesheet" can be replaced with `source: 'thermometer'` to use a built-in svg. 

Then the SVG would have properties you can change based on id or class that the properties in the `service_data` would manipulate.  It would give both flexibilities for people who know what they are doing, and simplicity for people like me that just want to have a thermometer that doesn't look like a 2-year-old put it together ;)

**Describe alternatives you've considered**
Currently, I am doing the approach based on https://github.com/ExperienceLovelace/ha-floorplan/blob/master/docs/_docs/floorplan/examples/home/home.yaml#L91, but I really dislike debugging code in yaml =)
